### ISSUE TITLE
Why column moving feature is enabled on a per-column level?

### ISSUE THREAD

**Issue by sddania** [IgniteUI/igniteui-angular#10176]
referring to https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-moving#overview actually in igx-grids some columns can be immovable or some other not. Why?
If you can move some columns you can reorder implicitly also the immovable one.
Do you have some use case that explain the utility to set some movable columns and other not?
If not can we update the igx-grid moving movable input parameter to grid level?
Many thanks

**Comment by kdinev** [comment]
@sddania This is actually an excellent question. Columns marked as `[movable]="false"` can still be moved (rearranged) by putting movable columns in front of them in the UI. I'm changing the labels of the issue from `question` to `refactoring` `enhancement` and we will work on changing this to be an input on the grid component level, instead of on a column level.
