### ISSUE TITLE
Export to excel is not working for MultiColumn Header having Same Column name

### ISSUE THREAD

**Issue by jaya0selva** [IgniteUI/igniteui-angular#10194]
## Description  
Export to excel/CSV is not downloading all the columns in MultiColumn Header which has Same Column name

 * igniteui-angular version: 9.1.28
 * browser: Chrome

## Steps to reproduce  
![image](https://user-images.githubusercontent.com/40403770/134902531-4bb1b765-931a-4558-b659-5a37c26130ae.png)

in above image only 1 column is getting downloaded in excel/CSV

## Result  
Only the first column is downloaded in excel

## Expected result  
All column with same name should be downloaded

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by gedinakova** [comment]
@jaya0selva This faulty behavior has been fixed in versions 12.1.0 and above as demonstrated in [this sample app](https://stackblitz.com/edit/github-dmqhbr?file=src%2Fapp%2Fgrid%2Fmulti-column-headers-export%2Fmulti-column-headers-export.component.html). Could you, please, update and let us know if you are still experiencing any issues?

**Comment by jaya0selva** [comment]
Hi @gedinakova ,
yes it is fixed in V12. but all other lower versions V9-11 having this issue and our app is using V9 contains 100+pages with infragictics grid component. We have to migrate our app only for this bug. Since we have to fix it ASAP,  Can you fix it in V9.

**Comment by gedinakova** [comment]
@jaya0selva I am afraid this won't be possible - the lowest version we currently support is 10.2.
