### ISSUE TITLE
Vertical scrollbar disappears when the grid has "width" set as a percentage

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#1023]
### Description  
In the Grid Performance demo the vertical scrollbar disappears if the "width" of the grid has been set as a percentage.

### Steps to reproduce  

1. Open branch 5.3.x.
2. In the Grid Performance demo set the grid width to"100%".
3. Open the Grid Performance demo.

### Result  
The grid vertical scrollbar disappears.

### Expected result  
The grid should have a vertical scrollbar.

### Attachments  
![sketch](https://user-images.githubusercontent.com/18643062/38856964-a7ff0632-4230-11e8-85d7-3d7d80cdea95.png)

**Comment by damyanpetev** [comment]
@simeonoff Doesn't seem to be as that one is related to the lack of virtual scrollbar.

Setting width in % (e.g. "100%" per the issue) triggers the horizontal virtualization and also calculates the actual width for the vistual container. But on init the page layout is still mid-animation due to transition styles on the nav drawer and the other time re-calculation happens is on window resize.

However, that is not quite enough (even if we fix the case with the drawer) as dynamic layout can shift from images loading, collapsible content, resizes (ala tile manager) and the list goes on. None of those are connected with window resize and the grid will not recalculate there as well.

As we discussed with @ChronosSF @rkaraivanov @skrustev a solution would be a good 'ol interval (`ResizeObserver`, one day..😞  ) **or** exposing the re-calculation method **or** both.
