### ISSUE TITLE
Multiple groups for the same value

### ISSUE THREAD

**Issue by michalsgit** [IgniteUI/igniteui-angular#10236]
## Description  
IgxGrid creates multiple groups for the same value.

 * igniteui-angular version: 12.x
 * browser: Chrome

## Steps to reproduce  
1. Open [stackblitz](https://stackblitz.com/edit/github-3zkfwu?file=src/app/app.component.ts)
2. Group by Carrier column

## Result  
There are two lines with "EuNetworks"

## Expected result  
There should be only one gropu for "EuNetworks"

## Attachments  
![Duplicit_groping](https://user-images.githubusercontent.com/6318187/135900933-420d9297-92bd-452f-b92a-f5ef37d6da0a.PNG)

**Comment by ChronosSF** [comment]
This happens because sorting is case insensitive and the equal values are separated by the sorting algorithm not bunching them together either before or after the lower case value. Try a case-sensitive sort and you'll get them together. 

https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxColumnComponent.html#sortingIgnoreCase

**Comment by michalsgit** [comment]
Yes, that technically solves the issue.
I think users expect the "bunching" as that is the purpose of grouping.
Also expanding one group automatically expands the other with the same name. On the one hand it separantes them, on the other it considers them the same. That looks to me like another inconsistency in the grid behavior.
