### ISSUE TITLE
If the underlying dataItem has "undefined" value for a property, the corresponding cell has "undefined" string value in edit mode

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1030]
### Description  
If the underlying dataItem has "undefined" value for a property, the corresponding cell has "undefined" value in edit mode, while having no value in normal mode (when it is not it edit mode).

**NOTES:**
The issue is **not** reproduced when the dataItem has a "null" value for a property. In that case, both the edit and display value of the cell is empty. (as it should be for "undefined")

### Steps to reproduce  

1. Download and run the attached sample application.
2. Enter edit mode for the "ProductName" cell of the first record (with ID=1).

### Result  
The edit value is **undefined**.

### Expected result  
The edit value is empty.

### Attachments  

![image](https://user-images.githubusercontent.com/12784974/38864886-cb660044-4244-11e8-929b-cec8d2082f87.png)
[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1919303/igxgridSample.zip)

**Comment by Aleksandyr** [comment]
@tachojelev this is not a bug because this is the representation of the value itself. There is a quit[ difference between null and undefined values](https://www.ajaymatharu.com/javascript-difference-between-undefined-and-null/) so that's why the representation is different. As for the visualization from user prospective, the user itself is allowed to override the default template of the "inlineEditor" template with the one they want.
