### ISSUE TITLE
[igxGrid]ngModelChange does not trigger when tabbing/clicking out of edit mode after sorting

### ISSUE THREAD

**Issue by tishko0** [IgniteUI/igniteui-angular#10322]
## Description  
ngModelChange does not trigger when tabbing/clicking out of edit mode after sorting

 * igniteui-angular version: 12.1 ( noticed on update from 12.0 to 12.1)
 * browser: 

## Steps to reproduce  - Using the sample in description:

Following works like it should:

1- Type value in Age column
2- Tab to the next cell to submit the value
3- The console.log() is triggered in the onchangeHandler

Following doesn't work:

1- Press sort button
2- Type value in Age column
3- Tab to the next cell to submit the value
4- The console log is not triggered in the onchangeHandler

## Attachments  
Sample - https://stackblitz.com/edit/github-wkze11-1gu3pu?file=src%2Fapp%2Ftree-grid-editing-sample%2Ftree-grid-editing-sample.component.html

**Comment by Volen99** [comment]
It seems that the problem is with **p-inputNumber** component coming from primeng. Replacing with it <input /> makes the example working properly following the steps described. Notice that when using <input /> , onchangeHandler is called BEFORE value is changed, as expected. However, with primeng input, this handler is called AFTER.

**Comment by EddyNll** [comment]
This used to work in the 12.0 igniteui-angular. The strange thing to me is that sorting breaks the functionality. When not sorting the p-inputNumber works fine.

**Comment by hanastasov** [comment]
Please tell us the exact version of 12.0 where this worked, this will help us easily find if there is a specific reason in the sorting.

**Comment by EddyNll** [comment]
We are using: 12.0.11

> Please tell us the exact version of 12.0 where this worked, this will help us easily find if there is a specific reason in the sorting.

**Comment by Volen99** [comment]
Thanks, I tried how it behaves in 12.0.11 - there it does really call the handler even after sort, even in the first version of 12.1 - 12.1.0-alpha.0, there the handler is no longer called. I looked at the relevant changes from column sorting, but even they isolated don't make any difference in the behaviour.

We can't afford to spend more time, because even if we manage to find out what exactly in our code dictates change, and we make the handler call, for us the change remains in primeNG component, because it always emits AFTER, not BEFORE the value changes.

For us, the component is not written OK, and we will not spend more time on it. We suggest you change **p-inputNumber** to a classic <input /> or use this one from IG.
