### ISSUE TITLE
Simple combo feedback

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10461]
## Question  
So a little bit of feedback/question about the new simple combo. 

1. There seems to be a fundamental difference in the simple and normal combo, in that you are actually using the input field to write in, instead of having a search field. I think I would have preferred it to have the same functionality as the combo, in order to get a uniform user experience. But the major issue is that the combo no longer forces you to select an item at all. I can actually write whatever I want into the input field, and that completely defeats the whole purpose of the component from our point of view. I don't really see the difference between this and just using an autocomplete?
2. Minor thing: can this be templated?
![image](https://user-images.githubusercontent.com/12936286/141010332-d22915da-64a5-4a84-9a27-f7a556336eda.png)

 * igniteui-angular version: 12.3 alpha

**Comment by StefanIvanov** [comment]
Hi @Eralmidia the reason for using just one input for the simple combo was that you always have 0 or 1 items selected and therefore as you make a new selection it would replace the old one. In the multiple combo a second input was necessary as you could also add more items from the list to the selection and we didn't want to complicate things for users by combining selected items and searching into one area. Since for the simple combo the scenario is different, we decided to simplify the interactions by using one input for both. All functionality is same between the two only this visual change is a subtle difference but we believe it simplifies things for users. Also the only way to actually select an item from the simple combo is through the list, even if adding custom values is enabled you have to add it first and then it gets selected, you cannot just provide arbitrary text that becomes the selected value.

**Comment by Eralmidia** [comment]
@StefanIvanov Yes, I do understand that design decision. It's a convenience vs uniformity question. I just noted it as a feedback. The main issue however, is that since you now write into the text field, the user might think that something is selected when its not. So for instance in this scenario, it might look like this is valid:
![image](https://user-images.githubusercontent.com/12936286/141075619-419e63d0-cd6b-4b44-921a-5e7757c64a1a.png)
 However, since the user wrote it with a lowercase w it's actually not. But when you then go to the next cell, the input remains, and still looks valid:
 
![image](https://user-images.githubusercontent.com/12936286/141075869-9bcffe3b-4e61-43fc-9046-d72f04057e61.png)

So while the simple combo might not see this as a value, there is still nothing to force the user to select a correct value. Instead of being a single select combo, this feels like a hybrid between a select and an auto complete.

In either case, I see the fundamental design of this component to not be what we were looking for. I think we will resume the creation of our own component in order to get exactly what we wanted: a single select combo, aka a select with a search field.

**Comment by kdinev** [comment]
@Eralmidia You can write whatever you want and it will stay in the input, if and only if, custom values are enabled. @jackofdiamond5 @Lipata Correct me if I'm wrong. 
We don't need chip selection with the single-selection combo, neither do we need to have a separate search input in this case. The only reason we have them in the combo is because it's meant for multi-selection.

**Comment by Eralmidia** [comment]
@kdinev Ok, is there any docs avaiable for this yet? Is there a [customValues]="false" input?

**Comment by kdinev** [comment]
Here's the [custom values input](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxComboComponent.html#allowCustomValues).

With `allowCustomValues: false` arbitrary text staying in the input after blur is simply a bug. @jackofdiamond5 @Lipata We need to fix that before the official version is out.

**Comment by jackofdiamond5** [comment]
@kdinev During the design meeting for the component we talked about this and we decided to keep everything in the input at all times since it is an input and we didn't want to force it to be cleared. Though, with custom values being allowed, the component doesn't clear if an arbitrary string is entered, which means that there's indeed a little bug. So yeah, we're going to fix both of these.

**Comment by kdinev** [comment]
@jackofdiamond5 Yeah, I remember we talked about this, but didn't remember the exact decision that was made. Since we have feedback on this, we should clear the input value on blur if it's doesn't exist in the list (no custom values, or custom values, but the user hasn't committed the value to the list).

**Comment by Lipata** [comment]
@Eralmidia, @jackofdiamond5 implemented clearing not matching values on blur. Please give it a try: https://github.com/IgniteUI/igniteui-angular/releases/tag/12.3.0-alpha.1

**Comment by Lipata** [comment]
@Eralmidia you can now use [12.3.0](https://github.com/IgniteUI/igniteui-angular/releases/tag/12.3.0)
