### ISSUE TITLE
Change "Row added" text

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10494]
## Question  
When a row is added, a toast-like popup is displayed. How do you control the template (or at least the text) of this?

![image](https://user-images.githubusercontent.com/12936286/141485895-b1507eaf-af95-49b2-8e4c-a2b8b6784b35.png)

 * igniteui-angular version: 13

**Comment by mddragnev** [comment]
Hello @Eralmidia,
Currently, we do not expose a template to change the snackbar component which is shown after adding a new row. So, in order to change the text, you should change the `resourceStrings` property of the grid. You can do something like this when having the grid object:
`this.grid.resourceStrings.igx_grid_snackbar_addrow_label = 'Your desired text';`
Please let me know if this works for you.

**Comment by Eralmidia** [comment]
Worked, thanks 😄
