### ISSUE TITLE
GroupBy row selection state not correctly updated when row is transferred between the groups

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#10507]
## Description  
When editing the only selected row in order to become part of another group where all rows are not selected, the group row checkbox of the new group should be in indeterminate state. However, it remains unchecked and none of the grid records appears as selected, although the header checkbox remains in indeterminate state.

Note: Review test scenarios 18-23 in the [groupby spec](https://github.com/IgniteUI/igniteui-angular/wiki/Group-By-Specification#test-scenarios).

 * igniteui-angular version: 12.3.x, 13.0.x
 * browser: any

**Comment by viktorkombov** [comment]
I have tried to reproduce the described behavior using 12.3.8 and 13.0.7 versions of the Ignite UI for Angular package. On my side everything works as expected and when I am moving the only selected row to a different group, the group row checkbox of the new group is in indeterminate state and the row is still selected. @mmart1n, since the described behavior cannot be reproduced anymore do you think that we can close the issue?
