### ISSUE TITLE
IgxCalendar: set weekStart globally

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#10543]
## Is your feature request related to a problem? Please describe.
If you use IgxCalendar or IgxDatePicker the `weekStart` property has to be set on every component.

## Describe the solution you'd like
It would be nice if you could set the `weekStart` default value somehow globally to avoid code duplication.

**Comment by hanastasov** [comment]
Hi @Timmeeeey , with the patch scheduled to be released today for **version 14**, the requeted feature will be available:
- ability to set `locale` and `weekStart for `IgxDatePicker`, as it has been available for the calendar
- ability to set `weekStart` per column for the grid, through the `pipeArgs` input property
- if not set, `locale` will inherit the value of the global application locale
- if not set, `weekStart` will be read from current locale

Since to achieve this new props are introduced, change is only introduced in version 14. Is this the version that you are using?

**Comment by Timmeeeey** [comment]
Hi @hanastasov, yes I am using version 14.

**Comment by hanastasov** [comment]
@Timmeeeey , the feature is going to roll out with version 14.1, not with minor patch of version 14.0. Sorry for misleading you with my information. Is that ok with you? I will try to give you an estimate of 14.1 release soon.

**Comment by Timmeeeey** [comment]
@hanastasov Version 14.1 would be ok for me, thanks!

**Comment by zdrawku** [comment]
As we discussed with Hristo, this feature will be available with the 14.0.6 weekly patches release next week.
