### ISSUE TITLE
Pinned and mini modes of navbar throw errors in the console

### ISSUE THREAD

**Issue by katherinedragieva** [IgniteUI/igniteui-angular#10570]
## Steps to reproduce  

1. Open igniteui-angular samples
2. Go to Navdrawer
3. Clock on the Pinned Navdrawer and Mini variant 

## Result  
With each click Pinned Navdrawer and Mini variant throw errors in the console
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/35975071/142580502-35fe6f00-1b9d-41e9-bf9a-578bdaed7aa8.png)

**Comment by Volen99** [comment]
After investigating, everything seems to work correctly in the library, my only guess is that the problem is in the sample.
In the Navdrawer sample, we use **this.app.navdrawer.isOpen** on the first visibility switch.
![image](https://user-images.githubusercontent.com/41373491/166694300-3032749e-427b-4c15-8d92-377b27f4f0ee.png)
![image](https://user-images.githubusercontent.com/41373491/166694975-88a58c33-a1df-43bc-9c80-dd043742eba9.png)


And when we click on any of the other switches
![image](https://user-images.githubusercontent.com/41373491/166694401-946de551-e8c1-4307-a2f9-cdca03f2b0bd.png)

**this.app.navdrawer.isOpen** is changed and it triggers the error. I tried to notify the component for the change with ChangeDetectorRef, but with no success :( 

Still, this error is shown only locally.

**Comment by hanastasov** [comment]
Issue is in the sample.
