### ISSUE TITLE
Azure DevOps Issues (with private support case)

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#10605]
C-00220605

**Comment by kdinev** [comment]
To elaborate, the issue is with Azure DevOps builds that use an on-prem agent. In the specific case `npm config set` commands do not populate the correct `.npmrc` that the agent uses for the build, hence the private package feed for the licensed `@infragistics/igniteui-angular` package does not get resolved upon `npm install`. The build tries to acquire the package from the default npmjs feed.

**Comment by ChronosSF** [comment]
I created a small sample pipeline in Azure DevOps that installs Node 10.24.1 and npm 6.14.12 . Node is installed by a predefined step called Use Node.js ecosystem (Preview) task version 1.* .

Then followed the guidance in the igniteui-angular docs for setting up an Azure pipelines build.

The build worked both on an on-prem build agent and on an Azure hosted one without issues. At this point what I can suggest is to try the pipeline that fails on an Azure hosted agent (windows-2019 specification) to exclude issues with the local one. I suspect that there are permission-related issues for the user that runs the agent process or something of this kind outside the pipeline setup itself.
