### ISSUE TITLE
[igxPivotGrid] ESF dropdown doesn't always reflect data

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#10626]
## Description  
The ESF dropdown doesn't always reflect what's in the grid.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the `/pivot` dev sample
2. Toggle the ESF dropdown for the City-row chip
3. Unselect Plovdiv
4. Close the row dropdown and toggle the dropdown for the Country-column chip
5. Unselect Bulgaria
6. Toggle the City chip's dropdown again
7. Observe that the values for Sofia and Plovdiv are still there, although all data for the two cities has been filtered out from the Country chip

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
I've compared it to the base grid and it seems that the order in which the expressions are applied matters.
For example in the first sample:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering
If you filter out from the first column all values except Chai and Chang and then go to the last boolean column and filter out the false values you'll get just 1 record, but the first drop-down will still show all values:

![image](https://user-images.githubusercontent.com/10397980/143435817-c189328d-fa32-4537-b24c-10fe3fefc444.png)

And Chai and Chang will remain selected even though Chai does not match the second filter.

This seems to be by design so I suggest we keep it the same in the pivot grid as well.
