### ISSUE TITLE
Accordion panels jumps on opening

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#10695]
## Description  
Accordion panels jumps on opening

 * igniteui-angular version: 
 * browser: All

## Steps to reproduce  

1. Open the accordion sample in dev demos
2. Collapse all header so it's easy to spot the problem
3. Clik on the second or third header to expand it and observe how a white gap is appearing between the headers.

## Result  
There is a white gap between the headers only when the panel is expanded

## Expected result  
Either there should not be a white gap at all, or if there is, it should be there, no matter if the panel is expanded or collapsed.

## Attachments  
![2021-12-07 11 26 06](https://user-images.githubusercontent.com/21260963/145002985-20418dcf-3d1f-4390-a301-0508608f3417.gif)

**Comment by StefanIvanov** [comment]
The gap is by design and according to the google material spec. It's size is configurable but by default it is not zero. However, I agree with you that the way it jumps is not optimal and we should apply an animation to it like for example the smooth transition we have here: https://mui.com/components/accordion/

**Comment by StefanIvanov** [comment]
@radomirchev should we assign also Teddy from Astrea on this as it looks like an enhancement we can add with a patch
