### ISSUE TITLE
Dropdown is closed on space and it is not possible to be prevented

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#10720]
## Is your feature request related to a problem? Please describe.
Not able to prevent close on space click when typing on input with igxDropDownItemNavigation  

## Describe the solution you'd like
Expose props like closeOnEnter, closeOnSpace etc.

**Comment by damyanpetev** [comment]
@Aleksandyr I think this request warrants a bit more detail.
So the feature request is specifically targeted at scenarios where the drop-down is used with a text field, right? That's kind of important distinction.
It's also not the close that needs preventing - the drop-down closing is merely part of the selection process, so what you're asking for is for the selection not to happen on space so it doesn't interfere with typing in the field, right? I'd leave Enter out though, with an open drop-down it should definitely go to selection first and then submit (if any).

Technically, this is controlled by the navigation directive entirely and it's pretty easy to either override the behavior of the key handle if you need to TBH or to add an option to the directive to ignore text entry keys. We could also add another directive specific to text input - but hey, we already kind of have one: the `igxAutoComplete`. That already overrides the key handling of the base navigation directive to avoid interfering with text entry.

So, I'd really love to know more about the scenario - because we already have a directive that should handle suggestive text input, while fixed selection should well be handled by either a select or one of the combos, right? Kind of curious what's missing.

PS: There's also the matter of the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/DropDown-Specification) describing both space and enter as selection (and thus close) keys, but the drop-down is more of a building block and its behavior is not that rigid due to use in different scenarios, so we should probably amend that a little.

**Comment by Aleksandyr** [comment]
@damyanpetev Actually we ended up using the `igxAutoComplete` directive.
The use case was pretty straightforward. We needed a filterable dropdown displaying users.

We were actually discussing this with @wnvko on that day and we've ended up with this issue.

The more I think about it the more I realize that this change might be abandoned.

**Comment by damyanpetev** [comment]
Okay, good. In that case there seems to be very little to be gained from such feature right now (most cases covered by existing directives and components) and it can be closed for now.
