### ISSUE TITLE
Grid consumes scrolling of scrollable cell/summary templates

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#10749]
## Description  

When a templated cell or custom summary cell has a scrollbar and the grid (IgxGrid, IgxHierarchicalGrid, IgxTreeGird) also has one, the templated cell cannot be scrolled with the mouse wheel.

 * igniteui-angular version: -
 * browser: any

## Steps to reproduce  
Cell Templates (IgxGrid)
1. Open this [sample](https://stackblitz.com/edit/igx-grid-scrollable-cell-templates?file=src/app/grid/grid-select/grid-select-sample.component.html)
2. Try to scroll any of the "Character name" column's templates
3. Observe the grid is scrolled.
4. Scroll grid to bottom.
5. Scroll the last row's template to bottom.

Summary Templates
1. Open the IgxHierarchicalGrid Summary Template [sample](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/summaries) (staging)
2. Expand any parent row
3. Attempt to scroll the custom summary cell that has a scrollbar.

Also reproduced in the IgxGrid Summary Template [sample ](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/summaries#summary-template)(staging), when there are grouped columns. 
The templated summary cell for the root level is correctly scrolled.

## Result  
The grid is getting scrolled.  Scrolling the templated cell with the mouse wheel only has effect, when the grid is scrolled up to the bottom, and the template in the last row is scrolled in the corresponding (bottom) direction, for example. 
![scrolling](https://user-images.githubusercontent.com/35433937/146532108-757abed2-2356-4861-8d37-8ddb186d4ff3.gif)

## Expected result  
To be able to scroll the templated cells with the mouse wheel.

**Comment by ChronosSF** [comment]
@rkaraivanov , do you think we should even support this?

**Comment by rkaraivanov** [comment]
@ChronosSF 
It will be a nice thing to have.
I think someone can take a look at it and if the implementation turns out to be
hairy or breaks some other behavior of the grid, then we can skip it.

**Comment by ChronosSF** [comment]
Fair enough. I'll look into it today and see if it is something that we can do.

**Comment by ChronosSF** [comment]
I started looking into it but noticed something that would make it potentially pointless - even if you can scroll inside the views, when the view gets out of the visible area and is reused for another row, the scroll position is getting lost. Customers will need to implement a custom solution to save and restore these states for the behavior to look native to end-users.

**Comment by rkaraivanov** [comment]
This is true, however I still think it'd be nice to be able to scroll overflown content inside the grid view even if the scroll position is lost eventually.

**Comment by ChronosSF** [comment]
We'll need something like this: https://github.com/IgniteUI/igniteui-angular/pull/10781/files because the outer container is not normally scrollable and requires full custom logic. This means its handler has to be able to tell if an inner element scrolled and if it can still scroll in that direction.

The `while` has to break when it sees a display container because otherwise the logic fails in hierarchical grids. The tbody of a grid is always considered scrollable because it renders a bit more than what it is capable of, however we scroll it using transformations not scrollTop so the logic like this will always stop parent hierarchical grids from scrolling after their children reached the end of their scrolls.

If you are ok with something like this, I'll assign it for some testing. It seems to do the job.
