### ISSUE TITLE
IgxGrid filter: IgxDatePicker.weekStart not changable

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#10852]
## Is your feature request related to a problem? Please describe.
Currently it is not possible to set `weekStart` for grid IgxDatePicker filter.
It is always set to Sunday.

## Describe the solution you'd like
A possible solution would be to make `weekStart` globally configurable.
See #10543

## Describe alternatives you've considered
Alternatively the first day of week could be read from current locale.

**Comment by hanastasov** [comment]
Hi @Timmeeeey , with the patch scheduled to be released today for **version 14**, the requeted feature will be available:
- ability to set `locale` and `weekStart for `IgxDatePicker`, as it has been available for the calendar
- ability to set `weekStart` per column for the grid, through the `pipeArgs` input property
- if not set, `locale` will inherit the value of the global application locale
- if not set, `weekStart` will be read from current locale

Since to achieve this new props are introduced, change is only introduced in version 14. Is this the version that you are using?

**Comment by hanastasov** [comment]
@Timmeeeey , the feature is going to roll out with version 14.1, not with minor patch of version 14.0. Sorry for misleading you with my information. Is that ok with you? I will try to give you an estimate of 14.1 release soon.
