### ISSUE TITLE
Changing a column's width at runtime through the API does not work unless a data operation is performed afterwards

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1087]
### Description  
Changing a column's width at runtime through the API does not work unless a data operation is performed afterwards.

**NOTES:**
Performing  sorting, filtering, pinning or just selecting a cell from the grid after the width of a column has been set through API fixes the issue (updates the width of the column).

### Steps to reproduce  

1. Run the attached sample application.
2. Click the button under the igx-grid.

### Result  
The column's width remains unchanged.

### Expected result  
The column's width is changed.

### Attachments  

![width](https://user-images.githubusercontent.com/12784974/39047785-e044d1e6-44a3-11e8-89e2-e3a2efba422a.gif)
[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1931845/igxgridSample.zip)

**Comment by zdrawku** [comment]
This is going to be closed with by-design label

**Comment by Aleksandyr** [comment]
This is by design. Performance issues would appear if we are forcing the grid to detect himself on every update of the property.
The user would have to handle this on application level by invoking markForCheck(which triggers changeDetection per every row) grid method when the corresponding property is updated.
