### ISSUE TITLE
Setting the "header" or "filterable" property of a column at runtime does not work unless the header is clicked

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1089]
### Description  
Setting the "header" and/or "filterable" property of a column at runtime does not work unless the header is clicked.

### Steps to reproduce  

1. Download and run the attached sample application.
2. Click the button under the igx-grid.

### Result  
The header is **not** updated and the filtering icon is **not** visible.

### Expected result  
The header is updated and the filtering icon is visible.

### Attachments  

![refresh](https://user-images.githubusercontent.com/12784974/39049100-abafbcc0-44a8-11e8-88ec-29cc8f06a2a0.gif)
[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1931954/igxgridSample.zip)

**Comment by Aleksandyr** [comment]
This is by design. Performance issues would appear if we are forcing the grid to detect himself on every update of the property.
The user would have to handle this on application level by invoking markForCheck(which triggers changeDetection per every row) grid method when the corresponding property is updated.
