### ISSUE TITLE
Setting "hasSummary" property of a column at runtime does not work

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1093]
### Description  
Setting "hasSummary" property of a column at runtime does not work.

### Steps to reproduce  

1. Download and run the attached sample application.
2. Click the button under the igx-grid.

### Result  
The summary of the "ID" column is **not** displayed.

### Expected result  
The summary of the "ID" column is displayed.

### Attachments  

[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1931968/igxgridSample.zip)

**Comment by Aleksandyr** [comment]
This is by design. Performance issues would appear if we are forcing the grid to detect himself on every update of the property.
The user would have to handle this on application level by invoking **markForCheck**(which triggers changeDetection per every row) grid method when the corresponding property is updated.
