### ISSUE TITLE
The selection in the last grid column does not span in the whole cell.

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1115]
### Description
The selection in the last grid column does not span in the whole cell.

### Steps to reproduce
Place a grid, where columns have their width set, but the columns' total width is less than the grid width.

### Expected result  
Selection to span the whole space.

### Attachments  
![39047063-3baa78e0-44a1-11e8-92cb-a11eaba4130e](https://user-images.githubusercontent.com/14248932/39123027-425f812a-46ff-11e8-84d8-3d562ec403f1.png)

**Comment by ChronosSF** [comment]
This is expected. Selection spans the exact set width of the last column. The remaining space is not covered by columns. 

@SlavUI , @rkaraivanov , @simeonoff  - one way to make it look less like an issue is to have a border on the last cell so the column area can be properly distinguished from the rest but imo it's not worth the added complexity.

**Comment by zdrawku** [comment]
@SAndreeva, could you share your proposal here. By my oppinion you can go ahead and implement a change for better look of the border and resizing action.

**Comment by SAndreeva** [comment]
I would suggest doing the following:
1. Adding a right border to last column header and summary.
2. Remove the subtracted 18px from the last cell width, so that cells, headers, summaries are equal in size and match the width property set on that column.
3. In case we have a vertical virtualization, we should add another 18px to the horizontal virtualization, so that the last column is not visually covered by the vertical scrollbar. 
The final result should be something like that:
![lastcol](https://user-images.githubusercontent.com/7972965/39744381-b7b7f606-52ac-11e8-816a-7713cad8c01f.png)

**Comment by hanastasov** [comment]
That's nice, but how would that play when there is more than 18px between the far right border of the last column and the scrollbar/ grid far right border ?

**Comment by SAndreeva** [comment]
The far right border marks the end of the last column. The remaining space is just another "fake column", no matter whether it is 18px or more, it spreads to the end of the gird. This is the way it has always been. The only difference is that now we will have a visual indication where the column actually ends, which will make it easier for the end user to perform actions like resizing. The way it is now, we cannot see where the last column ends and we are left we the pseudo impression that the last column fills all the available space...

**Comment by SAndreeva** [comment]
And we remain confused after selecting a cell, because we expect the selection to fill all the available space either.

**Comment by ChronosSF** [comment]
The original issue is behavior by design.

The remaining points are mostly covered by #3396 and solved by #3668
