### ISSUE TITLE
igx-simple-combo - Cannot use falsy values as valid selection values

### ISSUE THREAD

**Issue by mikerentmeister** [IgniteUI/igniteui-angular#11357]
## Description  
I am using an igx-simple-combobox to represent possible boolean values in our database. Null, True, and False are the 3 states that I need to be able to support, and let the user change values between the 3 states. (I thought about using an indeterminate checkbox to represent null, but there isn't a great way for users to set indeterminate themselves via clicking on the checkbox). I setup an array to represent these values, but users cannot actually persists a null/false selection, because it's falsy.

 * igniteui-angular version: 13.1.8
 * browser: chrome 100.0.4896.75

## Steps to reproduce  

1. [Stackblitz example](https://stackblitz.com/edit/angular-qxgo6e?file=src/app/lists/combo/simple-combo-main/simple-combo-main.component.ts)
2. The loaded combobox values should display "Null" to start with, but it does not
3. Try changing the selection to false instead and observe that nothing happens, and no `(selectionChanging)` event is emitted
4. Select "True" from the drop down, an `(selectionChanging)` event is emitted
5. Now try changing the selection from "True" to "False", no event is emitted and the value is not changed

## Result  
No selections of "Null" nor "False" are persisted

## Expected result  
Falsy values should be valid selections

**Comment by kdinev** [comment]
@mikerentmeister Since you have only 3 possible values, it might be better to use an `igx-select` instead of a simple combo. The combo has the advantage that you can filter larger data sets to select a single item, but with only 3, the select should be the better component. In a select, your binding would look like this:

```html
<igx-select [(ngModel)]="state">
  <label igxLabel i18n>Boolean Values</label>
  <igx-select-item *ngFor="let state of statesList" [value]="state.value">
	{{ state.display }}
  </igx-select-item>
</igx-select>
```

```ts
  public state = null;
  public statesList = [
    { display: 'Null', value: null },
    { display: 'True', value: true },
    { display: 'False', value: false }
  ];
```

**Comment by kdinev** [comment]
@mikerentmeister I'm going to close this issue, since `igx-select` would satisfy your usecase. 

Just to mention that the `selectionChanging` and any `ing` event fires before the action is completed, so the value shown is prior to the change. The `selectionChanged` is the one that would give you the value after the change.
