### ISSUE TITLE
DatePicker doesn't support 'MMM' as input formatter and shows f.e. "04_" instead of "Apr"

### ISSUE THREAD

**Issue by yl-endress** [IgniteUI/igniteui-angular#11350]
### Description  
A configured datePicker with the formats
`  [inputFormat]="'dd/MMM/yy'"
    [displayFormat]="'dd/MMM/yy'"`
will show f.e. 
- "06/Apr/22" as displayed value (OK)
- "06/04_/22" when clicking on the datepicker (not ok) 

**Note: it would be really nice if you add in your documentation information about the supported formats.**

 * igniteui-angular version: ~13.1.1
 * browser: Chrome Version 99.0.4844.84 (64-Bit)

### Steps to reproduce  

1. Configure input and display format as "dd/MMM/yy"
`  <igx-date-picker
    [(ngModel)]="date"
    [inputFormat]="'dd/MMM/yy'"
    [displayFormat]="'dd/MMM/yy'"
  >
  </igx-date-picker>`

You can easily reproduce it by modifying your example of 
https://stackblitz.com/edit/angular-nlkcjj?file=src%2Fapp%2Fdatepicker-sample-3%2Fdatepicker-sample-3.component.html

### Result  
"06/04_/22"

### Expected result  
"06/Apr/22"

### Attachments  
![image](https://user-images.githubusercontent.com/44203645/161926283-263c71a7-e0a8-443f-a6d8-979069fce234.png)

**Comment by jackofdiamond5** [comment]
Hi @yl-endress, the `IgxDatePicker` uses the [IgxDateTimeEditor](https://www.infragistics.com/products/ignite-ui-angular/angular/components/date-time-editor) internally which provides it with editing and formatting capabilities, this is mentioned in the [Display and input format](https://www.infragistics.com/products/ignite-ui-angular/angular/components/date-picker#display-and-input-format) section of the picker's documentation. For your convenience, [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/date-time-editor#display-and-input-format) you can find the table with all of the supported formats. In it you will see that the `MMM` format is not mentioned and this is because, by design, the editor uses numeric values while in edit mode.

**Comment by yl-endress** [comment]
Thank you! At the time I am kind of confused that the component provides 2 different formatters that behave differently. I expected the same functionality here + that it is somehow more present, that the [IgxDateTimeEditor](https://www.infragistics.com/products/ignite-ui-angular/angular/components/date-time-editor) is reused for this functionality.

It just feels weird/unexpected when you see the date formatted with "MMM", you click on it, and the format changes
