### ISSUE TITLE
Hierarchical Grid Virtualization: Poor scroll performance

### ISSUE THREAD

**Issue by Poseclop** [IgniteUI/igniteui-angular#11403]
## Description  
When scrolling through a virtualized hierarchical grid. I get a lot of "lag" while scrolling which makes it uneasy to use. After a few tests I discovered three potential suspects:

1. Non passive scroll events bound to the grid ![image](https://user-images.githubusercontent.com/37383113/163363131-b0763e9c-96f3-46d1-b2e1-e67e6530f889.png)
![image](https://user-images.githubusercontent.com/37383113/163365553-7cc93abb-6b24-4027-87c1-896821012be7.png)

2. Several Forced reflow when a row-island appears into the view (seems to be linked to [this](https://github.com/IgniteUI/igniteui-angular/blob/52c21d7822e4a4df70e2486d4557502282c5668b/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L6437))
3. Last, having structural directives in the cells template (ngIf or ngSwitch in my case) seem to make the problem much worse.

 * igniteui-angular version: 11.1.2
 * browser: Microsoft Edge Version 100.0.1185.39 (64bits)

## Steps to reproduce  

1. Create a hierarchical grid and ensure it has a set height
2. Scroll through it

## Result  
Scroll gets regularly blocked for 100-600ms. Browser shows warning for non passive events, 

## Expected result  
No "lag" and warnings in the console

## Attachments  
Just an exemple of what our hierarchical grid looks like:
![Just an exemple of what our grid looks like](https://user-images.githubusercontent.com/37383113/163365869-07a0a483-7b9a-426e-97cf-acd1f4517056.png)

**Comment by ChronosSF** [comment]
The hierarchical grid is by far the worst-case scenario for how virtualization is designed to work. Major factors are the constant swap of templates when all rows are expanded and the unequal heights of the elements (which is what your second point stems from). 

We'll certainly take another look to see if there haven't been any performance regressions but outside of those or completely reworking virtualization for HierarchicalGrid specifically (as it functions perfectly well for other types of grids) you shouldn't expect major performance gains.

Not trying to dismiss your concerns with scrolling performance but even if we can do something about it won't come soon / or at all.

If you need butter smooth scrolling you may look into changing your data structure fed to the grid so that it is possible to display the hierarchy with a tree grid or a flag grid with grouping.
