### ISSUE TITLE
grid.columns not getting initialized on ngAfterViewInit

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#11438]
## Description  
I had recently upgraded Ignite version and my existing code broke. I was using **grid.columns** on ngAfterViewInit() and it returned an empty array whereas previously it always returned the columns array. However **grid['_columns']** had the columns data. 
I am attaching the project file where the issue is recreated. 
[angular.zip](https://github.com/IgniteUI/igniteui-angular/files/8511908/a.zip)

 * igniteui-angular version: 13.1.8
 * browser: Chrome

## Attachments  Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/79090369/163978734-259c5cf7-6819-423d-8e85-d1630a3117e9.png)

**Comment by amitmoondra** [comment]
can someone look into this ASAP?

**Comment by kdinev** [comment]
@amitmoondra Use the `rendered` output, in order to have consistent access to the columns collection. The reason why, depending on the use-case, grid `rendered` may emit before or after `ngAfterViewInit`. If it's emitted before, the `columns` getter returns an empty array, because tapping into dynamic components (`IgxColumnComponent`) prior to the grid finishing its rendering lifecycle, may result in an undefined behavior.

**Comment by ChronosSF** [comment]
@KaushikEDS , please reopen the issue, if @kdinev's suggestion doesn't work for you or you have other concerns.
