### ISSUE TITLE
Fluent theme 'Datepicker' icon location

### ISSUE THREAD

**Issue by bzupancic** [IgniteUI/igniteui-angular#11474]
According to the Fluent UI Design System, the calendar icon should be aligned at the end of the date-picker input. Currently it is in the prefix.

On a related note, the icons for the dropdown chevron, date-picker calendar, combobox clear, are all placed inside the prefix or suffix which has a background of `hsla(var(--igx-grays-100), var(--igx-grays-a))`. This doesn't match the Fluent UI Design System.

**Comment by sdimchevski** [comment]
@bzupancic Hey, thanks for the comment! We've never had the plan to be 100% compliant with any of the design systems that we have themes for. Our themes are **inspired** by the different design systems and not an exact replica. So the decision to have certain background and to have the calendar icon in the prefix of date-picker input is by design.
