### ISSUE TITLE
Improve formatter and styles API for the IPivotValues

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#11531]
## Is your feature request related to a problem? Please describe.
Users need more context information for cell formatter and styling specific API's in the context of the PivotGrid.

## Describe the solution you'd like

The existing parameters for rowData in the [formatter](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IPivotValue.html#formatter) and the [styles](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IPivotValue.html#styles) APIs can be changed to pass the [IPivotRecord](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IPivotGridRecord.html) object since it has more contextual information on the row dimensions and their values.

One additional columnData parameter can be added for more context on the column to which the current cell belongs to.
For consistency it should also have the `dimensionValues` and `dimensions`.

**Comment by MayaKirova** [comment]
@ChronosSF @kdinev This can be considered to be breaking change since one of the optional parameters - rowData of the [formatter](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IPivotValue.html#formatter) and the styles changes to now contain the full [IPivotGridRecord](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IPivotGridRecord.html) instead of just the [aggregationValue](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IPivotGridRecord.html#aggregationValues) object. 
The request to add more context in the methods comes from a customer and we would consider this an improvement to the current API.

Let us know if this change sounds ok and if so whether we can also add it to 13.1.x or since it's a breaking change it can only be added in 13.2.x

**Comment by kdinev** [comment]
@MayaKirova Since the `rowData` parameter is of type `any`, can the change be to give a concrete type to the parameter and to include both `aggregationValue` and `IPivotGridRecord` in the parameter? Would that make sense? If we do that, then it should also be possible to implement a migration where all current use of `rowData` is migrated to `rowData.aggregationValue`.

**Comment by MayaKirova** [comment]
IPivotGridRecord already contains the aggregationValues as a property, however they're stored in Map vs just a plain object.
So I'm not sure we can migrate it from something like this:
`
formatter: (value: any, rowData: any) => rowData['someField'];
`

To:

`
formatter: (value: any, rowData: IPivotGridRecord) => rowData.aggregationValues.get('someField');
`

@damyanpetev Would a migration like that be possible? I don't think we have anything that complex out of the box, but maybe some custom migration scoped to just the formatter function in the IPivotValue object?

**Comment by damyanpetev** [comment]
In theory anything is possible, however at least atm not through the available configurable migrations - those cater to renames of classes and properties of components (either attributes or class members), but this is neither of those things.

You could probably do it custom, but it'd be a bit of work to properly detect the formatter since it was previously typed as `any` and you can't search for the `IPivotGridRecord` type directly. So it'd be going from the grid options to find the possible formatter callback somewhere in the code, likely not super simple
