### ISSUE TITLE
Pie chart - some properties don't work when creating custom themes 

### ISSUE THREAD

**Issue by SisIvanova** [IgniteUI/igniteui-angular#11558]
## Description  
The $labels-position, $leader-line-type, and $radius-factor properties of the pie chart component don't work when used in a custom component theme.

 * igniteui-angular version: 13.0.0 / 13.1.1

## Steps to reproduce  

1. Create a pie chart component
2. Create a custom pie chart theme
3. Try to change any of these properties: $labels-position / $leader-line-type / $radius-factor 

## Result  
The values specified in the custom theme produce CSS variables but don't take effect.

## Expected result  
The default values should be overwritten by the ones in the custom theme.

## Sample
https://stackblitz.com/edit/angular-hhghly-vnanwj?file=src/app/pie-chart/pie-chart.component.scss

**Comment by damyanpetev** [comment]
@simeonoff @SisIvanova Most likely those specific properties (label position, leader type and radius factor) fall under the configuration category rather than styling, so it makes sense they don't accept corresponding CSS variables.

**Comment by simeonoff** [comment]
@gmurray81 can you confirm that the properties that don't work in the attached example are not meant to be configurable via CSS custom props?

**Comment by gmurray81** [comment]
Huh, sorry, missed this. I think those would be config and not styling yes. Although I'm of two minds about the radius factor... 
I mean the other two are a bit debatable also, perhaps we should consider widening what we consider styling... Do you guys have strong feeling either way where to draw the line?

**Comment by gmurray81** [comment]
One way to draw the line is to consider the props that you would need to mutate to move from a light to a dark theme, or from bootstrap to fluent to be styling rather than config, and the rest config. But that might be too narrow given the quantity of things that CSS generally lets you tweak that aren't strictly styling.

**Comment by simeonoff** [comment]
I think @sdimchevski should also chip in on the issue.

**Comment by damyanpetev** [comment]
@simeonoff @sdimchevski
Should we have open still? Because I don't see a conclusion to the discussion, then again it's also not necessarily a bug or in the repo specifically.

PS: My 2c for the the label position at least - I believe that's in large part reliant on the data, i.e. the number of slices and their sizes, but also on the size of the entire pie and the radius. All of those dictate how much space there is for the labels and where and I'm not entirely certain we could (or should) try to dictate those through styling alone.
