### ISSUE TITLE
igx-slider label ticks have z-index: -1 and are not visible

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#11597]
## Description  
I'm using an `igx-slider` component with defined slider tick, which are not visible because of `z-index: -1` applied by the theme.

 * igniteui-angular version: 13.1.11
 * browser: N/A

## Steps to reproduce  

1. This is the component template: https://github.com/BellumGens/bellum-gens/blob/css-updates/projects/bellumgens/src/app/search/player-search/player-search.component.html

## Result  
Slider ticks are not visible.

## Expected result  
Slider ticks should be visible.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/169524281-04ffaf97-ccf0-4346-85c7-2ede9cb76090.png)
![image](https://user-images.githubusercontent.com/1472513/169524378-87d51c6f-27b7-4d9f-9d97-bad6b6dde652.png)

**Comment by desig9stein** [comment]
@kdinev the problem is that I've missed adding `z-index: 0` on the ` igx-slider` and because of that the stacking context for the element that has a `z-index:-1` is not correct. The solution is simple, I have to add `z-index: 0` to the `igx-slider`. Meanwhile, if you can't wait, as a quick fix you can add `z-index: 0` to the first element that holds your slider and changes the stacking context by having a position different from static. My guess is that in your case this is the `<form>` element or the `<div>` with `class="form-row"`.
