### ISSUE TITLE
IgxGrid: When the grid is being resized vertically its body flickers

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#11605]
## Description  
When the position of the grid's vertical scrollbar is not in the beginning and the grid is being resized vertically, its body is starting to flicker.

 * igniteui-angular version: 11.1.x, 12.3.x, 13.1.x, 13.2.x
 * browser: any

## Steps to reproduce  

1. Open the following sample - [here](https://stackblitz.com/edit/angular-2gppqt).
2. Scroll the first grid.
3. Move the splitter.

## Result  
The body of the first grid flickers.

## Expected result  
The grid's body should not flicker.

**Comment by mddragnev** [comment]
@viktorkombov 
Could you please verify that the issue is still reproducible in the supported branches. I have tested it in 13.2.x and cannot reproduce the same behavior like on the stackblitz sample. Here is a PR https://github.com/IgniteUI/igniteui-angular/pull/11503 which I have made couple of weeks ago that probably have fixed the issue.
Please let me know if you manage to reproduce and please share your exact steps.

**Comment by viktorkombov** [comment]
@mddragnev 
On my side the issue is still reproducible even if I am using 13.2.x version.
