### ISSUE TITLE
IgxComboComponent missing input template

### ISSUE THREAD

**Issue by katherinedragieva** [IgniteUI/igniteui-angular#11601]
## Is your feature request related to a problem? Please describe.
Currently I'm trying to set uppercase to the input value, but without success because of missing template for the input.

## Describe the solution you'd like
There should be a template for rendering the input so it can be used to modify the value of the input.

Right now if the values in the combo are with capital letters, it looks like  this:

![image](https://user-images.githubusercontent.com/35975071/169539045-795cef50-599c-4c0b-ba3e-85ef2359531c.png)

**Comment by imincheva** [comment]
The Design team has been made aware, that this issue is related to an enhancement we'd like to introduce in the Query Builder.

Currently, when a user selects all available items from the "Select return fields" Combo, the input value lists the names of all return fields.
<img width="892" alt="image" src="https://github.com/user-attachments/assets/96412c20-8552-4096-857e-f436d7d2501b">

In order to improve the UX, we'd like to introduce the following enhancement: instead of listing all return fields, the input value should return "All fields"
