### ISSUE TITLE
IgxCombo: Cannot select falsy values

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#11610]
## Description  
IgxCombo can't select items with falsy values like false, null or empty string.

Related to #11357

 * igniteui-angular version: 13.1.16
 * browser: Chrome

## Result  
Falsy values can't be selected.

## Expected result  
Falsy values should be selectable.

## Attachments  
https://stackblitz.com/edit/angular-obbbi4

**Comment by RivaIvanova** [comment]
@Timmeeeey, the described behavior is expected as while the display key (i.e., field) can be a falsy value, the value key (i.e., value) cannot, since it is used by the selection service as an identifier to determine what item should be added to the selection.

Having this in mind, in the newly introduced fix, items with falsy value keys will not be displayed in the combo in order not to confuse the users.

**Comment by Timmeeeey** [comment]
Hi, you said it is expected behaviour but is it intended?
I have a use case where I have to select objects with falsy value.

**Comment by kdinev** [comment]
@Timmeeeey Actually, the functionality should be the opposite of what @RivaIvanova is describing. Search should be performed by display value - it's what users see, so it makes sense search to search by the values they see - and display values should always be strings, so the only falsy value possibly there is `''`. Selection on the other hand is performed by value key, which should be unique and should allow any type of falsy value, as long as they are unique in the set provided.

@RivaIvanova I looked over the PR and I believe a different fix should be applied.

**Comment by kdinev** [comment]
This issue is a regression introduced with [#11206](https://github.com/IgniteUI/igniteui-angular/pull/11206)
