### ISSUE TITLE
Order by count in igx-grid group by

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#11642]
## Is your feature request related to a problem? Please describe.
When using the group by feature, you can set the sorting direction to alphabetical asc og desc, but you can sort by the number of occurrences in each group.

## Describe the solution you'd like
A new sort direction for count, or perhaps this could be default sorting if the sorting direction is set to None?
![image](https://user-images.githubusercontent.com/12936286/171131552-52c9abcb-547b-44f8-9e3c-6221a5d1fbc3.png)

**Comment by kdinev** [comment]
@ChronosSF wouldn't a custom sorting strategy change the grouping though? In this case the sorting would have to be the same, but a way for sorting the actual group headers would have to be introduced? Or you're suggesting to sort additionally after the alphabetical sort by reordering the unique values by number of occurrences? Can you provide an example?

**Comment by ChronosSF** [comment]
The custom strategy would sort twice - once to group the values into chunks then to get the chunks and sort them by size. Then you can leave grouping to group the result. My assumption is that any sorting on grouped columns would sort the groups by size so no extra UI is needed, but of course it can be wrong.

It's just a suggestion because barring the new UI, it can be achieved with the current feature set. If we are to release it as new functionality, it's unlikely the customer will get it this soon.

**Comment by kdinev** [comment]
@ChronosSF Seems to me that an additional UI needs to be provided for this feature, because sorting direction by occurrence should also be modifiable (ascending, descending), while the regular sorting should also be controllable through the chip UI, as it currently is. @sdimchevski Could you take a look at this FR and we can discuss?

**Comment by Svetloslav15** [comment]
Here is a PR creating custom sorting strategy for this scenario, and applying it in the groupBy sample. This can be achieved without breaking the current sorting behavior. First when groupBy is applied rows are sorted in asc order by fieldName, when the button for "Sort By Group Asc/Desc" is clicked, first time the groups will be sorted by number of values in each group DESC and if we click second time  they will be sorted in ASC order. 
![grid-group-by](https://user-images.githubusercontent.com/33124382/223719012-1055c3ea-ad20-4da7-9839-d50460d1ed81.gif)

**Comment by kdinev** [comment]
@Svetloslav15 The newly exposed grouping strategy looks good to me.

**Comment by hanastasov** [comment]
The PR will not wait for design, we can verify the code and even merge it. However, @sdimchevski  I think you can use thge dev demos and see how the feature works, if this would help with considering if any UI is needed.
