### ISSUE TITLE
Igx Grid allow cell selection on specific columns

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#11704]
## Question  
I am using the igx-grid component.
I have set the cellSelection property as 'multiple'.
I want to allow cell selection on specific columns.

Also, I want to be notified when a cell is selected. 
I tried to find an event emitter but couldn't.
 
 is there a way to achieve these in igx-grid.
 
 * igniteui-angular version: 
 * browser:

**Comment by KaushikEDS** [comment]
Thanks, @mddragnev.
For now, **selected** will do the trick. 
Should I close this thread or leave it open?

**Comment by mddragnev** [comment]
@KaushikEDS,
You can leave it open for now. I have made the question a feature request.

**Comment by dkamburov** [comment]
It's been almost an year since the issue was created. I assume the customer managed to achieve his goal by the selected event.

Not sure if that's feasible, but if we make the selected event cancelable maybe the scenario can be achieved and at first glance shouldn't be a big item if we agree with that approach.
@mddragnev any comments on that or anything I'm missing?

**Comment by dkamburov** [comment]
I don't think we should at this point, let's close it and please re-open it if needed.
