### ISSUE TITLE
[PivotGrid] Aggregation Method Label

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#11736]
## Question  

Is there an available property for hiding the aggregation method label (ex. "SUM(Disc01 BaseCcy)" -> "Disc01 BaseCcy")? This would help in saving some space in the column headers section. We can use the menu from the left icon for identifying what agreggation is being used if we need.

 * igniteui-angular version: 13.2.1
 * browser: Chrome

![aggregation-method-label](https://user-images.githubusercontent.com/32940839/174560317-bb4a80ee-f67e-474e-8030-970c036908a2.png)

**Comment by MayaKirova** [comment]
@dkamburov `label` is actually used for the drop-down content value where you change the aggregation from the chip:
![image](https://user-images.githubusercontent.com/10397980/174977816-bfca9bf2-a2f9-41f5-9a4f-5368be1f42e6.png)

It is a separate UI element, so it will not change the text in the chip by design. 

Even if we introduce a second separate label property for the chip section (we use `key` ATM) the scenario will not be fully achieved since this will not remove the (). So you'll get `(Disc01 BaseCcy)` at most. You cannot get  just `Disc01 BaseCcy`.

I'd suggest adding a custom template for the chip area, something like:

```
<ng-template igxPivotValueChip let-value>
         {{ value.member }}
    </ng-template>
```

So that you can fully customize it.
