### ISSUE TITLE
[PivotGrid] Sorting Expressions

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#11740]
## Question  

We need to do the sorting remotely and for that we are using the "noopSortStrategy", "dimensionsSortingExpressionsChange" and "sortingExpressionsChange" events. When sorting any dimension, seems that the event will only include the row dimension sorting expressions, even if the sorted dimension is a column. Also, the pivot grid's "sortingExpressions" property seems to only include the ones coming from sorting values and because of this we cannot retrieve the dimension sorting expressions from it if we need them later. Could the dimension sorting expressions be included here as well or in another separate property?

Related to sorting expressions events (not sure if expected):
- The "sortingDone" method seems to fire only when sorting values are performed.
- The "sort" method seems to trigger the "sortingExpressionsChange" event without updating the sorting direction icon for the header.

 * igniteui-angular version: 13.2.1
 * browser: Chrome

**Comment by MayaKirova** [comment]
We wanted to distinguish between sorting the dimension values and the aggregation values since dimension value sorting can be done on the original data (and as such can be faster), while the aggregation values can be sorted only after all groups and aggregates are resolved (more processing needs to happen, you need the full aggregations and hierarchy before sorting so it can be slower).

We store the dimension sorting data in the dimension's [sortDirection](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IPivotDimension.html#sortDirection) property. So each dimension carries its own sort direction rather than having it in a separate collection in the grid. 

We could expose a getter (something like `dimensionsSortingExpressions`)  from the grid that can return an array of expressions based on what's on the  dimension, if that would be more convenient. But you should be able to get the sorting information from the dimensions themselves as well. Let me know if adding a property like that on the grid will help or if collecting the information from the dimensions is ok for your scenario.

We've also split the events and the API. So the `sort` method will target the aggregation values, while the `sortDimension` method can sort a dimension. Events as well are completely separate, so `sorting`, `sortingDone` and `sortingExpressionsChange` will fire only for values, while dimensions for now have only `dimensionsSortingExpressionsChange`. We haven't really anticipated the need for more events on the dimensions, but if there is such need we can add more. 

Regarding the  `dimensionsSortingExpressionsChange`  including the row dimension sorting expressions, but not the column sorting expression, that one is probably a bug and we'll investigate it further.

I hope this covers all points. Let me know if I missed something.

**Comment by MayaKirova** [comment]
@anserban Sure, we can expose a `dimensionSortingExpressions` property. @dkamburov do you think we can add it to all versions or just as a new feature in master?

I've logged the issue with `dimensionsSortingExpressionsChange ` separately here: https://github.com/IgniteUI/igniteui-angular/issues/11773

About `sortDimension`, here's a small sample where on click of a 'Sort' button it's called for a row and column dimension:
https://stackblitz.com/edit/angular-wm1vgr
Are you using it in a similar way?

**Comment by dkamburov** [comment]
@MayaKirova It sounds to me that dimensionSortingExpressions property should be available for all versions

**Comment by anserban** [comment]
@MayaKirova, thanks for the sample.
It might be an issue on our side.
Let's ignore it for now.
