### ISSUE TITLE
[PivotGrid] State Persistence

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#11741]
Similar to Data Grid, would be possible for Pivot Grid to also have the option for setting and retrieving its state object?

**Comment by mddragnev** [comment]
Hello, @anserban

I have a couple of questions. Could you please give some more info about them:
1. What is your story and do you need just the functionality state ( filtering, sorting, expansions) or everything related to the pivot grid (this includes the pivot configuration - rows, columns, values) plus the functionality state ?
2. Where do you want to store that state? Do you need it stringified so that you can store it in browser session/local storage, do you need it stored in a database or do you need it in memory like an object (application based)?

Thanks

**Comment by anserban** [comment]
We are mostly interested in preserving the functionality state of the pivot on refresh, especially the sorting and filtering expressions. 

Would be easier I think to handle this with a state object - store it in the browser's storage, retrieve it at refresh and then apply it directly onto the grid.
