### ISSUE TITLE
[PivotGrid] Filtering Expressions

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#11786]
## Question  
We are trying to preserve the filtering expressions by getting the `filteringExpressionsTree` from the pivot (on `filteringDone` event) and save it in the browser's storage. After refresh, we set it back using the same property, but it doesn't seem to do the update.

Could you please confirm if this should work or not by having a small sample/example for this particular scenario?

- igniteui-angular version: 13.2.1
- browser: Chrome

**Comment by MayaKirova** [comment]
@anserban 
The filters can be set on initialization per dimension via the pivot configuration: https://www.infragistics.com/products/ignite-ui-angular/angular/components/pivotGrid/pivot-grid-features#dimensions-filtering
Here’s a small sample: https://stackblitz.com/edit/angular-m3m4m3

If you change directly the filteringExpressionsTree, without the dimension's collection, nothing will change in the grid.

I don’t think we have a method to change filter expressions runtime for the dimensions if that’s what you are looking for. Let me know if that's the case.

**Comment by anserban** [comment]
Yes, I thought it could also be changed at runtime and wasn't sure.
Let me know if this can be added for future versions.

**Comment by MayaKirova** [comment]
@anserban 
We could add an API for filtering runtime, similar to sorting, something like : `filterDimension`. 
The other option would be if the whole pivot configuration object is changed runtime with a configuration that contains the new filters (since Angular does not trigger a change automatically if you modify an internal property like `filter` inside an existing dimension object). 

Let me know if those would help.

**Comment by anserban** [comment]
We can try changing the pivot configuration for now and maybe, once we have a state object, we will be able to use it for setting multiple filtering expressions in one go.

Adding a `filterDimension` method could also be useful to have.
