### ISSUE TITLE
Dates sorting and filtering is not behaving correctly when the date values are not date objects

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#1179]
### Description  
Sorting and filtering on date columns when the dates are strings not date objects

### Steps to reproduce  

1. Open https://angular-c5hdty-wvun1s.stackblitz.io
2. Sort or filter the column

### Result  
The dates are not sorted or filtered as expected.

### Expected result  
Dates sorting and filtering should be handled as expected

### Attachments  
![string_date_handling](https://user-images.githubusercontent.com/1182001/39248389-9d08b4ba-48a4-11e8-8b1d-e52652beda94.gif)

**Comment by zdrawku** [comment]
This is by design. It was decided that only Date objects would be used for filtering and sorting.

Date parsing should be implemented on application level.

I have created [issue ](https://github.com/IgniteUI/igniteui-docfx/issues/377)for this in docfx in order to update the documentation.

If you have further questions, ask @rkaraivanov
