### ISSUE TITLE
IgxGrid: memory leak

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#11817]
## Description  
IgxGrid instances do not seem to get properly garbage collected.

 * igniteui-angular version: 14.0.x
 * browser: tested in Chrome

## Steps to reproduce  

1. Open [this sample](https://stackblitz.com/edit/igx-grid-memory-leak-14?file=src/app/grid/grid.component.html)
2. Click on the 'toggle' button
3. Open Chrome Dev Tools -> Memory tab -> Take heap snapshot
4. Filter the snapshot by "IgxGrid.."

## Result  
An instance of the IgxGridComponent remains. Toggling multiple times and taking another snapshot shows as many instances stored as the times toggled.

## Expected result  
The IgxGridComponent to be garbage collected.

## Attachments  
![image](https://user-images.githubusercontent.com/35433937/177173380-fe7a2639-ac40-423c-aac0-6324340de2c7.png)

**Comment by wizgob** [comment]
Any news on this issue?

**Comment by ChronosSF** [comment]
This is a side effect of how ngIf handles destroying the content under the hood. It actually tries to be smart about it to be able to recreate it more quickly which leads to perpetual left-overs. This happens with any content inside really, it's not igxGrid-specific.

Check the sample I am attaching. I replaced igxGrid with a very simple Material table. There is still a reproducible leak, albeit smaller (mostly due to Material table being a simpler grid implementation with a lot less code than igxGrid). To help make it more noticeable I added a button to start/stop a toggle loop.
[igx-grid-memory-leak-14.zip](https://github.com/IgniteUI/igniteui-angular/files/9261583/igx-grid-memory-leak-14.zip)

**Comment by wizgob** [comment]
I reviewed your sample and it dos not shows a leak

When the table is visible I get an instance after taking a heap snapshot in chrome developer tools.

![image](https://user-images.githubusercontent.com/29145536/188642466-5eb218b4-bf4f-47f8-8c06-fe653c61b65f.png)

When the table is hidden (ngIf with false condition), I do not get an instance of MatTable, demonstrating there is no leak

![image](https://user-images.githubusercontent.com/29145536/188642654-eef27726-71be-49ce-a08d-347c6a6dd18c.png)

**Comment by wizgob** [comment]
Here is a new sample that does not use *ngIf : I used the angular router to add and remove the igx-grid component:
https://github.com/wizgob/igx-grid-leak-2

Reproduction steps (in google chrome)
- run ng serve on the project above and load it in chrome
- Click on 'grid' link : igx-grid i showed
- Click on 'home' link : igx-grid is hidden
- Open chrome developer tools, go to 'Memory' tab, take a heap snapshot

Expected behaviour:
No instance of IgxGridComponent is found in heap snapshot

Actual behaviour:
An instance of IgxGridComponent is found in heap snapshot : there is a memory leak.
Each 'home'/'grid'/'home' cycle results in another instance being leaked.

![image](https://user-images.githubusercontent.com/29145536/188831705-e776dea3-2fa3-4c1b-bfdb-dc536c90e748.png)

**Comment by wizgob** [comment]
Any news on this problem?

**Comment by ChronosSF** [comment]
We'll be assigning it for further investigation most likely very early in November, after the current cycle of development is complete.

Generally speaking, Angular makes memory leak hunting a lot harder as it has quite a lot going on under the hood that's essentially blackbox . In many ways Angular routing is not that much different from how ngIf functions so it may have the same drawbacks as well. But we'll surely investigate it to be certain. I can just say that the last time we had a suspected memory leak in a different component it turned out to be ngIf's doing and during my initial research I did go over a list of suspicious (I use the term loosely as they were only suspicious if you expect Angular to cheat in some way) event handlers (those are almost always the culprit for GC to not do its thing) and swapping them with double and tripple safeguards did little to change the result.
