### ISSUE TITLE
Row adding transaction should not include the dummy PKs

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#12089]
Currently row adding transactions include the dummy negative values. Actually attempting to create EF entities with the objects from these transactions throws errors server-side.

These dummy values should be omitted from the transactions for users' convenience.

**Comment by mddragnev** [comment]
@ChronosSF I am not entirely sure that this is posible out of the box. Currently we can get the transactions in 3 ways from the transaction service:
1. `getTransactionLog` this is not currently used internally so there is an easy way to remove the custom generated id (which is actually the primary key)
2. `getAggregatedChanges` this is widely used in the code so removing the primary key field from the returned record causes many errors and bugs
3. `getAggregatedValue` same as 2. but it does return a single transaction
Currently, we do not have a single API method that we provide for the users that we do not use internally. Also, https://github.com/IgniteUI/igniteui-angular/issues/12091#issuecomment-1253383381 I have made some snippets which can be used to create a record in the database without using the dummy generated id.

Note that we must always have primary key (dummy key in terms of adding if the user hasnt set it otherwise in the `rowAdd` event) so the transactions can work correct.

**Comment by mddragnev** [comment]
One additional thing that came up to my mind now:
Even if we do delete the dummy rowID, if the user has subscribed to `rowAdd` event and manually changed the rowID, then we will remove it once the user get the transactions. I think this is not wanted.

**Comment by radomirchev** [comment]
@dkamburov are the proposals made from @mddragnev taken in consideration?

**Comment by dkamburov** [comment]
We haven't had a meeting or further discussion on this. Based on @mddragnev concerns we will need one if we want to start working on this issue

**Comment by radomirchev** [comment]
@dkamburov I have added the task to the sprint. It is your call if you can start working on this sprint or to move it for the next one.
