### ISSUE TITLE
cellEdit cancel not working consistently with validation

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#12127]
## Description  
When having a grid with a few columns set with the **required** attribute and **cellEdit** cancel is set to **true**, if a user adds a new row, starts typing in the field, and then deletes the input, the visual indicator is shown, the cell cannot exit edit mode by pressing "Tab" or clicking on other cells and the row cannot be added. (expected) 

However, if the user adds a row via the action strip and does not enter anything in the field - when pressing "Tab" the cell exits edit mode and the row can be added to the grid, although the required fields are empty.

 * igniteui-angular version: 14.1.x
 * browser: all

## Steps to reproduce  

1. Open this [demo](https://stackblitz.com/edit/angular-l1sty4-p5dlnw?file=src%2Fapp%2Fsample%2Figx-sample%2Figx-sample.component.html,src%2Fapp%2Fsample%2Figx-sample%2Figx-sample.component.ts).
2. Click the "Add new row" icon in the action strip.
3. Enter some text then delete it and press "Tab" - the cell remains in edit mode and the row cannot be added.
4. Add another row and immediately press "Tab". - the cell exits edit mode and the row can be added.

## Result  
Cell exits edit mode and a row with invalid fields can be added.

## Expected result  
The cell should remain in edit mode and the row should not be added.

## Attachments  
This could be observed in the below attachment:
![cellEdit-demo](https://user-images.githubusercontent.com/49126110/191937916-a0fd4972-2654-420b-99ac-970dd6526a70.gif)

**Comment by mddragnev** [comment]
@RivaIvanova 
Is this a bug that is from a client case?
This is somehow expected behavior. What I mean by this is that according to this [docs](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing#editing-templates) : 
`cellEdit` : `If value is changed, fires just before a cell's value is committed (e.g. by pressing Enter)` which completely answers the question why without changing any value the event is not emitted (keep in mind that only tabbing between the cells is not causing any updating on the values of those cells, thus not emitting `cellEdit`).
What you can do to avoid adding a row with invalid state is to bind to `rowAdd` event which is emmited just before you try to add new row (click done button). There you can have similar logic to cancel the row adding if the row is in invalid state.

Let me know if I am not understanding the issue correctly or there are any other cases that seem like a bug.

**Comment by RivaIvanova** [comment]
@mddragnev
Yes, this bug, which seems more like a feature request to me now, is from a client's case.

The requirement is that if the field/column is marked as `required` the user should not be able to tab out from the cell which is currently in edit mode and respectively not be able to add the new row. Similar behavior to the first example if the value was deleted.

Additionally, this seems to be the default behavior for columns with `dataType="date"` if `cellEdit cancel` is set to `true`, perhaps due to the `igx-date-picker` editor.
![cellEdit](https://user-images.githubusercontent.com/49126110/211050452-00209977-1ee0-4b4c-978a-424f8b76dc70.gif)

**Comment by mddragnev** [comment]
@RivaIvanova
I am not entirely sure that this can be achieved or to be more exact that this should be achieved with logic in the crud service. This is probably a perfect scenario where you should combine multiple events and create a custom logic that resolves that issue. I have created a stackblitz which IMO fixes your scenario. Let me know if thats not true.
[Stackblitz](https://stackblitz.com/edit/angular-l1sty4-svgtg2?file=src%2Fapp%2Fsample%2Figx-sample%2Figx-sample.component.ts)

**Comment by RivaIvanova** [comment]
@mddragnev 
The sample does fulfill the tab-out requirement, but the cell can exit edit mode when clicking on another cell. However, I played around with the sample and the editing events and you are correct that [this](https://github.com/IgniteUI/igniteui-angular/issues/12127#issuecomment-1373841213) could be achieved by using a combination of multiple events. 🙂  
[Here](https://stackblitz.com/edit/angular-l1sty4-2lgig6?file=src%2Fapp%2Fsample%2Figx-sample%2Figx-sample.component.html,src%2Fapp%2Fsample%2Figx-sample%2Figx-sample.component.ts) is the sample for a reference.

**Comment by mddragnev** [comment]
@RivaIvanova I`m glad that you managed to find a solution. Could we close the issue now?

**Comment by RivaIvanova** [comment]
@mddragnev Yes, definitely 🙂
