### ISSUE TITLE
IgxCarousel - Slides do not transition properly by pan gesture.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#12208]
## Description  
Slides do not transition properly by pan gesture.

 * igniteui-angular version: 14.2.2
 * browser: Safari, iOS 15.7

## Steps to reproduce  

1. Run the attached sample on iPhone.
2. Scroll the slides left and right continuously by pan gesture.

## Result  
Scrolling sometime stops in the middle of the slides transition.

## Expected result  
Scrolling do not stop in the middle of the slides transition.

## Attachments  
[carousel.zip](https://github.com/IgniteUI/igniteui-angular/files/9826741/carousel.zip)

**Comment by mkamiishi** [comment]
Hi,
Customer asks when this issue will be fixed.

**Comment by simeonoff** [comment]
Hi @mkamiishi , I spent the better half of the afternoon trying to figure this out. It seems there's an [ongoing issue](https://github.com/hammerjs/hammer.js/issues/1240) with the [touch gestures library](https://hammerjs.github.io/) we use. Since we allow users to scroll while also panning, the `panend` event never gets fired (third-party issue), hence why the slide appears to freeze in the middle of the transition. I will communicate with other colleagues in the company to see if we can come up with a solution, as it doesn't seem likely that it will be fixed by the Hammer.js team.

**Comment by mkamiishi** [comment]
Any updates on this?

**Comment by mkamiishi** [comment]
Any updates on this?

**Comment by simeonoff** [comment]
@hanastasov Can you guys check if there's any way to improve the gestures UX in iOS 13+ given the limitations of hammerjs?

**Comment by hanastasov** [comment]
> @hanastasov Can you guys check if there's any way to improve the gestures UX in iOS 13+ given the limitations of hammerjs?

Yes, sure. @dobromirts  will have a look at that. Thanks for the information you provided based on your testing!

**Comment by mkamiishi** [comment]
I'm closing this ticket as a third-party issue.
Thank you again for investigating this issue.
