### ISSUE TITLE
Grid body doesn't span its height correctly directly under shadow DOM root

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#12232]
## Description  
When I export an app from the App Builder containing an igc-tree-grid, the grid body doesn't calculate its height correctly.

 * igniteui-angular version: 14.2.x
 * browser: all

## Steps to reproduce  

1. Export an app from the App Builder containing a view with a tree grid with target Web Components
2. Run the app

## Result  
The tree grid generates fine and spans the height of the viewport, but its body doesn't

## Expected result  
The tree grid content should have correct height.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/197982659-050d9e02-0c12-42e4-a530-88ea3bfde4a9.png)

**Comment by damyanpetev** [comment]
@MayaKirova Valid for normal Grid as well, so assuming for all.
Seems to do with Shadow DOM, if the grid ends up directly under the shadowRoot. In that case it doesn't have `parentElement` and from what I can tell there are a few places where the nativeElement.parentElement are referenced, so that's my suspect cause
