### ISSUE TITLE
Grid "Pin all" action makes actions area go outside view

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#12249]
## Description  
"Pin all" action changes the toolbar size and hides the action buttons outside the grid's view

 * igniteui-angular version: 14.2.0
 * browser: any

## Steps to reproduce  

1. Open the column pinning topic
2. Scroll to the first demo
3. Click "pin all" button
4. Action area goes outside view

## Result  
Action area goes outside view

## Expected result  
Pinning action are to be visible/within view

## Attachments
Example that shows everything is available in the doom  
![image](https://user-images.githubusercontent.com/11193764/198964118-1d0c094a-80a6-4e08-bab3-afd90a00c6f2.png)

**Comment by desig9stein** [comment]
@zdrawku, @simeonoff this is expected behavior in the way we build the grid. It is not the "pin all" action that makes the buttons disappear it happens when the pinned columns overflow outside the grid body. The only fix that I can think of is to make the toolbar position: absolute, the same way we do for the filtering row.

However, I think we have a bigger problem, it is impossible to scroll the pinned columns horizontally since the scrollbar always starts at the last pinned column, and when the pinned columns overflow the grid body the user can't scroll them.

**Comment by desig9stein** [comment]
@zdrawku can you check the solution that I provide with the [PR?](https://github.com/IgniteUI/igniteui-angular/pull/12349)

**Comment by zdrawku** [comment]
Yes, I am currently checking it.

**Comment by zdrawku** [comment]
Everything was looking fine while I was testing it with the samples. Also within an iframe where the bug was first found.

**Comment by zdrawku** [comment]
I dont think that we are doing any mass merges anymore from 14.2.0. @desig9stein could you please cherry-pick your changes against 15.0.0. They will be merged [with this mass](https://github.com/IgniteUI/igniteui-angular/pull/12404) merge later on
