### ISSUE TITLE
Ignite favors module injector over current injector 

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#12450]
## Description  

Some Ignite components use module injector instead of current injector to instantiate components, ignoring any custom providers that the developer might have set.

 * igniteui-angular version: 14.1.1
 * browser:  any

## Steps to reproduce  

Provide my custom overlay Service:
`{ providers: IgxOverlayService, useClass: IgxOverlayService }`

Then instantiate a grid with excel style filters
```
    <igx-grid [data]="[ { col: 'text' }, { col: 'text' } ]" [autoGenerate]="true" [allowFiltering]="true" [filterMode]="'excelStyleFilter'">
    </igx-grid>
```

then try to set a custom text filter:
![image](https://user-images.githubusercontent.com/12942794/207116964-a710ba56-1cdf-4f55-801f-95c88c5469fe.png)

## Result  
The custom text dialog doesn't open.
See line where Grid is using moduleRef injector over current one:
https://github.com/IgniteUI/igniteui-angular/blob/9861f2c87bcfecbb3ede9e1ef9e49b44223d4176/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L3833-L3838

## Expected result  
The custom text dialog should open.

## Attachments  
[Stackblitz example](https://stackblitz.com/edit/angular-hws9fs?file=src%2Fapp%2Fgrid%2Fgrid-excel-style-filtering-sample-1%2Fgrid-excel-style-filtering-sample-1.component.ts)

**Comment by damyanpetev** [comment]
This bit in the Grid base is specifically for the ESF component, so adding that as a tag.
I believe we explicitly remove some similar use of [`NgModuleRef`](https://angular.io/api/core/NgModuleRef) around the overlay specifically since it can  be the wrong place in hierarchy to look for, so this might be a related leftover.

My suggestion would be to drop the module ref entirely (bonus one less thing to inject in the grid). Both it and the component injector are always provided and the latter should be sufficient anyway. The module ref's one will more than likely be somewhere on the parent environment injector chain anyway, so anything needed (+local overrides) should be available the component injector. 

There's one more use of `NgModuleRef` in the Date and Date Range Pickers that is also prone to this issue and should also be re-evaluated. Also, since stand-alone components are an option now, I'd advice against any module ref usage anyway

**Comment by damyanpetev** [comment]
Okay, so specifically for ESF as far as I can tell the NgModuleRef was in use from the initial implementation. There's a [fix that added the injector fallback](https://github.com/IgniteUI/igniteui-angular/pull/9686/files#diff-2ddc7fe3f58f826f4297d28f636d5d57b54a2c078973fff8630c68a0275ec2c1), though I can't quite tell how related that is to the issues it fixes. I would also like to see if the ESF can go through the overlay service component creation directly as it did before this?

Alternatively, while the dynamic component creation was moved to grid base during the Angular 13 update, there were a few in-between changes by @rkaraivanov that attempted to move the to the ViewContainerRef API (what we have to do too) might be helpful  and be picked up again: https://github.com/IgniteUI/igniteui-angular/commit/303718f51f755bb029a13b8c1b29f184114a90bc, https://github.com/IgniteUI/igniteui-angular/commit/8b752cc36aa0c83f8b5d32964983c4981e07427a, https://github.com/IgniteUI/igniteui-angular/commit/c6027e998ef54b717dcddccc1751881ccaeb16ca

**Comment by pmoleri** [comment]
The bot doesn't seem to agree that this is bug @damyanpetev

**Comment by damyanpetev** [comment]
https://github.com/IgniteUI/igniteui-angular/pull/11685 already cleared out the module use in the date and date range pickers, so just the ESF refactor waiting to be merged.
