### ISSUE TITLE
Row transactions and grid validation service are not sync when using transaction clear method to clear multiple invalid cells

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#12505]
## Description  
Row transactions and grid validation service are not sync when using transaction clear method to clear multiple invalid cells

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open editing dev sample
2. In the second sample add additional action button at the end
```
        <button (click)="clear('gridRowEditTransaction')">Clear</button>
```
3. Create the handler

```
 public clear(gridID) {
        const currentGrid: IgxGridComponent = this.getGridById(gridID);
        currentGrid.transactions.clear();
    }
```
4. Make multiple rows to be invalid (ProductName column is required)
5. Clear all transactions
6. Observe

## Result  
The values in the cells are cleared as the last value but the cell is still invalid.

## Expected result  
They should be synced correctly.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by mddragnev** [comment]
@damyanpetev As we talked, mentioning you here for further discussion on this one.
Here is a PR https://github.com/IgniteUI/igniteui-angular/pull/12507 that make those adjustments.

**Comment by MayaKirova** [comment]
@damyanpetev From what I remember there was some issue with the state update event not containing enough information on what was being cleared and why:
https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/services/transaction/igx-transaction.ts#L156

Since you could use it to clear all transactions or a particular transaction by id, but that information does not get emitted for the event. Also `clear` is called on `commit` as well, but commit simply applies the already validated changes to the grid so there's no need to clear the validation service (invalid values would still be invalid after you have committed them) .

To sync them correctly will probably require some changes to happen in the transaction service first.

I think that is why we did not attempt to do any synching in that case and left it up to the user to decide when to clear the validation states via the public APIs and showed it that way in the samples/docs.

**Comment by ChronosSF** [comment]
@wnvko , please check this bug and discussion.
