### ISSUE TITLE
igxCell template directive exposes "cell" as possibly undefined

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#12538]
## Description  

Add a custom cell template.

Try to use anything from "cell" context:
![image](https://user-images.githubusercontent.com/12942794/213201992-25d32e7b-66e7-4008-be4e-3335e25d1f79.png)

 * igniteui-angular version: 15.0.6
 * browser: N/A

## Steps to reproduce  

1. Add a grid with custom cell template:
   ```html
   <igx-grid #grid [data]="data">
    <igx-column dataType="string" field="Name">
        <ng-template igxCell let-cell="cell">
            <!-- Implement row deleting inside the cell template itself -->
            <span tabindex="0" (keydown.delete)="grid.deleteRow(cell.row.index)">{{ cell.value | titlecase }}</span>
        </ng-template>
    </igx-column>
    <igx-column dataType="boolean" field="Subscribtion">
        <ng-template igxCell let-cell="cell">
            <input type="checkbox" [ngModel]="cell.value" (ngModelChange)="cell.update($event)" />
        </ng-template>
    </igx-column>
   <igx-grid>
   ```
2. Try to use anything from `let-cell`

## Result  

> Object is possibly 'undefined'.ngtsc(2532)
![image](https://user-images.githubusercontent.com/12942794/213201971-dfa24aaa-5fe1-4070-b181-a84014e095c2.png)

## Expected result  
Since this is a cell template, my understanding is that "cell" should always be defined.

**Comment by damyanpetev** [comment]
As far as I can tell the `IgxCellTemplateContext` is used for cell template, edit template and validation errors, but all use the same context getter where the cell property is always assigned:
https://github.com/IgniteUI/igniteui-angular/blob/97367eb533d87dabb9190ae8ef1bc0d988bc931c/projects/igniteui-angular/src/lib/grids/cell.component.ts#L228-L231
Am I missing some other use that doesn't have the cell? Don't see a reason for the interface to describe the cell as optional, otherwise we could split interfaces if we have to per directive.
PS: Would be nice if the context getter was typed too :)
