### ISSUE TITLE
Wrap IgxColumn in a IgxGrid Wrapper Component

### ISSUE THREAD

**Issue by ammar4568** [IgniteUI/igniteui-angular#12605]
I want to create a wrapper for IgxGrid component which will have customizable inputs.

[https://stackblitz.com/edit/angular-n71deq](url)

Here is the stackblitz link which contains my problem. I have a component app-grid-wrapper which will contain igx-grid and another component which will pass <igx-column> as content wrapped inside the tag which will then show the columns as projection inside <igx-grid>. But using this approach breaks the application with the error.

NullInjectorError: No provider for InjectionToken IgxGridBaseToken!.

Is there any way this can be achieved. Thanks

**Comment by ammar4568** [comment]
@PlamenaMiteva @Lipata

**Comment by Svetloslav15** [comment]
The reason for this error is because **IgxColumnComponent** expects to be defined in an **IgxGridComponent** in order to work properly. In is not possible to dynamically create columns and assign them to the grid. The recommended way is by using [templates](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid#defining-columns). You can use an alternative approach by defining them in another component and dynamically generate them using ***ngFor**, but this should be done in the component where igx-grid is defined. Here is an [example](https://stackblitz.com/edit/angular-n71deq-hjt24i?file=src/app/app.component.html).
