### ISSUE TITLE
Migrations for ver.15 do not update $gray

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#12603]
## Description  
Migrations for ver.15 do not update `$grays` variable when they are supposed to do it: https://github.com/IgniteUI/igniteui-angular/pull/12409/files

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Run the attached sample (generated from AppBuilder production), that is having igniteui-angular ver.14. (angular is already updated to 15 for easy reproduction)
2. run `ng update @infragistics/igniteui-angular`

## Result  
Note that `$grays` variables are still presented and not replaced with `$gray`.

## Expected result  
With version 15 the variable name should be `$gray`.

In addition, the following improvements in the migrations should be done:

 - message should not be presented for projects that are not with SSR:
![image](https://user-images.githubusercontent.com/2621802/215984330-44625c2b-15ac-43cf-8bef-5e9ec9f439c2.png)

- migration for igx-typography -> ig-typography and igx-scrollbar -> ig-scrollbar
- removing ~minireset prefix (if possible)

## Attachments  
[Movie App_angular_14.zip](https://github.com/IgniteUI/igniteui-angular/files/10554558/Movie.App_angular_14.zip)

**Comment by kdinev** [comment]
I wonder just one thing. The `~minireset` import is something we add with CLI-generated projects but is not necessarily in a user's project using `igniteui-angular`. Hence, since migrations provided by us should cover only our product, I suggest we don't create a migration for the import, but instead once the App Builder is on ng15, the updated project generation would generate it without the `~`.
