### ISSUE TITLE
Incorrect grouping with Date and Time Column Type

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#12620]
## Description  
In the Column Types [documentation ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-types#datetime-date-and-time) it is clearly stated:

Time type column sorts based on the time portion of the object, ms will be disregarded. Date type column sorts based on the date portion, disregards the time portion. DateTime column sorts based on the full date.

(Please find attached an image in case the documentation changes)
![image](https://user-images.githubusercontent.com/36885861/217285284-38a8f489-6a41-42da-9fcf-4c2579a8e535.png)

But, I've modified your example to enable group by and disable summary and it doesn't work:

Same day but different times grouped separately:
![image](https://user-images.githubusercontent.com/36885861/217285830-88f8270e-a93d-4d54-b9a7-5a3e6875d7d2.png)

Same time but different day grouped separately:
![image](https://user-images.githubusercontent.com/36885861/217286311-77faf956-5a47-4ba5-9886-15e803741a9d.png)

[Here](https://stackblitz.com/edit/angular-nkg5vf) you have an example to try it.

I'm using@infragistics/igniteui-angular :12.3.45, but the example that I provide is with igniteui-angular: ^15.0.0.

It should sort by time regardless of day in columns of type time, and it should sort by day regardless of time in columns of type date.

**Comment by ddaribo** [comment]
Note: When grouping by a column of `dataType` `time` or `dateTime`, the groupRow's value is not displayed - visible in the referenced demo and screenshots.
Simplified sample - [here](https://stackblitz.com/edit/igx-grid-test-date-time-grouping?file=src/app/grid/grid-column-data-types-sample/grid-column-data-types-sample.component.ts).

**Comment by ssg127** [comment]
Yes, I also saw that grouping did not show the value in version 15, in the version I am currently using it works correctly.
![image](https://user-images.githubusercontent.com/36885861/217569975-9b796592-41d1-4b0c-acd1-8534fe7e0830.png)

**Comment by ssg127** [comment]
@ddaribo have you fixed the bug I reported or the second bug you found only? Have you fixed it for version 12? Because I'm using that versión of ignite.

**Comment by ddaribo** [comment]
Hi @ssg127,
According to our support policy version 12.x is considered retired and is no longer receiving fixes or new development.
The reported and the second bug are fixed for version 14.2.x, 15.0.x and our master branch (to be released as 15.1.x), which are the currently supported versions. The fixes are merged and will be entering the upcoming releases for the current minor version.  
In order to leverage the introduced fix, my suggesiton si to upgrade your project to any of the supported versions, if possible.

**Comment by ssg127** [comment]
@ddaribo ok, in some other occasion when reporting a bug, even if it was in an older version, it was corrected anyway. In angular 13 are they corrected or not?

**Comment by ddaribo** [comment]
Hi @ssg127,
I am afraid version 13.x is also out of support. Please, refer to our [Versioning Wiki](https://github.com/IgniteUI/igniteui-angular/wiki/Ignite-UI-for-Angular-versioning) for more details about the Ignite UI for Angular product lifecycle. As listed there, active support for versions 12.x and 13. x is over as more than 12 months since the corresponding Angular major version release date have passed.

**Comment by ssg127** [comment]
@ddaribo agreed. Thanks for the explanation.
Regards.
