### ISSUE TITLE
Non-pinned area not accessible when pinned area exceeds grid body area

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#12704]
## Description  
It is impossible to scroll the pinned columns horizontally since the scrollbar always starts at the last pinned column, and when the pinned columns overflow the grid body the user can't scroll them

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open a [toolbar sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/toolbar) and shrink the grid with the window a bit
2. Start adding pinned columns
3. When the pinned columns area exceeds the grid body width, the scrollbar will disappear 

## Result  
No horizontal scrollbar when pinned area exceeds grid body area

## Expected result  
I would expect a scrollbar to appear helping me reach out the non-pinned area OR the UI to prevent me from pinning more columns that can lead to this behavior (showing a notification snackbar or something)

## Attachments  
![Grid pinning scrollbar issue](https://user-images.githubusercontent.com/11193764/221574717-89f052e9-ae2a-4ba5-869f-44a7ef5e416e.gif)

**Comment by zdrawku** [comment]
@desig9stein I've assigned that issue to you as it was pointed out two months ago while you were fixing another issue. Its not a priority rather something to keep an eye on and decide whether we can fix it while working on bugs this quarter

**Comment by AnjiManova** [comment]
### Design Suggestion
We should change the "PIN ALL" button logic to resolve this issue and set up maximum and minimum width sizes for pinned and unpinned areas.

### Changed Pin All button logic and behavior

- By selecting “PIN ALL” no changes will be made to the grid because this is the default view. The change will be made after unselecting one of all options from the pinned columns dropdown menu. For visual reference, please check the [prototype](https://www.figma.com/proto/FuEB7l7M6fOZRJ7g40jEum/Task-23078-Issue-12704-in-GitHub?node-id=2-2&viewport=-900%2C-245%2C0.3&scaling=min-zoom&starting-point-node-id=24%3A128420) as well.
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/127843837/233042491-d81b89d7-32b5-47e5-84a3-8b614cd07062.png">

### Maximum and minimum width sizes for pinned and unpinned areas.

1. The **max** pinned area size **shouldn't be more than 80%** of the whole grid size
2. The **min** unpinned area size **shouldn't be less than 20%** of the whole grid size
- If there is a column with a width of more than 20%, take its width size as a minimum for the unpinned area.
- In cases where the column width is smaller than 20%, increase it to 20%.

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/127843837/233053885-59f3a68c-1cc9-4b62-bb88-a2d3d32f5991.png">

### Resources

- [Figma Prototype](https://www.figma.com/proto/FuEB7l7M6fOZRJ7g40jEum/Task-23078-Issue-12704-in-GitHub?node-id=2-2&viewport=-900%2C-245%2C0.3&scaling=min-zoom&starting-point-node-id=24%3A128420)

- [Design File](https://www.figma.com/file/FuEB7l7M6fOZRJ7g40jEum/Task-23078%3A-Issue-12704-in-GitHub?node-id=24%3A160818&t=bDFhyPAle5Dd2oTX-1)

- Prototype walkthrough

<img width="926" alt="image" src="https://user-images.githubusercontent.com/127843837/233044296-2dd3de6d-1c6f-436a-a66f-44b3900044d6.png">

- Video

https://user-images.githubusercontent.com/127843837/233056541-1451c3ce-3f61-4487-9379-fafb1b92c51b.mov

**Comment by simeonoff** [comment]
@radomirchev Are we gonna be prioritizing this anytime soon?

**Comment by radomirchev** [comment]
@simeonoff I will add the issue in the next sprint queue

**Comment by AnjiManova** [comment]
> The current behavior is by design and we shouldn't change it. Scrolling the pinned area both leads to further complications and doesn't make much sense from UX standpoint either.
> 
> When the end-user pins too many columns, this is clearly visible to them and it's their choice which ones they want to unpin to get the scrollable area visible again.

The current behaviour might be by design, but it causes accessibility issues and could bring more confusion than solving the user problems. The scrolling of both areas might lead to further complications (which should be mentioned because they are not known to everybody), and in this case, if there are such, we could still discuss it and find a solution for this case. At least we could add a scroll for the whole grid, not blocking the users and their grid visibility.
