### ISSUE TITLE
Grid combobox on paginator doesn't respect the displayDensity of the paginator

### ISSUE THREAD

**Issue by punker76** [IgniteUI/igniteui-angular#12846]
## Description  
Describe the issue.

 * igniteui-angular version: 15.1.x
 * browser: Chrome, Edge, Firefox

## Steps to reproduce  

1. Change the `displayDensity` property to any value

```html
<igx-paginator [displayDensity]="cosy" [perPage]="25"></igx-paginator>
```

## Result  
What is the actual result after following the steps to reproduce?

The combobox size is always the same for all density values.

![image](https://user-images.githubusercontent.com/658431/229568712-0317e98e-fe74-4557-9b11-b207c944e7d4.png)

## Expected result  
What is the expected result after following the steps to reproduce?

The combobox should also use the display density.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

see above

**Comment by ChronosSF** [comment]
This is intended. The material design inputs are a bit too large for the intended size of the paginator as material is primarily a mobile-first design system and doesn't have any consideration for dense components such as grids. We internally set this Select to 'compact' so that it looks better with the intended size of the paginator.

c.c. @sdimchevski , @simeonoff
