### ISSUE TITLE
RadioGroup: add label

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#12890]
## Is your feature request related to a problem? Please describe.
I'm using fluent design and it's currently not possible to add a label to a RadioGroup.

## Describe the solution you'd like
Please add the possibility to add a label to RadioGroup like in other components.

## Additional context
![image](https://user-images.githubusercontent.com/46870283/232401691-c41dd033-616e-49a1-bfca-1377728571b4.png)

**Comment by SisIvanova** [comment]
Here is a sample demonstrating how to use the IgxLabelDirective as a radio-group label. Do you need something besides that?

https://stackblitz.com/edit/c6fqyt?file=src%2Fapp%2Fradio-group-sample%2Fradio-group-sample.component.html

**Comment by Timmeeeey** [comment]
hi @SisIvanova 
I don't see any IgxLabelDirective in the example.
Can you use igxLabel without a IgxInputGroup?

**Comment by SisIvanova** [comment]
Hi @Timmeeeey 
Can you please explain to us what you need the radio group label for so we can decide how to proceed with this feature request? You want a label that is just styled properly or you expect specific functionality?

**Comment by Timmeeeey** [comment]
In some cases radio groups need labels for reasons of comprehensibility.
This label should look like all the other labels.

When displayed next to an input it would be nice if the radio buttons are vertically aligned with inputs for aesthetic reasons.
But I can just add some padding if this will not be the case.

Example:
![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/7aab59c5-f197-4b8e-be98-01e3744daa40)
![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/67b48a5a-f21d-4b73-a5b9-8064a932f07f)

**Comment by Timmeeeey** [comment]
@SisIvanova 
If I use the `igxLabel` directive then the label doesn't quite look like the label of the input.
Besides the asterisk for required input is missing.

current:
![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/4b365eaa-bd26-4533-bc7a-ea554059c927)

required:
![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/df06dbb4-a794-4696-902f-d479e9a0f2b1)

**Comment by SisIvanova** [comment]
Hi @Timmeeeey 
Our team is aware of this issue and we're planning to fix it soon. The igxLabel directive has always been part of the `igx-input-group` that's why when you want to use it separately some styles are missing. In a future release, we will extract the igxLabel directive and all of its styles from the `igx-input-group` theme so that all labels will look the same. Until then, you can use this sample to style the Radio Group Label in the same way as the Input Label in Fluent theme:
https://stackblitz.com/edit/c6fqyt-kbkxal?file=src%2Fapp%2Fradio-group-sample%2Fradio-group-sample.component.html
