### ISSUE TITLE
Column pinning visual errors

### ISSUE THREAD

**Issue by jberes** [IgniteUI/igniteui-angular#1293]
### Description  
Column header and pinned line not aligned

Vertical scrollbar of unpinned columns flows into pinned area

### Steps to reproduce  

1. Step 1
2. Step 2
3. ...

### Result  
What is the actual result after following the steps to reproduce?

### Expected result  
What is the expected result after following the steps to reproduce?
Column headers should align

Vertical scrollbar should not overflow into pinned column area

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![pinned-column-issus](https://user-images.githubusercontent.com/18453092/39969765-ecf65f30-56d8-11e8-8a97-6d41eb542c88.PNG)

**Comment by ChronosSF** [comment]
@rkaraivanov , @simeonoff - looks like, because of the 24px of padding on each side of the cells the minimum width one can take is 48. So calculations that rely on column widths would be incorrect if users set columns to be less than 48px in width.

My guess is that if we are to leave the current padding intact we should modify user-specified columns that are narrower to have 48px width internally so calculations are correct. Let me know if you have any other suggestions.
