### ISSUE TITLE
Blurry resolution of charts on Safari

### ISSUE THREAD

**Issue by nickko-vista** [IgniteUI/igniteui-angular#12941]
## Description  
When trying to render the charts in Safari, it's causing some rendering issue time to time.
Some times the rendered charts are crisp and looking good but some times it's blurry and low resolution.

 * igniteui-angular version: 15.0.13
 * browser: Safari

## Steps to reproduce  

The issue should be reproducible using an Iphone with the code provided in the Stackblitz.
https://stackblitz.com/edit/angular-lecymg?file=src%2Fmain.ts,src%2Fmain.html
Unfortunately, the issue doesn't appear on Stackblitz, I think it's because it's running in an iframe.
Try the code in a separate angular app.

## Result  
What is the actual result after following the steps to reproduce?
Some times the chart is rendered blurry.

## Expected result  
What is the expected result after following the steps to reproduce?
Chart is always rendered in crisp resolution.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

![expected resolution](https://user-images.githubusercontent.com/129129357/234730591-c1af493b-a7ab-4b41-af9b-6b82c91f0dfb.png)
![blurry resolution](https://user-images.githubusercontent.com/129129357/234730598-50d30fad-42b4-475c-8a30-e261a6f655db.png)

**Comment by gmurray81** [comment]
Hi, I believe this is not a bug.
The demo that you shared does not set the meta -> viewport (with initial scale) information which IIRC affects how mobile safari will treat high DPI screens. Without providing these details you will likely see images with reduced resolution also. I'd recommend making sure to provide to correct doc type and meta info in the html root page:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    <my-app>Loading...</my-app>
  </body>
</html>
```

I wasn't able to repro any blurriness with these settings. Without them, I actually wasn't able to tell if things were blurry since everything was rendered too small for my iDevice without initializing the viewport.

If there is some way you can repro this scenario still with the above settings, let me know and we can investigate.

**Comment by nickko-vista** [comment]
Would you be able to try it out with this code?
What I can observe is that the blurriness still happens even with the tags in the index.html file.
[src.zip](https://github.com/IgniteUI/igniteui-angular/files/11368640/src.zip)

**Comment by gmurray81** [comment]
Hi @nickko-vista I have not been able to reproduce this issue on my iPhone. Could you provide more information about the specific iOS hardware/os you are using? Are you able to reproduce this on any iOS simulator that I may be able to directly compare against? I only have a few pieces of iOS hardware to compare against. I can try the iPad here to see if I can reproduce on there.

**Comment by nickko-vista** [comment]
That's strange. We were able to reproduce the issue using that source code in the zip.
We used an iphone 12 simulator on mac, a physical iphone 8 and the Safari (version 16.4).
We were able to reproduce the issue on all of them.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/129129357/235794785-12ccf6e0-154a-4a66-927c-9a43308d7f4b.png)
<img width="1278" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/129129357/235795029-9f1d07ee-d976-4473-8307-4df197c102c3.png">

**Comment by gmurray81** [comment]
Hmmm... I'll have to try it in that simulator version. If you can repro in safari, next time it happens open the dev console and report what window.devicePixelRatio reads as and also if you can get a reference to the chart while the issue is occuring via ng.getComponent, please report what chart.actualPixelScalingRatio reads as.

**Comment by nickko-vista** [comment]
Both charts (blurry and non blurry) show actualPixelScalingRatio as 2 and window.devicePixelRatio as 3

**Comment by gmurray81** [comment]
Odd. Those should be in sync. In fact it keeps checking on an interval that they are. I'm still not able to repro locally yet... It's _extremely_ odd that both charts wouldn't be using the same pixelScalingRatio. Do you have any errors in the console? Have you adjusted the browser scale?

**Comment by gmurray81** [comment]
I'll also have to make sure I'm using the same safari version. Could you report which versions of Safari you are seeing the issue? And check if an upgrade is available? This has a bit of an odor of a Safari bug to me, since we haven't really run into this before.

**Comment by nickko-vista** [comment]
That's really odd. We've been able to reproduce it pretty easily with the source code i attached earlier.
There was no error in the console that I'm aware of.
The Safari version was 16.4.
The IOS version of Iphone8 that I was using is 16.3.1

**Comment by gmurray81** [comment]
well maybe that's telling since its possible I'm not fully up to date. So could be some safari bug or change in behavior in a more recent update.

Does it happen every time or only on some refreshes? I keep refreshing the page and it still doesn't repro. You doing anything odd with the browser scale/zoom?

**Comment by gmurray81** [comment]
yeah, lol, literally nothing is running safari 16 yet. Will see if that makes the difference. Unfortunately, that could mean this is a safari bug and may only have pretty ugly work arounds, but we'll see. This smells like a browser bug, but there's some outside chance that its an intended behavior shift that we need to accommodate for.

**Comment by gmurray81** [comment]
hmm... I was able to reproduce on an iphone in the latest version of safari.... I suspect this is actually a DPI bug in safari.... it seems like the pixel scaling ratio is correct in the chart, and the back buffer and css sizes are correct in the chart, yet something has inappropriately downscaled the back buffer... and it persists even if the canvases are repainted... I think I'm going to have to write up something for Apple. Do you mind if I submit them your repro?

**Comment by nickko-vista** [comment]
Thanks for looking into this. I don't you submitting them my repro steps and code :)

**Comment by kris-vista** [comment]
I was able to reproduce the same issue on my iPhone 12 pro max, ios 16.4.1 using the same code
![chart](https://user-images.githubusercontent.com/129016693/236068475-966dab3a-1b95-4b9e-98cc-4fe247c0a5e5.jpg)

**Comment by gmurray81** [comment]
I've seen this in scenarios now that aren't related to Angular at all let along router-outlet. It just appears to be a regression in Safari 16. I'll let you know if I manage to find a way to work around it. I did report this bug so maybe some of the webkit engineers will have an idea: https://bugs.webkit.org/show_bug.cgi?id=256260

I wound up using a different repro since it seemed to trigger the issue 90% of the time and is a bit simpler.
