### ISSUE TITLE
Keeping focus on selected row on sorting

### ISSUE THREAD

**Issue by Ugla-Bugla** [IgniteUI/igniteui-angular#12952]
Hi,
It would be very helpful if there was a way to make cell focus follow the selected row when sorting. 

If i select a row, sort the grid and press enter. It will start edit mode in the previously focused cell position independently of row selection or content.

image shows behaviour after pressing enter. 
![image](https://user-images.githubusercontent.com/63595471/235886305-de99ec06-5fe1-488d-8c24-822bdfb9d823.png)

I want to be able to:
  1. select a row by clicking it,
  2. sort the grid,
  3. Enter editmode in the first column(or a column of choice) of the row that was selected by pressing enter.
  
For reproducing unwanted behavior described above:
https://stackblitz.com/edit/nj51d7?file=src/app/grid/grid-row-editing-sample/grid-row-editing-sample.component.html

best regard

**Comment by GrblackStar** [comment]
Hello @Ugla-Bugla . 
Current implementation and behaviour is by design, thus this feature is behaviour changing and will not be introduced in the code. Instead, try this application level solution:
https://stackblitz.com/edit/nj51d7-a5eckj?file=src%2Fapp%2Fgrid%2Fgrid-row-editing-sample%2Fgrid-row-editing-sample.component.html,src%2Fapp%2Fgrid%2Fgrid-row-editing-sample%2Fgrid-row-editing-sample.component.ts


Here's a brief explanation of how it works:
When you add a grid, in the html you can add event handlers (in this case `selected` and `sortingDone`) and implement methods for them in the .ts. Make sure to remove the `cellSelection="none"`. 
![image](https://github.com/IgniteUI/igniteui-angular/assets/86851411/63524758-5f07-48f6-aec7-6e5f6a7f339f)

When selecting a cell (and focusing it), `onCellSelect` is called. In the event handler we can get the current cell and the key of it's row. Getting the key here is necessary for when you have multyselect (rowSelection="multiple"). 
![image](https://github.com/IgniteUI/igniteui-angular/assets/86851411/8e06b0e9-f65d-4e50-ab49-ee1a950135c2)

After sorting is done, rows' position is changed. in the handleSorting event handler try to find the previously active row and its new position index. If row is out of current view, you may need to scroll to it, because the grid uses lazy evaluation and everything that is not currently visible in the grid "doesn't exist". 
![image](https://github.com/IgniteUI/igniteui-angular/assets/86851411/cbf64bac-2dc8-46bc-bc55-7774cbad2537)


You can check other properties, methods and accessors in the documentation: 
https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html.


NOTE: Please consider the following scenarios:
1. The changes require the grid to have a `primaryKey`. So make sure to set it, otherwise searching for the exact row will not work.
![image](https://github.com/IgniteUI/igniteui-angular/assets/86851411/c3d79caf-ef79-48b1-a981-78ba043ebb4c)

2. If the selected record goes out of the `dataView` (aka goes on another page) after sorting, it will not be able to find it. Therefore it will not navigate correctly. One solution to that would be to add custom logic. Currently the grid loads only the records of the current page. That prevents massive delays when having a lot of data. But if you want to make it work you can get all the records as rows and search the key of the record there and get its index, so you can navigate to it. 
Another solution would be to simply remove the paginator.
![image](https://github.com/IgniteUI/igniteui-angular/assets/86851411/abd59bee-9bad-4459-8252-6573218c9cd0)

Note that both approaches would lead to delays in grids with many records. 

Good luck with your projects!
