### ISSUE TITLE
Error thrown by ResizeObserver

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#13000]
* igniteui-angular version: master
 *** browser:**

  -- Chrome 113.0.5672.92 - reproduce
  -- Edge 113.0.5672.92 - reproduce
  -- Firefox 110.0.1 - **does not reproduce**

## Steps to reproduce  

1. Run dev demos, go to grid sample http://localhost:4200/grid

## Result  
![image](https://github.com/IgniteUI/igniteui-angular/assets/14248932/1c60b2a8-35d5-4a57-a9a2-0a4f43c63123)

**Comment by hanastasov** [comment]
Was reported in TaskPlanner app also, after upgrade to version 16, see https://github.com/IgniteUI/TaskPlanner/pull/65#issuecomment-1540227450

**Comment by MayaKirova** [comment]
@tishko0 An easier way to reproduce in master is to attach to the window's error event, since the error no longer pops in a overlay. For example, for the dev demos:
1. Open the grid-auto-size.sample.ts sample and attach the window error event:

```
    public ngOnInit(): void {
        window.addEventListener("error", (e) => {
            console.log(e)
        });
...
}
```

2. Run the samples and open the related dev sample at: http://localhost:4200/gridAutoSize
3. Click the "Toggle Container Visibility" button twice to hide/show the container.
4. Open the console and observe the error and details:
![image](https://github.com/IgniteUI/igniteui-angular/assets/10397980/7e0e5e6b-c950-40d6-8daa-62c344497a46)
