### ISSUE TITLE
[Angular elements] Grid's dragGhostCustomTemplate renders ghost with incorrect position.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#13033]
## Description  
When setting the dragGhostCustomTemplate on the grid the ghost position is incorrect on drag.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Set `row-draggable="true"` for the grid.
2. Set a custom drag ghost template, for example:

```
   grid1.dragGhostCustomTemplate = () => html`Test`;
```
3. Start dragging a row.

## Result  
The template renders but somewhere on the bottom of the page.

## Expected result  
It should position correctly under the mouse pointer.

**Comment by damyanpetev** [comment]
@MayaKirova Could this be potentially related to https://github.com/IgniteUI/igniteui-angular/issues/12996? Would love a runnable repro and/or check if Angular sample can repro as well. Either way, may need @skrustev to help out with this one

**Comment by damyanpetev** [comment]
Mind you, setting ``html`Test`;`` as the drag ghost template won't work either way as it's supposed to be equivalent to `<ng-template igxRowDragGhost>Test</ng-template>` in Angular which fails outright:
https://stackblitz.com/edit/rdzeew?file=src%2Fapp%2Fgrid%2Fgrid-row-drag-base%2Fgrid-row-drag-base.component.html `Uncaught TypeError: Cannot set properties of undefined (setting 'transitionDuration')`

Apparently the Row Drag topics omit quite a lot that is needed - there **must ** be a single wrapper around the content, because the drag uses that to position the ghost, rather than provide it's own positioning wrapper. Also, apparently you are also supposed to adjust the `z-index` of the thing if it needs to go over other elements like a grid. Not terribly convenient.

So it should be ``html`<div class="z-index">Test</div>`;`` to get to something. Regardless, there's still a bug with that as well (https://codesandbox.io/s/xenodochial-mountain-6cj9zn) because of the way Elements templates are hooked back into Angular - requiring a wrapping element of their own. That's wrapper is also `display: contents` (as in it doesn't have a display box at all), yet the drag tries to use it to position the ghost, which obviously doesn't work. 

Unfortunately, I can't avoid the extra container and it also mustn't produce a layout box in to avoid messing with just about all other scenarios. So outside of reworking the drag templates with built-in wrapper, I suppose some patch for either this template or avoiding non-layout elements when picking the ghost element are options.
