### ISSUE TITLE
[WebComponents] Adding template to the row edit text throws an error

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#13065]
## Description  
Adding template to the row edit text with the input property `rowEditTextTemplate` throws an error. @skrustev said that this is related to more than this template input and is something to do with the lifecycle of the component.
Note that when wrapped around in the `DOMContentLoaded` event handler, it works as expected. 

## Steps to reproduce  
You can also use https://github.com/IgniteUI/igniteui-wc-examples/tree/vnext/samples/grids/grid/row-editing-options this sample
1. Create  an web components grid sample with editing 
2. Add this template to the `rowEditTextTemplate` property of the grid
```
public rowEditTextTemplate = (ctx: IgcGridRowEditTextTemplateContext) => {
        return html`Changes: ${ctx.$implicit}`;
    };
```
3. Start it and observe the console.

## Result  
An error is thrown.

## Expected result  
It should be working as expected.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by damyanpetev** [comment]
So the error should be something similar to:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/e9ad644f-40a1-468b-a6ef-e84c0115e6cc)
The issue is of course with:
https://github.com/IgniteUI/igniteui-angular/blob/74e2cb780c241fdb8915601812a0b5a9cebdd3d1/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L1286-L1287

@skrustev Is quite right actually, for the most part Elements follows the lifecycle of the component, which even in Angular **sets** Inputs way before content queries are initialized. Major difference being in Elements results might populate later (that doesn't affect the actual query being set) and it reads the value before setting. The latter _should_ be completely benign, but not so in our case.

If you actually use the input in Angular like so:
```html
<igx-grid #grid [rowEditTextTemplate]="rowEditTextTemplate">
    <!-- ... -->
</igx-grid>
<ng-template #rowEditTextTemplate>
    <!-- ... -->
</ng-template>
```

You will see the following order of operations - 1. setting `rowEditTextTemplate` input:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/66413d5b-b867-4f86-bcd8-5fbf9857ce59)
https://github.com/angular/angular/blob/4af49106aa2f588e7f6f15d6497c50e1f9b04352/packages/core/src/render3/instructions/change_detection.ts#L129
2. And then populating the `rowEditTextDirectives` content query:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/e404c4d5-8131-4b50-a24e-0e4060844ee1)
https://github.com/angular/angular/blob/4af49106aa2f588e7f6f15d6497c50e1f9b04352/packages/core/src/render3/instructions/change_detection.ts#L160
3. And technically third firing the `ngAfterContentInit` on the grid
https://github.com/angular/angular/blob/4af49106aa2f588e7f6f15d6497c50e1f9b04352/packages/core/src/render3/instructions/change_detection.ts#L174

If we have to be really strict about it, no input accessor should be touching content queries at all, certainly not before `ngAfterContentInit` or without a safety check.

Now, I could try and modify the Elements strategy to ignore reading values on first go but that might not be a full-proof solution and honestly not excited to poke around in there. Plus, it _**is**_ possible to touch the getter in Angular context too:

Take this silly check for demonstration:
 ```html
<igx-grid #grid [rowEditTextTemplate]="grid.rowEditTextTemplate || rowEditTextTemplate">
```
This will instantly produce the same error
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/54cf2988-0ac9-4461-a8d3-0de71d03f46b)
and even break the view since it throws during template execution.

Two possible approaches we can take:
- I'm not entirely sure _why_ template input getters also try to return the alternative content child result OR internal view child defaults at all. It's a property that wasn't set, it's okay for it to not have a value. Any other checks should be done internally.
Unfortunately, changing those getters could very very well be considered a behavior change (however unlikely its usage) and might not be something we could fix right away.
- Simply add a safe nullish accessor to the getter in case it's called before content init (`return this._rowEditTextTemplate || this.rowEditTextDirectives?.first;`). This will likely be the easier solution atm

I also have a feeling similar accessors are widespread as many template inputs were done in bulk. Might need some help to identify the really faulty ones that must be fixed right away. Any others already encountered?

**Comment by mddragnev** [comment]
@damyanpetev I havent encountered any other. I think that the second approach you suggested is good enough for now. Also, as you said there are many more content children that are used in a similar way. We should probably add a null check to all of them.

**Comment by damyanpetev** [comment]
Fair enough, I'll patch this one, drag indicator we've encountered too and any others I can find in this pattern without doing an exhaustive searches. Should still probably log an issue for a next major version and clean those out (the first option) eventually IMO.
