### ISSUE TITLE
Divider margin can't be changed without inline styles

### ISSUE THREAD

**Issue by dobromirts** [IgniteUI/igniteui-angular#13139]
## Description  
The divider margin can't be changed because other default rule is setting it to 0px.

 * igniteui-angular version: 14.2, 15.1, 16.0
 * browser: all

## Steps to reproduce  

1. Set margin style to the divider element without using inline styles.
2. Inspect the compiled element and the its styles

## Result  
![divider-margin](https://github.com/IgniteUI/igniteui-angular/assets/46093564/a2218a74-f64c-41d4-bc39-1f778dc4bc28)

## Expected result  
Custom set margins to be applied.

**Comment by simeonoff** [comment]
@dobromirts Bear in mind that when we allow changing the margin of the divider using external stylesheets, you will be directly interfering with the `inset` functionality of the divider. Meaning, if you have `inset` set to `16px` for instance, the inset functionality will not work since you explicitly change the margin yourself.
