### ISSUE TITLE
Grid error when there is focused element and you try to scroll inside shadow dom

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#13186]
## Steps to reproduce  

Reproducible only in Chrome under shadow DOM.
1. Add grid and add some cell tempate inside which place a button or input group.
2. Run the sample and click over the added button.
3. Scroll the mause wheel or with the scroll bar.
4. Observe the console.

## Result
![image](https://github.com/IgniteUI/igniteui-angular/assets/34240583/0e74734d-99e7-4066-b901-1d137b9fe11c)

## Expected result  
No error should be thrown

![columnTemplatesIssue](https://github.com/IgniteUI/igniteui-angular/assets/34240583/5b005b43-3e4b-4044-a627-c00c44c1f29b)

**Comment by pmoleri** [comment]
The issue happens when using focusable element and the grid is in a shadow dom:
Stackblitz repro: 
https://stackblitz.com/edit/mmtpvc?file=src%2Fapp%2Fgrid%2Fgrid-displaydensity-sample%2Fgrid-displaydensity-sample.component.html

 - Click on the `Customer Name` chip.
 - Scroll the grid
 - Look at the console
