### ISSUE TITLE
Using Tab key to navigate not focusing components In Safari

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#13224]
* igniteui-angular version: 14.2, 15.1, 16.0
 * browser: Safari

## Steps to reproduce  
1. Open dev demos input-groupe sample
2. Select the first input end and press the tab on your keyboard until you hit the input after the file type inputs.

## Result  
I am enabled to focus on the file type input using the tab key on my keyboard.

## Expected result  
I should be able to focus the file type input using the keyboard tab 

## Attachments  
Safari
https://github.com/IgniteUI/igniteui-angular/assets/21260963/a11358bc-f5ec-47c9-8806-63db88fbca93

Other browsers
https://github.com/IgniteUI/igniteui-angular/assets/21260963/f04cb0be-adbe-4a52-b8fe-9b08b7a141b5

**Comment by simeonoff** [comment]
After some digging around, turns out this is actually an accessibility 'feature' in macOS. By default macOS would only allow you to tab into text boxes and lists. To enable keyboard navigation using the Tab key in Safari, one would need to enable a toggle in settings.

Go to Settings -> Accessibility -> Keyboard and enable the `Keyboard navigation` feature. This will allow you to move the focus between all focusable elements in a page in Safari.

![Screenshot 2023-07-20 at 10 17 56](https://github.com/IgniteUI/igniteui-angular/assets/4118303/a4067ec9-1515-4f1e-815c-0044dd2a6c5a)
