### ISSUE TITLE
Cell change not committed when sorting right after

### ISSUE THREAD

**Issue by ljmcadenas** [IgniteUI/igniteui-angular#13226]
## Description  
When editing a cell, if you exit the editor mode by clicking on the sorting icon to perform a sorting action straight away then the cell change won't be committed.

 * igniteui-angular version: 16.0.11
 * browser: Chrome

## Steps to reproduce  

1. Go to https://stackblitz-starters-xunesh.stackblitz.io
2. Click on a cell to enter the editor mode and edit the cell's value
3. Exit the editor mode by clicking the sorting icon to perform a sorting action

## Result  
The sorting is performed but the cell value remains as before.

## Expected result  
The sorting should be performed as well as the cell value change committed.

## Attachments  

![igniteui-cell-editor](https://github.com/IgniteUI/igniteui-angular/assets/5069082/6f4cc516-99ae-4f87-9635-11ebb0bcde3e)

**Comment by hanastasov** [comment]
Hi @ljmcadenas,

This behavior is by design. Following the [Grid Editing Features Integration](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing#features-integration) section in the help topic, you will see the table describing how each behavior will affect editing. Sorting as well as Filtering, Paging, Moving, Pinning, Hiding and GroupBy will exit edit mode and discard the value:

![image](https://github.com/IgniteUI/igniteui-angular/assets/14248932/7c21ca58-9e2f-4b8d-8e30-c7b8d5b16ae5)

**Comment by ljmcadenas** [comment]
Hi @hanastasov ,

Thanks for your reply. I just had a look at the code to see what that method does and found out you guys have plans to mark it as _internal_ and _hidden_. I'm now confused whether we should use it or not.

![image](https://github.com/IgniteUI/igniteui-angular/assets/5069082/a242f5e6-d430-41d6-a87f-33be9e3f83bb)

**Comment by hanastasov** [comment]
Hey @ljmcadenas,

I really missed that one. Thank you for noticing. I raised an internal discussion where we will confirm or deny this plan.

Either way, an alternative approach would be to:

1. Instead of handling the original event - `sorting` in your case, but in occasion of pinning would be `rowPinning`, handle the `cellEditExit` event. (or `rowEditExit`)

```html
    <igx-grid
      [data]="data"
      (cellEditExit)="cellEditExit($event)"
      (rowEditExit)="rowEditExit($event)"
    >
```

2. Manually update the cell/row that are currently in edit mode:
```typescript
  public cellEditExit(eventArgs: IGridEditDoneEventArgs) {
    // why is this if statement?
    // in edit flows, for example edit a value and press enter to commit, eventArgs.event will contain the original KeyBoard event, that triggered the operation
    // in the case of doing sorting, paging, etc, evenrArgs.event does not contain the original event
    // this if helps ud differentiate the flow that triggered the cellEditExit
    if (!eventArgs.event) {
      (eventArgs.owner as IgxGridComponent).updateCell(
        eventArgs.newValue,
        eventArgs.rowID,
        eventArgs.column.field
      );
    }
  }
  
  // The cast to IgxGridComponent will not be needed after https://github.com/IgniteUI/igniteui-angular/issues/13239 is fixed.
```

**Comment by ljmcadenas** [comment]
Hi @hanastasov ,

No worries :) I think the alternative way should work for us.

Thanks for your help.

**Comment by hanastasov** [comment]
> Hi @hanastasov ,
> 
> No worries :) I think the alternative way should work for us.
> 
> Thanks for your help.

As a matter of fact, our discussion will most probably end to keeping the `endEdit` method as is. Will keep you informed,

**Comment by hanastasov** [comment]
> > Hi @hanastasov ,
> > No worries :) I think the alternative way should work for us.
> > Thanks for your help.
> 
> As a matter of fact, our discussion will most probably end to keeping the `endEdit` method as is. Will keep you informed,

Keeping the `endEdit` method as is. Closing the issue.
