### ISSUE TITLE
[Data Grid] GroupBy() function in grid doesn't work correctly if SortingDirection.None

### ISSUE THREAD

**Issue by itvius** [IgniteUI/igniteui-angular#13301]
## Description  
[Data Grid] GroupBy() function in grid doesn't work correctly if SortingDirection.None

 * igniteui-angular version: 16.0.13
 * browser:  Edge, Chrome

## Steps to reproduce  

1. Open component with data grid ( with default grouping expression or not ) for example https://stackblitz.com/edit/angular-a5e8ph-czjofm?file=src%2Fapp%2Fgrid%2Fgrid-groupby-sample%2Fgrid-groupby-sample.component.ts
2. Change grouping use groupBy() function. Inside grouping expression use SortingDirection.None
3. Change grouping use GroupingExpression =  Array<IGroupingExpression>. Inside grouping expression use SortingDirection.None

## Result  
Grouping expression empty grouping doesn't work

## Expected result  
Grouping expression have expression with  dir = SortingDirection.None ( without sorting )

## Attachments  
![Screenshot 2023-07-24 125120](https://github.com/IgniteUI/igniteui-angular/assets/7572804/05ce0e2c-8d35-4dbb-b730-bf73c9e75d4c)
![Screenshot 2023-07-24 125228](https://github.com/IgniteUI/igniteui-angular/assets/7572804/0ce26bb5-2542-4e15-b4b5-784895d7b0a6)

![2023-07-24_13h11_51](https://github.com/IgniteUI/igniteui-angular/assets/7572804/2573e449-d674-4b7a-9344-3814ee37a674)

**Comment by mddragnev** [comment]
Hello @itvius,
Even though, the gropuing and sorting functionalities are decoupled, the grid still sorts the data by the field which you want to group by in order to generate correct group rows. If you set the grouping sorting dir to None  in the grouping expressions we cannot get the groups. Could you please provide some more information about your data and what exatly are you trying to achieve so that I can get a little more context and help you with your specific issue.
