### ISSUE TITLE
Chart tooltips on Mobile render off screen

### ISSUE THREAD

**Issue by AndrewLyall-Vista** [IgniteUI/igniteui-angular#13421]
## Description  
When viewing tooltips on a mobile device the tooltip always render to the right of the users finger. This means that the tooltip renders off screen when trying to view data on the right side of the chart. This occurs using both the default tooltip and the custom tooltip.

 * igniteui-angular version: 15.0.0
 * browser: 
    * Android - Chrome
    * iOS - Safari

## Steps to reproduce  

1. Create a graph with tooltips enabled that spans the width of a page.
2. On a mobile device, open the tooltip on the right side of the chart (where the tooltip will render fully or partly off screen)

## Result  
Tooltip renders off screen

## Expected result  
Tooltip adjusts positioning so that the whole tooltip remain on screen (as it does using mouse hover)

## Attachments  
https://stackblitz.com/edit/angular-otvjvp?file=src%2Fmain.html
You will need to open the preview of the stackblitz on a mobile device to reproduce

Below are two screenshots of tooltips being cut off.

![MicrosoftTeams-image](https://github.com/IgniteUI/igniteui-angular/assets/129119857/24948bbb-1045-4e90-95a0-8ded36a41b87)
![MicrosoftTeams-image (1)](https://github.com/IgniteUI/igniteui-angular/assets/129119857/425bedae-688b-4c2a-98bf-4fea5775c2d7)

**Comment by jamesp-v** [comment]
Following up on this, DataTootipLayer seems to suffer from the same issue:
![image](https://github.com/IgniteUI/igniteui-angular/assets/129116326/e551180f-c26f-4ed5-a6a1-00a828c412ae)

ItemTooltipLayer positions itself correctly, but suffers from another issue (#13527)

Here's an [updated stackblitz](https://stackblitz.com/edit/angular-9fblmi) which lets you mix and match tooltip modes

**Comment by gmurray81** [comment]
at least under normal conditions, data tooltip layer is shifting itself leftward

**Comment by gmurray81** [comment]
![image](https://github.com/IgniteUI/igniteui-angular/assets/4264873/317071dd-e2d5-4880-9d74-7d9b60dc903d)

**Comment by gmurray81** [comment]
to avoid going out of bounds. I think you may be hitting the more extreme case where neither position would be in bounds, so I believe the current behavior is to give up shifting the tooltip. In your case it would have been preferable to shift it left since more of it would have been visible in that case, but it still would have been somewhat obscured.

ATM, I believe there is no detection for "lack of space" that might cause it to decide to truncate a long series title, or force a line break in the title. This would have to be added as a feature request.

It may also have been that the default tooltip was refusing to shift since both orientations would have resulted in the tooltip being clipped. Maybe we'll adjust he behavior such that if both positionings would result in the tooltip clipping, that it will at least pick the least bad option.
