### ISSUE TITLE
Automated migrations fail in igniteui-angular-samples repo

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#13458]
When trying to bump the package version of igniteui-angular in my [branch for the sizing update](https://github.com/IgniteUI/igniteui-angular-samples/pull/3385) using `ng update igniteui-angular --next` fails with an error.

![image](https://github.com/IgniteUI/igniteui-angular/assets/4118303/5847c964-7579-4f0c-8eef-0d5543ed165f)

Here's the full log:
[angular-errors.log](https://github.com/IgniteUI/igniteui-angular/files/12595594/angular-errors.log)

**Comment by Lipata** [comment]
The bug was reopened, because of the following error still appearing, when running `ng update` for igniteui-angular 16.1. However, it is hardly reproducible and will be logged as a separate issue: 

![image](https://github.com/IgniteUI/igniteui-angular/assets/2621802/99363f92-aee0-4393-ba5d-abdee77c33a1)
