### ISSUE TITLE
igx-icon instance width/height can no longer be overridden with a css class

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#13534]
## Description  
I want to override width/height of some `igx-icon` instances in a view. I was previously doing it by applying a class. This no longer works, because the theme's default icon size overrides it.

 * igniteui-angular version: 16.0.x
 * browser: all

## Steps to reproduce  

1. Define an `<igx-icon class="custom-size"></igx-icon>`
2. Define `.custom-size { width: 60px; height: 60px }`

## Result  
The icon should be 60x60px.

## Expected result  
The icon is 1x1em.

![image](https://github.com/IgniteUI/igniteui-angular/assets/1472513/6d464ec8-f929-492e-85d0-159985c0cc81)

**Comment by simeonoff** [comment]
This is intentional, please use the `--size` or `font-size` properties to override the icon size.

```css
.custom-size { 
  --size: 60px;
}
```

**Comment by kdinev** [comment]
@simeonoff Which version would be the first one this applies in?

**Comment by simeonoff** [comment]
> @simeonoff Which version would be the first one this applies in?

The one you have logged it for - 16.0.x; however, the icon size has had the `--size` property for quite some time now and it has always been the one intended to be used to modify the size of the icon.

**Comment by kdinev** [comment]
@simeonoff I noticed the icons becoming smaller now and they definitely weren't smaller in 15.1, so I would assume it's somewhere around `16.0.0`

**Comment by simeonoff** [comment]
> @simeonoff I noticed the icons becoming smaller now and they definitely weren't smaller in 15.1, so I would assume it's somewhere around `16.0.0`

There were changes to the default icon sizes, but it's not related to the changes made with regards to width and height being set to 1em. This is purely so that the icon size can depend on the font-size context of its parent as it's assumed that it's often used alongside other elements - like text. If you have an icon in a button and want to scale the icon with the size of the text in the button, having the width and height of the icon expressed and set in stone as 1em makes a whole lot more sense without taking away the ability to specifically target the icon and define its size.
