### ISSUE TITLE
IgxSimpleCombo: form gets dirty by opening and closing dropdown

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13557]
## Description  
When you open an empty IgxSimpleCombo and close it without selecting something then the form gets dirty.

 * igniteui-angular version: 16.1.2
 * browser: Chrome

## Attachments  
https://stackblitz.com/edit/fayo3e

![2023-10-17_10h20_28](https://github.com/IgniteUI/igniteui-angular/assets/46870283/75e6a4a7-e5fd-4009-a43c-f51219988982)

**Comment by ChronosSF** [comment]
@Timmeeeey , I am scheduling this for next sprint starting Oct 30, but we'll try to take a look at as early as next week.

**Comment by ChronosSF** [comment]
@Lipata , I gave this a try but the issue is that null is actually an accepted value and not the same as having nothing chosen , which for me is a bit baffling. There is no clean solution imo with this logic in place, because not doing anything with the editor actually means no selection while a null ng model actually pushes an accepted null value in the selection so the two differ and a change is pushed simply by tabbing through.

There are two options but I think someone who worked on the control from the start should choose what to go for:

1. make setting null mean no selection (right now only undefined works like this) 
2. make it so outside of writeValue, selection can only be changed through user interaction such as typing or selecting a value from the dropdown. This means that even though null would be different than no selection, selection won't be cleared as there is no user interaction to trigger it. This is quite convoluted and I think I like it less than option 1.
