### ISSUE TITLE
igx-data-chart Plotting data 

### ISSUE THREAD

**Issue by Vighneshaa** [IgniteUI/igniteui-angular#13711]
I am trying to plot the chart which has data in decimal format and I am trying to set the property actualMaximumValue :  0.001866496497 and actualMinimumValue : 0.001208243544 (Values mentioned here are part of chart data). This chart is not getting plot. Also, when all the values are same it does not get plot.
What should be done to support this case?

ChartData:- 
[data.json](https://github.com/IgniteUI/igniteui-angular/files/13450283/data.json)

![image](https://github.com/IgniteUI/igniteui-angular/assets/121025954/75996eb0-ff3d-437e-9df4-488591b52bcc)

**Comment by agoldenbaum** [comment]
It appears that the IgxFinancialChart component is failing to parse the property path ""LMDX-USA-Master-Convertible Bond-LMDX   6.000 03/01/27 CVT : % of Equity" in your json data. Specifically, it looks like it's tripping over the 6.000 part of the data path due to the decimal point as if this part is removed, the data plots as expected.

As a workaround to this, I would recommend renaming that data path to something a bit more concise so the chart can read it. For example, if you rename it to something like "Value" the chart will plot it as a line series.

**Comment by Vighneshaa** [comment]
Renaming does not satisfy the use case for which I want to plot the data. Are there any other workarounds that can be implemented to plot it as a line series?
