### ISSUE TITLE
How can I increase the dialog height width using PositionSettings?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [IgniteUI/igniteui-angular#13783]
I refer to [this](https://www.infragistics.com/products/ignite-ui-angular/angular/components/dialog) documentation and try to increase the dialog height width using settings. 
I tried. It's possible with SCSS using below code. 
```
:host {
  display: block;
  padding: 0 16px;
  ::ng-deep {
    .igx-dialog__window {
      min-width: 200px;
      width: 200px;
    }
  }
}

```
But Is there any way with the settings?
Here is my [example](https://stackblitz.com/edit/gsqzmv?file=src%2Fapp%2Fdialog%2Fdialog-styling-sample%2Fdialog-styling-sample.component.ts) which was i tried. I tried both Strategies. But, It's not work.
```
//positionStrategy: new GlobalPositionStrategy(this._animaitonSettings),
positionStrategy: new ElasticPositionStrategy(this._animaitonSettings)
```

**Comment by simeonoff** [comment]
@chaklasiyanikunj The [`minSize`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/PositionSettings.html#minSize) property of the [`PositionSettings`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/PositionSettings.html) interface can work to specify only minimum sizes when used in combination with the [`Elastic Position Strategy`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/ElasticPositionStrategy.html).

The dialog was designed this way so that it can be fluid enough when used on various devices and display resolutions. As you've already discovered, you can manually overwrite the styles of the dialog window, which is the only viable way to do it.
