### ISSUE TITLE
Facing the issue with igx Grid Master-Detail

### ISSUE THREAD

**Issue by chaklasiyanikunj** [IgniteUI/igniteui-angular#13792]
I refer to the [example](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/master-detail) and make master-detail with igx Grid Master-Detail.

I used igx-grid inside Grid Master-Detail and inside Grid Master-Detail I have another igx-grid.

I am facing problems like When I click on expand, data does not update. If I press another single click or mouse hover, it will update. Does anyone know what causes the issue?
or 
Is there any field available for Strick to render the data for the master data

**Comment by IMinchev64** [comment]
Hello,

Thank you for reaching out with your issue regarding the master-detail implementation in the igx-grid. To better assist you, could you please specify the version of IgniteUI you are currently using in your project? This information is crucial as it will help in identifying any version-specific issues or bugs.

Additionally, it would be extremely helpful if you could replicate your setup in an online platform like Stackblitz and share the link with us. This will allow me to examine the problem more closely and provide a more accurate solution.

Understanding the exact behavior and having the ability to interact with your code will greatly aid in pinpointing the cause of the issue and suggesting the appropriate fix.

Looking forward to your response.

**Comment by chaklasiyanikunj** [comment]
My version is 16.0.26. In that version it's happen I am using the igx-grid inside the igx model dialog box.

In Stackbliz, I tried with latest version 17.0.0, but it's not reproducible. here is the [example](https://stackblitz.com/edit/vu2fqv?file=src%2Fapp%2Fdialog-sample-1%2Fdialog-sample-1.component.ts,src%2Fapp%2Fapp.module.ts,package.json,src%2Fapp%2Fdialog-sample-1%2Fdialog-sample-1.component.html)

Let me create an example with version 16.0.26.

Thank you.

**Comment by IMinchev64** [comment]
Hello,

Thank you for sharing the Stackblitz example with IgniteUI version 17.0.0. After reviewing it, I can confirm that the issue is not reproducible in this version. Additionally, I conducted a test using IgniteUI version 16.0.26, but the issue did not manifest there either.

Given this, there might be specific factors in your original environment causing the issue. Could you please share the example with version 16.0.26 as you mentioned? This would be incredibly helpful in pinpointing the exact cause. It's also possible that other factors, such as browser version or additional configurations in your project, might be influencing the behavior.

**Comment by dkamburov** [comment]
@chaklasiyanikunj Please re-open if you need further assistance or have more questions on this matter
