### ISSUE TITLE
IgxSelectionAPIService should be provided on a component level 

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#13938]
Related to #13923 
IgxSelectionAPIService should be provided on a component level  instead of on a root level
![image](https://github.com/IgniteUI/igniteui-angular/assets/52423497/3da9dc0f-6c45-4309-9801-f4d66ebc7a65)

**Comment by pmoleri** [comment]
@damyanpetev somehow 1 service instance per component seems more expensive than 2-Set per-component? Can't be 100% sure, but my hunch is that the opposite is true.
IMO, root service means more complexity and more chances for mistakes (as already proven). And only worth it if there's a use case for it.

As a side note, I remember a conference with Ryan Dahl mentioning that he regretted not having Promises for node async APIs because his initial thought was that it meant _an extra object_ per API call.

**Comment by pmoleri** [comment]
Also, is uses these `id`s which if I'm not mistaken their sole purpose is to be able to track the instances in the root service.
![image](https://github.com/IgniteUI/igniteui-angular/assets/12942794/8a872656-e687-4369-99f6-d8ec6bc69bec)
