### ISSUE TITLE
igxIconButton - unknown property error in migration from v16 to v17

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular#13964]
## Description  
Upgrading from version 16 to 17 generates unknown property error with igxIconButton 

 * igniteui-angular version:  17.1.1
 * browser:  Chrome 122.0.6261.71

## Steps to reproduce  

1. Download sample
2. Run migration
`ng update igniteui-angular --from 16 --to 17 --migrate-only`
3. Build sample 
` npm run build`

## Code to migrate
```

    <div class="button-sample">
        <button igxButton="icon" type="button" class="prefixIcon" [disabled]="searchBusy"
            [igxButtonBackground]="caseSensitive ? 'rgb(73, 180, 254)' : 'transparent'"
            [displayDensity]="displayDensity" igxRipple [igxRippleCentered]="true">
            <igx-icon family="material">search</igx-icon>
        </button>
    </div>
```

## Result  
The sample fails to build

```
   <div class="button-sample">
        <button igxIconButton="flat" type="button" class="prefixIcon" [disabled]="searchBusy"
            [igxButtonBackground]="caseSensitive ? 'rgb(73, 180, 254)' : 'transparent'"
            [displayDensity]="displayDensity" igxRipple [igxRippleCentered]="true">
            <igx-icon family="material">search</igx-icon>
        </button>
    </div>
```
![image](https://github.com/IgniteUI/igniteui-angular/assets/7459881/f53377da-5c12-4391-85d3-f78cea5cbb5d)

## Expected result  
The migration does not fail

## Attachments  

[c8psbg--run.zip](https://github.com/IgniteUI/igniteui-angular/files/14436175/c8psbg--run.zip)

**Comment by SisIvanova** [comment]
Hey @lalo-mx, we are aware of this issue that is caused because the `igxButtonBackground` input property which could previously be used with the icon type buttons, cannot be applied to the newly created `igxIconButton`. You can find information about how to manually migrate it in our [Update Guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide#from-170x-to-171x)

**Comment by lalo-mx** [comment]
> Hey @lalo-mx, we are aware of this issue that is caused because the `igxButtonBackground` input property which could previously be used with the icon type buttons, cannot be applied to the newly created `igxIconButton`. You can find information about how to manually migrate it in our [Update Guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide#from-170x-to-171x)

How about displayDensity?

**Comment by SisIvanova** [comment]
@lalo-mx The `displayDensity` property has been deprecated since version 16.1, therefore, we haven't implemented it in the newly created `igxIconButton` directive. To change the size of an icon button, you should use the custom CSS property `--ig-size`. More information can be found in the [Update Guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide#from-160x-to-161x) and the [Display Density / Size topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/display-density).

**Comment by lalo-mx** [comment]
@SisIvanova Thank you, just maybe it is a breaking change
