### ISSUE TITLE
How can I copy the selected cell if it comes under the ng template?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [IgniteUI/igniteui-angular#13983]
I am trying to copy and paste selected cell.

I know this selected cell copy-paste depends on the field.  I am applying multiple way to achieve this. But, no luck.
Is there any way available if multiple values need to be put in the igx-column?.
Then how can I copy and paste this whole cell?

Here, I want to put both the value in cell and try to copy and paste. But not working.
```
  <igx-column [header]="'UnitsOnOrder and ReorderLevel'">
            <ng-template igxCell let-cell="cell">
              {{ cell.row.data.UnitsOnOrder }} -
              {{ cell.row.data.ReorderLevel }}
            </ng-template>
 </igx-column>
```
Here is my [example](https://stackblitz.com/edit/6rwcpe?file=src%2Fapp%2Fgrid%2Fgrid-clipboard-operations-sample%2Fgrid-clipboard-operations-sample.component.html,src%2Fapp%2Fgrid%2Fgrid-clipboard-operations-sample%2Fgrid-clipboard-operations-sample.component.ts).

Thank you.

**Comment by ChronosSF** [comment]
@chaklasiyanikunj , while the copy procedure can read formatters, it can't read custom templates. For this specific scenario, you can just use formatters, though for more complicated cases where you must use templates, the solution might not be so straightforward.

Anyhow, to get copying work properly for this specific scenario you should do something like this:

For your column just assign a formatter instead of template:
```html
<igx-column [header]="'UnitsOnOrder and ReorderLevel'" [formatter]="columnFormatter"></igx-column>
```

Then your formatter would look like this to achieve the same as the template:
```ts
public columnFormatter(value, rowData) {
    return `${rowData.UnitsOnOrder} - ${rowData.ReorderLevel}`;
}
```
