### ISSUE TITLE
Infer as many editor options from column options as possible

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#14010]
## Is your feature request related to a problem? Please describe.
Users expect to set something once. There are cases where column options are not transferred to editor options and have to be set separately or even worse - call for entirely custom templates. One example is the date-time formatting. For cells you set it using pipeArgs to the Angular date pipe but you cannot set it for its corresponding date-time input. Its format is currently hardcoded through a hidden property.

## Describe the solution you'd like
The example above is just one of possibly many. The FR requires a research in what we use to create the underlying editors and how options for columns affect those and how these can  be transferred so the editors work seamlessly in the same way the user expects based on the columns they set.

**Comment by ddaribo** [comment]
For columns of dataType `date`, `time` and `dateTime` and their corresponding editors - IgxDatePicker, IgxTimePicker, igxDateTimeEditor), while in theory their `inputFormat` can be inferred from the column’s `pipeArgs.format` property, I am not convinced this would be the best approach. Since the `pipeArgs.format` could be any among the predefined/custom ones, in case it includes non-numeric parts, it would not be applicable as `inputFormat`. Users would still need to override it by declaring a custom edit template.

Probably a separate property could be introduced for this. For example an `inputFormat` on the pipeArgs or something like `editorInputFormat`on the column, or else. This would rather be covered by the other logged issue on the topic - https://github.com/IgniteUI/igniteui-angular/issues/14009, as it is about providing additional properties.

Regarding the `pipeArgs.timezone` option, I am not sure if it is applicable in the context of editing, since the original value is edited?

For other data types – `number`, `currency` and `percent`, I believe what is lacking is the ability to set a mask on the editor. This could be another candidate for additional property on the pipeArgs or the column. I am not convinced if this should be related to other pipeArgs options, such as `digitsInfo`, or if it could and should be inferred from it. In any case, the user has to be able to opt in or out of applying a mask on the default editor.
For  `string` dataType a mask may still be applicable to it.

**Comment by ChronosSF** [comment]
Thank you for looking into this. I agree it's probably the best to just allow editor options on a column level. I am closing this and leaving the improvements to #14009
