### ISSUE TITLE
How to hide TreeGrid groupby row count(length)

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#14088]
Like igx-grid groupbyrow templating, there doesn't appear to be a way to do this with the igx-tree-grid. As such is there a way to remove the row count and modify other parts of the groupby row?

![image](https://github.com/IgniteUI/igniteui-angular/assets/17785923/b0b0491b-bf31-4629-85e8-1789a63f74c8)

**Comment by gedinakova** [comment]
@mddifilippo89 Hi Mike, the simple answer is no. The Tree Grid grouping is not a built-in feature and in general is something we do not want to add to the component itself, as it is very specific and comes with a lot of complications.
For the grouping sample purposes we use a special pipe and we assign the number of records to the acual record value. That's why currently there's no way to change it.
