### ISSUE TITLE
17.0.10 not found

### ISSUE THREAD

**Issue by pierophp** [IgniteUI/igniteui-angular#14101]
## Description  

Our CI is failing to install the NPM Package from Infragistics' NPM.

I've found similar issues: #13463  and #13345

npm ERR! code E404
npm ERR! 404 Not Found - GET https://packages.infragistics.com/npm/js-licensed/@infragistics/igniteui-angular/-/igniteui-angular-17.0.10.tgz
npm ERR! 404 
npm ERR! 404  '@infragistics/igniteui-angular@https://packages.infragistics.com/npm/js-licensed/@infragistics/igniteui-angular/-/igniteui-angular-17.0.10.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

 * igniteui-angular version: 17.0.10

## Steps to reproduce  

1. npm install

**Comment by ChronosSF** [comment]
@pierophp , usually these happen either because of our server experiencing temporary issues or issues with your license. If you keep getting the error you could open a support case through your infragistics.com customer portal so that our support staff can check everything is in order with the latter.

**Comment by pierophp** [comment]
@ChronosSF, thank you for your response. In fact, our license is expired. However, the server could have a better response than 404 for that, like 403. I would never have thought it was a licensing problem with a 404 error.
