### ISSUE TITLE
Northwind service changed - sample not loading data

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#14102]
Northwind service changed - but sample not loading data
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote-data-operations#infinite-scroll-demo

New Products url is 
https://services.odata.org/northwind/northwind.svc/Products

Old url is 
https://services.odata.org/V4/Northwind/Northwind.svc/Products

Demo doesn't load data:
https://stackblitz.com/edit/rkkjim

**Comment by mddifilippo89** [comment]
@dkamburov 
https://github.com/IgniteUI/igniteui-angular-samples/pull/3454
https://github.com/IgniteUI/igniteui-blazor-examples/pull/686
https://github.com/IgniteUI/igniteui-react-examples/pull/526
https://github.com/IgniteUI/igniteui-wc-examples/pull/721

**Comment by MarielaTihova** [comment]
Old URL seems to be working now. 
![Screenshot 2024-07-11 104629](https://github.com/IgniteUI/igniteui-angular/assets/28449885/74ce3a6b-345f-4f17-8b4d-7ea0f7b55c4b)

There is the following issue with the new URL:
![Screenshot 2024-07-11 104552](https://github.com/IgniteUI/igniteui-angular/assets/28449885/097b9743-324b-4f12-b349-50828f1076ce)

If the old URL is going to stay active and not going to be deprecated, can we just use that? Because otherwise additional work would have to be done on either the Angular code or the code of the service. Please advise, @mddifilippo89

**Comment by MarielaTihova** [comment]
Closing since it is no longer an issue. Keeping the old URL as per the previous comment.
