### ISSUE TITLE
Custom Sorting Strategy is not working properly in multiple sorting mode

### ISSUE THREAD

**Issue by Zneeky** [IgniteUI/igniteui-angular#14261]
## Description  
When a custom sorting strategy is  applied to a column and I try to sort the grid by an additional column there is no effect

 * igniteui-angular version: 17.0.0
 * browser: any

## Steps to reproduce  

1. Open the attached [StackBlitz sample](https://stackblitz.com/edit/aczfih-qchedt?file=package.json) 
2. Sort by the first column
3. Sort by the second column

## Result  
The second column is not  adequately sorted, the default strategy is not applied

## Expected result  
The second column should be sorted alphabetically 

## Attachments  
[StackBlitz sample](https://stackblitz.com/edit/aczfih-qchedt?file=package.json)

**Comment by sboggs-trs** [comment]
Hi, I originally reported the issue. We currently have 5 different custom sorting strategies. But, we only experience this problem for date columns (with data data having values for the time portion of the date) that are displayed as shortDate and therefore require the custom sorting strategy in the Stackblitz example. To be clear - we do not have this issue when using the other 4 sorting strategies. It is as if igx-grid is additionally  sorting the data using the default strategy behind the scenes, in addition to the custom sorting strategy) - this is just speculation and not based on any source code evaluation, though.

**Comment by MonikaKirkova** [comment]
When custom sorting strategy is used and the column is sorted based on transformed values and not the default ones and a second column is sorted, the values of the first one are grouped in order to sort the second column only for the groups (the same values) and not to reorder the first column. 
However, when the grouping is executed the first column is grouped based on a groupingComparer. If there is non set, the default one is used. In order to successfully sort multiple columns with custom sorting strategy a groupingComparer should be set to the column with the custom strategy:

public onColumnInit(ev: IgxColumnComponent) {
        if (ev.field === 'ADate') {
            ev.sortStrategy = this.shortDateStrategy;
            ev.groupingComparer = (a: any, b: any, currRec: any, groupRec: any) => {
                const aDate: number = this.getShortDate(a);
                const bDate: number = this.getShortDate(b);
                let comparison: number = 0;
                if (!aDate && !bDate) return 0;
                if ((!aDate && bDate) || (aDate && bDate && aDate < bDate)) {
                    comparison = -1;
                } else if ((aDate && !bDate) || (aDate && bDate && aDate > bDate)) {
                    comparison = 1;
                } else if (aDate && bDate && aDate === bDate) {
                    comparison = 0;
                }
                return comparison;
            }
        }
    }
Please test the [modified sample](https://stackblitz.com/edit/aczfih-iksxur?file=src%2Fapp%2Fgrid%2Fgrid-sorting-sample%2Fgrid-sorting-sample.component.ts), demonstrating this behavior.

**Comment by sboggs-trs** [comment]
The example provided does not sort correctly when "ADate" is the primary sort and "Product Detail" is the secondary sort column. Note the dates in the "ADate" column are out of order in the image:
<img width="444" alt="Screenshot 2024-06-12 at 1 17 55 PM" src="https://github.com/IgniteUI/igniteui-angular/assets/19690013/c71993b8-06ba-4a91-81b3-c6136704f4be">

**Comment by MonikaKirkova** [comment]
The custom sorting strategy sorts based on the date without taking the hour under consideration and this is why ‘2023-02-02 6:30’ is below ‘2023-02-02 8:30’. If the ‘Adate’ column should be sorted based on the hour as well what I could suggest is changing the sorting strategy and removing the comparer or changing the method passed as groupingComparer.
