### ISSUE TITLE
When change in first row of dropdown then 13 th row dropdown changes automatically

### ISSUE THREAD

**Issue by SunnyDohale** [IgniteUI/igniteui-angular#14305]
After an investigation, I assume that this behavior is observed because of the virtualization of the igx-grid and because only the first 12 rows are displayed initially.

 * igniteui-angular version:  17
 * browser:  Edge

## Result  
When change in first row of dropdown then 13 th row dropdown changes automatically

## Expected result  
When change in first row of dropdown then 13 th row should not show data from first row dropdown

## Attachments  
Attached is the sample code

[s6z9dg.zip](https://github.com/user-attachments/files/15516554/s6z9dg.zip)

**Comment by ChronosSF** [comment]
@jackofdiamond5 , since the templates are being reused during the scroll the combos are getting updated inputs instead of being recreated. When the id of a combo in the template changes , it is no longer able to find its selected state from the service. This could be as simple as having some reinit logic around an id setter but it needs further investigation.
