### ISSUE TITLE
Filtering not working properly when is applied to column outside of the view port

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#1431]
### Description  
Filtering not working correctly when we have column with identical widths and the filterable column is outside of the visible area.

### Steps to reproduce  

1. Open grid-summary sample
2. Enable filtering for the last column
3. Scroll to the last column
4. Open filtering and pick 'Null' as a condition
5. Pick 'Equals' as condition

### Result  
The input field is not displayed.

### Expected result  
The input field should be displayed.

NOTE: This should be considered as part of the general issue with the virtualized columns missing change detection cycle, and therefore fixed in the virtualization implementation.

**Comment by zdrawku** [comment]
This is general issue that should be reviewd by @ChronosSF and @rkaraivanov , we had similar issue for the summaries which was fixed, but this new issue is for the filtering and the same is visible in scenarioos when editing. In a few words, this is general issue that shouldnt be fixed for each separate feature, this should be fixed in general.
