### ISSUE TITLE
Grid:Excel Style Filtering - selecting more than two text filters and their visualisation

### ISSUE THREAD

**Issue by AnjiManova** [IgniteUI/igniteui-angular#14449]
I noticed something else, and we talked with Desi: This is an additional issue that should be logged, but we can create such from this comment here. 

When I select one list item, the Text filter is changed to Text filter (1), and "Equal" is selected from the filters.
When I select two list items, the Text filter is changed to Text filter (2), and the "Custom filter" is selected from the filters. However, when I select three items, the Text filter is changed to Text filter (1), and there is no selection in the Text filters. Shouldn't it be showing the "Custom filter" again? This is replicated from the Master, and it is an issue there as well.

https://github.com/IgniteUI/igniteui-angular/assets/127843837/eb651517-be31-468c-81a7-98dc938d5417

I believe the logic should be: when two or more items are selected to apply the Custom filter, the filters should be indicated with (n) next to the Text filter.

Something interesting here is that everything looks fine if I select two items and then add more from the Custom filter. After manually adding an additional filter, there is no indication of which items/filters are selected.

https://github.com/IgniteUI/igniteui-angular/assets/127843837/73b7640c-7f0d-4ea9-b953-78786037dfbb

_Originally posted by @AnjiManova in https://github.com/IgniteUI/igniteui-angular/issues/14328#issuecomment-2196387445_

**Comment by georgianastasov** [comment]
After discussing with @hanastasov, we have confirmed that this is not a bug and does not need fixing. When one or two items are selected, we use individual equality conditions. However, for selections greater than two, the expression tree consolidates these into a single filtering operand with multiple values under an 'IN' condition.

Additionally, the part regarding Text filter(n) should not be fixed. Technically, when the "IN" condition is created, it acts as a single condition even though it checks against a collection of items. 

In the dialog where filters are listed, we should avoid making changes too. Including an 'IN' filter along with 'Contains', 'Does not contain', and other filters would require a UI to list all values against which we match (i.e., all selected items in the ESF list). This 'IN' filter is very specific to ESF and does not make sense to be displayed in this dialog, which is why it is not shown there initially.
