### ISSUE TITLE
Need SASS Function to set ripple for button.

### ISSUE THREAD

**Issue by kdawg1406** [IgniteUI/igniteui-angular#1445]
Need to be able to use igx-ripple-theme SASS function to set the ripple color on a button.

**Comment by SDinev** [comment]
For codegen purposes, we will apply a **default** IgxRipple to each button _(without a color value)_. The Sketch libraries do not provide a visual or otherwise representation of the ripple, let alone an option to change its color.

This is, however, a nice to have feature, and should be considered to be added July-Aug. @SlavUI @simeonoff

**Comment by kdawg1406** [comment]
@simeonoff @SDinev This is not how code gen is set up.  I use different logic for determining the color.

**Comment by simeonoff** [comment]
In order for the ripple to work at all you have to set the igxRipple directive on the target element, in your case the element that also has the igxButton directive. This will apply the default ripple, you don't have to pass any value to the igxRipple directive for it to work.

Even if the theming engine allowed you to change the ripple color for the button theme via Sass, you would still have to set the igxRipple directive on the button.

That being said, I don't see why what @SDinev suggested wouldn't work.

**Comment by kdawg1406** [comment]
@simeonoff yes, know how the ripple works, thanks.
