### ISSUE TITLE
igx-button-theme needs ability to style button font size, weight, family

### ISSUE THREAD

**Issue by kdawg1406** [IgniteUI/igniteui-angular#1448]
igx-button-theme needs ability to style button font size, weight, family.

Nebula Sketch allows customizing the button font size, weight, family, but when I add a class to the button, it's not being used.

Only Scenario.
igx-button-theme is used to set button text color and button background, using pallet names.

Must also be able to set the font size, weight, family, in CSS.

How is this accomplished?

**Comment by zdrawku** [comment]
You can check the sass docs for the component that you are using. For example there is explanation how to set the default font size used globally:

https://staging.infragistics.local/products/ignite-ui-angular/docs/sass/

![image](https://user-images.githubusercontent.com/11193764/40904008-02cb71b4-67e2-11e8-9ad5-1abdf80c50dd.png)

I see different options to set the color of the button, although I dont see such option for the fonts:

![image](https://user-images.githubusercontent.com/11193764/40904122-74b8b822-67e2-11e8-90f9-1754d3adc221.png)

**Comment by kdawg1406** [comment]
@zdrawku  we can't set font sizes globally for code gen.

I need what I requested:  igx-button-theme needs the ability to style button font size, weight, family.

**Comment by simeonoff** [comment]
@sdinev do we need this?

**Comment by SDinev** [comment]
We will review and implement changes to the buttons in the months following the marketing release, to align them with the new material guidelines from a couple of weeks back.
https://material.io/design/components/buttons.html#specs

Before that, this could cause more issues and inconsistency than do us good. 

For codegen v1, we agreed that we will only take into consideration the color of the text, and not the possible alignment/weight/size changes a designer makes. 

I am leaving this issue open, since at least some of the changes will be implemented in the foreseeable future and we can then close it

**Comment by simeonoff** [comment]
This has been resolved with the introduction of component typography.
