### ISSUE TITLE
Filter icon is misplaced

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1451]
### Description  
Go to the grid performance sample in grid dev samples.

### Result  
The columns that are with the min width have the filter icon misplaced.

![capture](https://user-images.githubusercontent.com/14248932/40905861-db806a32-67e7-11e8-8686-a8134d2cc5a1.PNG)

**Comment by simeonoff** [comment]
@hanastasov It's not misplaces, it's just that the content of the column header cell is set with overflow visible. This is due to the way the filtering menu is implemented to be a part of the header block. Once we implement the overlay module, we'll be use it to display the filtering menu, and the column header cells can have their overflow set to hidden. This will make the icon rather hide behind the next column.
