### ISSUE TITLE
TimePicker does not support specific time zones, like the DatePicker

### ISSUE THREAD

**Issue by MagisterXero** [IgniteUI/igniteui-angular#14515]
## Is your feature request related to a problem? Somewhat
The DatePicker component has support for specific time zones, but the TimePicker does not

## Describe the solution you'd like
The TimePicker should have the same support as the DatePicker for time zones, allowing the user to prevent it from automatically adjusting the time based on local time.

## Describe alternatives you've considered
Writing custom CSS to hide the displayed Time label and replace it with my own

**Comment by ddaribo** [comment]
Hi @MagisterXero,

Before the team proceeds with reviewing this as a candidate feature request, could you please describe what behavior you are referring to in terms of the `IgxDatePicker` supporting specific time zones?
In its [API](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDatePickerComponent.html) there aren’t any timezone related properties, I am afraid. 
Both the date and time pickers do not alter the bound date depending on the timezone. In order to display a specific timezone-aware date-time value, one could convert the date value itself, for example by leveraging the `Intl.DateTimeFormat` API.

For your convenience, I prepared [this sample,](https://stackblitz.com/edit/igx-date-and-time-pickers-timezone?file=src%2Fapp%2Fdatepicker-sample-1%2Fdatepicker-sample-1.component.ts) where you could see the date and time pickers initially showing the date and time for today’s date for 22 hours (10 PM). If changing the timezones and converting the date accoridngly, you will see all values are displayed as expected. Additionally, if the timezone is such that the date is already the next day, this is also reflected in the date picker's day and time picker’s day period values.

If you still need assistance, I could suggest also forking and modifying the sample in order to elaborate further on your request, precisely what you are currently attempting, what are the expected and actual results and anything else relevant.
