### ISSUE TITLE
Label in Indigo Style overlaps with input

### ISSUE THREAD

**Issue by Szanik** [IgniteUI/igniteui-angular#14566]
## Description  
Inputs with Labels not looking good in indigio design, overlapping labels, maybe not enough spac?

 * igniteui-angular version: 18.x
 * browser: edge (chromiumbased)

## Steps to reproduce  

1.  Go to [ Infragistics Display Density](https://www.infragistics.com/products/ignite-ui-angular/angular/components/display-density) 
2. Switch theme to indigo
3. make the density small

## Result  
Not sure how to describe it in words but the text is to big and the labels are overlapping to the other inputs above

## Expected result  
None of this and the same behavoiur like the material theme

 
![image](https://github.com/user-attachments/assets/781e6a0b-cd50-4dd3-b0a5-029be1723819)

**Comment by desig9stein** [comment]
@ChronosSF I believe the problem lies with the theme switcher. For some reason, it only changes the color palette. What we see in the screenshot is not indigo. If you open the StackBlitz sample and change the palette and schema in `_variables.scss `to `$palette: $light-indigo-palette;` and `$schema: $light-indigo-schema;`, you will see the indigo theme working as expected.
