### ISSUE TITLE
Grouping by Date Column Causes Incorrect Collapse/Expand Behavior After State Restoration

### ISSUE THREAD

**Issue by Zneeky** [IgniteUI/igniteui-angular#14619]
## Description  
When grouping by a date column and saving the grid state, the functionality works as expected. However, upon restoring the saved state, all groups are either collapsed or expanded simultaneously, making it impossible to collapse or expand individual groups. The grid state does not correctly restore the previous grouping state, leading to this unintended behavior.

 * igniteui-angular version: 18.0.x
 * browser: any

## Steps to reproduce  

1. Implement the igx-grid component and configure a date column with groupable = true. (or use this sample on [StackBlitz](https://stackblitz.com/edit/fcajvm?file=src%2Fapp%2Fgrid%2Fgrid-save-state%2Fgrid-state.component.ts))
2. Group the grid by this date column.
3. Expand at least one group.
4. Save the grid state and store the serialized value in a database or local storage.
5. Restore the saved grid state.
6. Observe the behavior of the groups

## Result  
The groups cannot be collapsed or expanded individually; all groups are affected simultaneously.

## Expected result  
The grid should restore the state correctly, with only the previously expanded groups being expanded. Individual group rows should be expandable and collapsible independently.

## Attachments  
[StackBlitz](https://stackblitz.com/edit/fcajvm?file=src%2Fapp%2Fgrid%2Fgrid-save-state%2Fgrid-state.component.ts) sample

**Comment by ddaribo** [comment]
Adding another related behavior, reproduced for other column data types as well - In the referenced [demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/state-persistence#demo):

1.	Group By “Country”
2.	Collapse the “Canada” and “Italy” group hierarchies to leave only a single one expanded (“USA”).
3.	Click “Save” to persist the state.
4.	Click the “Expand all groups” icon in the first header cell in order to collapse all groups -> the `grid.groupsExpanded` property will be changed to `false` in result of that.
5.	Click “Resotre” button to restore the state.
6.	At this point all groups will be expanded, which is not the correct state that was saved.

![grid-state-expansion-restore-issue](https://github.com/user-attachments/assets/15c12eea-62ac-4896-b935-fb110b0e017d)
