### ISSUE TITLE
[IgxGrid] - RowEditDone returns [object Object]

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#14736]
Run sample
https://stackblitz.com/edit/t515fr

Edit a value in a cell. Review output on the right side. 

![image](https://github.com/user-attachments/assets/b9d947a7-00a4-4809-81c0-fb1cecaf62c4)

**Comment by RivaIvanova** [comment]
Hi @mddifilippo89,

This is the expected behavior since multiple cells per row can be edited and the `newValue` parameter of the `rowEditDone` event is the whole data object with the updated properties.
![row-edit-events](https://github.com/user-attachments/assets/ef645a33-db40-47ae-b130-625629552084)

In order to log the data object in the "Events execution sequence", I could suggest using the [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) method:
```ts
public rowEditDone(evt) {
  console.log(evt);
  this.logAnEvent(`=> 'rowEditDone'` + JSON.stringify(evt.newValue));
}
```
[Here](https://stackblitz.com/edit/t515fr-f2sczs?file=src%2Fapp%2Fgrid%2Fgrid-editing-lifecycle-sample%2Fgrid-editing-lifecycle.component.ts) is a modified sample.
