### ISSUE TITLE
In IE when navigate with right arrow the grid layout is broken

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#1483]
### Description  
In IE when navigate with right arrow key the grid layout is broken

### Steps to reproduce  

1. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_sorting.html in IE
2. Select a cell in column OrderDate
3. Press right arrow key 2 times

Note: this happens only when the the grid does not have horizontal scroll

### Result  
The grid layout is boken

### Expected result  
Grid should look correct

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/41037961-7ebcb488-699d-11e8-96c9-10a4d724e2bd.png)

**Comment by Aleksandyr** [comment]
@nrobakova It's not a bug. It's a problem of the sample because it is not configured correctly. We currently do not support the percentage width per column and whenever the last column is without specified width like in this particular case it becomes bigger than it should be, because when you set width per column in percentage it comes down to pixels and whenever the grid tries to calculate the width for the last column it gets bigger than it should be.
