### ISSUE TITLE
Cannot set OverlaySettings to IgxToast, IgxSnackbar

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#14934]
## Description  
The documentation states that both components use _"[Overlay Settings](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/overlaysettings.html) to control the position of its container. The default settings can be changed by defining Custom OverlaySettings and passing them to the `open()` method."_

```ts
public customSettings: OverlaySettings = {
    positionStrategy: new GlobalPositionStrategy(
        { 
            horizontalDirection: HorizontalAlignment.Left,
            verticalDirection: VerticalAlignment.Top
        }),
    modal: true,
    closeOnOutsideClick: true,
};

toast.open(customSettings);
snackbar.open(customSettings);
```
[Toast Overlay Settings docs](https://www.infragistics.com/products/ignite-ui-angular/angular/components/toast#overlay-settings) & [Snackbar Overlay Settings docs](https://www.infragistics.com/products/ignite-ui-angular/angular/components/snackbar#overlay-settings).

However, none of the `open` methods accept `OverlaySettings` as a parameter. ([toast open()](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/toast/toast.component.ts#L164C5-L164C74), [snackbar open()](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts#L158))
```ts
// toast
public override open(message?: string, settings?: PositionSettings) {
   ...
}

// snackbar
public override open(message?: string) {
   ...
}
```

 * igniteui-angular version: master, 18.1, 17.2
 * browser: 

## Steps to reproduce  

1.  Define custom `OverlaySettings` and pass them to the `open()` method.

## Result  
Cannot set OverlaySettings to IgxToast, IgxSnackbar.

## Expected result  
Should be able to set OverlaySettings to IgxToast, IgxSnackbar.

**Comment by damyanpetev** [comment]
@RivaIvanova @SisIvanova
Outside of what the docs say (which is obviously not correct), is there an actual need for some use case that requires anything from the full `OverlaySettings`? That's keeping in mind both components expose the `outlet` and `PositionSettings` atm.

From what I can tell, those already cover most needs and the other settings don't entirely make sense for those more specialized components - i.e. I don't think we care to have a positioned toast around a target or a modal one. These components are not intended for active interaction either, so close on outside click and escape also don't make too much sense. That doesn't leave much else useful from the settings, so this could be a case of correcting the documentation.

PS: What might be useful for the Toast/Snackbar would be if we had a way to utilize the Container strategy instead of just Global (perhaps based on outlet use) and if the user-provided position settings were merged with defaults :)

**Comment by RivaIvanova** [comment]
This was originally reported by a client who had the `closeOnEscape` and `positionStrategy` options set. After a discussion, it turned out that positioning the `igx-snackbar` was the main task so setting the `PositionSettings` worked for her. I guess it does seem to be a case of just correcting the documentation so this issue can be closed.
Logged a new one for the documentation [here](https://github.com/IgniteUI/igniteui-docfx/issues/5988).
