### ISSUE TITLE
WebComponents grid issues

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#15073]
Run the following sample
[HGrid_webComponents.zip](https://github.com/user-attachments/files/17773849/HGrid_webComponents.zip)

 "igniteui-webcomponents": "~5.1.0",
 "igniteui-webcomponents-core": "~5.0.0",
 "igniteui-webcomponents-grids": "~5.0.0",

## Steps to reproduce  

1. Run the attached sample
2. [SAME ON BLAZOR] Open Advanced Filtering and try to Select a column, the dropdown select a column does not open anything:
![selectColumn](https://github.com/user-attachments/assets/9a8e6814-3193-4f03-8865-3e986864d96d)

3. Expand the child grid and observe the BilboardReview column, which is templated to display a slider. SLider does not show a value and looks strange

4. Observe the HGrid page:
![image](https://github.com/user-attachments/assets/f143c575-8b08-4b11-b91e-59542e4a1a33)

5. Observe the Hgrid Flat Data page:
![image](https://github.com/user-attachments/assets/32270fa9-42d7-4acf-85f2-030b7ee5947d)

![image](https://github.com/user-attachments/assets/d8d43071-a4d2-4d86-befe-6aafb86d4959)

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by damyanpetev** [comment]
@hanastasov Okay multiple issues, mostly configurational:
4. and 5. are both due to missing link to the grid theme:
```html
<link rel='stylesheet' href='node_modules/igniteui-webcomponents-grids/grids/themes/light/material.css'>
```
like the third grid view has. If that's App Builder generated, then the issue is there //CC @Lipata 

3. For the slider, the 5.1.x Web Components package is unfortunately slightly ahead with theming updates and thus doesn't quite work w/ 5.0.0 grids package. Roll back to `igniteui-webcomponents@~5.0.0` for now or wait for the updates on the rest of the packages. For now with 5.0.2 the slider seems to work
![image](https://github.com/user-attachments/assets/c88f35da-a989-4e17-8f11-ee59dd47b35f)
Still looks slightly odd tho, seems like the inactive track is on top of the value fill - kinda makes it looks like a border. That might be an issue with the slider itself, possibly resolved already.

The **_actual issue_** here for sure is the Advanced Filtering - from what I can see the select is empty (no items) which probably means the columns are not passed to it. Possibly due to loading a bit late (that's what normally causes issues for Elements), though the live samples work just fine - https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/hierarchical-grid/advanced-filtering meaning this might have been regressed even.

**Comment by damyanpetev** [comment]
Oh, sigh @hanastasov - there's a reason why the column select is empty:
![image](https://github.com/user-attachments/assets/2ff03507-b87f-4f8f-ba6e-aedd27b93e68)
They are all marked `filterable="false"`... Drop that and it works fine 😁
