### ISSUE TITLE
Setting/hiding the label of a igx-datePicker

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1519]
### Request
Setting 'Date' above the actual igx-datePicker is stating the obvious as the global style shows what it does.
It would be nice if you could change the label 'Date' to something meaningful or hide it. This would make it more consistent with the rest of the controls.
For example: the input(groups) don't have "input" above them.

**Comment by zdrawku** [comment]
@Hypenate the PR looks good, although we need to mark the issue as "Feature request" because additional changes should be considered. We've implemented directives like prefix and suffix and we need to add them as well, although this will happen at the beginning of July (at the earliest).

@SlavUI if you are okay with these change we definetely could consider them at this point.

My personal opinion is that we should be able to hide/show the label and to have the ability to set different text values, so I am okay with the currently proposed enhancement.

@desig9stein if you have any comments from UX point of view, let us know

Related to #1518

**Comment by SlavUI** [comment]
@zdrawku hi Zdravko i agree with your opinion and with the suggestions of @Hypenate so let try to adjust this as soon as we can even before beginning of July

**Comment by zdrawku** [comment]
@Aleksandyr the changes are merget to master, could you proceed with the tests
