### ISSUE TITLE
There's no highlight on the group row while focus is on it.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#1659]
### Description  
When navigating via keyboard through group rows there's no highlight on which group row is currently focused.

### Steps to reproduce  

1. Open the dev demos and go to to the Grid GroupBy sample.
2. Group by multiple columns.
3. Click on a cell and start navigating up/down using the arrow keys.

### Result  
You can navigate successfully between group and data cells however when passing through group rows there's no visual highlight on which group row is currently focused.

### Expected result  
Group row that currently holds the focus should be highlighted in some way.

**Comment by desig9stein** [comment]
There is a highlight on the grouping indicator which is the interactable element, you cannot interact with the row so there is no need to have a highlight there. In the spec I saw that there are two options, one is to highlight the row and the other one is to highlight the cell that holds the expand/collapse indicator, I decided to go with the second one since, in my opinion, it's more convenient. However, the keyboard navigation is not working, for some reason, it doesn't move the focus when you press the keyboard arrows if you use tab it works fine. I think that the igx-grid__group-content should not have tabindex="0" since it's not an intractable element.

**Comment by MayaKirova** [comment]
@desig9stein the content should be focusable for ARIA support since it contains the group information, which screen readers should be allowed to read.
Keyboard navigation via the arrow keys goes through the group content (not the expansion indicator), since that would be the next element that matches the previous selected cell index.
