### ISSUE TITLE
When grid has parent containers with flex used, the grid is incorrectly rendered

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1662]
### Description  
When grid has parent containers with flex used, the grid is incorrectly rendered.

**NOTES:**
In **6.0.x**, the grid is not rendered at all and only a blank page is visible (no console errors).

### Steps to reproduce  

1. Download and run the attached sample application.
2. Scroll the grid horizontally.

### Result  
Grid starts resizing and rendering **in**correctly.

### Expected result  
Grid is rendering correctly.

### Attachments  

![flex](https://user-images.githubusercontent.com/12784974/41766118-c054cb56-760e-11e8-9c25-455cef68729b.gif)
[gridSampleFlex.zip](https://github.com/IgniteUI/igniteui-angular/files/2126846/gridSampleFlex.zip)

**Comment by ChronosSF** [comment]
I think this is related to #1668 and the correct behavior for the sample's configuration is that nothing is shown. This is because the flex container doesn't have any inherent width. 

In master it does this because the thead element has display:table which gives some but wrong inherent width for the flex column. I am fixing it with the PR for #1668 so it will again just show an empty page (everything is rendered mind you, it is just hidden behind this flex column with width 0).

If you copy the configuration in the dev samples app, everything works because there is another wrapping element that has width 100% and that is enough to make the flex column have width and therefore the inner grid to be shown.

I hope @simeonoff can confirm my observation.
