### ISSUE TITLE
Feature request: Igx tooltip

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1710]
### Description  
Material style tooltip, similar to https://material.angular.io/components/tooltip/overview

**Comment by Eralmidia** [comment]
It would be great if this was templateable as well. So a simple igxTooltip="Some text" easy tooltip for most occasions, but the ability to render html or a full component in a tooltop would also be useful.

**Comment by StefanIvanov** [comment]
Link to the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/Tooltip-Specification#user-stories) for the Tooltip

**Comment by Eralmidia** [comment]
Great to see templating is implemented 👍 What exactly does the limitation entail? Do we always have to create a separate DOM element for a tooltip?

**Comment by tachojelev** [comment]
@Eralmidia, we are glad you enjoy the templating functionality.

The answer to your last question is yes. In order to set a tooltip to an element, we need to create a separate DOM element, which represents the tooltip itself. While this is not as convenient as setting a single property for text only tooltips, it makes the templating, styling and access to the tooltip a lot easier.

**Comment by Eralmidia** [comment]
Ok. I was thinking it would be possible to stream a template ref from the directive to the igx overlay, and only have a single tooltip component reside there? Still it's a great addition to have a templateable tooltip.
