### ISSUE TITLE
Grid Keyboard navigation performance issue

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular#1923]
### Description  
When you open the Propeller Grid and you select a cell and hold the right arrow key to start navigation the scroll is lagging. 

### Steps to reproduce  

1. Open Staging
2. Scroll the Grid with the keyboard
3. ...

### Result  
There is a lag on scrolling

### Expected result  
There should be no lag

**Comment by mpavlinov** [comment]
This also is visible in the "Grid Performance" dev sample:

### Steps to reproduce  

1. Open: http://localhost:4200/gridPerformance dev sample
2. Click on a cell and press the right arrow key. Keep it pressed.
3. Observe the navigation

### Result  
The grid freezes and the active cell stays still

### Expected result  
The grid should scroll and the active cell should change


Note: This is regression due to the changed cell component change detection strategy from OnPush to Default
