### ISSUE TITLE
Horizontal Scrolling is not shown when you have paging activated and you start resizing the columns

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular#1951]
### Description  
Horizontal Scrolling is not shown when you have paging activated and you start resizing the columns

 * igniteui-angular version: 6.1.0
 * browser: Chrome

### Steps to reproduce  

1. Open Cell editing sample on staging 
2. Start resizing the first column and it will push the columns to the right but there will be no horizontal scroll
3. 

### Result  
The columns are pushed to the right but there is no horizontal scroll. If you push more and more the scrolls appears but again you can't see all of the pushed columns.

### Expected result  
Upon the push of the columns to the right a horizontal scroll should appear

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by skrustev** [comment]
This seems to related to the column widths being in percentage.
Currently when resized the resized column get its width changed to pixel while the rest have it in percentage. Since `totalWidth` takes the number of the width. If a column has width `25%` it will take that it's width is `25px`.

I believe in order for this to be fixed there are 2 options:
1) All column widths should be converted to pixels when resizing is started 
2) The percentages for the resized column should change based on current resizing action. For example if made bigger it will have its width in percentage increased and not switched to pixels, while the rest of the columns would have their widths in percentage decreased.

@SAndreeva @ChronosSF What do you think?

**Comment by mpavlinov** [comment]
@skrustev I think the second approach is the correct one.

**Comment by tiliev** [comment]
We're going to wait until [this ](https://github.com/IgniteUI/igniteui-angular/pull/2656)PR is merged, because it introduces a big change in the width/height logic of the grid. After that we'll fix this issue.

**Comment by zdrawku** [comment]
@tiliev we can start with this issue

**Comment by ddincheva** [comment]
This issue is related with version 6.1.x which is no longer supported, but is another issue (#3513) that describe the same problem for our latest versions: 6.2.x  and 7.1.x. There is also a PR that fix this issue: #3515 and #3518
