### ISSUE TITLE
aside in igx-nav-drawer surpasses height of igx-nav-drawer

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1981]
### Description  
The right border of the `aside` surpassed the length of the `igx-nav-drawer` when the height of the `igx-nav-drawer` is limited.

 * igniteui-angular version: 6.1
 * browser: Chrome

### Steps to reproduce  
1. /

### Result  
The right border of the `<aside />` goes to the bottom.

### Expected result  
The right border of the `<aside />` inherits the height of it's parent, the `igx-nav-drawer`

### Attachments  
![image](https://user-images.githubusercontent.com/7478681/42558481-aa95bf9a-84f1-11e8-8430-727c5b999363.png)

![image](https://user-images.githubusercontent.com/7478681/42558809-a7042276-84f2-11e8-84fe-60bf715da427.png)

**Comment by damyanpetev** [comment]
I assume the app is using a pinned nav drawer and perhaps flex layout?
The `<igx-nav-drawer>` is just a container that doesn't even have `display` set so it usually collapses entirely or flexes based on its content depending on styling. The `<aside>` is the actual menu and the issue is that it takes the window's height without much consideration.

The nav drawer was always intended to be at the top level of app hierarchy (thus the window size) and the case with a drawer nested inside the layout has been sitting on the back-burner. The only meaningful approach I see would be to leave it at `"100%"` height, which will inherit the either the main element height or the closest block parent. 
<sub>That'll of course leave the possibility of the drawer collapsing miserably if the app layout is not set up right, which seems fine to leave to the developer.</sub>
