### ISSUE TITLE
Feature Request: Vertical tabs

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1982]
A request for vertical tabs 😄 

**Vertical (feature)**
![image](https://user-images.githubusercontent.com/7478681/42562378-e8e169de-84fb-11e8-8ed8-ab3ac02cab25.png)

**[Horizontal](https://www.infragistics.com/products/ignite-ui-angular/angular/components/tabs.html#tabs-demo) (default)**
![image](https://user-images.githubusercontent.com/7478681/42562434-fef5cfc6-84fb-11e8-9585-a31b7976260e.png)

**Comment by StefanIvanov** [comment]
Hello @Hypenate 
Here is Stefan from the Design team working on Ignite UI for Angular. I firmly believe that Tabs is not the right control to use for your scenario, as it is conceptually meant to help organize different views of the same information or switch between similar or related data sets, rather than for app navigation. The suitable controls for what you are trying to achieve are the Bottom Navigation and the Navigation Drawer, but since the former is meant to always render horizontally at the bottom, you seem to be left only with the latter. Therefore, I would strongly advise that using a Navigation Drawer is the best UX decision you could make, and if it causes issues or misbehaves like in #1548 , then those issues should be addressed by our team with priority.

**Comment by Hypenate** [comment]
@StefanIvanov  Thank you for the feedback.

**Comment by StefanIvanov** [comment]
@Hypenate feedback is always welcome, I am glad I could provide some guidance
