### ISSUE TITLE
Sorting broken after clicking different column headers

### ISSUE THREAD

**Issue by jberes** [IgniteUI/igniteui-angular#2009]
### Description  
Sorting stops working after sorting several columns

 * igniteui-angular version: 6.1
 * browser: Chrome

### Steps to reproduce  

1. Step 1
2. Step 2
3. ...

### Result  
What is the actual result after following the steps to reproduce?

### Expected result  
What is the expected result after following the steps to reproduce?

### Attachments  
Attach a sample if available, and screenshots, if applicable.  

![grid-broken-sorting](https://user-images.githubusercontent.com/18453092/42742218-3b65408e-8887-11e8-97d2-08358fa8caec.gif)

**Comment by kdinev** [comment]
@jberes You have applied sorting on the `Order Date` column, which has unique dates, and then your applying a second sort on the `Units in Stock` column, which doesn't apply any additional sorting, since there's no records that repeat the same date. The sorting by the second column is applied to records that have identical values for the first sorting. It's the same with groupby: when you group by a column with unique values, and sort by a different column, nothing changes, since there's never more than 1 record in the groups to resort by.
