### ISSUE TITLE
When column has template and column width is smaller the cells content is not previewed correct

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2016]
### Description  
Describe the issue.

### Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-l3wwaa?file=app%2Fgrid%2Fgrid-sample-3%2Fgrid-sample-3.component.html
2. Look at column ProductName

### Result  
The rows width is not correct and cells contend is over the next cell

### Expected result  
Cells text should be visbble

### Attachments  

![image](https://user-images.githubusercontent.com/11463104/42760339-d358876c-8912-11e8-9bda-11ce93add90d.png)

**Comment by DDavidkov** [comment]
@nrobakova The column is so small, because its width is set in the grid template to 88 pixels, so this is expected. If you want to make the grid column width larger, you can set it to a bigger number, or leave all columns with unset width and the grid will spread the available width equally among all columns.

Also, if you want to prevent the cell text from overlapping the next cell, you should put it a container of class "igx-grid__td-text", which will cut the text that can't be fit in the cell, using an ellipsis (or alternatively you can manually apply the desired styling). We can't do a lot more if we simply don't have the space to display the cell value.
