### ISSUE TITLE
igx-nav-drawer__overlay vs igx-overlay__wrapper

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#2045]
### Description  
I'm currently implementing the following quick navigation menu, to navigate between the main modules of our application:
![image](https://user-images.githubusercontent.com/12936286/42933413-046dff92-8b45-11e8-8d20-8f462853be16.png)
It utilizes the new igx-drop-down component, and as far as I can tell, the igx-drop-down uses the new igx-overlay for rendering.

There is however one problem with this. On the left hand side of the page, we have a menu, using the igx-nav-drawer:
![image](https://user-images.githubusercontent.com/12936286/42933631-80a9c438-8b45-11e8-83bf-be0a807d2a1c.png)

The overlay for the nav drawer (.igx-nav-drawer__overlay), seems to have a z-index of 999. The overlay used for the dropdown (.igx-overlay__wrapper), has a fixed, position, but no z-index. I do agree, that in most cases, the content of the overlay, should be rendered below the nav drawer. But in this scenario this is not the case. So how can I render a drop down above the nav drawer?

Wanted result:
![image](https://user-images.githubusercontent.com/12936286/42933834-19e58e7a-8b46-11e8-8542-99735e1d07a4.png)

 * igniteui-angular version: 6.1.1
 * browser: Chrome

**Comment by damyanpetev** [comment]
Indeed, the nav drawer is supposed to be topmost layer when not pinned (temporary). It's even now called modal in the updated Material Guidelines and the case with a sticky header on top seems to be gone.

Back on topic, the overlay doesn't rely on `z-index` due to it's position in the DOM and part of the reason for that is so we can reduce the index war inside more complex components. As the overlay should be in the same stacking context (being fixed), to put it on top of the drawer you'd have to at least match the index:
```css
.igx-overlay__wrapper {
  z-index: 999;
}
```
*this should be in the app styles or component without view encapsulation*

We considered adding a static value of `1` in our styles to compensate for some application layouts, though that won't be enough in this case. Such static index can lead to drop-downs left open peaking through the drawer which will likely be undesirable in most other cases, so whether this style works for you depends on the application I suppose.

Alternatively, to control per-dropdown you can use the the `open/toggle` methods of the `IgxDropDownComponent` that accept overlay settings and one of those is the [position strategy](https://www.infragistics.com/products/ignite-ui-angular/angular/components/overlay_position.html):
```ts
export class CustomPositionStrategy extends ConnectedPositioningStrategy {
  position(contentElement: HTMLElement, size: { width: number; height: number; }, document?: Document, initialCall?: boolean): void {
    contentElement.parentElement.style.zIndex = '999';
    super.position(contentElement, size, document, initialCall);
  }
}
```
The parent is the same `.igx-overlay__wrapper` element, but specific to this dropdown. And then pass the strategy when opening the dropdown:
```ts
// in component.ts
@ViewChild(IgxDropDownComponent) public igxDropDown: IgxDropDownComponent;

public toggleDropDown(eventArgs) {
  this.igxDropDown.toggle({
    modal: false,
    positionStrategy: new CustomPositionStrategy({ target: eventArgs.target })
  });
}
```

**Comment by damyanpetev** [comment]
@Eralmidia Have you been able to test any of the suggestions in your app?

**Comment by damyanpetev** [comment]
This has been inactive for a while and I'll close the issue.
Feel free to discuss if there are any further questions.

**Comment by Eralmidia** [comment]
Hi Damyan

Sorry for the late reply, I was on holiday.

The custom position strategy sample you provided worked perfectly. Thanks for the assistance.
