### ISSUE TITLE
Print pins the nav drawer

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#2334]
### Description  
It seems that opening the print dialog of the browser changes the pin state of the nav drawer. I tried setting a negative value for the pinThreshold as well, without any luck.

 * igniteui-angular version: 6.0.1
 * browser: Chrome

### Steps to reproduce  

1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/navdrawer.html
2. Make sure the pin switch is off
3. Press Ctrl + p
4. Cancel the print
5. Pin is now turned on.

### Expected result  
Print dialog should not affect pin state

**Comment by damyanpetev** [comment]
To disable [`pinThreshold`](https://www.infragistics.com/products/ignite-ui-angular/angular/components/navdrawer.html#api) it should be set to a falsy value (e.g. `0`, `null`, `false`):
https://stackblitz.com/edit/angular-6isttg?file=app/navdrawer/navdrawer.component.html  
Otherwise it will update the state when the window resizes, which is what happens here.

Apparently the print dialog triggers resize on the actual window/child frames, which would seem fair if the page was reused for the preview, but it's not really. This is specific to WebKit-s; Blink-based Chrome/Opera seem to [trigger](https://stackoverflow.com/questions/29296733/window-resize-and-print-preview-mode) before print dialog and at least on this page Safari triggers after closing the dialog, but sometimes and only if the iframe is not focused.

Not too keen on adding browser+print specific workaround in the component.
But, if the goal is to keep the auto pinning enabled _and_ the manual override _when_ printing.. I could play with caching the window width to see if that'll help ignore those events.
Do let me know if that's the case.

**Comment by Eralmidia** [comment]
I see. Working on web myself, I see the reluctance of trying to fight the browser in the component ;) I'll just leave it up to you to decide if this is as intended, and close the issue when you see fit.

In my case, I had some other issues with the nav when window resize occured, which I had to handle (but I belive those are more related to our application and not the nav drawer), and that workaround has fixed the pinning issue for us as well.

I'll let you close the ticket whenever you feel this is resolved. Thanks again for the support Damyan =)

**Comment by damyanpetev** [comment]
No problem! :)
I figure storing the window width won't hurt and not doing anything if it hasn't changed might even be better. Chrome is pretty chatty with those resize events and at least it did stop the auto pin when opening the print dialog.
