### ISSUE TITLE
The ripple circle should become light gray when igx-checkbox is unchecked.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#2495]
### Description  
The ripple circle should become light gray when igx-checkbox is unchecked.

 * igniteui-angular version: 6.1.4
 * browser: IE11

### Steps to reproduce  

1. Open the attached sample with IE11.
2. Click on the check box of "Check1" to uncheck it.

### Result  
The ripple circle becomes light red.

### Expected result  
The ripple circle becomes light gray.
With Chrome, Firefox and Edge, the ripple circle becomes light gray as expected, but with IE11, it does not become light gray.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
[my-app2.zip](https://github.com/IgniteUI/igniteui-angular/files/2322719/my-app2.zip)

**Comment by tkiryu** [comment]
In addition, I found that the ripple circle becomes light **RED** as well when focusing on unchecked `igx-checkbox`.

- igniteui-angular version: 6.1.4
- browser: **Chrome** and IE11.

### Steps to reproduce
1. Go to https://stackblitz.com/edit/igx-checkbox
2. Press TAB key in order to focus on `igx-checkbox`.

### Result
The ripple circle becomes light **RED**.
<img width="59" alt="2018-08-29 10 27 58" src="https://user-images.githubusercontent.com/15909409/44759647-43fdd780-ab76-11e8-9287-a531a749a5e8.png">

### Expected result
The ripple circle should become light **GRAY**.
