### ISSUE TITLE
Typedoc search is not working

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#2526]
### Steps to reproduce  

1. Generate documentation with `npm run build:docs`
2. Once it is generated, find the search input at the beginning of the page and type some string value (image below)
3. Nothing happens

Note:
It is highly possible the search to be broken by a configuration that we have or the structure of our files. 

### Result  
Search is not working

### Expected result  
Search should be working

### Attachments  
![image](https://user-images.githubusercontent.com/11193764/44836398-80e1d100-ac3f-11e8-9e5f-da49d242d821.png)

**Comment by Aleksandyr** [comment]
It seems that the problem comes from how you are passing the reference to the main file/directory of the project you would like to generate.

If you give the direct reference to the main file that exports all of the components typedoc perceives all files that are out of the scope of this direct reference as external and respectively they are not included into the search data that it performs before building the static html files.

But if you pass a direct reference to the directory which contains the whole hierarchy of the project including the main file, everything is perceived as internal and works as expected.

**Comment by rkaraivanov** [comment]
Closed via #2580
