### ISSUE TITLE
Time starts from 03 minutes instead of 00

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#2541]
### Description  
Time starts from 3 minutes instead of 00

### Steps to reproduce  

1. [Open time-picker demos](https://www.infragistics.com/products/ignite-ui-angular/angular/components/time_picker.html#time-picker-demo)
2. Open the time picker

### Result  
Initial time value is not correct (:03) minutes instead of (:00)

### Expected result  
Time should be correct

### Attachments  
![image](https://user-images.githubusercontent.com/11193764/44987606-73567f00-af90-11e8-9b0d-71b333526090.png)

**Comment by sstoyanovIG** [comment]
When we set the isSpinLoop to false, the default value in the dialog is 01:00 AM: 
https://www.infragistics.com/products/ignite-ui-angular/angular/components/time_picker.html#change-delta-and-spin-mode
For the default mode isSpinLoop = true, we should manually set the value, but it cannot be 01:00 AM, because if the user change the itemsDelta to {hours:2, minutes:5} e.g. we no longer have 01 as item in the hours section. I guess we can only change the minutes?

@kdinev @StefanIvanov  What do you think?

**Comment by StefanIvanov** [comment]
As we discussed this seems like the most minimalistic solution that gives a more expected and desirable default state

**Comment by zdrawku** [comment]
Now it looks better, I just tested the PR with variety of scenarios and not having the minutes to start from the 3rd minute item is a better solution:

![image](https://user-images.githubusercontent.com/11193764/45015368-2a530900-b02a-11e8-9817-6f469b4f5dde.png)

**Comment by StefanIvanov** [comment]
Great job on the reaction time @sstoyanovIG
