### ISSUE TITLE
Selected row color

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#2572]
### Description  
Hi guys. A couple of question in regards to the color of a selected row in the igx-grid. My goal is to produce a simple coloring of a selected row (not multiselect). The following is an example of a current grid (using igniteui grid), and lilustrates what I need:
![image](https://user-images.githubusercontent.com/12936286/45137916-d15eae80-b1aa-11e8-822b-ad4a0358fa90.png)

I have two issues achieving this:
1. You can't disable the selected cell color: Of course, you do have the $cell-selected-background (setting it to the same color as the row), but if you use different colors for odd and even rows, this isn't sufficient. As a workaround I have set the selected cell color to transparent. Would this be the advised solution?
2. I'm having trouble getting the $row-selected-background to work. It seems that this only affects the selected row when using multiselect. ([rowSelectable]="true"). What I would like is the ability to select a single row with a simple click (like in the screenshot).

 * igniteui-angular version: 6.1.4
 * browser: Chrome

**Comment by Lipata** [comment]
Hi, @Eralmidia.

When [rowSelectable]="false", still you can use grid API that is responsible for row selection.

```
<igx-grid [rowSelectable]="selection" (onSelection)="handleRowSelection($event)">...</igx-grid>
```

```
handleRowSelection(args) {
     const targetCell = args.cell as IgxGridCellComponent;
     if  (!this.selection) {
         this.grid1.selectRows([targetCell.row.rowID], true);
     }
}
```

You can look at the following [sample](https://github.com/IgniteUI/igniteui-angular/tree/master/src/app/grid-selection), and this is they way you can achieve single selection in the grid right now. This is because when row selection is enabled it is multiple by default. One of the reasons for this is that Material Design guidelines state this behavior. If you run our demos that are part of the igniteui-angular repository, then you will be able to see that sample above in action.

As far as about the cell background, what you also can do is to have the same color as the selected row, but this is similar to the transparent background. In the code, the cell selected style is bound to cell `selected` property, and whenever the property is true than the class is applied. On other hand, when cell is clicked, it immediately set its property `selected` to `true`.

Regards
