### ISSUE TITLE
deselect_item does not remove the cell from the selected cells collection

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#2636]
### Description  
Describe the issue.

### Steps to reproduce  

1.Go to https://stackblitz.com/edit/angular-mkx9q5-cxqoh2
2. Select the first cell on the first row
3. Click the clear selection button

### Result  
Cell stays selected

### Expected result  
Cell to be deselected

**Comment by Lipata** [comment]
Using reference for a cellID (which is object) seems to introduce other problems. Either a new way of saving ID in the selection will be introduced or better solution will be found. This could happen while creating the multi cell selection feature and this problem will be taken into account. This is because the other two options that are iterating through each object properties and comparing them and serialization of the object to string is neither.

**Comment by wnvko** [comment]
You should set `selected` of cell to `false` like this:

```
public clearSelection() {
    const cell = this.grid1.getCellByColumn(0, "ProductName");
    cell.selected = false;
    this.grid1.cdr.detectChanges();
}
```

Note, to update the UI you should also call `detectChanges` over the grid.
This should work in this way in current version `8.1.0` and `7.3.11`.
