### ISSUE TITLE
Sort direction of a column header icon is not correct when a column is grouped by program.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#2669]
### Description  
Sort direction of a column header icon is not correct when a column is grouped by program.

 * igniteui-angular version: 6.1.4
 * browser: IE11, Chrome

### Steps to reproduce  
Run the attached sample.

### Result  
Sort direction of col3 header is descending.

### Expected result  
Sort direction of col3 header should be ascending. 

### Attachments  
[igxGridGroupingSort.zip](https://github.com/IgniteUI/igniteui-angular/files/2432608/igxGridGroupingSort.zip)

**Comment by MayaKirova** [comment]
@mkamiishi The problem is due to incompatible type being set to the grid’s groupingExpressions.
The groupingExpressions should be of type ISortingExpression[], where the dir type should be SortingDirection (or number) : 
https://github.com/IgniteUI/igniteui-angular/blob/6.1.x/projects/igniteui-angular/src/lib/data-operations/sorting-expression.interface.ts

In the sample it is set as string, which is not valid:
this.gridOption.groupingState = [
      {
        dir: "1",
        fieldName: "col3",
        ignoreCase: true
      }
    ];

Should be:

this.gridOption.groupingState = [
      {
        dir: SortingDirection.Asc,
        fieldName: "col3",
        ignoreCase: true
      }
    ];
 When set correctly there are no issues with the column header sort direction.

**Comment by mkamiishi** [comment]
@MayaKirova
This problem has been resolved.
Thank you.
