### ISSUE TITLE
Can't get samples to run locally

### ISSUE THREAD

**Issue by dbronk** [IgniteUI/igniteui-angular#27]
I've downloaded from git.  Ran npm install and grunt build.  I simply double click index.html and that page takes over 2 minutes to show anything.  I click on a sample and those pages take over 2 minutes to load and when they do the sample do not show correctly at all.  Like there is no styling at all.

What's going on?  I simply want to run the sample local to play with and when I do have the patience to wait for the pages to load locally they look like crap.  For example, here is what my Layout Manager looks like after waiting for it to load locally.

![untitled](https://cloud.githubusercontent.com/assets/7817799/5058196/dfeff89a-6cb3-11e4-8e0b-25f823c35a26.png)

**Comment by mpavlinov** [comment]
There is no need to run "npm install". What you should do is to create a virtual directory in your web server and point it to the place where you have downloaded the project.
The reason for the problem is that we're using “protocol-less” Urls to the JavaScript files which will not work for the "file" protocol, thus you need to host the project.
