### ISSUE TITLE
IE11: Cell does not go into edit mode after editing ends on blur event

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#2774]
### Description  
Cell is not editable after editing ends by cell.update() method on blur event.

 * igniteui-angular version: 6.2.0-beta.3
 * browser: IE11 (not reproduced on Chrome)

### Steps to reproduce  

1. Run the attached sample
2. Edit a cell on "startDate" column and type some characters
3. Press Alt + Tab to switch active window
4. Press Alt + Tab again to switch back the active window
5. Double click any cell on "startDate" column

### Result  
On step 5, cell does not go into edit mode.

### Expected result  
On step 5, cell goes into edit mode.

### Attachments
[igniteui-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/2494492/igniteui-app1.zip)

**Comment by ddincheva** [comment]
Hello @ymita, 
After some investigation over the described issue, we found that this problem have the same cause as in the issue #1780 . As you can see the root cause of the problem [is in IE browser](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14325016/) . So as workaround I can suggest you to define custom cell template like in the sample: 
[igniteui-app_IEissue.zip](https://github.com/IgniteUI/igniteui-angular/files/2513642/igniteui-app_IEissue.zip)

**Comment by ymita** [comment]
If div tag around interpolation is removed, the original issue is gone. But text on edited cell becomes selected like in the attached screenshot.

```
<igx-column width="160px" field="startDate" header="startDate" dataType="string" width="200px" [editable]="true">
    <ng-template igxCell let-value>
        {{ value }}
    </ng-template>
    ...
</igx-column>
```

![image](https://user-images.githubusercontent.com/14340675/47540750-8bec7100-d911-11e8-945f-2438be729fee.png)

**Comment by zdrawku** [comment]
@ymita this selection is comming from IE11 and it is not something that we should handle.

**Comment by ymita** [comment]
@zdrawku and @ddincheva 
The provided workaround does not work. Can you double check the video attached on my post the other day? https://github.com/IgniteUI/igniteui-angular/issues/2774#issuecomment-433264708
Do you have a workaround that makes igx-grid work with the steps in the attache video?

**Comment by hanastasov** [comment]
Hi Yuki,

in the corresponding [#2774 comment](https://github.com/IgniteUI/igniteui-angular/issues/2774#issuecomment-433264708) you **DO CONFIRMED** that removing the `<div>` resolved the original issue (cell not going into edit mode). I also double checked the behavior on my side with IE 11, using the sample that @ddincheva  has attached and not using the `<div>` tag. 

As @ddincheva initially explained, root cause is issue in IE 11 (same for #1780, where @Lipata [suggested the same](https://github.com/IgniteUI/igniteui-angular/issues/1780#issuecomment-407460922) - not using `<div>`.

If you are having a new/different problem now, please log a new issue about it.
