### ISSUE TITLE
Drop-down flickers in IE and EDGE

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular#2867]
### Description  
Drop-down flickers in IE and EDGE

 * igniteui-angular version: 6.2.0-beta.7
 * browser: IE, EDGE

### Steps to reproduce  

1. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/drop_down.html
2. Open any drop-down

### Result  
Drop down flickers

### Expected result  
Drop down should open smoothly

**Comment by tachojelev** [comment]
Adding the **toggle** label, since this issue is reproduced by using a simple toggle directive as well.

**Comment by tachojelev** [comment]
This issue seems to be caused by the fact that IE triggers animations a bit slower when compared to browsers like Chrome and Firefox. The element we want to show first gets attached in the overlay fully visible and then we trigger an animation for it. This operation is the one that is visibly flickering in IE.

If we attach the element in the overlay by setting its **display** to **none** and then trigger the animation and set the **display** back to **block** a bit after the animation has already started, we can notice how the issue is no longer reproduced. However this is not a suitable solution, since we need the element to be fully visible initially for the Scroll strategy and in order to work with various animations (when it comes to animation duration).

![image](https://user-images.githubusercontent.com/12784974/48692992-a21fe100-ebe0-11e8-8407-c1569520a681.png)
