### ISSUE TITLE
Vertical scroll leaves a gap on the right when shrinking grid height

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#2974]
### Description  
Describe the issue.

 * igniteui-angular version: 6.1.x/6.2.x
 * browser: *

### Steps to reproduce  

1. Open the sample
2. Resize (shrink) the browser window vertically so that the grid gets vertical scroll

### Result  
There is a vertical gap on the right of the grid (only when shrinking the grid)

### Expected result  
There should be no vertical gap.

### Attachments  
[cas30111-app1_1.zip](https://github.com/IgniteUI/igniteui-angular/files/2560950/cas30111-app1_1.zip)
![image](https://user-images.githubusercontent.com/6794133/48187350-847e8c00-e343-11e8-9757-0f867226a93c.png)

**Comment by MartinKamenov** [comment]
@mpavlinov The issue comes from setting the height when resizing using gridWrapper.nativeElement.clientHeight. This returns a rounded integer number which leads to cases when the grid container's height is for example 399.6px and after it is rounded becomes 400. Grid becomes bigger than the page so a vertical scrollbar appears(or as in your case a white space). 
I suggest using getComputedStyle(this.gridWrapper.nativeElement).height which is more accurate and returns a float number.
