### ISSUE TITLE
Filter row not respecting compact displayDensity

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#3003]
### Description  
The new quick filter row doesn't seem to respect the displayDensity property.
![image](https://user-images.githubusercontent.com/12936286/48404672-0ea66600-e731-11e8-99b8-7cb6eb342487.png)

 * igniteui-angular version: 6.2.0
 * browser: Chrome

### Result  
Filter row is too high

### Expected result  
Should have same height as the other rows

**Comment by bkulov** [comment]
@Eralmidia By design filtering row always items have hardcoded displayDensity. Chips are using `cosy` and the input group is using 'compact'.

**Comment by bkulov** [comment]
@Eralmidia If you change the default displayDensity settings there might be a misalignment in the filtering row when in edit mode. As the edit mode component covers exactly the filtering row, making the one of them smaller will cause the edit mode component to partially cover the first row. We cannot make the edit row component smaller because of the input group.
