### ISSUE TITLE
igx-grid isn't displayed properly in IE11 when it is inside an igx-tabs-group.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#3047]
### Description  
igx-grid isn't displayed properly in IE11 when it is inside an igx-tabs-group.

 * igniteui-angular version: ^6.2.0
 * browser: IE11

### Steps to reproduce  

1. npm install and npm start. Open http://localhost4200 in IE11.
2. Click ">" several times and click "Tab 3"

### Result  
The grid is not displayed properly.
See the attached screen shot. It seems that the data records are rendered in a very narrow width.

Note1:
This issue is not reproduced with Chrome.

Note2:
If you resize the browser width, the grid is displayed properly.

### Expected result  
The data records are displayed properly.

### Attachments  
![actualscreenshot](https://user-images.githubusercontent.com/33947244/48756452-987ba380-ecdc-11e8-8d24-bf16e379b724.png)
[igx-grid in igx-tabs - Copied.zip](https://github.com/IgniteUI/igniteui-angular/files/2598440/igx-grid.in.igx-tabs.-.Copied.zip)

**Comment by tkiryu** [comment]
I checked this issue on igniteui-angular@7.0.1 and later and it turned out that the following two problems are showing up.

Have you recognized these problems with igniteui-angular@7.0.x and 7.1.0? If not, could you take a look at them? Or, should I log it as another issue?

1.  `igx-grid` throws errors at `igx-tabs` initial rendering, although `igx-grid` has not been rendered yet.
![image](https://user-images.githubusercontent.com/15909409/50277779-af9ee400-0488-11e9-9c1c-190278390756.png)
In English.
> Cannot read property 'clientHeight' of undefined or null.
Cannot read property 'offsetHeight' of undefined or null.

2. `igx-grid` also throws errors when resizing window, , although `igx-grid` has not been rendered yet.
![image](https://user-images.githubusercontent.com/15909409/50278121-83379780-0489-11e9-95c9-d4b2003737f5.png)
In English.
> Cannot read property 'offsetHeight' of undefined or null.

**Comment by mpavlinov** [comment]
@tkiryu Yes. We've identified those and they should be fixed by the current PRs. However there are some other issues that we will list shortly. That's the reason Zdravko returned the issue in "in-development" state.

**Comment by ChronosSF** [comment]
- If you put width in pixels and remove the column width the following happens:

```html
<igx-grid #grid [data]="data" [primaryKey]="'id'" [width]="'700px'" >
    <igx-column *ngFor="let column of columns" [field]="column.field" [header]="column.field"></igx-column>
</igx-grid>
```
In Chrome:
![i1](https://user-images.githubusercontent.com/2188411/50284040-6a66bc00-0460-11e9-94d6-f021e20d1c29.JPG)

- If you put height in pixels, the height specified is assigned to the body and the header takes **additional** 50 pixels cutting off the bottom of the grid in a tab.

```html
<igx-grid #grid [data]="data" [primaryKey]="'id'" [height]="'300px'" >
    <igx-column *ngFor="let column of columns" [field]="column.field" [header]="column.field" [width]="column.width"></igx-column>
</igx-grid>
```

In Chrome:
![untitled](https://user-images.githubusercontent.com/2188411/50284409-9f274300-0461-11e9-8c4f-00fa48caa8c1.png)
