### ISSUE TITLE
Translate SASSDOC and TYPEDOC strings Components and Get Started in header views

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#3161]
Components and GetStarted should be translated as well:

![image](https://user-images.githubusercontent.com/11193764/48914244-7d976380-ee83-11e8-962e-2229d762d855.png)

**Comment by yoshimis** [comment]
Could you please update urls for these buttons as well?
1. "Component" should point to https://**jp**.infragistics.com/products/ignite-ui-angular instead of https://www.infragistics.com/products/ignite-ui-angular.
2. "GET STARTED" should point to https://**JP**.infragistics.com/products/ignite-ui-angular/getting-started instead 
 of https://www.infragistics.com/products/ignite-ui-angular/getting-started.
