### ISSUE TITLE
IgxGrid rendering issues on IE

### ISSUE THREAD

**Issue by rmkrmk** [IgniteUI/igniteui-angular#3317]
### Description  
A lot of IgxGrid samples are not rendered correctly on IE on the staging.

 * igniteui-angular version: 7.0.x
 * browser: IE

### Steps to reproduce  

Open staging and try the following IgxGrid samples:
"Row Editing", "Filtering", "Sorting", "Searching", "Export to Excel", "Past from Excel", "Multi Column Headers" and more.

### Result 
Some of the column headers are missing. The grid content is also missing.

### Expected result  
The samples should be rendered correctly and should be fully functional.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![igxgrid-filtering](https://user-images.githubusercontent.com/11978058/49505597-c5a38680-f884-11e8-8c21-6b0e2f71bfe4.png)
![igxgrid-rowediting](https://user-images.githubusercontent.com/11978058/49505598-c5a38680-f884-11e8-8f7d-883c7590fa30.png)
![igxgrid-toolbar](https://user-images.githubusercontent.com/11978058/49505599-c63c1d00-f884-11e8-8f7b-64b5d7d8678c.png)

**Comment by HristoP96** [comment]
The rendering issues were caused due to not enabling the [Autoprefixer](https://www.npmjs.com/package/autoprefixer) plugin to work with grid layouts.

A decision was made that this enabling will be done on customer side (if they want to use our controls in IE 11). 

This [pull request](https://github.com/IgniteUI/igniteui-docfx/pull/950) provides a documentation on how and why the customers should enable the autoprefixer for grid layout.
