### ISSUE TITLE
Cannot read property 'valid' of undefined.

### ISSUE THREAD

**Issue by grosch** [IgniteUI/igniteui-angular#3475]
### Description  
I'm getting the error in the subject when I use the igx-input-module with a custom component.

 * igniteui-angular version: 7.1.0
 * browser: Chrome

### Steps to reproduce  

https://stackblitz.com/edit/angular-9gwplk

### Result  
See the errors in the console

**Comment by tiliev** [comment]
@grosch, the issue is you are nesting `igx-input-group`. Igx input groups cannot be nested and should be used with an `igxInput` inside as a direct child. I updated your sample - https://stackblitz.com/edit/ig-ng-issue-3475?file=src%2Fapp%2Fapp.component.html by removing one of the groups. You can remove either one of them depending on your use case. Please include styles and fonts if you want to have your sample styled.
