### ISSUE TITLE
igxDialog goes behind the igxForOf scrollbar

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#3736]
### Description  
igxDialog goes behind the igxForOf scrollbar.

 * igniteui-angular version: 7.1.3
 * browser: Chrome

### Steps to reproduce  

1. Run the attached sample.
2. Click the ‘Show Dialog’button.
3. Resize the browser window so the dialog overlaps with the scrollbar.

### Result  
igxDialog goes behind the igxForOf scrollbar.

### Expected result  
igxDialog should appear in front of the igxForOf scrollbar.

### Attachments  
[igxfor-igxdialog.zip](https://github.com/IgniteUI/igniteui-angular/files/2801679/igxfor-igxdialog.zip)

**Comment by Aleksandyr** [comment]
@mkamiishi This is not a bug. Probably It is a bug into the documentation because it wasn't documented but the tricky part here is that the **vertical virtual for of directive** and the **overlay** has their own positioning and z-index, which means that they are forming two different **stacking contexts** which are hooked for the **document** and the fact that the **vertical helper** possess a **z-index** which is bigger then the overlay it overlaps it.

If you want to find more about that problem you can read [this ](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/) article which is more technical and it is described really well how those **stacking contexts** and **stacking orders** work.

I have modified the [StackBlitz sample](https://stackblitz.com/edit/angular-2vylgf-fvzgd9?file=src/app/grid/grid-row-editing-sample/grid-row-editing-sample.component.html) and everything seems to work fine now. I've added a **z-index: 0** on the parent which holds **igxFor** implementation(**table**).

**Comment by mkamiishi** [comment]
Adding z-index:0 to the parent element worked.

**Comment by zdrawku** [comment]
Let us know if you have any other questions or concerns
