### ISSUE TITLE
ScrollInertiaDirective blocks browse scrolling on mouse wheel when the grid doesn't have a scrollbar

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#3769]
### Description  
When you have a grid without a scrollbar inside a page that has a scrollbar using the mouse wheel while on the grid

 * igniteui-angular version: 6.2.x
 * browser: n/a

### Steps to reproduce  

1. Open the sample https://stackblitz.com/edit/angular-4dcgwz-a73fx8
2. Try to scroll the page with the wheel while the mouse is on the grid 

### Result  
The page will scroll but only once you rotate the wheel for a while (until internally it thinks the inertia container has reached a wrongly put threshold scrolltop point) 

### Expected result  
As the grid doesn't have a vertical scrollbar the page should immediately be scrollable with the wheel

**Comment by skrustev** [comment]
This seems to be already fixed in the master branch due to changes not related to the scroll intertia directive, but probably to the scrollbar changes.
It previously was returning scroll position different from 0 even though the scrollbar was not visible and should always return 0 which lead to this behavior described in the issue.
