### ISSUE TITLE
Lazy-loaded grid components throw an error caused by the IgxFilteringService.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#3842]
### Description  
An error stating 'Cannot read property 'isSvgIconCached' of undefined' as well as some other errors coming from the IgxIconService are thrown and the grid is not loaded. 

 * igniteui-angular version: 7.1.x, 7.2.x
 * browser: N/A

### Steps to reproduce  

1. Run the attached sample application
2. Check the console

### Result  
The grid is not loaded. A number of errors are thrown in the console.

#### Note
The issue is not observed if the component is eagerly loaded. 
The issue will go away if the IgxIconService is provided in the component's providers (for instance).

### Expected result  
The grid should be loaded successfully both in eager and lazy scenario.

### Attachments  
[infragistic-tree-grid-integration.zip](https://github.com/IgniteUI/igniteui-angular/files/2836757/infragistic-tree-grid-integration.zip)

**Comment by bkulov** [comment]
`IgxIconService` is provided in the root of the client's application while the `IgxFilteringService` is provided per grid component. This means that there will be one instance of the `IgxFilteringService` for each grids' instance, but only once instance of the `IgxIconService` shared in all grids' instances.
The problem in this sample is that the `IgxFilteringService` cannot find instance of `IgxIconService` in the lazy loaded injector or in the parent (app level) injector. The reason is that `IgxIconModule` is not imported anywhere in the application and that's why there is no instance of `IgxIconService` created at bootstrap or during lazy loading module.
So this is not a bug but a problem in the sample.
