### ISSUE TITLE
igx-grid: Incorrect height calculation when setting height in percent and binding empty data.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#3950]
## Description  
There is a problem with height calculation when setting height in percent and binding empty data.

 * igniteui-angular version: 7.1.7
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample.

## Result  
Although I set `igx-grid` height to `100%`, `igx-grid` doesn't fit to its parent.

## Expected result  
`igx-grid` should fit to its parent.

## Attachments  
[my-app.zip](https://github.com/IgniteUI/igniteui-angular/files/2878857/my-app.zip)

**Comment by mpavlinov** [comment]
This is related to issue #3949. The cause is the same. The grid miscalculates its height so it set it to `null`, which means no virtualization. The faulty code is in [`_derivePossibleHeight`](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-base.component.ts#L3530) method.

**Comment by LabDeve** [comment]
anyone coming here can use this code as a workaround to get 100% of the height
 `[height]="grid.nativeElement.parentElement.offsetHeight+'px'"`

**Comment by tkiryu** [comment]
Hi, let me confirm. This fix hasn't been merged to 7.2.x yet. Is there any problem?

**Comment by kdinev** [comment]
@mpavlinov Will the fix make it in `7.2.x` and `master` soon?

**Comment by mpavlinov** [comment]
@kdinev Yes.
