### ISSUE TITLE
Define different styling for hours/minutes outside min and max values

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#3978]
## Is your feature request related to a problem? Please describe.
When there is a minValue and maxValue defined in the igx-time-picker, there is no indication and it is not possible to close the dialog, when trying to set a date that is outside the defined minimum or maximum.

## Describe the solution you'd like
The igx-time-picker should have some disabled styling for the hours/minutes that are outside the minValue/maxValue.

**Comment by StefanIvanov** [comment]
We initially thought to react to such conditions with a validation error, but @Lipata makes a good and strong point that for the case of the time picker I 100% agree with. If min or max or both are set all values that don't below to the selectable range should be disabled.

**Comment by StefanIvanov** [comment]
Let's use the same color that is used for the date picker to disable certain dates (date-disabled-text-color)

**Comment by Lipata** [comment]
With the pull request above, @simeonoff is adding the disabled style. What needs to be done is that the component use that style for the disabled time period. In addition, when scrolling and reaching a max or min value, the disabled hours/minutes/AM or PM should be skipped, and active time period should become the opposite - min or max value.

**Comment by Lipata** [comment]
There is a new issue #7173 that will be related to the mechanism of scrolling to the valid hours/minutes. With this, we will just apply the already-created class.

**Comment by valadzhov** [comment]
@StefanIvanov a [draft PR](https://github.com/IgniteUI/igniteui-angular/pull/7347) has been created for this issue which turned out to be regarded as a feature. The initial approach was to just apply the disabled style to the <span> but this way the style wouldn't be applied dynamically to the hour, minute, second and AM/PM items when they were being changed by the user while still in the drop-down. Instead new logic was implemented to determine whether the value which was still in the drop-down was in the range of the min/maxValue. What was achieved with this is that if the minValue is 9:40 AM and maxValue is 11:20 AM when the user selects 10 as the hour all the items for the minutes would be available for selection but if the user selects 9 or 11 as the hour only the items for minutes which fall under the range of the minValue and maxValue would be available, the rest would be has the new disabled style.
Can you review this behaviour and give your comments, please.

**Comment by StefanIvanov** [comment]
I will review the behavior on the PR and provide feedback later today

**Comment by StefanIvanov** [comment]
I am happy with the solution provided, feel free to assign me as a reviewer of the PR and I will approve it.
