### ISSUE TITLE
Hovering over grid rows shows and hides horizontal grid lines.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#3982]
## Description  
On hovering with the mouse from bottom to top, the horizontal row separators disappear, then on hovering in the opposite direction, the lines appear again.

 * igniteui-angular version: 7.2.x, 7.1.x
 * browser: Edge

## Steps to reproduce  

1. Run DEV Demos in Edge
2. Navigate to Grid demo
3. Hover over the data rows up and down
4. Note the horizontal lines

## Result  
On hovering up the lines disappear, then re-appear when hovering down.

## Expected result  
The horizontal lines should not disappear.

## Attachments  
![image](https://user-images.githubusercontent.com/16817847/53231474-ae10b880-3691-11e9-8b83-6a01309bbc17.png)

**Comment by simeonoff** [comment]
@gedinakova I have tried fixing this before with no success. Will try again.

**Comment by desig9stein** [comment]
There is an open bug ticket for EDGE. The issue was first reported back on Apr 5, 2016, and the last update on it is made on Mar 26, 2018. The good news is that there solution to the problem, the bad news is that the solution is hacky and may cause other problems. Because of that, we need to discuss it before I take action to apply it.

@simeonoff @kdinev @ChronosSF The following change needs to be made to fix the issue.
We need to add one extra pixel to the border-bottom of the row and then subtract 1pix from the row position to compensate that one extra pixel on the border.

I need to change this
```
.igx-grid__tr { 
    border-bottom: 1px solid --var($theme, 'row-border-color');
}
```
to this
```
.igx-grid__tr {
    border-bottom: 2px solid --var($theme, 'row-border-color');
    margin-bottom: -1px;
}
```
In your opinion what could I break if I made that change?

Here is a link to the issue in EDGE: [developer.microsoft.com](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7119159/)

ISSUE EXAMPLE
Left is Edge, followed by Firefox and finally Chrome.

![rykwlsk](https://user-images.githubusercontent.com/21260963/53330228-aa31a000-38f6-11e9-8182-e9afe6cc3741.gif)

**Comment by simeonoff** [comment]
@desig9stein I am ok with this approach if it doesn't break anything else, like the virtualization.
@ChronosSF do you think this change might affect the virtualization in any way?

**Comment by desig9stein** [comment]
I've tested all grid samples, and couldn't find any issue, but it still needs to be checked from @ChronosSF or somebody else for the dev teams. If they don't find any critical problem, we can merge the PR

**Comment by ChronosSF** [comment]
I'll take a look asap. Sorry for the late response.

**Comment by simeonoff** [comment]
@Cjr

> I'll take a look asap. Sorry for the late response.

Can you take look?

**Comment by desig9stein** [comment]
@gedinakova Can you close the issue?
