### ISSUE TITLE
IgxHierarchical grid throws an error on an attempt to pin a column from a child grid

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#3998]
## Description  
When you try to pin a column on a child grid, it throws a `Cannot read property 'unpinnedColumns' of undefined at IgxColumnComponent.get` error and does not pin the selected column.

 * igniteui-angular version: 7.2.x
 * browser(s): all

## Steps to reproduce  

1. Run the attached sample.
2. Click on the `Artist` column's pin button.
3. Observe.
4. Expand the grid's first row.
5. Click on the `Albums` column's pin button.
6. Observe.

## Result  
Nothing happens.

## Expected result  
The `Albums` column should be pinned. The behaviour should be the same as with the `Artist` column.

## Attachments  

[HGColumnPinning.zip](https://github.com/IgniteUI/igniteui-angular/files/2900051/HGColumnPinning.zip)
![capture](https://user-images.githubusercontent.com/16020256/53330951-70fa2f80-38f8-11e9-8a3e-3a66c55875f4.PNG)

**Comment by skrustev** [comment]
The method of getting column reference in the sample will not work because the direct reference to the column from inside the sample template points to the `row-island` column which has no grid rendered for it.

I've pull requested a way how this could be achieved by getting the column from the context of the custom column template that would be specific for each child grid.

Example of how this should be used in this current sample for `Album` column:

```html
<igx-column field="Album" [editable]="true" [dataType]="'string'">
    <ng-template igxHeader let-columRef="column">
        <div class="title-inner">
            <span style="float:left">Albums</span>
            <igx-icon class="pin-icon" fontSet="fas" name="fa-thumbtack" (click)="toggleColumn(columRef)"></igx-icon>
          </div>
     </ng-template>
</igx-column>
```
