### ISSUE TITLE
Cannot set option at runtime using Angular expression binding "{{}}"

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#40]
It will be good if options can be set using the Angular expression binding "{{}}" like this:
```html
  <feature name="Updating">
                <column-settings>
                    <column-setting column-key="Id">
                        <editor-options read-only="{{IsReadOnly}}"></editor-options>
                    </column-setting>
                </column-settings>

</feature>
```

**Comment by kdinev** [comment]
Anything below the top level directive produces JSON configuration for the control, rather than markup. In this sense expression binding should be supported to any top-level directive that can be modified through a standard jQuery UI setOption call, like the igGrid width:

    <ig-grid width="{{modelWidth}}">
    </ig-grid>

This is not applicable to more complex object configurations like `features`, `columns`, etc.
