### ISSUE TITLE
IgxGrid cell edit does not update values (onCellEdit)

### ISSUE THREAD

**Issue by jdk339** [IgniteUI/igniteui-angular#4055]
## Description  
When editing a cell value in single-cell edit mode, after pressing `<Enter>`, the property of the updated row is not updated before `onCellEdit` is called. The property does get updated, but not in time for `onCellEdit` to recognize the change.

 * igniteui-angular version: 7.1.7
 * browser: Chrome 72.0.3626.109

## Steps to reproduce  

1. Edit a cell in single-cell edit mode
2. Press enter
3. Call `(onCellEdit)="updateGuest($event)"`
4. Run the following code: 
```
  updateGuest(e: IGridEditEventArgs) {
    console.log(e);
    const guest = e.rowID;
    console.log(guest);
    this.submitUpdate(guest);
  }
```

## Result  
`onCellEdit` gets called before the property values are updated on the object

## Expected result  
`onCellEdit` should only be called after the values are actually updated on the object

## Attachments  
The issue can also be seen in this screenshot which weirdly shows the value "changing" after it is expanded in the browser console vs when it was initially logged to the console (group is the pertinent property):

![image](https://user-images.githubusercontent.com/16578448/53424050-75821f00-39b0-11e9-9e92-446985c54b6c.png)

**Comment by zdrawku** [comment]
Hey @jdk339, the behavior that you've described is by design. [onCellEdit ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#oncelledit)emitter is used when editing has been performed and the data source is not yet updated with it. This event allows you to do any type of custom operations, like value validation, before sending the updated object to the server for example. This event is cancelable.
We do not provide event that you can handle in order to access the actually updated object, this is something that the Grid is not responsible of.
Could you please let me know what you are trying to achieve?

**Comment by jdk339** [comment]
@zdrawku I was hoping it would behave as `onEditDone` behaved before that was deprecated. I believe it was `"igniteui-angular": "^7.1.1"` or prior when it worked for me. You were able to use `(onEditDone)="updateUser($event)` in the table, and then use:

```
updateUser(e) {
  const cell = e.cell as IgxGridCellComponent;
  const user = cell.row.rowData;
  // other code
}
```

Not a huge problem, I just switched all my tables to use the row-editing feature instead, but I just thought it was odd behavior. Because the cell value _does_ change on the object, it just doesn't do it until _after_ the method is called.

**Comment by zdrawku** [comment]
Let me check that out prior to addressing your last comment.

**Comment by zdrawku** [comment]
@jdk339, I see that you want to be able to get the row data object with the updated value? I can assure you that particularly for the `cell editing` this functionality was always as it is not, even with the old `onEditDone` event (see the image below). Version 6.1.9 is used.

![image](https://user-images.githubusercontent.com/11193764/53641062-83e16c80-3c36-11e9-9eb4-b735c9448cb2.png)

The change from `onEditDone` to `onCellEdit` happened in version 6.2.0 - [Changelog](https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#620). 

The important here is that in order to get the updated Row object you should use `onRowEdit` event, which will give you both `current` and `updated row objects`, as you said:

![image](https://user-images.githubusercontent.com/11193764/53641419-86909180-3c37-11e9-88ec-4bc13ee3c782.png)

**Comment by jdk339** [comment]
@zdrawku That's weird that it was behaving differently for me in that it was returning the updated value for me. Perhaps I had an even older version of igx.

It's no problem for us to use the row-editing feature. Thanks for your investigation of this issue. I believe the issue could be closed now since this is the desired behavior for that method.

**Comment by zdrawku** [comment]
Great, you can reopen the issue or leave a comment if something comes up.
