### ISSUE TITLE
Filters with implied values should not open the custom filter dialog.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#4066]
## Description  
Filters like empty, not empty, today, this month, etc. should not open the dialog but directly apply the filter.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run Column Moving Dev demo
2. Open filtering drop down on ID column
3. Open text filters sub menu
4. Select "Not Empty"

## Result  
The custom filter dialog is opened with "Add filter value" disabled. One should press "Apply" to filter.

## Expected result  
Filters that do not need a value should be applied immediately.

## Attachments  
![image](https://user-images.githubusercontent.com/16817847/53478370-4b4b6280-3a7f-11e9-9e4f-a93a135b4b78.png)

**Comment by bkulov** [comment]
This functionality is correct. When you select an unary condition (a condition which doesn't have value) the value input should be disabled. It's working the same way in the quick filtering.
The dialog shouldn't be closed automatically when the user selects an unary condition because those conditions are not mutually exclusive and could be combined. For example someone may want to define filter `last year or next year`. Also `not empty and not null` is valid user scenario.
If we close the dialog when the user selects an unary condition he/she won't be able to define more complex filters.
