### ISSUE TITLE
Cannot navigate with Shift+Tab keys from root cell to child cell

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4086]
## Description  
Describe the issue.

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Open dev sample hierarchicalGridUpdating
2. Expand first row
3. Click on second root row cell in column CustemerID
4. Press Shift+Tab keys

## Result  
There is an error in the console and the selected cell is not be chaged

## Expected result  
Last cell in the child grid should be selected without error

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/53497949-fb37c480-3aad-11e9-8d10-7be8aabe7ff9.png)

**Comment by skrustev** [comment]
There are a few similar scenarios that have the same effect that will be fixed in this issue:

-  Navigating from last cell of parent using ArrowUp/ArrowDown to child grid that has less columns
-  Navigating from last cell of child grid using ArrowUp/ArrowDown to another sibling that has less columns.
