### ISSUE TITLE
DatePicker from a RowIsland Grid opens beneath a sibling RowIsland Grid

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#4169]
## Description  
DatePicker from a RowIsland Grid opens beneath a sibling RowIsland Grid.

 * igniteui-angular version: 7.2.x
 * browser: any

## Steps to reproduce  

1. Open the staging topic for "**Hierarchical Grid Row Editing**".
2. Expand the top root row.
3. Double click the "Launch Date" of the last album for the expanded row.
4. Click the calendar icon in the cell to open the date picker.

## Result  
The date picker opens beneath the sibling RowIsland Grid (the Tours grid).

## Expected result  
The date picker opens above the sibling RowIsland Grid (the Tours grid).

## Attachments  

![hiergrid](https://user-images.githubusercontent.com/12784974/53807059-45f68800-3f57-11e9-9f4c-0801d08e05e0.gif)

**Comment by mpavlinov** [comment]
@tachojelev I cannot reproduce this behavior (I checked Chrome, Edge, IE11 and FF). I suspect that this is before the RC deployment. Can you check it once again on your side.

**Note:** The only problem I see is that the date-picker is partially visible due to the IFrame that the sample is hosted in.

**Comment by tachojelev** [comment]
@mpavlinov I checked the issue and it seems to be no longer reproduced. It was possibly fixed after the RC deployment)
