### ISSUE TITLE
[igx-date-picker] unnecessary suffix "日" to the date part of the calendar.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4224]
## Description  
I'm trying to localize igx-date-picker to Japanese locale. I found that the formatting of date part is not what Japanese people expect. Until v7.1.9, there is no problem.

 * igniteui-angular version: 7.2.0-rc.3
 * browser: N/A

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-date-picker-template-issue
2. Show the dialog mode datepicker.
3. Show the dropdown mode datepicker.

## Result  
"日" is suffixed to each date number.
![image](https://user-images.githubusercontent.com/15909409/54013956-578d9900-41be-11e9-82e0-e92d4a34ae6b.png)

## Expected result  
"日" should be removed. `igx-date-picker` should format date parts as before.
![image](https://user-images.githubusercontent.com/15909409/54013975-6b38ff80-41be-11e9-9931-a6e7cb3724c4.png)

## Attachments  
https://stackblitz.com/edit/igx-date-picker-template-issue

**Comment by sboykova** [comment]
Hello Tatsushi,
igx-calendar uses Intl.DateTimeFormat for formatting dates according to the set locale. I’ve tested the day formatting for ja locale and 日 appears always.
If you test this:
const formatter = new Intl.DateTimeFormat("ja", { day: 'numeric' });
const day = formatter.format(new Date(2019,2,10));
the returned formatted date is 10日.

https://stackblitz.com/edit/igx-date-picker-template-issue-djqt2h?file=src%2Fapp%2Fapp.component.html

**Comment by SAndreeva** [comment]
@tkiryu, your problem is partially fixed by #4195.
Currently there are two properties that take care of formatting the views: [formatViews](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdatepickercomponent.html#formatviews) and [FormatOptions](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdatepickercomponent.html#formatoptions). As far as you use the default `formatViews` settings, where the days are not affected, you will have the desired display, as in the use case from your sample. Otherwise, as @sboykova has explained, ` Intl.DateTimeFormat ` will append the 日 and unfortunately we cannot do much about it.

**Comment by tkiryu** [comment]
@SAndreeva , @sboykova , is it possible not to use Intl.DateTimeFormat for formatting dates?

Why I'm thinking of that is because previous versions are able to achieve what Japanese people expect. Therefore, my feeling is that this issue is a kind of regression bug. 

Please see `igx-date-picker` using igniteui-angular@7.1.9. The result of this sample is what Japanese people expect.
https://stackblitz.com/edit/igx-date-picker-v7-1-9

By the way, there is no problem with localization of `igDatePicker`. 
https://jp.igniteui.com/editors/date-picker-new
