### ISSUE TITLE
Igx-grid: How do i focus on the newly added row using grid.addRow()

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#4234]
### Description  
From article: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/batch_editing.html

After adding a row to aIgx-grid, i would like to automatically focus on the first columb in the newly added grid row. 

 * igniteui-angular version: 
 "igniteui-angular": "7.1.9",
 "igniteui-angular-wrappers": "6.0.0",

### Result  
Row is added, row is not focused, grid is not scrolled to newly added row

### Expected result  
Row is added, focus is set to the first columb in the new row, and view/scroll changes to visualize the newly added row

**Comment by ViktorSlavov** [comment]
@VirtualisProject 
I've created a [StackBlitz example](https://stackblitz.com/edit/focus-add-row-igxgrid?file=src/app/grid/grid-batch-editing/grid-batch-editing-sample.component.ts) that should cover your scenario - please have a look and let me know if works for your case.
In the example, I'm making use of the grid's `onAddition` emitter to scroll to the row once it's added.
Since the event only emits the data of the added row, we are not sure if the row will be into view or not (since the grid is virtualized). Hence, we need to apply custom logic to move the row into view (by scrolling the grid, changing the page or both).

Please note that there is an [open issue and discussion](https://github.com/IgniteUI/igniteui-angular/issues/4054) going on about enhancing the grid's navigation API. In the future, it would likely be easier to scroll to a row/column that is out of view.
