### ISSUE TITLE
Highlight specific day on calendar

### ISSUE THREAD

**Issue by TachyonRSA** [IgniteUI/igniteui-angular#4339]
## Question  
I am currently implementing a calendar into one of my websites and I would like to highlight the days that events are taking place with the same highlight that is applied to the current day. Is there anyway to do something like this?

 * igniteui-angular version: latest
 * browser: Chrome

**Comment by zdrawku** [comment]
Het @TachyonRSA, you can [define a calendar theme](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/component-themes.html) and use `$date-special-background` and `$date-special-text-color` assuming you are using special dates for your events.

This is a [StackBlitz sample](https://stackblitz.com/edit/angular-calendar-style) for the above suggestion.
Have a look at [all other parameters](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/#function-igx-calendar-theme) that you can use in order to define your theme.

```
$my-calendar-theme: igx-calendar-theme(
  $date-special-background: purple,
  $date-special-text-color: yellow
);

// Pass the theme to the igx-calendar component mixin
@include igx-calendar($my-calendar-theme);
```

**Comment by TachyonRSA** [comment]
Worked like a charm thanks @zdrawku !
