### ISSUE TITLE
igx-drop-down allowItemsFocus not working

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#4395]
## Description  
Describe the issue.

 * igniteui-angular version: 7.2.2
 * browser: Chrome latest

## Steps to reproduce  

1. Create a dropdown with [allowItemsFocus]="false"

## Result  
Items are still selected when clicked

## Expected result  
Should work like a menu, where items are not selected

![image](https://user-images.githubusercontent.com/12936286/54911092-f966f280-4eed-11e9-9771-66d314c51af0.png)

![image](https://user-images.githubusercontent.com/12936286/54911080-f2d87b00-4eed-11e9-96c1-fea37c4de018.png)

**Comment by Lipata** [comment]
Hi, @Eralmidia.

Property [allowItemFocus](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdropdowncomponent.html#allowitemsfocus) is not related to the focused style. As written in the documentation this option specifies if the list items will get real focus (by default they will not). The focus and selected styles are applied in any case - with or without the allowItemFocus option. Do you want to remove the focused and selected style - like [this](https://stackblitz.com/edit/angular-vptwap)? 

If you want to remove the entire navigation through items then you can remove the igxDropDownItemNavigation directive?

**Comment by Eralmidia** [comment]
Hi @Lipata 

Thanks for your reply.

The issue is that the the focused style still is applied to the element. Lets say I have a white background in the dropdown, and a red hover color. 

By default, the igx component will apply a purple color when the item is focused. To combat this, I will set white as focus bg color in the theme. But the focus class now overrides the hover color, meaning that when I hover over an item I previously clicked, the red hover color does not show.

Take a look at the follwing screenshots: This is an item which I have not previously clicked, and works as expected:
![image](https://user-images.githubusercontent.com/12936286/54926211-20362080-4f10-11e9-8405-95bc373278ea.png)

Now, the last item, I have previously clicks, and thus have focus, and the hover color does not show:
![image](https://user-images.githubusercontent.com/12936286/54926300-52478280-4f10-11e9-8dc6-e63eb50aa5a4.png)

**Comment by Lipata** [comment]
@Eralmidia, I've updated the [demo](https://stackblitz.com/edit/angular-vptwap?file=src/app/dropdown-sample-4/dropdown-sample-4.component.scss) CSS and what was needed to be set was selected and selected:hover styles. This is necessary because the drop down always save selection and there isn't option to turn this off.

>Note: I've used colors related to the theme used in the demo.

**Comment by Eralmidia** [comment]
So I will have to manually override .igx-drop-down__item--selected:hover for each component to achieve this then? You can't do it in the theme? The reason this works in the demo, and not in my app is that you have the component css overriding the theme right?
![image](https://user-images.githubusercontent.com/12936286/54928692-9ccafe00-4f14-11e9-89fe-7622dd4485c5.png)

**Comment by Lipata** [comment]
@Eralmidia.

In order to add different CSS rules to the theme, we should have a drop down option (e.g. saveSelection=false) in order to apply the different style in that case, because by default selection is saved and a corresponding style is needed. Currently, we don't have such an option in the drop down and what we propose is to cancel the `onSelection` event in order to achieve this.

I found an old [issue](https://github.com/IgniteUI/igniteui-angular/issues/2031) (request by you) with the same problem. Here is the [updated demo](https://stackblitz.com/edit/angular-vptwap), where I cancel the selection and manually update value.

As far as about overwriting the component classes - in our demo, the CSS is defined inside a component and angular automatically add the _ngconent-c1 class and suffix all classes defined in that control. If you have the overwrites in the general app then they are not going to overwrite the theme rules.

**Comment by Eralmidia** [comment]
I didn't remember I had already brought this up once before. Sorry about that. I'll try not to start a third issue then ;)

I do hope that there will be an easy input to control this yes. As @kdinev states in https://github.com/IgniteUI/igniteui-angular/issues/4338#issuecomment-473819553, the drop down is a "menu like" component, where "most common use-case is navigation". It would be nice if it could then easily replace the functionality found in the mat-menu component (https://material.angular.io/components/menu/overview), which really is the behaviour I'm after most of the time.

Again, thanks for the support @Lipata

**Comment by Lipata** [comment]
@Eralmidia, you are welcome!

Your scenario (the one that mat-menu is also proposing) can be achieved with some slight igx-drop- down modifications - canceling the event, applying the selected value and closing the drop down (like in  [demo](https://stackblitz.com/edit/angular-vptwap)). Introducing an option in the igx-drop-down will simplify that case for sure but will introduce additional logic in the component. The demo shows a straightforward solution and even can be wrapped in component on an application level and reused. If you insist on an option, we can rethink the possibility of introducing it.

Talking about a separate menu component - this is a different topic. A menu, for example, can have a hierarchy of menus, which is more than just a drop down without a selection.

Thank you, @Eralmidia.

**Comment by Eralmidia** [comment]
@Lipata Yes, I've implemented the cancellation of selection, and it works fine 😃 

A separate menu component is an interesting discussion as well. As you say, someone will surely raise the need for a nested menu structure before long. Personally I would probably prefer a new component to modifications to the drop down. Anyway, the issue is solved. Keep up the good work 🏅
