### ISSUE TITLE
Use igx-tree-grid instead of igx-grid

### ISSUE THREAD

**Issue by ammritt** [IgniteUI/igniteui-angular#4411]
## Question  
With new igx-tree-grid which is separate module and component I realized if I just set the childDataKey to a value that doesn't existing in data object then the grid with render as non-tree structure like a igx-grid. Working example here https://angular-wandvj.stackblitz.io
Code: https://stackblitz.com/edit/angular-wandvj

My questions is that as IgxTreeGridComponent extends IgxGridBaseComponent, can I just use the tree grid and set my childDataKey to get the desired tree-grid or regular grid. Is this going be OK moving forward? Any functionality that I will miss in current of future releases?

**Comment by DiyanDimitrov** [comment]
@ammritt, The only difference in the functionality between the igx-grid and the igx-tree-grid is that the igx-tree-grid does not support grouping. Technically you could use the IgxTreeGridComponent for non-tree structures, but using the IgxGridComponent would have a bit better performance since the IgxTreeGridComponent has some additional logic for handling the tree structure.

**Comment by SlavUI** [comment]
@ammritt  I'm closing this as answered re open if you have more questions :)

**Comment by ammritt** [comment]
@DiyanDimitrov  I tried your way, this works as we are basically using an edit input as bodyTemplate for the cell.
Unfortunately this is not what I need, this solution will need me to write the cell editor markup for all the column definitions each time I define a grid. HTML5 input markup also look bit off when used.

All I want for my users is to be able to start editing without double-clicking on any cell. I think a simple method to set the edit mode of the grid can be useful. What you guys think?
