### ISSUE TITLE
Filtering conditions drop down does not behave consistently when the button that opens it is clicked multiple times

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#4470]
## Description  
When the button that opens the drop down with filtering conditions is clicked multiple times it does not behave consistently. The first two times when it is clicked the drop down with the conditions closes and opens again, the third time when it is clicked the drop down just closes.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Open Grid Column Groups sample.
2. Click "Filter" for any of the columns.
3. Click the button that opens the drop down with filtering conditions.
4. Click it one more time.
5. And one more time.

## Result  
After steps 3 and 4 the conditions drop down is closed and opened again. After step 5 it is not opened.
If you continue clicking on the button the same repetitive misbehavior can be observed -twice the drop down is opened and once it is not.

![grid](https://user-images.githubusercontent.com/13034836/55625194-bc81e200-57b0-11e9-9e71-5973bdf748dc.gif)

## Expected result  
Filtering conditions drop down to be opened after every click of the button

**Comment by tkiryu** [comment]
On IE11, it still occur on `igniteui-angular@7.2.9`.

I found that if `event.target` is svg element, `elem.contains()` method returns wrong value on IE11.

I'm attaching a small sample. 
[svg-click-sample.zip](https://github.com/IgniteUI/igniteui-angular/files/3206230/svg-click-sample.zip)
1. Run the sample on IE11.
2. Open console.
3. Click on the svg.

If you click outside the svg stroke, `contains()` returns true. BUT, if you click over the svg stroke, it returns false, which causes this issue.

![IE11-contains-method-issue](https://user-images.githubusercontent.com/15909409/58158597-b474f780-7cb5-11e9-884f-eba9d53c7377.gif)


Therefore, the following logic doesn't work as expected on IE11. That's why filtering conditions drop down doesn't toggle correctly.

https://github.com/IgniteUI/igniteui-angular/blob/711244b/projects/igniteui-angular/src/lib/services/overlay/overlay.ts#L627-L628

```
                    // On IE11, contains() returns false when you click over the svg stroke.
                    const clickOnPositionTarget = positionTarget && positionTarget.contains
                        ? (positionTarget as any).contains(ev.target)
```

**Comment by tkiryu** [comment]
Here is a quick fix.
```
:host::ng-deep {
  .filtering-icons.igx-icon {
    pointer-events: none;
  }
}
```
If you style like the above, event.target won't be svg element, you can avoid this issue.
