### ISSUE TITLE
More features in date picker

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#4647]
## Is your feature request related to a problem? Please describe.
We are currently trying to implement the date/time pickers, and due to how older components work, we are forced to use the dropdown mode to keep the user experience the same. However, there are a couple of features we need in order to use this.

## Describe the solution you'd like
1. When in drop down mode, it seems like the cancel and today buttons are not shown (not sure if this is a bug?). We can't really use this component without it (well, the cancel button isn't important, but the today button is). Also, if possible, it would be great to have the ability to choose whether clicking the today button should actually select today and close the dropdown, or simply move the date picker view to today.
2. It would be nice to have an option to add custom buttons to the bottom of the datepicker, with ng-content or similar, in order to enable custom logic. For instance, say we want a "quick selection" button for the day exactly 1 month ago.

Of cource, if 2 were implemented, then 1 isn't really an issue, as long as there are methods to select today.

**Comment by StefanIvanov** [comment]
Hi @Eralmidia as we were using a dialog to display the picker before, the buttons came from it and we saw it as sort of a modal experience that required confirming/canceling and other actions but once we moved away from that we thought the buttons may not be necessary anymore but you have a very good point about the today/now button. And our approach for that will be template-able of course as it is for the dialog. Since drop downs close upon selection by default we will keep that behavior as default but will provide a mechanism to cancel the closing event of the overlay that contains the picker.

**Comment by Eralmidia** [comment]
Hi @StefanIvanov Templateable buttons and the ability to cancel close sounds great. 

We have tried half a dozen pickers over the years. Seems like we finally will get one which has all the features we need 👍

**Comment by StefanIvanov** [comment]
I have updated the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/igx-datePicker-Specification) to be inclusive of the requests mentioned above. I have also made consistent updates to the [time picker spec](https://github.com/IgniteUI/igniteui-angular/wiki/Time-Picker).

**Comment by Eralmidia** [comment]
@SAndreeva Hi Stefana. Do you have an ETA for the release of this one? 😃

**Comment by SAndreeva** [comment]
Hi, I suppose it will make it in 7.3.4

**Comment by Eralmidia** [comment]
Thanks
