### ISSUE TITLE
Is it possible to two-way bind Igx-time-picker? (input => dialog)

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#4657]
## Question  
I was wondering if it would be possible manually write a time (of the same format) in the input field of a igx-time-picker (templated with the igxTimePickerTemplate directive) and have it update the time-picker dialog values. Basically a two-way binding for the value input in the input field. 

1. User selects time from igx-time-picker dialog => input displays selected value
2. User inputs a time in the input field (20:00), then opens dialog => dialog is set to 20:00

I've made a Stackblitz example containing the code i'm currently running, see link below
https://stackblitz.com/edit/angular-e2xxxe

Thaks alot, 

 * igniteui-angular version: 7.2.6
 * browser: All

**Comment by bkulov** [comment]
Hi @VirtualisProject,
igxTimePicker exposes two values in the template context: `value` and `displayTime`. The first one is a `Date` object and is the real value of the igxTimePicker. The value contains date and time portions of the `Date` object but the igxTimePicker only uses the time portion. `displayTime` is of type string and represents the formatted value according the igxTimePicker `format` input. This is what the user sees in the input. `displayTime` is read-only so you can't use it with two-way binding.
What you can do in order to implement two-way binding in the template is to subscribe to some of the input's events and update the `value`. I slightly modified your sample to demonstrate that. If you change the time and press `enter` key the new value will be applied and if you open the igxTimePicker dialog it will be updated.
https://stackblitz.com/edit/angular-e2xxxe-ys2o1s

Let me know if you have any other questions.

**Comment by VirtualisProject** [comment]
Hi @bkulov, 

Thanks alot for taking the time to answer my question so rapidly. I think your example will work perfectly in my case, thanks alot.
