### ISSUE TITLE
Range error is thrown when you try to open MRL dev sample

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#4678]
## Description  

 * igniteui-angular version: 7.3.x
 * browser: all

## Steps to reproduce  

1. Open the MRL dev sample
2. Observe the console

## Result  
What is the actual result after following the steps to reproduce?
![Screenshot_24](https://user-images.githubusercontent.com/34240583/57131961-baf30c00-6da6-11e9-96fa-b4eb95ca353e.png)

## Expected result  
What is the expected result after following the steps to reproduce?
No errors should be thrown and the column should be pinned

**Comment by skrustev** [comment]
Currently in general the pinning with column widths set to percentages is not supported by the igxGrid, that is why I've changed the sample to have column widths in pixels.

**Comment by zdrawku** [comment]
This issue aims to point out the returned error with that specific scenario (widths in percentages and enabled pinning feature). Either we should document this limitation as well, or at least handle the error because the scenario is not so uncommon.

The current limitation [states](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column_pinning.html#pinning-limitations): 

> Setting column widths in percentage (%) explicitly makes the Grid body and header content to be misaligned when there are pinned columns.

In this case, I can accept a misalignment, but not the "Maximum call stack size exceeded" error. Let me know if I am missing something here?

**Comment by zdrawku** [comment]
Set the issue back in development, as we discussed with @skrustev we need to fix this issue.
Also, it looks like the Limitation is invalid, and actually the Grid set with percentages and using Column Pinning, is working just fine. Svetlio, you may consider this as well, and validate this behavior.

**Comment by skrustev** [comment]
I've created a PR that should fix mainly the issue present in the Multi Row Layout that throws an error. 

With @rkaraivanov we noticed that while pinning works in the igxGrid without MRL, it does not work correctly when there are pinned columns and the unpinned area has horizontal scrollbar. I can look into that as a separate issue since it is not related to Multi Row Layout.

Because the sample has changed, in order to reproduce this issue the configuration would need to have a pinned block and width of at least 1 columns set to percentages.
