### ISSUE TITLE
Values changed in `ng-template` in IgxGridComponent do not get updated nor trigger `newValue` to be updated

### ISSUE THREAD

**Issue by jdk339** [IgniteUI/igniteui-angular#4688]
## Description 

Values changed in custom `ng-template`s **will not** trigger a changed row value.

[In the StackBlitz sample for the documentation's "Grid Row Editing" page](https://stackblitz.com/angular/gagpbalpqoe), here is the result after changing a row's `UnitsInStock` value:

`{rowID: 1, oldValue: {…}, newValue: null, cancel: false…}`

The expected result would be:

`{rowID: 1, oldValue: {…}, newValue: {...}, cancel: false…}`

This is an extremely important feature for our company, so please fix quickly.

 * igniteui-angular version: 7.2.7
 * browser: Latest Chrome

**Comment by wnvko** [comment]
This is an issue in the smple. I logged this sample issue [here](https://github.com/IgniteUI/igniteui-angular-samples/issues/1137). To fix this at your side bind `ngModel` to `cell.editValue` instead of to `cell.value`.

[Here](https://stackblitz.com/edit/angular-ptep1a?file=src%2Fapp%2Fgrid%2Fgrid-row-editing-sample%2Fgrid-row-editing-sample.component.html) is updated StackBlitz where I have fixed this issue.

**Comment by jdk339** [comment]
Great! That works perfectly. Thanks @wnvko
