### ISSUE TITLE
Only allow a single selection inside IgxComboComponent

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#4799]
## Question  
How do I only allow the user to make a single selection inside the IgxComboComponent?

I understand that typically the IgxComboComponent is used to allow a user to make multiple selections.  I only want the user to be able to make a single selection inside the IgxComboComponent.  I recognize that there are other components IgxDropDownComponent and IgxSelectComponent that will allow a user to make a single selection.  I would prefer to use the IgxComboComponent instead of the IgxDropDownComponent or the IgxSelectComponent because I like the checkbox feature of IgxComboComponent.

 * igniteui-angular version: 7.2.4
 * browser: Google Chrome Version 74.0.3729.157

**Comment by Lipata** [comment]
@brookhutchinson why do you need to have checkboxes, when you have a single selection? 

Do you want to still have all the checkboxes presented, and when selecting one item then to prevent selecting another using the other checkboxes? In that case, you can use the [onSelectionChange](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcombocomponent.html#onselectionchange) event which is cancelable.

Here is a great [explanation](https://github.com/IgniteUI/igniteui-angular/issues/4338#issuecomment-473819553) by @kdinev (the issue is not directly related to the combo), in which he explains the purpose of our igxSelect, igxDropDown, igxCombo, and igxAutocomplete components.

**Comment by rkaraivanov** [comment]
@brookhutchinson

Additionally you can template the igxSelect items themselves with checkboxes.
You can check out [this sample.](https://stackblitz.com/edit/angular-ag3gps)

**Comment by brookhutchinson** [comment]
Thank you to everyone for your help.  I decided to template the IgxSelectComponent items to add a checkbox to each item inside the IgxSelectComponent.  The only reasons that I need to add a checkbox to a IgxSelectComponent is for cosmetic reasons and believe it or not, an intuitive user experience.  For now when a user checks the checkbox for an item then the user has selected that item from the checkbox.  Currently I only want a user to be able to select one item from the IgxSelectComponent. In the future we will have our users use the IgxComboComponent and allow the user to make multi-selections.
