### ISSUE TITLE
how to change icon color in bottom navigation?

### ISSUE THREAD

**Issue by iehsanamiri** [IgniteUI/igniteui-angular#4810]
## Question  
I have an issue with "x" and I'm not sure if I'm doing it right.

 * igniteui-angular version: 
 * browser:

**Comment by simeonoff** [comment]
Read [the documentation](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-bottom-nav-theme) about styling the bottom navigation bar with Sass using our theming system.

If you are new to the theming, take a look at [this intro article](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/component-themes.html).

Otherwise, here's a short snippet that allows you to theme the active item color in the bottom navbar.

```scss
$bottom-nav-theme: igx-bottom-nav-theme($active-item-color: orange);
@include igx-bottom-nav($bottom-nav-theme);
```

If you are still struggling after that, please post a sample so we can help you with you concrete implementation.
