### ISSUE TITLE
IgxSelectComponent requires an exact click to make an item selection

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#4819]
## Description  
When a user selects a value from an IgxSelectComponent by clicking on an item the user has to make sure to click "exactly" on the text of the item.  If the user does not click exactly on the text and instead clicks just above the text on the same row in the items list then the item will not be selected.

 * igniteui-angular version: 7.2.4
 * browser: Google Chrome 74.0.3729.157

## Steps to reproduce  

1. Click on placeholder text of IgxSelectComponent
2. User should see an expanded list of items below the IgxSelectComponent
3. Example 3 items display inside the IgxSelectComponent
4. User tries to select an item by clicking on vertical area just above the item text
5. No item is selected, placeholder text is still displaying as the selected value
6. User tries to select an item by clicking exactly on the item text
7. The user selected item is selected and the placeholder text is replaced with the item text

## Result  
What is the actual result after following the steps to reproduce?
Nothing is selected from the IgxSelectComponent if the user does not click exactly on the item text
## Expected result  
What is the expected result after following the steps to reproduce?
User should be able to click anywhere on the row inside the IgxSelectComponent to select an item. This means that the user should be able to click on the vertical area just above the text (on the same row as the item) or the user should be able to click exactly on the item text

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by IvayloG** [comment]
Currently, the expected behavior is **_User should be able to click anywhere on the select item inside the IgxSelectComponent list to select an item_**. You can test this at: https://www.infragistics.com/products/ignite-ui-angular/angular/components/select.html

As there is no particular sample referenced, it seems to me this could be a duplicated of https://github.com/IgniteUI/igniteui-angular/issues/4724. Can you check and confirm if this is the issue you are experiencing?

If it is a different one, could you specify what is the exact sample you are referencing (either from https://github.com/IgniteUI/igniteui-angular-samples OR the DEV samples from this igniteui-angular repository)

**Comment by IvayloG** [comment]
Closing this one as duplicated of #4724
