### ISSUE TITLE
Selected cell moves to the right column when column that has selected cell becomes hidden

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#4820]
## Description  
Selected cell moves to the right column when the column that has the selected cell becomes hidden.

 * igniteui-angular version: 7.3.0
 * browser: n/a

## Steps to reproduce  

1. Run the attached sample
2. Open browser's developer tool
3. Select a cell on 'ID' column
4. Click 'Toggle ID column' button
5. Click 'Get selected cell' button

## Result  
- Cell on the Country column becomes selected.
- On the developer tool's console, the column index of the selected cell becomes 1.

## Expected result  
- Cell on the Country column does not become selected.
- On the developer tool's console, the column index of the selected cell remains 0.

## Attachments  
[igx-grid-hiding-selection.zip](https://github.com/IgniteUI/igniteui-angular/files/3189994/igx-grid-hiding-selection.zip)

**Comment by ymita** [comment]
The same behavior is observed by hiding IgxColumnLayout (Multi-Row Layout).

**Comment by nrobakova** [comment]
@ymita  this is by design. 
When a user hides a column the cell next to that column becomes selected.
You can look at the documentation for selection with all other features:
https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Multi-cell-selection-Specification#33-other-igxgrid-features-integration

**Comment by ymita** [comment]
@nrobakova Thank you for pointing it out!
