### ISSUE TITLE
Selected cell moves after sorting is performed

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#4821]
## Description  
Selected cell moves after sorting is performed.

 * igniteui-angular version: 7.3.0
 * browser: n/a

## Steps to reproduce  

1. Run the attached sample
2. Click 'Apple' on 'Name' column
3. Click header on 'Name' column to perform sorting

## Result  
Selected cell becomes 'Grape'.

## Expected result  
Selected cell remains 'Apple', or selected cell is cleared.

## Attachments  
[igx-grid-sorting-selection.zip](https://github.com/IgniteUI/igniteui-angular/files/3190224/igx-grid-sorting-selection.zip)

**Comment by nrobakova** [comment]
@ymita this is by design.
The selection is index based (DOM elements selection). So when user sort the cell in same column and row should be selected.
You can look at the documentation for selection with all other features:
https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Multi-cell-selection-Specification#33-other-igxgrid-features-integration

**Comment by ymita** [comment]
@nrobakova Thank you for pointing it out!
