### ISSUE TITLE
[igx-grid][MRL] row-spanned header cell text is aligned to the bottom.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4827]
## Description  
About `igx-grid` with multi row layout, row-spanned header cell text is aligned to the bottom. It is different from data cell.

 * igniteui-angular version: 7.3.1-beta.1
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample.

## Result  
![row-spanned-cell-vertical-alignment-issue](https://user-images.githubusercontent.com/15909409/57919919-cc730280-78d4-11e9-96a0-91c4135919d0.png)

## Expected result  
Header cell text should be aligned to the middle as data cell is.

## Attachments  
[igx-grid-multi-row-layout.zip](https://github.com/IgniteUI/igniteui-angular/files/3190911/igx-grid-multi-row-layout.zip)

**Comment by StefanIvanov** [comment]
Hi @tkiryu the observed behavior is **by design** and is mainly explained by the different role of header cells that stick to the top of the grid and may define some column operations e.g. filtering and the body cells that usually scroll vertically due to the amount of data in the grid.

**Comment by tkiryu** [comment]
@StefanIvanov , OK, I get it. Thanks for explaining!

I'm closing this issue.

**Comment by gdayori** [comment]
@StefanIvanov Is there any specific reason being stick with the header label aligned to the bottom? It is weird to me because header labels are always aligned center when I see MRL grid in LOB app.

**Comment by StefanIvanov** [comment]
Yes reason is that we want to have the same layout for the header for MCH and MRL and since it is important to have the header action such as filter, sort etc as close to the body where the content is, we align them to the bottom. Also imagine that we have MRL with 5-6 internal rows in a grid row and a column layout with just one column, then the heading and actions are pushed up unnecessarily rather than being close to the content they affect. It is an interaction optimization and UX improvement as we defined it back for MCH.
