### ISSUE TITLE
Vertical Scrollbar disappear when hide/unhide all columns

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#4855]
## Description  
Vertical Scrollbar has odd behavior when hide/unhide all columns from the toolbar dropdown menu.

1. When click hide all button the scrollbar, stays visible even if there is no need for it to be visible.
2. When click show all the scrollbar is hidden and we can't scroll the content.

 * igniteui-angular version: 7.3.x
 * browser: All

## Steps to reproduce  

1.  Go to [The sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column_hiding.html)
2. Click on the button "HIDDEN" in the toolbar to show the dropdown.
3. Click on the "HIDE ALL" Button.
4. Click again on the "HIDDEN" button to hide the dropdown.
5. Using your mouse left button click, hold and drag the VERTICAL scrollbar.
6. Click again on the "HIDDEN" button to show the dropdown.
7. Click on the "SHOW ALL" Button.
8. Click again on the "HIDDEN" button to hide the dropdown.

## Result  
After step 3 the scrollbar is visible.
After step 8 the scrollbar remains hidden

## Expected result  
After step 3 the scrollbar should be hidden.
After step 8 the scrollbar should be visible

## Attachments  
https://drive.google.com/file/d/1pu4AnlfgquZYKV94K9tkYPrLLSxVrKV0/view?usp=sharing

**Comment by tachojelev** [comment]
When we hide all columns in the grid and then manually invoke the following methods (for example on a button click):
```typescript
this.grid1.verticalScrollContainer.recalcUpdateSizes();
this.grid1.reflow();
```
the **div child** of the igx-virtual-helper gets its height updated **in**correctly, which leads to keeping the vertical scroolbar visible. However if we try to scroll, the **div child's** height gets updated correctly and the scrollbar disappears. If after that, we invoke reflow(), the grid would refresh its sizes correctly.
We should probably take a look at the recalcUpdateSizes() method logic in order to update the scrollbar's visibility accordingly.
