### ISSUE TITLE
[igxForOf] scroll position of  components that use igxForOf is not saved when they are in a igx-tabs-group.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4884]
## Description  
Scroll position of  components that use igxForOf is not saved when they are in a igx-tabs-group.
e.g) igx-grid, igx-list with igxForOf

 * igniteui-angular version: 7.2.10
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample.
2. At "Tab2", scroll down/right.
3. Switch to another tab.
4. Switch back to "Tab2".
5. Go to "Tab3".
6. Scroll down.
7. Switch to another tab.
8. Switch back to "Tab3".

## Result  
Scroll positions are not saved.
![scroll-position-issue](https://user-images.githubusercontent.com/15909409/58402073-72272e00-809a-11e9-8199-bb15358e0a10.gif)

## Expected result  
Scroll positions should be saved.

## Attachments  
[igx-grid.zip](https://github.com/IgniteUI/igniteui-angular/files/3222270/igx-grid.zip)

**Comment by kdinev** [comment]
The data position seems to be preserved, because the data doesn't change through tab switching, so just the scrollbar doesn't get adjusted.

**Comment by MayaKirova** [comment]
This works in a consistent way with hidden containers – since component and DOM do not get destroyed/recreated/moved on change the scroll state and the component state (startIndex, chunkSize etc.) are both persisted.
And also works in a consistent way when ngIf is used – since the component and DOM are destroyed/recreated on change scroll state and the component state are both cleared.

The inconsistency between the component state and the DOM comes in scenarios where the content is created once and then the DOM nodes get moved runtime. In such scenarios because the nodes are detached from the DOM and them added in a different place they will not persist their scroll state, while since the component is not destroyed/recreated it will still persist its internal state.

The igx-tabs use content projection(ng-content), which does exactly that - the projected nodes/components are always created initially (even if you wrap them into *ngIf) and are then moved from/to the specified container runtime. I don’t think this is in the official Angular Docs yet, but here is a docs issue that describes the ng-content behavior - https://github.com/angular/angular/issues/17983 .

There’s no simple way to detect when a node was moved in the DOM other than using a global MutationObserver that can listen for node changes. MutationObservers are slow (especially in IE) and may have a significant performance impact so I’m not sure adding one just to sync the state of DOM and Component state for such scenarios would be justified.

@kdinev @mpavlinov @ChronosSF @rkaraivanov  Let me know if fixing this is feasible considering the potential performance impact or if we should just document it – provide a workaround an close this.

**Comment by kdinev** [comment]
@MayaKirova Thanks a lot for the explanation. Sounds like we should document the behavior and provide potential solutions, if users run into this scenario.

**Comment by MayaKirova** [comment]
Ok. Marking this as not to fix. Here are possible workarounds depending on whether the user wants to reset the state or persist it:

1)	To reset states.
User can wrap the content/component in an ngIf, for example:
<igx-tabs-group label="Tab 3" #tab3
                    *ngIf="true">
      <igx-list *ngIf="tab3.isSelected"
…
With this when the tab is selected/deselected the component will be created/destroyed hence all states will be reset.
2)	To persist states.
Use mutation observers or other means to determine when the components have been re-added to the DOM tree and reset the scroll position manually.
Here’s a sample with Mutation Observer:
[persistScrollStateOnDomMove.zip](https://github.com/IgniteUI/igniteui-angular/files/3248142/persistScrollStateOnDomMove.zip)

**Comment by mpavlinov** [comment]
I created a separate issue to document his behavior as a known issue: https://github.com/IgniteUI/igniteui-docfx/issues/1270
