### ISSUE TITLE
In IE11 the excel style filter dialog is closed when change a filter condition

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4901]
## Description  
In IE11 the excel style filter dialog is closed when change a filter condition

 * igniteui-angular version: 7.3
 * browser: IE11

## Steps to reproduce  

1. Open dev sample gridColumnMoving in IE11
2. Open text filter for column ConpanyName and condition contains
3. In the excel style filter dialog click to change the condition

## Result  
The excel filter dialog is closed

## Expected result  
The dialog should not be closed

**Comment by tachojelev** [comment]
The issue seems to be related to the fact that the HTML **contains** method does not work properly with SVG images (as it is in the case when clicking the outline of an svg icon), which is an overlay specific logic.
Similar issue has been fixed [here](https://github.com/IgniteUI/igniteui-angular/issues/4470) (scroll to the bottom of the issue for more details).

In order to reproduce the current issue, the filter condition in the custom filter dialog shold be changed by clicking the outline of the current icon.
