### ISSUE TITLE
[igx-grid] improve IGridEditEventArgs

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4965]
## Is your feature request related to a problem? Please describe.
No.

## Describe the solution you'd like
1. I'd like `IGridEditEventArgs` to have the reference to the cell instance like `IGridCellEventArgs` does.
```ts
onCellEdit(event: IGridEditEventArgs) {
    // reference to IgxGridCellComponent
    const cell = event.cell;

    // do something to the cell
}
```
2. I'd like `IGridEditEventArgs.cellID.columnID` is renamed to `IGridEditEventArgs.cellID.columnIndex`. Because, columnID is not id but index of column, which is confusing,
```ts
onCellEdit(event: IGridEditEventArgs) {
    // Bad
    const columnIndex = event.cellID.columnID;
    // Good
    const columnIndex = event.cellID.columnIndex;
    ...
}
```

## Describe alternatives you've considered
No

## Additional context
I want to get the reference  to`IgxGridCellComponent` instance to do something to the cell when I hook the following events, 
- onCellEditEnter
- onCellEdit
- onCellEditCancel
- onRowEditEnter
- onRowEdit
- onRowEditCancel

Currently, we can't get the cell directly from event params. We have to code like below. It's a pain. 
```ts
onCellEdit(event: IGridEditEventArgs) {
    const columnIndex = event.cellID.columnID;
    const column = this.grid.columns[columnIndex];
    const cell = this.grid.getCellByKey(event.rowID, column.field);

    // do something to the cell
}
```
In addition, `event.cellID.columnID` property is confusing because it means not `ID` but `index` of column.

**Comment by wnvko** [comment]
@tkiryu 
We are on the way to update `IGridCelleventArgs`. We will add the entire column to the arguments as well as the row data. In this way:
1. You will be able to get the cell via `rowIndex` and column field like this:
```
const cell = this.grid.getCellByKey(event.rowID, event.column.field);
```

Note, because of grid’s virtualization, this may return `null` if the cell is not visible. My suggestion is to manipulate grid’s cells only via the public API and not trough `IgxCellComponent` instance. This is aso why we cannot expose the cell itself.
2. Event args will now expose the entire column. You can take column index, field and whatever you need.

We are on the way to deprecate `cellId` as it does not provide any meaningful information in these events.
