### ISSUE TITLE
[igx-grid] onCellEditCancel emits incorrect 'newValue'/'oldValue'

### ISSUE THREAD

**Issue by Lightw3ight** [IgniteUI/igniteui-angular#5096]
## Description  
When a user cancel's the editing of a cell (pressing esc key) the original value of the cell is restored and an `@Output` named `onCellEditCancel` is emitted with a `IGridEditEventArgs` object
There are two properties on `IGridEditEventArgs` named `oldValue` and `newValue` which I believe to be around the wrong way.
Given that the cell is about to have it's original value restored, I would expect `newValue` to contain the original cell value as it is to be the _new value_ applied back to the cell, and the _old value_ would be the uncommitted value that is about to be overwritten.

Below is the code from cell.component.ts where the event is emitted and as you can see, the opposite is true, the `editValue` of the cell which is the value that is about to be overwritten is assigned to `newValue` and `value` which is the value that is about to be restored is assigned to `oldValue`
```typescript
    /**
     * @hidden
     * @internal
     */
    public onKeydownExitEditMode() {
        if (this.isInCompositionMode) {
            return;
        }

        if (this.editMode) {
            const v = this.crudService.cell;
            const args = {
                cellID: v.id,
                rowID: v.id.rowID,
                oldValue: v.value,
                newValue: v.editValue,
                cancel: false
            } as IGridEditEventArgs;
            this.grid.onCellEditCancel.emit(args);
            if (args.cancel) {
                return;
            }
            this.grid.endEdit(false);
            this.nativeElement.focus();
        }
    }
```

 * igniteui-angular version: 7.3.4

## Result  
When listening to the `onCellEditCancel` event, it is confusing to know what the actual display value of the cell is.

## Expected result  
I believe the args should be constructed as below
```typescript
            const args = {
                cellID: v.id,
                rowID: v.id.rowID,
                oldValue: v.editValue,
                newValue: v.value,
                cancel: false
            } as IGridEditEventArgs;
```

**Comment by ViktorSlavov** [comment]
@Lightw3ight 
This is by design. Between entering cell edit (after [`onCellEditEnter`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#oncelleditenter)) and either committing or discarding any changes ([`onCellEdit`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#oncelledit) or [`onCellEditCancel`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#oncelleditcancel), resp.), `cell.value` has not changed. That is why it is passed under `oldValue`. The cell's `editValue` *could* have changed in that period and is passed under `newValue`. The developer might also choose to *not* discard the cell's `editValue` (as `onCellEditCancel` is cancelable).

I agree that `newValue` might be a bit misleading in some cases (something like `pendingValue` might make more sense here) but we use that property name to be consistent in our use of [`IGridEditEventArgs`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/igridediteventargs.html), which is also used in `onCellEdit` and `onCellEditEnter`.

**Comment by Lightw3ight** [comment]
Thanks for the clarification
