### ISSUE TITLE
Column Virtualization hides last data of grid.

### ISSUE THREAD

**Issue by Jigar95137** [IgniteUI/igniteui-angular#5153]
![hiddenRow](https://user-images.githubusercontent.com/52149479/59995475-dc6cc780-9674-11e9-8849-bc2c41f400b5.png)
![StartPosition](https://user-images.githubusercontent.com/52149479/59995476-dc6cc780-9674-11e9-8ca2-1d4f744cf6a1.PNG)

## Description  
Bottom most row gets disappeared, when row height increases as per added content in the cell on horizontal scroll.

 * igniteui-angular version: 7.2.6
 * browser: chrome

## Steps to reproduce  

1. Scroll grid(vertically) to last row
2. Fill any cell with more data so that it can increase grid height accordingly on horizontal scroll to that cell.
3. Last row gets hidden

## Result  
Last row gets hidden

## Expected result  
We should be able to scroll vertically to see last row back OR it should be visible

**Comment by Jigar95137** [comment]
hello, @nrobakova is there any update on this issue?

**Comment by ChronosSF** [comment]
@Jigar95137 , could you please share the code you use to change the content of the cell?

**Comment by Jigar95137** [comment]
<div *ngFor="let col of columnData">
    <igx-column [sortable]="true" [hidden]="col.key === 'tags' || col.key === 'party_code'" [field]="col?.key"
      [pinned]="col?.key === 'party_code_with_name'" [header]="col?.headerText" [width]="col?.width" [resizable]="true">
      <ng-template igxCell let-cell="cell">
        <div *ngIf='!cell.value && cell.value !== 0; else availableValue'>-</div>
        <ng-template #availableValue>
          <div class="company-name-cell" [ngSwitch]="col?.key">
            <div *ngSwitchCase="'party_code_with_name'">
              <a (click)="actionOnClick(col.key, cell.rowData.party_code)">
                {{cell.rowData.party_name + ' [' + cell.rowData.party_code + ']' | uppercase}} <br>
              </a>
              <span *ngIf="cell.rowData.tags">
                <i class="fa fa-fw" aria-hidden="true"></i> {{cell.rowData.tags | titlecase}}
              </span>
            </div>
          </div>
        </ng-template>
      </ng-template>
    </igx-column>
</div>

**Comment by MayaKirova** [comment]
@Jigar95137 
Vertical Virtualization cannot size the content based on column cells that are not in the current column virtualization viewport as they are not rendered in the DOM until scrolled in view. The size of those cells cannot be determined before they are rendered.

You should either disable column virtualization by setting a bigger width and allow the related columns to be rendered in order for the rows to have the correct height or you can manually trigger a recalculation of the DOM element sizes via the recalcUpdateSizes() method when scrolling horizontally.
Please note that recalculation will cause the row sizes to change and as a result the scrollbar size and possibly the scroll position will also change due to that difference.

You can refer to the following sample, which uses custom template for the last column to set a bigger size for it and test out both suggestions and see which one is a better fit for your scenario:
[GridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/3373605/GridSample.zip)

**Comment by Jigar95137** [comment]
Hey, @MayaKirova, thank you for this solution.
It's working fine for me.
You can close this issue.
