### ISSUE TITLE
[igx-combo] initial values are not checked.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#5217]
## Description  
Initial values are not checked.

 * igniteui-angular version: 7.3.7
 * browser: any

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-combo-initial-value-not-selected-issue
2. Open drop down

## Result  
Initial values are in the textbox, but they are not checked on the drop down.
![image](https://user-images.githubusercontent.com/15909409/60248745-3fbd5a80-98fe-11e9-98bb-3f1dc44676b9.png)

## Expected result  
Initial values should be checked on the drop down.

## Attachments  
https://stackblitz.com/edit/igx-combo-initial-value-not-selected-issue

**Comment by ViktorSlavov** [comment]
@tkiryu 
The combo items are marked as selected by object reference. Since you're initializing new items inside the `selectedItems` array, they are not present in the `items` array and are not mapped as selected.
If you pass `[this.items[0]], this.items[1]]` under `selectedItems`, the entries in the list will be properly marked. Here's the [updated example](https://stackblitz.com/edit/igx-combo-initial-value-selected?file=src/app/app.component.ts)

We'll review how the combo handles passing selected items, as with the current implementation it's a bit tricky to implement `ngModel` binding if both your data an selected items are coming from separate services. We'll investigate if we could maybe streamline that more w/o impacting performance.

**Comment by zdrawku** [comment]
This approach does not work appropriately when it comes to remote data, I needed to add more logic (selectItems and triggerCheck) in order to accomplish an initial selection of items.

As I spoke with @Lipata one of the next sprints we should definitely find time for this bug, our combo should provide `ngModel` binding.

**Comment by ViktorSlavov** [comment]
@zdrawku @tkiryu @rkaraivanov @damyanpetev 
Since the fix for the value binding has the potential to **break** applications using binding w/ object references + defined `[valueKey]`, I've targeted the [PR](https://github.com/IgniteUI/igniteui-angular/pull/5569) to `8.2`.
When the [PR](https://github.com/IgniteUI/igniteui-angular/pull/5569) is merged, there will be two ways to bind to the combo's `[(ngModel)]`:
- If `valueKey` is **defined**, `[(ngModel)]` should be an array containing only the resp. values. For example, if `valueKey="id"`, `[(ngModel)]` should be an array containing the item **ids**.
```html
<igx-combo #combo [data]="data" valueKey="id" displayKey="text" [(ngModel)]="values">
</igx-combo>
```
```typescript
export class MyExampleComponent {
    ...
    public data: {text: string, id: number, ... }[] = ...;
    ...
    public values: number[] = ...;
}
```
- If `valueKey` is **not defined**, `[(ngModel)]` should be an array of items **equal (===)** to the items that should be selected. If the `[data]` input is `string[] | number[]`, `[(ngModel)]` should be an array w/ the resp. entries. If the `[data]` input is `{[key:string]: any}`, `[(ngModel)]` should be object references.
```html
<igx-combo #combo [data]="data" displayKey="text" [(ngModel)]="values">
</igx-combo>
```
```typescript
export class MyExampleComponent {
    ...
    public data: {text: string, id: number, ... }[] = ...;
    ...
    public values: {text: string, id: number, ...} [] = [this.items[0], this.items[5]];
}
```
