### ISSUE TITLE
Expansion Panel title is not previewed in IE11

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5239]
## Description  
Expansion Panel title is not previewed in IE11

 * igniteui-angular version: 8.0
 * browser: IE11

## Steps to reproduce  

1. Open [link](https://www.infragistics.com//angularsite/components/expansion_panel.html) in IE11

## Result  
Title is not previewed

## Expected result  
Title should be previewed

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/60326599-a0967280-9992-11e9-91ff-ff051e4d9a60.png)

**Comment by ViktorSlavov** [comment]
This looks like a styling issue - both the `title` and `description` elements are present in the DOM, but the title doesn't take up any space and hides it's content (due to `overflow: hidden`).
![image](https://user-images.githubusercontent.com/24314672/60328752-988d0180-9997-11e9-9f29-a8bf18f1767d.png)

![image](https://user-images.githubusercontent.com/24314672/60328731-8b701280-9997-11e9-9e67-3c42ea4fbbc0.png)

@simeonoff @desig9stein 
When you have the time, could you please take a look? Thank you!

**Comment by simeonoff** [comment]
@ViktorSlavov might be a sample issue. Will check it out.
