### ISSUE TITLE
When load on demand is enabled and add a child row the expand indicator is not previewed

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5479]
## Description  
When load on demand is enabled and add a child row the expand indicator is not previewed

 * igniteui-angular version: 8.1
 * browser: n/a

## Steps to reproduce  

1. Open dev sample treeGridLoadOnDemand
2. In the first grid select row with FirstName 'Jonathan'
3. Click Add Child Row button

## Result  
Child row is added, but the expand indicator is not previewed

## Expected result  
Expand indicator should be previewed

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/61642533-be14de80-aca9-11e9-9923-f77e281565e4.png)

**Comment by DiyanDimitrov** [comment]
In order to show the indicator the user should change the `hasChildrenKey` property of the parent row to `true`. I have thought about changing it in our code, but the idea of the `hasChildrenKey` property is the user to provide us with information from the server whether a row has children or not, so it is not a good idea to modify it on the client. Also there are some complex scenarios as deleting rows and transactions, which are hard to handle.

I will make a PR to update the dev demo with setting `hasChildrenKey` to `true`.
