### ISSUE TITLE
Dynamic multiheader

### ISSUE THREAD

**Issue by ivanovla** [IgniteUI/igniteui-angular#5485]
Hello.
I do table with remote data and different config. I wants build table with multi header( Tab index). 
In order to achieve this, I recursively insert columns and it does not work. How can I still achieve this?
Thanks in Advance.
![image](https://user-images.githubusercontent.com/31878467/61710241-d0e6ec00-ad59-11e9-8904-caf1ce1b031b.png)

app-group-columns.html:

![image](https://user-images.githubusercontent.com/31878467/61710253-db08ea80-ad59-11e9-8468-5fcd514b2c0e.png)

**Comment by ivanovla** [comment]
Is there any information?

**Comment by zdrawku** [comment]
@ivanovla I don't see any reason this to be a problem, could you please share with me the exact version of our product that you are using?

**Comment by ivanovla** [comment]
> @ivanovla Я не вижу причин, чтобы это было проблемой, не могли бы вы поделиться со мной точной версией нашего продукта, который вы используете?


The problem is that if I wrap igx-column or igx-column in other component, I get an empty table. Columns are not initialized. And in another recursive insertion, I cannot achieve. 

What i expect: 
![image](https://user-images.githubusercontent.com/31878467/62518289-e5cf7f00-b831-11e9-9e9f-e9a2682fd4de.png)

What i get:
![image](https://user-images.githubusercontent.com/31878467/62518346-07306b00-b832-11e9-992e-2af81879cdf1.png)

**Comment by ivanovla** [comment]
@zdrawku 
Is there any information?

**Comment by zdrawku** [comment]
He @ivanovla, your approach is pretty good. Having configuration file with structural purposes is cleaner and will reduce the template code of your application indeed. I've used your approach in order to try to replicate the issue and everything seems to be working file. 
By simply using `ng-container` grouping element and `ngIf` directive you can implement the recursive configuration that is needed for dynamic creation of Multi-header and regular columns. Please let me know if I am missing anything here.

[Working sample with StackBlitz](https://stackblitz.com/edit/angular-grid-dynamic-columns-creation)

[Column configuration](https://stackblitz.com/edit/angular-grid-dynamic-columns-creation?file=src%2Fapp%2Fgrid%2Fmulti-column-headers%2Fmulti-column-headers.ts)

```
public gridConfig =  {
      parentColumns: [
        {
          pHeader: "ID",
          field: "ID"
        },
        ...
        { 
          pHeader: "General Information",
          childColumns: [ 
              { header: "Company name", field: "CompanyName" }, 
              { header: "Contact Name", field: "ContactName" },
              { header: "Contact Title", field: "ContactTitle" } 
          ] 
        },
        {
          pHeader: "Address Information",
          childColumns: [
              {
                header: "Town Location",
                field: "Address"
              },
              {
                header: "Country Location",
                grandChildColumns: [
                  { header: "Country", field: "Country" }, 
                  { header: "Postal Code", field: "PostalCode" },
                  { header: "City", field: "City" },
                  { header: "Address", field: "Address" }
                ] 
              }, 
              ...
    };
```

[igxGrid Columns configuration by using `ng-container`](https://stackblitz.com/edit/angular-grid-dynamic-columns-creation?file=src%2Fapp%2Fgrid%2Fmulti-column-headers%2Fmulti-column-headers.html)

```
...
<ng-container *ngFor="let childColumn of column.childColumns">
  <igx-column *ngIf="childColumn.field" [movable]="true" sortable="true" [header]="childColumn.header" [field]="childColumn.field"></igx-column>
  <igx-column-group *ngIf="childColumn.grandChildColumns" [movable]="true" [header]="childColumn.header" [filterable]="false">
    <ng-container *ngFor="let grandChildColumn of childColumn.grandChildColumns">
      <igx-column *ngIf="grandChildColumn.field" [movable]="true" sortable="true" [header]="grandChildColumn.header" [field]="grandChildColumn.field"></igx-column>
    </ng-container>
  </igx-column-group>
</ng-container>
...
```

**Comment by ivanovla** [comment]
@zdrawku 
Yes, you sent me a similar example, as I wrote, only with more nesting.
I do it because there is no choice.
Too bad there is no solution with recursion, thanks for the support

**Comment by AndriiDidkivsky** [comment]
Any news ?
