### ISSUE TITLE
Grid does not implement height=100% correctly

### ISSUE THREAD

**Issue by ramunas-k** [IgniteUI/igniteui-angular#5493]
## Description  
I'm working on a project that uses `IgniteUI Angular` `Grid` component to display tabular data. There are a couple of pages where it is desired to have grid expanding a full height of it's container. But navigatinig between those two pages makes grids on those pages expand in height.

 * igniteui-angular version: 8.1.0
 * browser: Chrome (latest), Firefox (latest)

## Steps to reproduce  
https://igniteui-angular-grid-height-issues.stackblitz.io  
This is a small application with three pages in it:
- Home - has no content
- Page 1 - header and grid with `[height]="'100%'"`
- Page 2 - header and grid with `[height]="'100%'"`  

Data for grids (sequence of numbers) is rendered by a service.

## Result  
Navigating between `Page1` and `Page2` routes makes grids in both pages expand in height. Visiting `Home` and going back to `Page1` or `Page2` 'resets' the issue untill you visit `Page2` or `Page1`.

## Expected result  
Grid component with `[height]="'100%'"` takes full height of it's container at all times.

## Attachments  
None

**Comment by ChronosSF** [comment]
@ramunas-k , the issue is not with the grid. Your main container should also be `display: flex` otherwise it's block and would have a height equal to the whole outer container regardless of the nav header in it. Check the following sample: https://stackblitz.com/edit/igniteui-angular-grid-height-issues-fe5raz?file=src/app/app.component.css

**Comment by ramunas-k** [comment]
Cool. Thanks a lot.
