### ISSUE TITLE
IgxInput does not remove validation error style after the form is reset

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#5497]
## Description  
IgxInput does not remove its validation error style after the form is reset.

 * igniteui-angular version: 8.1.0
 * browser: any

## Steps to reproduce  

1. Run the attached sample
2. Set focus on Name field
3. Set focus on Price field
4. Click "reset state" button
![IgxInput_Validation](https://user-images.githubusercontent.com/14340675/61774946-e419ba80-ae32-11e9-979f-8d8bf54a8ea7.gif)

## Result  
Form state is reset but the Name field and Price field keep invalid style.

## Expected result  
Name field and Price field does not have invalid style.

## Attachments  
[igx-input-group.zip](https://github.com/IgniteUI/igniteui-angular/files/3425567/igx-input-group.zip)

**Comment by GeanAlexandre** [comment]
any update for this issue ?

**Comment by PixelShoot** [comment]
+1

**Comment by Lipata** [comment]
@GeanAlexandre, @PixelShoot we are starting to work on this. Regards!

**Comment by wnvko** [comment]
This issue should be fixed in next version. One note. If developer changes the value of any input by calling `setValue` or `patchValue` the input may or may not show validation errors. Here is how input should work by specification:
- if input is pristine and untouched it will never show validation errors whatever value developer sets through code behind.
- if input is touched or dirty:
  - if developer sets correct value through code behind form will not show validation errors.
  - if develper sets incorrect value through code behind form will show validation errors.

If developer needs to set invalid value, e.g. `null` or `undefinde` on touched or dirty form, and need to hide validation errors, he should call `reset` to make input pristine and untouched.

**Comment by HamzaTatheer** [comment]
setTimeout(() => {
			document.querySelectorAll('.igx-input-group--invalid').forEach((key) => {
				key.classList.remove('igx-input-group--invalid');
			});
		}, 300);
