### ISSUE TITLE
Igxgrid: Right click is not working on Header template

### ISSUE THREAD

**Issue by shaileshyadav24** [IgniteUI/igniteui-angular#5570]
### Description  
Added a method on right click of the header, which is created using HeaderTemplate. Sort is also enabled on it.

HTML :

```
<ng-template igxHeader let-col>
 <div class="text-center" (contextmenu)="contextmenuEVENT()">
                <b>{{col?.header }}</b>
              </div>
</ng-template>
```

TS:
```
contextmenuEVENT() {
console.log("EVENT OCCURED");
}

```
 * igniteui-angular version: 7.3

### Result  
Outcome:
Console is not printed

### Expected result  
What is the expected result after following the steps to reproduce?
Console should be printed

**Comment by zdrawku** [comment]
[onContextMenu ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#oncontextmenu )should be set to the Grid components in order to emit the event on right-click. I believe you will find very helpful [the following sample and documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection.html#grid-context-menu), which explains how to implement copying of data with context menu in the Grid.
