### ISSUE TITLE
ngModel is not working when datePicker is within a form html element

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#5659]
## Description  
ngModel is not working properly when igxDatePicker component is part of a <form>

 * igniteui-angular version: 8.1.3
 * browser: any

## Steps to reproduce  

1. Open [the sample](https://stackblitz.com/edit/angular-form-ngmodel-issue-dropdown-mode?file=src/app/scheduling/datepicker/datepicker-dropdown/datepicker-dropdown.component.html)
2. You can see that the datePicker input is set to `new Date('8/10/2019'),`
3. Open the `component.html` file and comment out the <form> element
4. Check the datePicker input, value is cleared out

## Result  
datePicker value is not set to `new Date('8/10/2019'),`

## Expected result  
datePicker to display `new Date('8/10/2019'),` date

Samples for [dropDown mode](https://stackblitz.com/edit/angular-form-ngmodel-issue-dropdown-mode?file=src/app/scheduling/datepicker/datepicker-dropdown/datepicker-dropdown.component.html) and [dialog mode](https://stackblitz.com/edit/angular-form-ngmodel-issue-dialog-mode).

**Comment by ViktorSlavov** [comment]
This does not seem like a bug w/ the datepicker.
In order to have proper `ngModel` binding in a `form` tag, a `name` attribute needs to be provided for the input you're using *OR* you need to provide `[ngModelOptions]="{standalone: true}"`.
When you uncomment the `form` tags in the provided samples, the error shows up in the console:
```
Error: If ngModel is used within a form tag, either the name attribute must be set or the form
control must be defined as 'standalone' in ngModelOptions.

Example 1: <input [(ngModel)]="person.firstName" name="first">
Example 2: <input [(ngModel)]="person.firstName" [ngModelOptions]="{standalone: true}">
```
When either of these is provided, the controls [work as expected](https://stackblitz.com/edit/angular-ngmodel-form-datepicker?file=src%2Fapp%2Fscheduling%2Fdatepicker%2Fdatepicker-dropdown%2Fdatepicker-dropdown.component.html).
This is also applicable in the case of the [basic HTML `input`](https://stackblitz.com/edit/angular-ngmodel-form-input?file=src/app/app.component.ts).
