### ISSUE TITLE
Custom scroll container for igxGrid

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#5698]
## Is your feature request related to a problem? Please describe.
In one of our pages, the page consists of a rather large filter, which is always present, combined with a grid.
![image](https://user-images.githubusercontent.com/12936286/63774400-72270c00-c8dd-11e9-8646-9d9c1d3611a0.png)
Currently, the only way to use virtualization in a scenario like this, would be to accept a double scrollbar (one for the page and one for the grid). It would be very nice, if you could pass a reference to another element, which could work as the scroll area instead of the grid body, enabling us to use the page scrollbar only.

## Describe the solution you'd like
Ability to assign a elementRef as the basis for igxFor virtualization, or any other solution which would accomplish the above .

**Comment by ChronosSF** [comment]
@Eralmidia , I am not sure what the end goal is for this scenario as it is hard to tell based on a screenshot alone. Please, let me know if my assumptions below are correct:

1. You need this UI to look in the same way regardless of screen height.
2. You expect that no grid height will work for every screen height so you actually need a scroll that can scroll the grid into view (and hide part of the filter pane).
3. But you also don't want to have the same scrollbar scroll the grid __content__ once it scrolls the whole grid into view.

**Comment by Eralmidia** [comment]
@ChronosSF 

1. Correct
2. Correct
3. No, I actually do want the same scrollbar. I would like a single scrollbar for the whole page. The visible columns should be based on the scroll position of the page and position of the grid within the page. For instance, consider the following sample:
![Untitled-2](https://user-images.githubusercontent.com/12936286/64847011-48285600-d60e-11e9-9e8f-5d51bff4834a.png)

Here, the red square represents the visible area on the screen. The yellow is the filter, the pink the scroll bar (for the whole page), and blue and green are two igx grids. If the grids know their scroll positions within the page, I recon it should be possible for the blue grid to know which columns are currently within view, and for the green grid to know that it is not in view at all.

**Comment by ChronosSF** [comment]
Yes, that's what I meant more or less with 3. though you described it detail. You need this singular container scrollbar to smartly scroll the virtualized grids based on its scroll position.

(I assume you do want for the grids to only show part of their data at once (i.e. be virtualized), otherwise you could simply set grid height to null and have them wrapped in a container with overflow scroll)

I don't think exposing an external scrollbar would work because there is no out of the box way for `igxForOf` to know that it should do nothing in e.g. 2/3 of its scroll height (you obv don't want for the first grid to show a row index 1/3 of the way down when the end-user first manages to scroll to it). I am thinking more of a custom scroll implementation on application level and hidden virtual scrollbars for the grid. Then the custom implementation would modify the scroll top and call `scrollTo` for each grid based on the end-user interaction.

I'll play around with it a bit but I don't think there will be anything to implement for this in the virtualization directive. This looks like something to accomplish on app level.

**Comment by Eralmidia** [comment]
@ChronosSF Thanks. I'm not exactly sure how you would implement your idea of virtual scrollbars and scrollTo. Any chance of a sample? If this is indeed achievable on our end, there is really no need to do research on the directive. It's just that with the current setup, we get horrible performance unless we do paging (and small number of rows per page) because we render the whole grid (null height)

**Comment by Eralmidia** [comment]
@ChronosSF Also, please note that the pages doesn't necessarily only contain grids. There may be pages with some charts or other elements in there as well. Just in case that has any impact on your idea.

**Comment by ChronosSF** [comment]
The idea is more or less the following:

1. Outer scrollbar is virtual with scroll height equal to the sum of heights of non-virtual components (such as charts and the filtering pane) + the __scroll__ heights of virtual components such as grids.
2. Scrolling down from top changes the scroll top of the outer container until the bottom edge of a virtualized component is reached in which case further scrolling calls its `scrollTo` method until its bottom-most virtualized frame is reached. This is followed by further scrollTop changes until another bottom edge is reached.
3. Same is applied in reverse for scrolling up.

This may or may not look weird when you add the fixed grid headers and other parts in cases where the whole grid can fit into the window height. 

You have to hide all virtual grid vertical scrollbars so that only the outer one can be used by the end-user.

I'll try to apply the idea in a small sample that you would be able to modify/extend to work for  your application.

**Comment by Eralmidia** [comment]
Thank a lot. Looking forward to seeing the sample 👍

**Comment by ChronosSF** [comment]
It took more time than I anticipated but the sample I am attaching does most of what I wanted correctly.

[virtual-scroll.zip](https://github.com/IgniteUI/igniteui-angular/files/3619938/virtual-scroll.zip)

The scroll handler is far from ideal as I am pretty sure it should never depend on the `isScrolledToBottom` and `isScrolledToTop` handlers but instead ensure they are scrolled at those positions based on the new scroll position. As it is now, clicking anywhere on the scrollbar (instead of dragging the thumb) will probably break it. In addition fixed elements inside virtual components would require additional logic so that when scrolling up the real scroll can stop at them instead of before them (if scroll all the way down in the sample then start scrolling up, you'll notice that the second grid starts scrolling up before its header is seen).

You'll also need a global wheel handler which I didn't implement.

One thing that came up is that there is no way to "lie" to the grid that its scrollbars are invisible without breaking its virtualization. Simply hiding them leaves space where they should be as it is clearly shown int he sample. If you like this solution we should consider exposing an input (something like `externallyScrolled: true|false`) that would make the grid not render its scrollbars but still have all virtualization features available.

**Comment by Eralmidia** [comment]
@ChronosSF Thanks. I'll use this as basis for exploring what options we have regarding this.
