### ISSUE TITLE
Grid transactions undo does not restore original cell value

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#5779]
Grid transactions undo does not restore original cell value

 * igniteui-angular version: 8.2.0-beta.4

## Steps to reproduce  

1. Run the sample
2. Edit the Capacity field twice
3. Click the undo button
4. Click the undo button again

## Result  
The value restored in the cell is the value that the user has entered first

## Expected result  
The value restored to be the original cell value.

## Attachments  
[grid-excel1.zip](https://github.com/IgniteUI/igniteui-angular/files/3604532/grid-excel1.zip)

**Comment by GibletJr** [comment]
The issue is important as the data represented in the grid should mirror/align with the data stored in the backend.  This issue allows the data displayed in the grid to be out of sync.  In our case, multiple fields are updated if the user edits a column that is an operand to a calculated field's formula.  We rely on updateRow() to track the multi-field edit as a single transaction. It is critical that our users see the data based on their last edit when commit() is called, not the second to last (n-1) edit.

**Comment by radomirchev** [comment]
@GibletJr , I agree on the importance of the issue. It is scheduled for the next Sprint run.

**Comment by GibletJr** [comment]
Can you please confirm which release this fix is in?

**Comment by hanastasov** [comment]
> Can you please confirm which release this fix is in?

It will be included in next version, please monitor https://github.com/IgniteUI/igniteui-angular/releases. There should be next release within a week.
