### ISSUE TITLE
Attach drag ghost to a predefined HTML element

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#5799]
## Is your feature request related to a problem? Please describe.
If you have on the page elements with big z-index the drag ghost is drawn behind those elements while dragging.

## Describe the solution you'd like
Right now the drag ghost is attached to the document's body. If there is a way to tell the drag ghost to attach to some predefined element one can set the necessary z-index to this element. This will allow the drag ghost to be drawn above all the elements in the page.

## Additional context
Here is a [Stackblitz](https://stackblitz.com/edit/angular-du45ua?file=src/app/drag-drop/icons-sample/icons-sample.component.html) showing the issue.

**Comment by skrustev** [comment]
@wnvko There is already a [`ghostHost`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdragdirective.html#ghosthost) input that appends the drag ghost to a specific element in the DOM. It should provide the desired behavior.
That's why I think this issue can be closed.
