### ISSUE TITLE
Ivy Support

### ISSUE THREAD

**Issue by vanslly** [IgniteUI/igniteui-angular#5849]
## Is your feature request related to a problem? Please describe.
Angular 8 has the Ivy renderer as an opt-in, but when I create a new Angular 8 app with ivy enabled certain properties (like `[paging]="true"`) causes build errors with `igniteui-angular@8.1.8`. When is full Ivy support scheduled for?

## Describe the solution you'd like
I would like to enable ivy in my application so I get a faster application with a smaller bundle size, but `igniteui-angular@8.1.8` does not fully work with Ivy. I would also like ivy support tracked so I'll know when `igniteui-angular` is fully Ivy-ready.

## Additional context
I've investigated the issue a bit and turns out `IgxGridComponent extends IgxGridBaseComponent` is currently a problem for Ivy because https://github.com/angular/angular/issues/30080

**Comment by rkaraivanov** [comment]
Indeed the change between abstract classes and Angular metadata (`@Inputs/@Outputs/etc.`) is unfortunate. Ivy is set to be the default compiler/rendering pipeline in Angular version 9 and as such this is the version that we're targeting

**Comment by Eralmidia** [comment]
Definitely waiting for this one as well. Angular 9 should be in beta any day now 👍

**Comment by ChronosSF** [comment]
@Eralmidia , @vanslly , we just published version `9.0.0-beta.1` which should work under Ivy in the latest Angular 9 betas. If you have time to test it with your Ivy-enabled apps, please do. The sooner we identify any additional incompatibilities the better.

Currently the only known issue is that igxCombo won't select any elements because of an issue with angular that we logged - https://github.com/angular/angular/issues/33300

**Comment by radomirchev** [comment]
Ivy support is considered - complete. Remaining issues are covered by #6175
