### ISSUE TITLE
Can’t clear selected date in calendar when clicking on it or pressing Enter.

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#5869]
## Description  
Can’t clear selected date in calendar with range selection when a click on it or press Enter.

 * igniteui-angular version: 8.1.4

## Steps to reproduce
1. Go to https://stackblitz.com/edit/igniteui-angular-issue-5869
1. Click on any date, for example 11 September.
2. Click on **later date** to apply range selection, for example 5 November.
2. Click on a date between the first two dates, for example 22 September
3. Click again on 22 September

## Result  
the date is selected

## Expected result  
the date should be deselected

**Comment by ddincheva** [comment]
This issue is reproduced only when we have a range selection that covers two /or more/ months that are currently in the view. In this case, each selection is executed for each date view and the calendar state is not correct/rangeStarted property is not correct/. So this problem should be fixed when calendar refactoring is performed.  #8328
