### ISSUE TITLE
Allow master-detail style visualization with igxGrid

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#5880]
## Is your feature request related to a problem? Please describe.
I want to be able to create a master-detail view with igxGrid, where the master is the grid rows that are expandable and expanding them shows custom template / component for their details.

## Describe the solution you'd like
Clear-cut way for defining "details" template for grid rows.

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by MayaKirova** [comment]
@StefanIvanov @radomirchev @rkaraivanov @ChronosSF 

As previously discussed this will be a feature of the igxGrid ( will not affect the other grids - TreeGrid and HierarchicalGrid).
In order to differentiate from the GroupBy feature, which also renders expander indicators, when master-detail template is defined it will render expander inside the cell and will no have an expand/collapse indicator in the header (like in the TreeGrid) :

![image](https://user-images.githubusercontent.com/10397980/67934681-0872f900-fbd1-11e9-9ba4-67714b482fde.png)

**Comment by MayaKirova** [comment]
@radomirchev @kdinev @rkaraivanov @ChronosSF 

Please review the initial spec and let me know what you think:
https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Master-Detail

**Comment by kdinev** [comment]
@MayaKirova I have put some changed in the spec and have signed it off on my end.
