### ISSUE TITLE
Transparent effect of row selectors on horizontal scrolling

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#5977]
## Description  
Row content (text, templates etc) appear above the row selectors when using grid-theme for alternating rows style.

 * igniteui-angular version: 8.2.0
 * browser: any

## Steps to reproduce  

1. Open [the sample](https://stackblitz.com/edit/angular-alternating-rows-problem-with-row-selectors)
2. Start horizontal scrolling

## Result  
![image](https://user-images.githubusercontent.com/11193764/66759006-183bcf00-eea8-11e9-9936-1bb33a5b83ae.png)

**Comment by simeonoff** [comment]
@zdrawku I see that you have applied a custom grid theme with $row-even-background set to rgba(0, 0, 0, .03); This value is essentially what is causing the problem, since it's a transparent color.

The selection container is affixed to the left of the grid and inherits the color of its parent row. If the background color of the parent row is translucent, so is the background color of its child selection container. Changing the background color of the even rows to a solid color, say #eee, will produce a better result.

This is a conscious decision that the creator of the theme made.

I don't see how we can fix this, without altering the color the user passed, essentially disregarding their choice of transparency.
