### ISSUE TITLE
Add Bootstrap theme

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#5990]
Can you please provide an example of how to easily implement a different guideline for themes?

- Fluent
- Bootstrap

Currently i'm having big troubles trying to copy Fluent theme:
https://www.microsoft.com/design/fluent/#/

**Comment by desig9stein** [comment]
Hi @luiscla27 
Since version **8.2.0**, We have visual implementation for **Microsoft fluent** theme. You can switch between **Material** and **Fluent** by changing the **igx-theme** mixin in your **SCSS** file.

Here is an example:

```
// In your theme file Replace
@include igx-theme($default-palette);

// Depending on your use case choose between Light or Dark version of the theme

// Light version
@include igx-fluent-theme($fluent-excel-palette);
// OR
@include igx-fluent-theme($fluent-word-palette);

// Dark version
@include igx-fluent-dark-theme($fluent-excel-palette);
// OR
@include igx-fluent-dark-theme($fluent-word-palette);
```

In the end, you should get something like this: 

```
@import '~igniteui-angular/lib/core/styles/themes/index';
@include igx-core();
@include igx-fluent-theme($fluent-excel-palette)
```

In case you don't use SCSS you can use one of the pre-compiled CSS files.
igniteui-fluent-light-excel.css
**igniteui-fluent-dark-excel.css**
igniteui-fluent-light-word.css
**igniteui-fluent-dark-word.css**

We don't have Foundation and Bootstrap themes. However, you can create your own, by extending our component [schemas](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/schemas.html#extending-schemas) and changing the default [palette](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/palette.html).

**Comment by luiscla27** [comment]
Thank you so much! i'll try it :)

**Comment by simeonoff** [comment]
We've decided to only support the following themes:
- Material
- Bootstrap
- Fluent
