### ISSUE TITLE
Localize Advanced Filtering Dialog on igx-grid

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#5992]
## Is your feature request related to a problem? Please describe.
Some labels on the Advanced Filtering dialog are not localized by igniteui-angular-i18n.

## Describe the solution you'd like
They are localized when igniteui-angular-i18n is loaded. My idea for localization into Japanese is as below image.
![image](https://user-images.githubusercontent.com/7350918/66896364-9ecee880-f02f-11e9-9a34-509e7f60a8b6.png)

## Describe alternatives you've considered
If registered conditions (in blue rectangle in the above image) is quite difficult to localize perfectly, 
 please localize labels other than registered conditions (in blue rect). People would understand the meaning of the conditions.

To localize registered conditions part perfectly, It would require to replace the label position of the condition (Equals / Contains) with Value label.

## Additional context
N/A

**Comment by yoshimis** [comment]
@bkulov Should this be submitted under https://github.com/IgniteUI/igniteui-angular-i18n? 
This request requrires changes in word order for grid conditigx_grid_filter_contains and igx_grid_filter_equals.

**e.g.** 1 should come after igx_grid_filter_contains instead of 1 + igx_grid_filter_contains.

**The below has same sympton and needs changes:**
igx_grid_filter_contains
igx_grid_filter_doesNotContain
igx_grid_filter_startsWith
igx_grid_filter_endsWith
igx_grid_filter_equals
igx_grid_filter_doesNotEqual
igx_grid_filter_greaterThan
igx_grid_filter_lessThan
igx_grid_filter_greaterThanOrEqualTo
igx_grid_filter_lessThanOrEqualTo

**Comment by DiyanDimitrov** [comment]
@yoshimis, Localizing the advanced filtering strings is handled in this [PR](https://github.com/IgniteUI/igniteui-angular-i18n/pull/20). Swapping the value and the condition name is a feature request.
