### ISSUE TITLE
How to change CSS max-height of <igx-select> dropdown list

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6046]
## Question  
When a user clicks on a `<igx-select>` the dropdown list displays
How do I change the CSS max-height of the dropdown list?
Where do I need to apply the CSS?

 * igniteui-angular version: 8.2.3
 * browser: Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by IvayloG** [comment]
Hello Brooke,

Currently, **max-height** is set internally by the select component to **256px**, to ensure an appealing overall appearance for the items container. On the other hand, there is the following class applied to the select items container class="**igx-drop-down__list--select**". You can use it to set a different max-height. However, this may require to:
1)	If the component is using an Emulated ViewEncapsulation, it is necessary to penetrate this encapsulation using **::ng-deep.** .
2)	use the **!important** rule on the style declaration.

You can refer to the [following fork](https://stackblitz.com/edit/select-ddl-max-height-css) of one of our select samples, in order to see an illustration example on how to set a different max-height for the select items list.

```
::ng-deep {
  .igx-drop-down__list--select {
    max-height: 328px !important;
  }
}
```

**Comment by brookhutchinson** [comment]
@IvayloG Thank you for your suggestion.  Your suggestion worked.
