### ISSUE TITLE
Incorrect display of the table after upgrading to 8.2.x

### ISSUE THREAD

**Issue by ivanovla** [IgniteUI/igniteui-angular#6068]
Hello. 

After updating to version 8.2.x, problems with displaying the table began.
1. The table is not completely filled, the lines occupy half.
2. When you click on a cell, a row is highlighted. This is inconvenient, is it possible to disable it somehow?
3. Is there a flag to disable igxgrid automatic recalculation? It hits performance

After update:
![0-02-08-7b96d002ad313f041b580bab73ab5be11b6c4b86f991b0650181ed8f5316a0f4_27b5bd8a](https://user-images.githubusercontent.com/31878467/67658046-8cc34300-f969-11e9-9be7-2043bc195490.jpg)

Before update:
![image](https://user-images.githubusercontent.com/31878467/67658014-7d43fa00-f969-11e9-8c55-edc1ad14a0f3.png)

**Comment by ChronosSF** [comment]
Hello,

Thanks for reporting this! Which browser do you experience the issue with? Could you please share your grid configuration?

In 8.2.x selection is controlled by two seperate properties. If you don't want row selection you can set ```[rowSelection]="'none'"```. Please, check [this topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection.html) for more information.

**Comment by ivanovla** [comment]
I use Chrome 78.0.3904.70.

My config : <igx-grid
    #grid

    [displayDensity]="config.gridConfig.displayDensity"
    [data]="data"
    [primaryKey]="'weldId'"
    [height]="'100%'"
    [width]="'100%'"
    [rowSelectable]="true"

    (onFilteringDone)="changeCfg()"
    (onRowSelectionChange)="handleRowSelection($event)"
    (onRowEdit)="handleRowEdit($event)"
    (onCellEdit)="handleCellEdit($event)"
    (onSortingDone)="sortingDone($event)">

I want the row selection to occur only through checkboxes, otherwise what are they for.


> Привет,
> 
> Спасибо за сообщение об этом! С каким браузером у вас возникла проблема? Не могли бы вы поделиться своей конфигурацией сетки?
> 
> В 8.2.x выбор контролируется двумя отдельными свойствами. Если вы не хотите, чтобы выбор строки вы можете установить `[rowSelection]="'none'"`. Пожалуйста, проверьте [эту тему](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection.html) для получения дополнительной информации.

**Comment by ChronosSF** [comment]
Regarding selection, the recommended approach to allow selection from the row selectors column only has been covered in this issue: #6035 and more specifically with this [sample](https://stackblitz.com/edit/angular-grid-cell-and-row-selection-sgjw5a).

Basically, you have to set ```[rowSelection]="'multiple'"``` to show multi-row selection checkboxes, ```[cellSelection]="'none'"``` and then handle the ```onRowSelectionChange``` event and cancel it if it is triggered by the end-user clicking on data cells.

With 8.2 sizing of the grid is handled by a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver). Having half the height of the grid empty indicates that it is most likely not working correctly. Could you please share your package.json/angular.json and polyfills files so that we can see if everything looks correct there. If you can reproduce the issue in a stackblitz sample, it will be incredibly helpful to us.

Also, is the screenshot from Chrome running on a Mac?

**Comment by ivanovla** [comment]
@ChronosSF 
By selecting the lines, the option you proposed suits me, thank you.

And here is an example of a problem grid.
https://stackblitz.com/github/Elburevestnik/WB-test-table-wrapper?file=package.json
We did not test on Mac.

**Comment by MayaKirova** [comment]
@ivanovla 
The parent container - app-table-wrapper, has inherited display style “inline”, with which the specified height:100% setting is ignored, hence the container has no height when the grid tries to determine its available height.
You can set a different display style so that the height:100% can take effect. Here’s a modified sample for your reference: https://stackblitz.com/edit/github-jwzmss

**Comment by ivanovla** [comment]
> Что касается выбора, в этом выпуске был рассмотрен рекомендуемый подход, позволяющий выбирать только из столбца селекторов строк: [# 6035](https://github.com/IgniteUI/igniteui-angular/issues/6035) и, более конкретно, в этом [примере](https://stackblitz.com/edit/angular-grid-cell-and-row-selection-sgjw5a) .
> 
> По сути, вы должны установить `[rowSelection]="'multiple'"`флажки выбора нескольких строк, `[cellSelection]="'none'"`а затем обработать `onRowSelectionChange`событие и отменить его, если оно вызвано щелчком конечного пользователя по ячейкам данных.
> 
> В версии 8.2 размер сетки обрабатывается [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) . Если половина высоты сетки пуста, это означает, что она, скорее всего, работает неправильно. Не могли бы вы поделиться своими файлами package.json / angular.json и polyfills, чтобы мы могли убедиться, что все выглядит правильно. Если вы можете воспроизвести проблему в образце стекаблица, это будет невероятно полезно для нас.
> 
> Кроме того, работает ли скриншот с Chrome на Mac?

Hello @ChronosSF. How can i disable ResizeObserver? With automatic recalculation, rendering is much worse.

**Comment by MayaKirova** [comment]
@ivanovla As the ResizeObserver is used to calculate actual size when grid has width/height set in % you can disable it by setting a specific width/height in pixels.

**Comment by ivanovla** [comment]
> @ivanovla As the ResizeObserver is used to calculate actual size when grid has width/height set in % you can disable it by setting a specific width/height in pixels.

@MayaKirova Thank you, I created an issue with a detailed explanation #6388
