### ISSUE TITLE
AOT Compilation Error related to igx-grid-paginator-theme inside theme.scss

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6080]
## Description  
When I perform a AOT build I receive an compilation error related to the igx-grid-paginator-theme inside theme.scss

What specific CSS needs to be changed inside my theme.scss so that my project will compile successfully as expected.

 * igniteui-angular version: 8.2.6
 * browser: Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

## Steps to reproduce  
1. Run command "ng build --prod"
2. Errors written to console (Screenshot below) 

## Result  
What is the actual result after following the steps to reproduce?
Screenshot of errors written to console
![igniteuit-compilation-error](https://user-images.githubusercontent.com/6993852/67723526-5823ab80-f9aa-11e9-9d9e-fd5ee7f685b3.PNG)

## Expected result  
What is the expected result after following the steps to reproduce?
No compilation errors

## Attachments  
Here is a screenshot of my theme.scss showing my $my-grid-paginator-theme
![my-paginator-theme](https://user-images.githubusercontent.com/6993852/67724218-52c76080-f9ac-11e9-964d-6549e77cbda2.PNG)

**Comment by hanastasov** [comment]
As of version 8.2.6, https://github.com/IgniteUI/igniteui-angular/releases/tag/8.2.6
 so all classes and theme names related to it have been renamed to exclude 'grid':

Since `IgxPaginatorComponent` is already a standalone component decoupled from `IgxGrid`, in 8.2.6 all classes and theme names related to it have been renamed to exclude 'grid':
igx-grid-paginator --> igx-paginator
igx-grid-paginator-theme --> igx-paginator-theme
my-grid-paginator-theme --> my-paginator-theme

See [release changelog](https://github.com/IgniteUI/igniteui-angular/releases/tag/8.2.6)
The igniteui-angular and igniteui-angular-samples repos will have be updated with the corresponding migration today, I will keep you notified.

**Comment by brookhutchinson** [comment]
Thank you for your response. Once I changed the CSS class names to the new CSS class names the issue was addressed.

**Comment by hanastasov** [comment]
Migrations with `ng update` added by #6091
