### ISSUE TITLE
igx-select doesn't close in Form

### ISSUE THREAD

**Issue by IvanMiandrusic** [IgniteUI/igniteui-angular#6088]
## Description  
When you open a igx-date-picker in "dropdown" mode and then you open a igx-select without closing the datepicker, this one will close, but the igx-selector won't. It stays open and you can't close it. 

 * igniteui-angular version: 8.2.2 to 8.2.6
 * browser: Chrome

## Steps to reproduce  

1. Open a igx-date-picker in "dropdown" mode
2. Without closing the datepicker, open a igx-select 

## Result  
The igx-select will open, but you couldn't close it anymore

## Expected result  
The datepicker closes when the igx-select opens. And then you can select a value from the select or simply close it.

## Attachments  
https://stackblitz.com/edit/igx-select-doesnt-close-6088

**Comment by IvayloG** [comment]
The issue is reproducible outside Form. I have attached a sample reproducing it.

**Comment by IvayloG** [comment]
The igxDatePicker and igxTimePicker focus management should be revised, as currently, the wrong behavior appears because the igxDatePicker input is focused after the overlay hide animation completes. 
- Focusing the input on outside click should be revised as a behavior.
- If the behavior will stay the same, the focusing should happen prior to the animation.
