### ISSUE TITLE
igx-row-island: Is it possible to get the rowData object used as the key in the igx-row-island?

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#6151]
I am currently working on a recursive, hierarchical grid, using the igx-hierarchical-grid component. 
I have a igx-row-island element where i insert a template containing igx-colum's. The template takes in a object, so i need to have the igx-row-island's object exposed so that i can insert it in the template (see picture).

![image](https://user-images.githubusercontent.com/43247999/68466972-b0ae4080-0215-11ea-9bd1-83b7e45525e0.png)

Is there a undocumented template for igx-row-island that i can use to expose the rowData? Is there any other way to expose the rowData? or finally, if there is no way to get the instance of the rowData object, do you guys have a way to deal with recursive hierarchical grids that does not use this approach? 

Thanks alot! 

 * igniteui-angular version: 7.3.20
 * browser: Chrome, any

**Comment by ChronosSF** [comment]
Hi,

row-islands are not content in angular terms. They are more like blueprints we internally create HierarchicalGrid components with. This is because we don't expose templating for the grid's body content so there is no way for users to declaratively create the grid's hierarchy.

With this said, there might be a way to achieve what you need but I am unsure what you mean by "recursive" hierarchical grid. Could you please elaborate? 

By the way, we are also currently in the later stages of development of a master-detail visualization for the grid that allows for assigning custom templates as "details" view for rows in the grid that users  expand to see. Maybe this functionality will be closer to what you need.

**Comment by VirtualisProject** [comment]
Hello @ChronosSF, and thanks for the reply :) 

Firstly, thank you the quick reply. The new Master-Detail feature is kind of what i am looking for. To elaborate on the "recursive" hierarchical grid:

As i've understand, there are no limitations to insterting row-islands inside a row-island, which would make the first role-island the parent for the child row-island. This is the behaviour i am looking for, the problem is that the rendering of child row-islands is only applicable if the data specified it. 

I've attached some pictures of the code below, which might help you to understand my request. 

Template:
![image](https://user-images.githubusercontent.com/43247999/68551013-8cff1c00-0408-11ea-8340-f2e5691f3f8d.png)

Mochup data:
![image](https://user-images.githubusercontent.com/43247999/68551023-b3bd5280-0408-11ea-921d-7f436ded592a.png)

**Comment by ChronosSF** [comment]
From what I understand you don't know how long that chain of children is beforehands?

Actually I don't think such self-referencing template is allowed in Angular in general? Have you tried it for something simple, such as chaing div elements?

In either case, I can see two options - either assume a maximum hierarchy depth and declarively create the hierarchical grid for that depth or create a [tree grid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/tree_grid.html) instead. This really looks like a tree grid scenario with the only caveat being that you have two seperate entities - report and unit. This means that you will have to process your data so that it uses a generic "children" property and have some empty columns for unit and some for report as the tree grid will have to define both entities' properties as a single column list.

**Comment by VirtualisProject** [comment]
Hey again @ChronosSF, 

No, i have not. I'm just doing some R&D for one of our upcoming features, and wanted to try self-referencing templates to see if it could solve my need. You might be right assuming it won't work at all. 

The issue with a tree grid is that i need to have seperate columb headers for the parent and child grid. 

I'll try to look into other options, thank you for helping me out :)

**Comment by VirtualisProject** [comment]
It seems that <igx-row-island> does not support native angular template outlets (see code below)

```
<igx-row-island [key]="'unitData'" [autoGenerate]="false">
    <ng-container *ngTemplateOutlet="unitHistoryHierarchicalGridTemp"></ng-container>
</igx-row-island>

<ng-template #unitHistoryHierarchicalGridTemp>
    <igx-column field="uuid" [resizable]="true" [hidden]="true"></igx-column>
    <igx-column field="process" header="{{'[|Process|]' | translate}}" [resizable]="true"></igx-column>
    <igx-column field="status" header="{{'[|Status|]' | translate}}" [resizable]="true"></igx-column>
</ng-template>
```

Is this a bug or by design? It would be nice to be able to work with the <igx-row-island> more dynamically. 

Also, it would be great if you could provide me with a barebone example of tree-grid approach you provided in the last message. 

Thanks alot!

**Comment by ChronosSF** [comment]
The issue with the outlet is similar to what is described in #4966 . Basically, we select the columns with ContentChildren selectors that don't work with your template, therefore the child grids' column lists are empty. We also dropped the idea of creating a column input to provide a way for users to pass columns in another way. If you check the issue, there is a workaround provided that creates column instances on the fly and adds them to the QueryList but I am not sure if that will be useful for what you are trying to achieve. Please, give it a look though.

As for the tree grid approach, I am attaching a sample that implements such a tree grid for a part of the mock data you shared earlier. The main thing to take from the sample is the pipe that changes the different entities' child keys into one that can be used as `childDataKey`. I hope this helps!

[qoynlaevvpg.angular.zip](https://github.com/IgniteUI/igniteui-angular/files/3841406/qoynlaevvpg.angular.zip)
