### ISSUE TITLE
Advanced filter dialog is moved with scroll in Edge

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#6219]
## Description  
Advanced filter dialog is moved with scroll in Edge

 * igniteui-angular version: 9.0
 * browser: Edge

## Steps to reproduce  

1. Open dev sample gridFiltering in Edge
2. Open advanced filter
3. Scroll the page

## Result  
Advanced filter dialog is moved

## Expected result  
Advanced filter dialog position should not be changed

## Attachments  

![AFScroll](https://user-images.githubusercontent.com/11463104/69730709-3e07f500-1131-11ea-8724-9fd4b5976d3b.gif)

**Comment by wnvko** [comment]
ESF is scrolling with the grid in GC because of the `perspective` set in `.content` class. If you remove this style ESF will not scroll in any browser. This is a known [limitation](https://github.com/IgniteUI/igniteui-angular/issues/4927) of `IgxOverlay`.
In Edge there is some flickering while scrolling - this is already logged in #4927
