### ISSUE TITLE
IgxSelectItemComponent throws an error when testing with Jest

### ISSUE THREAD

**Issue by jdpearce** [IgniteUI/igniteui-angular#6273]
## Description  

When trying to set the value of an `igx-select` component in Jest tests, an error is thrown : 

```bash
TypeError: Cannot read property 'trim' of undefined
```

## Steps to reproduce  

See repro repo at https://github.com/jdpearce/nx-igx-select-test

Run `ng test` to see [the failing test](https://github.com/jdpearce/nx-igx-select-test/blob/a265454f0af477dfe9a7e715630af53634c8cf05/apps/igx-select-test/src/app/select-form/select-form.component.spec.ts#L28-L31).

It seems to be due to this method : https://github.com/IgniteUI/igniteui-angular/blob/c268bcb9e8315aaaf559af7b3c6dc8d1f4665309/projects/igniteui-angular/src/lib/select/select-item.component.ts#L35-L41

**Comment by IvayloG** [comment]
This error is due to a Jest [limitation](https://github.com/jsdom/jsdom/issues/1245) regarding the use of innerText property under default [jsdom ](https://jestjs.io/docs/en/configuration.html#testenvironment-string)testEnvironment. It does not seem likely for this to be fixed soon. The primary issue is the fact that innerText leans on the layout engine for guidance, and jsdom has no layout engine. As an alternative "full" browser support, it may be an option to use [puppeteer](https://jestjs.io/docs/en/puppeteer.html#content).

We consider addressing this in the product.

**Comment by dafo** [comment]
While verifying this issue on the "master" branch, an exception that "PointerEvent is not defined" was thrown when executing the tests. This is related to this issue in "jsdom" - https://github.com/jsdom/jsdom/issues/2527
