### ISSUE TITLE
Igx-grid. Performance reducing after update to 8.2+ from 8.1

### ISSUE THREAD

**Issue by ivanovla** [IgniteUI/igniteui-angular#6388]
Hello.
I noticed that performance dropped a lot. After profiling, I noticed that the _shouldAutoSize function has this effect. This function is located at grid-base.component.ts.
I understand that this helps with resizing, but is called every time the data changes (@Input () data in IgxGrid). This causes the layer to recalculate. Why is this done if the window size does not change? My data is dynamically loaded from multiple requests with a large number of pages. Accordingly, for any user action, these requests and data are also sent via delayed download. Can you help me or i should create fork and resolve it by myself?
![image](https://user-images.githubusercontent.com/31878467/71519850-41c29f00-28ca-11ea-818f-db1975f29969.png)

This is my table:
![image](https://user-images.githubusercontent.com/31878467/71520424-12f9f800-28cd-11ea-8edb-659d67a7b9da.png)

Every click in next page paginator:
![image](https://user-images.githubusercontent.com/31878467/71520444-2f963000-28cd-11ea-88c8-ae3d36c10d3f.png)

![image](https://user-images.githubusercontent.com/31878467/71520451-3fae0f80-28cd-11ea-8080-be2f2cea8144.png)

Profile before update. 
Every click in paginator:
![image](https://user-images.githubusercontent.com/31878467/71520514-9a476b80-28cd-11ea-9bf4-b54125684b92.png)

Thank in advanced.

**Comment by MayaKirova** [comment]
@ivanovla 
If the issue you encounter is related to frequent data changes that trigger size recalculations the following PR may already have resolved your issue:
https://github.com/IgniteUI/igniteui-angular/pull/6322
This fix is included in the latest version - 8.2.14 . Please update to latest, test it and let me know if it solves your issue.

**Comment by ivanovla** [comment]
@MayaKirova 
Yes, after the update, the problem is gone. But there is still a question with virtual-scroll. In my case, the time of each task on the scroll event increased 2 times. What do you think about this?

**Comment by MayaKirova** [comment]
@ivanovla We have not identified major performance differences between those versions in a typical use cases. Could you share a sample with your grid and/or a performance profile during scrolling so that we can further investigate your scenario?

**Comment by ivanovla** [comment]
@MayaKirova 
This profilies after and before update: 

[Profilies.zip](https://github.com/IgniteUI/igniteui-angular/files/4039812/Profilies.zip)

**Comment by MayaKirova** [comment]
@ivanovla 
Thank you for the profiles. As the profiles show that the mouse wheel interaction is used could you let me know if this difference is specific to the mouse wheel or does it occur on any scroll operation (for example scrolling down so that the full view is changed)?

I tested this with a sample you have previously shared with both versions in the following stackblitz samples:
8.2.14 -> https://stackblitz.com/edit/github-jwzmss
8.1.1 -> https://stackblitz.com/edit/github-jwzmss-dumgax

When profiling I see that a single scroll handler, initiated from a single mouse wheel interaction takes ~ 70 ms on average in both versions. Profiles attached for reference: 
[Profiles.zip](https://github.com/IgniteUI/igniteui-angular/files/4041052/Profiles.zip)

Please test the samples on your side and let me know if you notice any differences.

If the sample does not exhibit the mentioned performance degradation then please share your full grid sample and/or the full grid definition so that we can investigate it further.
If you are comparing different versions of the product that do exhibit a difference, let me know which ones.

**Comment by ivanovla** [comment]
@MayaKirova 
This problem occurs with any scroll. I attached a profile in which the first half is initiated by the wheel, and the second scrollbar.
[ProfileScroll.zip](https://github.com/IgniteUI/igniteui-angular/files/4046150/ProfileScroll.zip)

In your example, I also observe a slight difference:

![image](https://user-images.githubusercontent.com/31878467/72162770-a0f8d700-33d3-11ea-921e-146d2847d24e.png)
![image](https://user-images.githubusercontent.com/31878467/72162849-ba9a1e80-33d3-11ea-9044-8f4b1999b5e0.png)

My old version is 8.1.0.
New version is 8.2.14

**Comment by MayaKirova** [comment]
@ivanovla  As there is always a slight difference between scrolls (even scrolls done on the same version in the same performance profile) it is rather difficult to determine whether there is a problem when comparing individual scrolls between the versions especially when the difference does not appear to be that big. Even if there is a performance degradation it does not appear to be major as a difference of 17ms would not really be perceivable. 

In any case when building your project in production, when all angular performance optimization are applied,  you should see a significant performance boost and shouldn’t notice any issues with scrolling.

**Comment by ChronosSF** [comment]
@ivanovla , let us know if you have any other questions or concerns!
