### ISSUE TITLE
Igx-tree-grid: Is possible to use loadChildrenOnDemand on child level?

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#6402]
## Question  
I am working on a recursive tree grid where i have the following structure: 

API response returns a list of objects. let's name these objects **a**. 
object **a** has a property to **a's** related reports, let's name this object **b**

At initial load, i will have a tree-grid behaviour, and i use the igx-tree-grid's input **childDataKey**="'b'" to display the child data rows. This works fine. 

Now for the part where i need some clearification. 
property **b** has a propery **a** within it's object, and i would like to be able to load these on demand. I tried to do this with using the following inputs on the igx-tree-grid:

[childDataKey]="b"
[loadChildrenOnDemand]="callbackfunction"
[hasChildrenKey]="a"

This enables me to view the initial children **b**. The issue arrives when i try to load one of the children that are set up to use loadOnDemand:

![image](https://user-images.githubusercontent.com/43247999/71729491-26aedc80-2e40-11ea-962a-41eb80e4cc5a.png)

I get this error message: 
![image](https://user-images.githubusercontent.com/43247999/71729590-6ecdff00-2e40-11ea-864c-52f31764695e.png)

Please note that i am sure that the grid's data input object is NOT readonly. 

So i would like one of the following:
1. Clarification if it even is possible to use both of the grid settings i am doing
2. Extend the loadChildrenOnDemand type declaration to include the parent object. This would allow me to identify which object is used and programatically determine what to return as the parent child.

Thanks alot for taking the time to read my issue, please let me know if you need any clearification.

 * igniteui-angular version: 7.3.20
 * browser: Chrome, any

**Comment by DiyanDimitrov** [comment]
@VirtualisProject 
1. It is possible to use the `childDataKey`, `loadChildrenOnDemand` and `hasChildrenKey` properties at the same time. However I didn't completely understand your data structure so I am not sure if you are using those correctly.
2. The `loadChildrenOnDemand` provides you the parentID as an argument so you can determine its children. If you have set `primaryKey` on the grid component, the parentID will contain the value of the primaryKey, otherwise it will contain the whole parent object.

In order to help you better could you provide a sample with some mock data that demonstrates your data structure?

**Comment by VirtualisProject** [comment]
Hello @DiyanDimitrov, thank you for the reply. 

1. That is good to hear, could you please provide me with a code snippet that uses my mockup data? 

so in the explaination over **A** == Unit and **B** == Reports. **B's** property "subUnit" is supposed to load on demand. 

```
export class Unit{
  guid: string;
  name: string;
  partNumber: string;
  serialNumber: string;
  firstSeenDate: string;
  reports?: Array<Report>
}

export class Report{
  guid: string;
  reportType: string;
  partNumber: string;
  serialNumber: string;
  revision: string;
  subUnits?: Array<Unit>
}

const EMPLOYEE_DATA: Unit[] = [
    { 
      guid: "sdfsdf",  
      name: "card ss335", 
      partNumber: "1234567", 
      serialNumber: "AABBCC",
      firstSeenDate: "12/12/12",
      reports: [{
        guid: "xcvxcvv",
        reportType: "UUT",
        partNumber: "1234567",
        serialNumber: "AABBCC",
        revision: "1",
        subUnits: [{
            guid: "sdfsdf",  
            name: "card ss335", 
            partNumber: "1234567", 
            serialNumber: "AABBCC",
              firstSeenDate: "22/12/12",
        }]
      },
      {
        guid: "sefsefvfvfv",
        reportType: "UUR",
        partNumber: "1234567",
        serialNumber: "AABBCC",
        revision: "1",
      }],
      },
];
```

**Comment by DiyanDimitrov** [comment]
Hello @VirtualisProject,

The tree grid renders only homogeneous data which means that you cannot have two different childDataKey properties which in your case are `reports` and `subUnits`. These two properties should have the same name. I have renamed them to `children` and I have created a stackblitz sample with your data https://stackblitz.com/edit/angular-1qyqoa. 

Please note that in the sample above the expansion indicators are shown for all records and after expanding if no children are provided the expansion indicator is hidden. In order to prevent showing expansion indicators for each row, you should add a boolean property to your data which provides information if a record has children or not prior to expansion. You should set the name of this property to the tree grid's `hasChildrenKey` property.

**Comment by VirtualisProject** [comment]
Hi again @DiyanDimitrov, 

Thank you for the clearification and the provided stacktrace, case closed! :)
