### ISSUE TITLE
igxDatePicker: Full-width characters can be entered when mode is set to ”editable” or “dropdown".

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#6427]
Description  
When igxDatePicker is editable with mode=”editable” or “dropdown”, full-width characters can be entered into the editor. It throws script errors since they are invalid characters.

 * igniteui-angular version: 8.2.14
 * browser: IE, Chrome, Edge, FireFox

### Steps to reproduce  

1. Run the attached sample.
2. Click into the editor part of igxDatePicker.
3. Enter some full-width characters.
4. Click outside of the editor to focus out.

### Result  
Script error is thrown:
InvalidPipeArgument: 'Unable to convert "Invalid Date" into a date' for pipe 'DatePipe'

### Expected result  
Full-width characters should not be entered.
[datePicker.zip](https://github.com/IgniteUI/igniteui-angular/files/4034240/datePicker.zip)

**Comment by PlamenaMiteva** [comment]
Hi mkamiishi,

I have tested the behavior you describe with the latest release version since there has been a refactoring of both date and time picker components. When I try to type in a wide character into the date picker in dropdown mode, it can not be entered and the script error is no longer thrown. The description of this issue suggests that this is the behavior you expect and yet I think the right behavior should be the one that allows the user to type in full-width characters into the picker's editor?

**Comment by mkamiishi** [comment]
Hi @PlamenaMiteva 
I tested the behavior with the current latest version to see full width characters are no longer accepted. That looks good. 
But I agree with you on that point that ideally the user should be able to input full-width characters. If the input is a valid date, the editor should accept it as a new value and ignore it otherwise.
It's the behave like igDatePicker .
https://www.igniteui.com/editors/date-picker-overview

**Comment by Lipata** [comment]
This issue is resolved in 12.0.0 and we have logged improvement in the date editors that will allow typing full-width characters #9568
