### ISSUE TITLE
Incorrect width calculation in igx-grid when printing

### ISSUE THREAD

**Issue by VirMaker** [IgniteUI/igniteui-angular#6466]
## Description  
Describe the issue.

 * igniteui-angular version: 8.2.0
 * browser: Chrome

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/virtualization.html#additional-resources (in chrome)
2. Press Ctrl + P

## Result  
Columns in the grid don't span entire preview window

## Expected result  
Columns in the grid span entire preview

## Attachments  
![image](https://user-images.githubusercontent.com/5204757/72350947-00d9d100-36a5-11ea-83b0-57fdd795bb97.png)

**Comment by 3phase** [comment]
Hi @VirMaker,
After a brief research, I conducted that the described by you issue is not a bug with our product. It occurs because that's the way Google Chrome (and Chromium-based browsers) perform the preview of the page that is about to be printed. 
Instead of previewing the page, as the name suggests, the browser will also shrink it in attempt to make a more accurate visualization. That shrink changes the width of the grid, triggering a new change detection cycle which on its side will resize the whole grid.
Please note, that that's not the case when using a different engine browser (as Edge, for instance). The print preview feature there would only show you the page as is, without modifying it in any way.
Just for your information, we have a topic on [Printing styles](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/printing-styles.html) that you may find helpful.
