### ISSUE TITLE
How to not show tooltip on a specific column header

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6541]
## Question  
How to not shown tooltip when a user hovers over a specific column header in IgxGridComponent?

 * igniteui-angular version: 8.2.15
 * browser: Google Chrome

**Comment by zdrawku** [comment]
This is expected behavior, the components should be accessibility compliant. Each of the `header` html elements has a `title` attribute and if you want to change that, you should again use `igxHeader` template as suggested [here](https://github.com/IgniteUI/igniteui-angular/issues/6515), without `title` attribute usage. 

For any further tooltip implementations I believe you will find our [documentation ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/tooltip.html)very helpful.

**Comment by brookhutchinson** [comment]
Can you please provide an example of how to not show a tooltip on a column?

I tried to click on the example links provided above and I did not see a "title" attribute being set to an empty string for a column in the grid. Help me understand what I am missing.
