### ISSUE TITLE
Incorrect behavior of the Select All checkbox in Excel Style Filtering 

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#6617]
## Description  
When a user types a value in the search input of the Excel Style Filtering, items get filtered. Then, if a user unchecks all filtered items (except for Select All checkbox), the Select All checkbox goes indetermined, instead of unchecked. Select All affect all items, even if they are filtered by the value in the search input. There is no way to act on the filtered items all at once.

## Steps to reproduce  

1.  The goal is to filter all users by the name containing "ste"
2. Trigger Excel Style Filtering
3. Deselect all items by unchecking the "Select All" item in the list of unique values
2. Type "ste" in the search input
3. It is not possible to select just the filtered items as "Select All" would check all items in the grid, independent from the search term typed in

## Result  
Finally, Select All goes indetermined instead of unchecked. 

<img width="865" alt="Screen Shot 2020-02-05 at 3 26 51 PM" src="https://user-images.githubusercontent.com/41998471/73854106-a0205d00-483a-11ea-811e-b39c4c697286.png">

## Expected result  
I expect to be able to select/deselect all filtered items at once when a search criterion is specified. 

## Solution
- When having a value in the search input, we will add not one but two items besides the unique ones
- First will appear: "Select All items" - affecting all list items
- Next will come: "Select Filtered Items" - affecting only the filtered list items

**Comment by StefanIvanov** [comment]
I would say the behaviour is correct and if we deselect all filtered items the state should be indeterminate. However, if we add another item that says "Select 2 Search Results" it can have behaviour as requested and let the end-user select/deselect only the filtered items in the search list.

**Comment by DaniMarinov** [comment]
@StefanIvanov I've updated the proposed solution yesterday, you can check it.

**Comment by williamverdolini** [comment]
Users expect that excel style filter should behave like Excel; any other behaviour (unless better) is considered often as a bug. Sorry if I seem rude, but sometimes some chooses could be wrong even if they are developed "by design".
This issue is a typical case of this perception. Here is how excel manage it:

![image](https://user-images.githubusercontent.com/6443266/89228471-f438ae00-d5df-11ea-9f01-124e8652a222.png)

the actual behaviour is very "uncommon" for an excel user. I think that the behaviour in the image above or your suggested solution is the expected one, the important thing is that, with some value in the search input, the item that says "Select all search results" should be automatically selected.

**Comment by williamverdolini** [comment]
@StefanIvanov do you have some updates about this issue? Any kind of roadmap to understand if you will work on it and when?

**Comment by StefanIvanov** [comment]
Here is the [roadmap](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md), and it should be updated soon with the planned work for our next milestone i.e. number 13 @radomirchev may want to consider this as he should be in the planning phase right now...
