### ISSUE TITLE
igx-grid - pre-select rows

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular#6653]
## Is your feature request related to a problem? Please describe.
I want to pre-select rows in a grid

## Describe the solution you'd like
a)  I would like to be able to pre-select rows as a property of the grid
b) I would like that the grid emits an event when the data is fully loaded so i can select the rows with selectRows

## Describe alternatives you've considered
Set a timeout to wait for the rows to be rendered.

## Additional context
Sample of pre-select rows https://stackblitz.com/edit/angular-qzbw2o

**Comment by kdinev** [comment]
Related #6974

**Comment by jackofdiamond5** [comment]
Hi @lalo-mx, we've created a PR, with the needed changes, that will allow you to bind to a `selectedRows` input property. So now you will be able to do something like this:
```html 
<igx-grid [data]="myData" rowSelection="multiple" primaryKey="MyColumn" [selectedRows]="myRowIds"></igx-grid>
```
This means that we don't need an event on which to attempt and select rows because now it can be easily achieved using property binding alone. Additionally, with the grid being virualized, meaning its data gets loaded in chunks, we don't really have a situation where all of the data has *just* been loaded.

Please feel free to add any additional notes/comments or ask us any questions about the feature.
