### ISSUE TITLE
Igx time picker not supporting for IE browser.

### ISSUE THREAD

**Issue by sjPrajwal** [IgniteUI/igniteui-angular#6702]
## Description  
igx time picker with angular framework not supporting for IE browser.
 * igniteui-angular version: 8.2.15
 * browser: IE 11

## Steps to reproduce  

1. open the https://www.infragistics.com/products/ignite-ui-angular/angular/components/time_picker.html in IE.
2.  try to open the demo session in IE.

## Result  
in IE browser input field looks empty, i think some css class missed for IE.

## Expected result  
in all the browser picker should work as some.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
@sjPrajwal when saying demo session, do you mean opening the demo in StackBlitz?

**Comment by sjPrajwal** [comment]
Hi @Lipata,

Yes and also i integrated the time-picker with angular framework and running in IE, its not working.
input fields are showing blank, if i selected time, i think this may be styles issues.

In all other browser, its working perfectly fine.

**Comment by Lipata** [comment]
Hi, @sjPrajwal.

Regarding StackBlitz, there is an [issue](https://github.com/stackblitz/core/issues/461) in their repository. Using one of the [following](https://www.infragistics.com/products/ignite-ui-angular/angular/components/time_picker.html) samples, run in IE11, can you describe in details what the problem is? If the problem is not visible there, can you attack an isolated demo? Thank you!

**Comment by sjPrajwal** [comment]
Hi @Lipata ,

please go through the below link.

https://xentryframeworkdiagnosis-int.corpinter.net/time-picker/.

integrated time-picker with angular framework, time-picker mask value and data is not visiabling in IE browser.

in all other browser its working fine.

**Comment by Lipata** [comment]
Sorry, @sjPrajwal I cannot open, the project you have sent, in any browser.

**Comment by sjPrajwal** [comment]
@Lipata , can you please open the project now.
https://xentryframeworkdiagnosis-int.corpinter.net/time-picker/

**Comment by Lipata** [comment]
@sjPrajwal, thank you for the update, now I see the problem. Can you share with me the time picker configuration, in order to be able to investigate the problem further? As I mentioned above, the best solution for us will be to send an isolated demo.

**Comment by sjPrajwal** [comment]
@Lipata, i follow the your documentation guidelines to add the ignite-ui-angular  to angular as mentioned in below link.

https://www.infragistics.com/products/ignite-ui-angular/angular/components/time_picker.html#usage 

configured steps.
Angular 8.
1). ng add igniteui-angular == added to angular app.
2). imported 
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { IgxTimePickerModule } from 'igniteui-angular';
3). then add below code component.
<igx-time-picker format="HH:mm" formControlName="endTime" name="endTime" id="endTime" mode="dropdown"
          [(ngModel)]="enquiry.endTime" (focusout)="endTimeFocusOutFunction(enquiry.endTime)">
        </igx-time-picker>
Thats it.

expect IE in other browser working fine.

**Comment by Lipata** [comment]
Hi, @sjPrajwal.

I'm attaching two projects and I hope you will be able to reproduce the issue in one of them because I'm not able to reproduce your issue on an isolated demo. Thank you for the assistance!

 - time-picker_8.2.x.zip - generated with our [igniteui-cli@4.4.0](https://github.com/IgniteUI/igniteui-cli/releases/tag/v4.4.0) and pointing to Angular 8 and [igniteui-angular@8.2.20](https://github.com/IgniteUI/igniteui-angular/releases/tag/8.2.20).
- time-picker_9.0.x.zip - generated with our [igniteui-cli@5.0.0](https://github.com/IgniteUI/igniteui-cli/releases/tag/v5.0.0) and pointing to Angular 9 and [igniteui-angular@9.0.2](https://github.com/IgniteUI/igniteui-angular/releases/tag/9.0.2)

1. Unzip the file.
2. In a console run `npm i`.
3. Then run `ng start -c=es5` (this will start the project so that it runs on IE11)


[time-picker_8.2.x.zip](https://github.com/IgniteUI/igniteui-angular/files/4225877/time-picker_8.2.x.zip)
[time-picker_9.0.x.zip](https://github.com/IgniteUI/igniteui-angular/files/4225879/time-picker_9.0.x.zip)

**Comment by sjPrajwal** [comment]
Hi @Lipata ,

i am unable to reproduce the issue from the attached file, and finally fixed the by comparing both the souce.

But in the IE only time-picker is auto focusing.

**Comment by Lipata** [comment]
Hi, @sjPrajwal.

Do you mean that when you select a value from the calendar and then press the OK button, in IE only igx-time-picker is focusing the input again? Whatever issue it is, if it is something different from the current one, please log it as a separate issue with an example. You can use the one that I have attached, or for bugs not related to IE, you can use StackBlitz.
