### ISSUE TITLE
Adding more than one pinned columns doesn't position them to the right of the already fixed column

### ISSUE THREAD

**Issue by 14520582** [IgniteUI/igniteui-angular#6823]
## Description  
I have a pinned column which always is first column.
And other columns are based on a array is loaded at runtime.
Ex: 
```
 columns = [
  {header: "Second", field: "name", pinned: true},
  {header: "Last", field: "age"}
 ]
<igx-grid>
   <igx-column header="First" field="'id'" [pinned]="true"></igx-column>
   <igx-column *ngFor="let col of columns"  [header]="col .header" [field]="'col .field'" [pinned]="col.pinned"></igx-column>
</igx-grid>
```
**Issue**: I get `columns` from api and first column is rendered before  `columns` shows up
 * igniteui-angular version: 8.2.20

## Result 
![Capture](https://user-images.githubusercontent.com/22111947/75312542-cf037f00-588c-11ea-923e-fb8308cbc343.PNG)

## Expected result  
![75312542-cf037f00-588c-11ea-923e-fb8308cbc343](https://user-images.githubusercontent.com/22111947/75761521-ce2a8b80-5d6b-11ea-811c-9956f372fc25.png)

**Comment by ChronosSF** [comment]
@14520582 , thanks for the report!

Unfortunately, for this to work correctly we need to trust the `@ContentChildren` query list's order. We don't do that currently because of issues with it when there are nested `ngIf`-s. To fix this without breaking other functionality, we need this https://github.com/angular/angular/issues/35807 issue to be fixed first (there are probably other reports in different cases of the same underlying Ivy problem).

I'll keep this issue open but for the time being I can only offer you a workaround. Instead of binding to the pinned prop of the columns coming from your backend, try subscribing to the `onColumnInit` event and use the pin method in the handler.

```html
<igx-grid (onColumnInit)="colInit($event)" >
</igx-grid>
```

```typescript
 public colInit(col: IgxColumnComponent) {
     if (col.field === "name") {
         col.pin();
     }
 }
```
