### ISSUE TITLE
igx-time-picker in dropdown mode, if we switch to next picker using keyboard tab, point to end of the field.

### ISSUE THREAD

**Issue by sjPrajwal** [IgniteUI/igniteui-angular#6827]
## Description  
If we switch to next picker using keyboard tab, it is point to end of the field.

 * igniteui-angular version: 8.2.20
 * browser:  all browser

## Steps to reproduce  
https://xentryframeworkdiagnosis-int.corpinter.net/time-picker/

1. open the link in browser, click on vin field and enter 17 character, then press keyboard tab cursor move to next field.
2. again press tab then move to start time field, observe the issue, cursor pointing to end of --:-- directive 

## Result  
Cursor pointing to end of --:-- directive 

## Expected result  
Cursor should pointing to start of --:-- directive 

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
Hi, @sjPrajwal.

You can set the `igxTextSelection` directive and it should select all the text on focus.

```
[igxTextSelection]="true"
```

You can check that [demo](https://stackblitz.com/edit/mask-select-all).

**Comment by sjPrajwal** [comment]
Hi @Lipata ,

If the value is already pre-filled with the time-picker field then` igxTextSelection` directive will work.

But if the empty field is there, in that situation it ll not work. I am facing the same problem.

i tried to manually change the position of the cursor in input focus method. But on-focus method not working in igx-time-picker.

please see the below code.

   <igx-time-picker format="HH:mm" [igxTextSelection]="true" formControlName="startTime" name="startTime"
          id="startTime" [(ngModel)]="enquiry.startTime" mode="dropdown"
          (focusout)="startTimeFocusOutFunction($event)" (focus)="onStartfocus($event)">
        </igx-time-picker>

focusout method is working, but not focus method.

Please revert me  back.

**Comment by Lipata** [comment]
This is bug in the component. [Here](https://stackblitz.com/edit/time-picker-text-select) is the demo that reproduces it.

**Comment by damyanpetev** [comment]
@sjPrajwal @Lipata Actually, the issue is with timing and perhaps the `igxTextSelection` directive.
Even if the directive could work on the time picker (it can't, see below) I'm not sure if it's listener will bet attached before the internal igxMask's. It (and thus the time picker) applies the mask focus and that needs to run before the selection can be changed.

Frankly, this is already built into the date picker (https://github.com/IgniteUI/igniteui-angular/issues/5658) and would make a ton of sense we do the same to the time picker and ensure the order while at it. Would that be good enough for everyone?

---
Explanation why the directive won't work:
- `igx-time-picker` is not a focusable element, the input field inside is
- `igxTextSelection` is intended to be applied to `<input` directly as it uses host bind, which is likely to never trigger on the picker, because:
- `focus` even by spec shouldn't propagate up, which is why it won't trigger
- `focusin/out` on the other hand do bubble

**Comment by sjPrajwal** [comment]
Hi @Lipata and Hi @damyanpetev ,

Can i expect any fix for this ?

**Comment by Lipata** [comment]
We are making some improvements in the editor controls and we are expecting them in 9.1.x in April. Along with them, we are fixing bugs, like this one, which we have planned also for 9.1.x, because improvements and fixes are affecting each other. @sjPrajwal thank you for contributing with your cases, we appreciate that!
