### ISSUE TITLE
Spreadsheet component don't lose focus clicking outside the grid

### ISSUE THREAD

**Issue by sddania** [IgniteUI/igniteui-angular#6834]
## Description  
If I try to put some vaule on cell of the spreadsheet component, the only mode to "commit" the value is to click another cell.
If i click outside the component the cell will not get the new value and the `workbookDirtied` will not be fired.
Check also on [Spreadsheet demos](https://www.infragistics.com/products/ignite-ui-angular/angular/components/spreadsheet_overview.html).

 * igniteui-angular version: 
        "igniteui-angular": "8.2.18",
        "igniteui-angular-core": "8.2.12",
        "igniteui-angular-excel": "8.2.12",
        "igniteui-angular-spreadsheet": "8.2.12"
 * browser: Chrome

## Expected result  
If i click outside the component the cell will get the new value and the `workbookDirtied` will be fired.

**Comment by radomirchev** [comment]
@igandrews could you update the status of the issue?

**Comment by igandrews** [comment]
Sorry. This isn't actually a bug. We cannot (and do not) assume that lost of keyboard focus means the edit should be committed as there can be scenarios where focus may need to be elsewhere. For example one might have an external menu (like how Excel has its Ribbon) that needs to manipulate the value or control how one exits exit mode. 

Also there are other ways to commit besides clicking on another cell or worksheet tab. One can use the keyboard - enter updates the active cell, ctrl+enter updates the entire selection, ctrl+shift+enter updates the entire selection creating an array formula if one is entering a formula. One can use the X and check buttons in the formula bar. In addition one can programmatically commit/cancel using the [executeAction](https://www.infragistics.com/products/ignite-ui-angular/api/docs/typescript/latest/classes/igxspreadsheetcomponent.html#executeaction) method and using one of the exit edit mode values such as [ExitEditModeAndUpdateActiveCell](https://www.infragistics.com/products/ignite-ui-angular/api/docs/typescript/latest/enums/spreadsheetaction.html#exiteditmodeandupdateactivecell).

**Comment by sddania** [comment]
@igandrews you didn't understand the issue, if change a value into the cell and you click into the spreadsheet, the cell will change the own value.
If you click outside the spreadsheet, the cell will not change the value, moreover workbookDirtied will not be fired.
I only need the workbookDirtied event will be fired when the user will click outside the spreadsheet component the cell if the cell value has been changed.
in excel when you loose the focus on the cell the cell will commit the changed value.

**Comment by igandrews** [comment]
I did understand what you described but as I said clicking outside the spreadsheet or any other method by which focus is shifted elsewhere is not assumed to mean that edit mode should be exited. WorkbookDirtied will fire when a change has been made but if the cell remains in edit mode then that change has not been pushed into the cell(s) so that event would not fire. Clicking on another cell or a worksheet tab within the spreadsheet does implicitly exit edit mode. With regards to excel, it is an application and can decide when it wants to exit edit mode. Even in excel though shifting of keyboard focus is not assumed to exit edit mode. For example you can be in edit mode in a cell in excel and click into say the font combo in the ribbon (which does result in a change to the HWND with keyboard focus) and it does not exit edit mode. If you want it to exit edit mode when focus leaves the element then you could handle focusout and use the executeAction method I mentioned.
