### ISSUE TITLE
Seamless lazy loading

### ISSUE THREAD

**Issue by jks-mkt** [IgniteUI/igniteui-angular#6859]
The current implementation of [Remote Virtualization](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html) (see second grid called "Remote Virtualization Demo" on this page) is problematic in terms of usability.
Scrolling down is very disturbing for the user, because the content is hidden from his view, even if the user scrolls a little bit.
I have explained the problem in detail in the screenshot below:
https://imgur.com/lDGAR7s

Solutions are possible, as can be seen on the internet:
- [Example 1 on Kendo](https://demos.telerik.com/kendo-ui/grid/virtualization-remote-data)
- [Example 2 on DevExpress](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/)

In the above, the transition to the next chunk is much better and is basically "seamless": there is no interruption for the user (when scrolling little by little, a few rows at a time; we accept that when jumping to the end of the grid all of a sudden, we need to reload everything, of course).

Therefore, please find a detailed concept of the proposed solution of a "seamless lazy loading" in the following mockup:
 https://imgur.com/V5ifJ5c

I believe this is a big miss from Ignite right now. Can you consider it and let us know about an implementation?

Regards,

**Comment by MayaKirova** [comment]
@jks-mkt 
It appears that you already have logged this question in our internal support case system at infragistics.com. In order to provide more visibility for this issue in case someone else is wondering about possible implementation of remote virtualization I will also share the same response here:

By design the igxGrid does not expose a default loading UI or default remote load functionality.
It currently exposes a single event – onDataPreLoad, which contains information in the event arguments on the current chunk of data that the grid should display and hence the developer, implementing the remote virtualization, should provide to the grid (presumably getting the data from a remote service).
It's up to the developer to then decide how much data to request and what loading indicator to display.
If he wishes he can pre-load extra data and cache it so that less requests are made.

Here is one such example for your reference:
https://angular-nwwbgt.stackblitz.io/
Here is also the related code, which you can edit and view on Stackblitz:
https://stackblitz.com/edit/angular-nwwbgt

This sample contains a simple example of pre-loading implemented in the remoteService that handles all requests.
Please refer to the remoteService: https://stackblitz.com/edit/angular-nwwbgt?file=src%2Fapp%2Fgrid%2Fservices%2FremoteService.ts

Note that there is an preLoadCount property, which determines how many records on top of the default displayed rows to pull from the remote service.
Those extra records are cached and used without the need for extra remote requests and loading as they are available in the service and can be directly set in the grid when needed. Once you scroll down over half of the extra records (so around record 15 for example) the next records are requested and stored in the cache.
This allows small scrolls (of 5 records or less) to not display a loading indicator as the data is pre-loaded once the defined threshold is reached. Larger scrolls will still trigger a separate loading for the new requested chunk of data and show the related loading indication (which in this case is a custom cell template).

As this implementation is entirely up to you to design and implement you have full control over the behavior. If you wish you can pre-load larger or smaller chunks or show a totally different loading indicator, hence customizing the user-experience of your application to best match your desired outcome.

Let me know if you have any questions.
