### ISSUE TITLE
Choose label -text for igxTimePicker

### ISSUE THREAD

**Issue by AvanadeCermak** [IgniteUI/igniteui-angular#6905]
## Is your feature request related to a problem? Please describe.
The default Timepicker tag (without Template) has all that functionality but no way to change the lable. And if I use Templates there is no way to get the same functionality the default Timepicker has.

## Describe the solution you'd like
Enable to choose the Labletext on TimePicker (like on DatePicker)
Or provide Timepicker -Template setup with the same Funktionality as the default TimePicker.

## Additional context
![image](https://user-images.githubusercontent.com/30624341/76530956-c27a4b80-6474-11ea-95f3-a74fd2a10fb5.png)

**Comment by valadzhov** [comment]
Hi @AvanadeCermak 
We've implemented a custom label functionality in the time picker which can be used in the following way:
`<igx-time-picker>
    <label igx-label>Custom label</label>
</igx-time-picker>
`
We chose to implement it this way in order for it to be consistent with the combo/select and also because it's more powerful than a text property.

It was also decided that the date picker's label will use this implementation.
All these changes will be present in our 10.2.0 release which is scheduled for October.
