### ISSUE TITLE
igx-grid Filter behavior

### ISSUE THREAD

**Issue by kijomito** [IgniteUI/igniteui-angular#6973]
I have the problem that the browsers behave differently. If I enter a comma in the filter of a column with the data type number in Chrome everything works. But in Firefox, IE, EDGE only an integer is adopted.

I'am using Windows 10 in German Language.

IgxGrid is set to German locale:
this.grid.locale = "de";

Version:
igniteui-angular 8.1.0

Browser Versions:
Edge: Version 80.0.361.69 and latest Windows 10 Version
Chrome: Version 80.0.3987.149
Firefox: 74.0

## Steps to reproduce  
1. Open StackBlitz Example on Chrome and enter a Filter on UnitPrice
2. Open StackBlitz Example on FireFox and enter a Filter on UnitPrice
3. Open StackBlitz Example on Edge and enter a Filter on UnitPrice

## Result  
Filter behavior on number Field
On Dot Input:
Edge resets Filter.
Chrome resets Filter.
Chrome works with Comma!
Firefox only work with Dot in Filter ignores Comma.

## Expected result  
All Browsers working like Chrome with Comma for German Language.

## Example on StackBlitz
https://stackblitz.com/edit/angular-xp1hw2

**Comment by dkamburov** [comment]
@kijomito You should note that different browsers behave differently with input `type="number"`. You can play around with [that sample](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number). Some of the browsers allow invalid characters, others don't.  I also found this issue for Firefox - https://bugzilla.mozilla.org/show_bug.cgi?id=1199665. There might be one for Edge too.

I believe that you have a point that the value should not be reset even if not valid, so we would try resolving that.

**Comment by MayaKirova** [comment]
@kijomito Just to add some clarification on what we can and cannot resolve in relation to this.

We can prevent the input from being reverted if an invalid value is entered. Hence you will be able to enter values with the separator in Edge/Firefox as well – ex. “20,75”.
However, we cannot prevent browser specific issues with regional separators being considered as invalid for inputs with type number.

As Deyan mentioned, FireFox has issues with how it parses regional specific separators (like “,”) in numeric inputs.
Due to this if you type in “20,75” in FireFox for filtering, only the valid part of the number will be applied to the filter – “20”.

We will document this as a limitation to prevent future confusion. The related issue is: https://github.com/IgniteUI/igniteui-docfx/issues/1880

**Comment by ChronosSF** [comment]
The fix causes issues and a new fix will be proposed in the future.
