### ISSUE TITLE
Two-way data binding of igGrid does not detect changes correctly.

### ISSUE THREAD

**Issue by humblepie** [IgniteUI/igniteui-angular#70]
The change detection routines are making assumptions on the count of the array of old vs new records to determine whether or not inserts or deletions occurred.  This is improper as an insert and deletion may have occurred within the same cycle.

**Comment by kdinev** [comment]
@humblepie Can you provide us with an example of when such an issue is reproducible?

**Comment by humblepie** [comment]
The example I am providing actually demonstrates multiple issues with 2 way data binding.

- **Add and Remove first item button** will demonstrate the issue originally described.
- **Add button** demonstrates issue with unbound column using formula not being rendered when using grid.renderNewRow to add the new row.  **Status column is not being rendered.**


[igniteui-angular-iggrid.zip](https://github.com/IgniteUI/igniteui-angular/files/300479/igniteui-angular-iggrid.zip)

**Comment by kdinev** [comment]
@humblepie thanks a lot for the sample.

@mpavlinov who can take this and investigate?

**Comment by dkamburov** [comment]
This issue is reproducing due to the fact of how both `ng-click` and `ig-grid` were designed. 

1. `ng-click` wraps its function in `$apply`
2. change detection mechanism of `ig-grid`

Change detection mechanism relies on the length of the data to figure out, whether the change is adding, deleting or updating a record. And if both of the changes - removing and adding a record are done, the grid actually considers this as an update(since the length of the new and the old data is equal).

At some point we may improve this changes recognition. But for know you have to use custom click directive, which won't trigger the digest cycle. This way you could trigger the digest cycle for each change and make the grid treat them correctly.  I modified the attached sample to demonstrate, what I mean.

[igniteui-angular-iggrid-modified.zip](https://github.com/IgniteUI/igniteui-angular/files/341433/igniteui-angular-iggrid-modified.zip)
