### ISSUE TITLE
igx-icon problems when using SVG and OnPush

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#7024]
## Description  
When using OnPush I can't see the icons until some change occurs in the component that is using them.

 * igniteui-angular version: 9.0.1
 * browser: FF & Chrome (any afaik)

## Steps to reproduce  

Example at: https://stackblitz.com/edit/igx-icon-onpush
 - Start from igx-icon + svg sample  (works)
 - Use changeDetection OnPush (stops working)
 - Move icons initialization code to App constructor, still not working.

## Result  
Can't see the igx-icon instances

## Expected result  
Icons should load

**Comment by pmoleri** [comment]
My understanding from the Icon code is, that because the Icon is not yet cached it's choosing to render an empty template (`#noLigature`).
I think that at that point the Icon component should subscribe to a new observable in iconService to wait for that Icon to exist, so it can switch to the correct template once the icon is loaded.

**Comment by rkaraivanov** [comment]
@pmoleri 
Unfortunately, that won't fix the scenario where the parent has OnPush change detection. While the icon will update its template when the "icon value" is loaded (Http request), you still need to trigger the change detection cycle from its parent downwards, otherwise the UI won't update. 

I do however agree that we should expose an observable on the icon service itself, when an icon is "loaded" into the service. In case of the sample, you would need to subscribe in the parent component, (either through async pipe or in the typescript file itself).

**Comment by pmoleri** [comment]
Does that mean that change detection always need to happen in the topmost parent?
My understanding is that in child can update itself while it's in an OnPush hierarchy.
i.e. igx-icon should be able to call change detection on itself.

**Comment by pmoleri** [comment]
I updated the [sample](https://stackblitz.com/edit/igx-icon-onpush?file=src%2Fapp%2Fsvg-icon-sample%2Faware-counter.component.ts) with an example of this.
Even when the component is OnPush, if I add a child component that subscribes to an observable, the child is able to update itself and as a side effect everything else on the parent also updates.
