### ISSUE TITLE
Support for nested properties

### ISSUE THREAD

**Issue by katyFaulkner** [IgniteUI/igniteui-angular#7083]
Currently the data grid only supports flat data. 

You can currently use cell templates for more complicated data but then filtering and sorting are not supported so that isn't really viable where you just want to pull through 'normal' data. 

You could flatten the data first but if you are using the grid for editing data then this becomes a bit complicated as you then have to then try and transform it back to its original shape before submitting it back.

It would be good if instead it could support nested objects. So for example for an object like:
{teamName: 'team1', teamId: 1, reportingDetails: { area: 'TC', region: 'LDN'}, region: 'IND'}
You could use field in the column as reportingDetails.area
This should support filtering, sorting, cell edits etc

**Comment by kdinev** [comment]
Since we don't want to change the structure of the original data that is provided, because this will break all interactions with a backend service with a Entity model of any kind, we have exposed extensibility for sorting/filtering/grouping for such scenarios, where custom strategies can be provided to the columns that have the complex data objects bound to. Also the exposed cell and cell editing templates solve the issue of visualizing and editing the data.

**Comment by katyFaulkner** [comment]
Sorry are you saying you have added that or it already exists? Because I can't see how to make the sorting/filtering/grouping work for complex data. Also I wouldn't expect the original data to be altered either but couldn't the grid support complex keys for fields? Other grids like ag-grid have the feature. I would think it would be a pretty common request. So couldn't a standard handler be built in for that?

**Comment by kdinev** [comment]
@katyFaulkner For the scenarios where a single column is bound to an object, we've exposed a way to write a custom value resolver for each of the features utilized by the grid, in the form of a strategy pattern exposed through each of them. E.g. [sortingStrategy](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcolumncomponent.html#sortstrategy).

@DiyanDimitrov created custom value resolvers for Filtering/Sorting for the IgxTreeGrid, which inherits from the same base, so he can give you an example of how this can be achieved with just adding a single method to the [default strategy](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/defaultsortingstrategy.html)

It's a really good idea to just expose a general value resolver, thought, instead of to have a resolver provided to each feature.

**Comment by katyFaulkner** [comment]
Having a general value resolver would be great. If you were to pick up that as a feature what sort of timeframes would it be available in? Just a rough idea would be great so I know whether I could wait for it or need to try the above approach with providing it to each strategy.

**Comment by user42istheanswer** [comment]
I would also like to see this implemented. I constantly run into issues where it would be wonderful to not have to implement custom filters or sorters for every field. It would be great if every feature of the grid just worked with nested data.

The latest one I've ran into is trying to use the "Excel style filter" for the grid with nested data. All it sees is the top level object and I can't see how it exposes anything I can apply a custom filter to.

As @katyFaulkner said there isn't any need to alter the underlying data and other grids have this feature.

**Comment by radomirchev** [comment]
@katyFaulkner , the feature request is in the list for the current milestone. You could follow the milestone progress on the [Roadmap board](https://github.com/orgs/IgniteUI/projects/122) or in the [Roadmap file](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md)
