### ISSUE TITLE
igxMask always set the symbol '9' as a fillable spot 

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#7089]
## Description  
If the mask is set to "'(966) #### ####'" when you enter into edit mode the symbol '9' is always treated as a fillable spot.

 * igniteui-angular version: 9.0.1 

## Steps to reproduce  

1. Run the sample
2. Click on the input

## Result  
The digit 9 is replaced as fillable spot.

## Expected result  
To be able to set some indication in case you want the symbol '9' to be treated as a digit, not special symbol and after the input is clicked to looks like (966) _ _ _ _  _ _ _ _.

## Attachments  
https://stackblitz.com/edit/angular-9kocto

**Comment by damyanpetev** [comment]
Since `9` is one of the [standard mask characters](https://www.infragistics.com/products/ignite-ui-angular/angular/components/mask.html#supported-built-in-mask-rules) that specifies a digit input, that's sort of the expected behavior. As the Mask directive currently doesn't support escaping mask characters, we'll mark this as a feature request for that.

PS: I understand a decent workaround in this case would be using a prefix, though that'd exclude it from selection.

**Comment by kdinev** [comment]
@damyanpetev There's a particular issue with using the prefix, and this is that the prefix is not included in the `ngModel` value or your form value and thus is not sent to the server. If the prefix is appended on submit to the value, then it's shown in the editor as both prefix and the start of the value. Character escaping should be implemented in the mask.

**Comment by damyanpetev** [comment]
@kdinev I agree, that's why the issue is still open :)
Whether the static part is part of the value is based on use, but fact is atm there no choice for that (think data mode of old) without a custom handler on submit and escaping chars will solve that.
