### ISSUE TITLE
[filtering row] when adding faster filtering conditions, chips disappear from the view

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#7175]
## Description  
when adding faster filtering conditions, chips disappear from the view

 * igniteui-angular version:
 * browser: 9.0.x +

## Steps to reproduce  

1. Open filtering sample
2. Open any filtering row
3. Start typing and pressing enter faster till chips disappear

## Result  
All chips go strongly left

## Expected result  
Chips should stay and keep their order.

## Attachments  
![chips-desappear](https://user-images.githubusercontent.com/7037740/79988296-269e1f80-84b7-11ea-986b-742e138fd12b.gif)

**Comment by DiyanDimitrov** [comment]
The implemented fix does not resolve the issue completely. There is still some offset to the left, but it is smaller than before. The reason for this is that the `chipsArea` reports a larger width than actual. Unfortunately, we couldn't find the reason for this.

We have agreed that the current fix is good enough since the issue doesn't seem to be a common scenario.
