### ISSUE TITLE
when we should emit groupingExpansionStateChange

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#7218]
## Question  
When we should emit groupingExpansionStateChange? 
As far as I understood the event corresponds to the interaction of the expand/collapse rows which means that the event should not be triggered when we are clearing the grouped columns, as I saw that we have other events for that purpose **groupingExpressionChange** and **onGroupingDone**.

The other note is that the event is emitted only when the column group is cleared but not when it is added to an expression.

 * igniteui-angular version: 9.1.x
 * browser: all

**Comment by ChronosSF** [comment]
AFAIR, an expansion state is added if it differs from the default. This means that if an unrelated action clears a state it changes it hence the event fires. If you just group a column, no expansion state is created because it doesn't differ from the default and there is ***no change*** in the  expansion.

**Comment by ChronosSF** [comment]
Are you trying to solve a customer case or? Any additional context for the question?

**Comment by Aleksandyr** [comment]
@ChronosSF I'm just trying to set up a sample for kb navigation so I use some of the mentioned events above. Actually we were looking with @rkaraivanov in that matter and it was confusing for both. 
Also, that behavior is not specified anywhere.

**Comment by Aleksandyr** [comment]
Actually the problem here is the bizarre behavior. Because as I stated above **groupingExpansionStateChange** is fired actually when we group a column but not when we ungroup it.

**Comment by ChronosSF** [comment]
You probably mean it's the other way around as I tested it and it fires when you ungroup but doesn't fire when you group.

It's a change event meant to implement a banana in a box two-way binding scenario. As such it's implemented correctly - it gets fired when the setter is hit with a value that is different than the previous one. Of course since the value is an object, it only checks for a different ref.

Now, whether or not we correctly change the ref internally is arguable. When we group, no expansion change is required, the value remains intact, the setter is not hit and the event doesn't fire. 

When we ungroup, the expansion states for the column should be cleared so that subsequent groups would be on a clean state. Here, the issue is that we filter the collection which returns a new instance and therefore hits the setter and emitter. What we can do is check if the filter produces the same result i.e there haven't been any expansion states for the column being ungrouped and not set the new instance in this case so that the event doesn't fire. Feel free to convert this to a bug and we'll handle it.

**Comment by Aleksandyr** [comment]
@ChronosSF Thanks for the brief explanation.
