### ISSUE TITLE
Horizontal virtualization

### ISSUE THREAD

**Issue by SebastianCarreira** [IgniteUI/igniteui-angular#7241]
## Question  
We have an issue with "horizontal virtualization" using the **IgxGrid component**. We need to disable the horizontal virtualization; if we set the width = null, it is disabled as expected, but the scrollbar is not visible (which is expected too according to the documentation)
We "disabled" the virtualization for the vertical scrolling by chaging the **verticalScrollContainer.igxForTotalItemCount** value. Is there a way to disable the **horizontal virtualization** without losing the horizontal **scrollbar**?
 * igniteui-angular version: 9.x.x
 * browser: Any

**Comment by ChronosSF** [comment]
The grid is not designed to work without virtualization. What are the issues you are having with it that force you to think about disabling virtualization in the first place?

**Comment by SebastianCarreira** [comment]
Hi! 
We use the grid to dynamically add a group of fields (row) to a form. If the fields are virtualized, the validation of the form will ignore them because they are not present in the DOM. 
We know that the IG grid was not designed for this approach but the virtualization was the only obstacle that we had to get it working.

Thank you for your time!

**Comment by ChronosSF** [comment]
I see, virtualization would certainly be problematic in this case. Have you tried setting width to null but wrapping the grid in a div that has overflow: scroll, so that you can scroll to see all the columns?

If you don't need features like hiding or moving columns, you could also put all your grid columns into a single column layout (check [this](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/multi_row_layout.html) sample). Column layouts are never separated in virtualization frames, so while they have a different purpose, you could use them to essentially disable horizontal virtualization for a set of columns.

**Comment by SebastianCarreira** [comment]
Nice! We'll try it and let you know, but sounds like a good approach!

We already tried wrapping the grid in a container setting the width to null but in this case the "pin" section and the verticall scrollbar are not visible at the same time if the grid is too wide (the grid should be horizontally navigated).

Thanks a lot!

**Comment by ChronosSF** [comment]
Pinning is one of the features that work on column layouts instead of columns when layouts are used. So you can pin a whole layout but not the columns in it separately. If your pinning is static, you can just create a seperate layout just for the pinned columns. If it is dynamic, you may need some additional code the swaps columns between the layouts. Let me know if it is the latter so I can help.
