### ISSUE TITLE
tabulation does not have the desired behavoiur

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#7275]
## Description  
When there are more than one grid expanded and try to tab through them the sequence gets totally messy

 * igniteui-angular version: 9.1.x
 * browser: all

## Steps to reproduce  

1. Open some of the hGrid dev samples
2. Expend 1+ grids
3. Try to tab and shift+tab through them and observe the sequence

## Result  
The tabulation skips the grids that are inside and goes directly to the tfoot of the grid

## Expected result  
The tabulation should go thorough each new grid thead and body one after another.

**Comment by MayaKirova** [comment]
@Aleksandyr 
This does not seem to be specific to the hierarchical grid.
It can be reproduced in any grid where the next focusable element is not fully in view and requires scroll to come fully in view.
Here’s an example with a grid that has a tabbable buttons templated in a cell:
https://stackblitz.com/edit/angular-pxhou6

Steps to reproduce:
1.	Scroll to the middle so that the last row’s button is half-visible.
2.	Click on the next-to-last row’s button to focus it.
3.	Hit tab.

Result: Next button that should take the focus is scrolled in view but is not focused.
![tab](https://user-images.githubusercontent.com/10397980/81085467-ec457100-8eff-11ea-9eb8-a816bc637c2e.gif)
