### ISSUE TITLE
igDataChart's visibility of axes, series, and chart itself cannot be controlled by angular’s ng-if condition.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#73]
[CASE-23805_.zip](https://github.com/IgniteUI/igniteui-angular/files/329502/CASE-23805_.zip)

**Comment by dkamburov** [comment]
Yep, that's a correct behavior, `ng-if` is removing and creating DOM elements and it is not going to $compile the ng directive for you. Therefore `ng-if` is used for expressions mainly, it could work if you compile manually the directive though. As of the `ng-show`, it doesn't remove the elements from DOM, but only hides them. That's why it works.



The answer of both is no. These axes and series (and all of the nested options for all of the widgets) are **not** ng-directives. They are just a declarative syntax and are used only for declaration of the widget.

**Comment by mkamiishi** [comment]
Thank you for the explanation.
