### ISSUE TITLE
When there is master details rows scrollTo does not work properly

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#7300]
## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/angular-welvfv)
2. Try to navigate with the buttons to the row 20 or 21

## Result  
The row is not scrolled in to the view.

## Expected result  
The row should be scrolled in the view.

## Attachments  
This bug can also be reproduced and in the following test: 'Should navigate to the correct row/cell when using the navigateTo method in a grid with expanded detail views'.

**Comment by 3phase** [comment]
I think that the issue is with the `igxTabs` and more specifically with the fact that when the tabs initialize their content is not yet rendered in the DOM. After scrolling, the size of the content changes twice - once when the tabs initialize in the template and then a second time when their content is rendered. Unfortunately the `igxForOf` cannot anticipate multiple content size changes that occur inside the user template in order to adjust the scroll position. It currently renders and adjusts the scroll position once - reaching the desired index. However if any content size changes occur after this they will not be taken into consideration as part of the `scrollTo` logic.

This issue can be worked around if the tabs have some explicit size set, so that the delayed loading of the content does not affect their size. You could observe this in the following [Stackblitz sample](https://stackblitz.com/edit/angular-welvfv-k5bvbq).

@ChronosSF, @rkaraivanov, do you think if we should log that as a limitation?
