### ISSUE TITLE
Extension of Navigation Bar component for advanced scenarios 

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#7377]
For the needs of the App Builder, we need advanced navigation bar scenarios, not only the basic mobile ones. It is needed:
1. To be set up three general zones - left, middle, right
2. Option various components to be added in each of these zones (e.g. text, avatar, action icons, dropdown, buttons, SVG logos, navbar items etc.)

The extended navbar should cover scenarios like these:
![b3964133-3943-4d86-aec0-1a25e3c95e88](https://user-images.githubusercontent.com/41998471/82452404-e0d57680-9ab7-11ea-9183-218767d7705e.png)
![f364278c-3bd3-43cc-abd2-c575e59f31ae](https://user-images.githubusercontent.com/41998471/82452406-e16e0d00-9ab7-11ea-98a7-184ec42728da.png)

![719a47b9-b6d7-4e7c-9415-f0453f31f7fa](https://user-images.githubusercontent.com/41998471/82452398-df0bb300-9ab7-11ea-8a2d-51c373141378.png)
![ae9ee3c2-fd2a-4627-b063-002274ae2870](https://user-images.githubusercontent.com/41998471/82452401-e03ce000-9ab7-11ea-96d6-78e61ad9d248.png)

**Comment by StefanIvanov** [comment]
After talking to @ig-georgeA we noted also the following desirable scenarios
<img width="972" alt="Screenshot 2020-05-20 at 15 47 27" src="https://user-images.githubusercontent.com/1702064/83734197-582e0d00-a657-11ea-8aae-71aa6ef86cc9.png">

**Comment by DiyanDimitrov** [comment]
We have decided to expose a new directive for re-templating the title area called `igx-navbar-title`. 
By re-templating the title area you will be able to split it to several zones.

We will rename the `igx-action-icon` directive to `igx-navbar-action` since the old name is too generic.

We will add new selectors for the `igx-navbar-title` and `igx-navbar-action` which will be `[igxNavbarTitle]` and `[igxNavbarAction]`.
