### ISSUE TITLE
Virtualization for igx-hierarchical-grid parent grid

### ISSUE THREAD

**Issue by akhilgundam** [IgniteUI/igniteui-angular#7412]
Implemented Virtualization for igx-hierarchical-grid and facing issues.

The implementation of Virtualization for igx-hierarchical-grid I found on the website is only for the child grid(on the expansion of row) but not for the parent grid.

But as per the requirement I need to implement virtualization for the parent grid, not for the child grid.

By taking the reference from igx-grid virtualization implementation
(https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html)
 I implemented virtualization for igx-hierarchical-grid and facing issue with scrolling as specified below.

When I tried to look into the last row child grid that is when I click on the expand button I need to look into the child grid, in order to look into the child grid I need to scroll down please refer to the attached image.

![image](https://user-images.githubusercontent.com/22490534/83007453-55b52d00-a031-11ea-9d57-8e9cb664edd9.PNG)

Since I have added virtualization to the grid and when I tried to scroll down to look into the child grid (last rows) the whole page is refreshed due to virtualization. 

Please provide us the solution.

Thanks,
Akhil

**Comment by ChronosSF** [comment]
@radomirchev 

Just for clarification, this is a feature request for enabling **remote** virtualization for the hierarchical grid.

All igx grids are virtual, but only the flat grid may be configured for remote chunk loading currently.

**Comment by ChronosSF** [comment]
@akhilgundam , with the major release 10.0.0 we've tinkered with the hierarchical grid so that it may be used in a remote virtualization scenario using a custom data service. You can check how it works in the following dev sample: https://github.com/IgniteUI/igniteui-angular/tree/master/src/app/hierarchical-grid-remote-virtualization . To run it just call `npm start` in a clone of the repository using the master branch and navigate to the `Hierarchical Grid Remote Virtualization` sample from the left-side menu.
