### ISSUE TITLE
IE11 memory leak with igxGrid

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#7419]
## Description  
The grid is consuming memory based on how the source data is updated.

 * igniteui-angular version: 9.0.13
 * browser: IE11

## Steps to reproduce  

1. Download and open the sample
2. run `npm install` and `npm run build:prod`
3. use a tool like `lite-server` to serve the produces app from dist/GridMemoryLeakApp

```cmd
npm i lite-server
```
```cmd
cd dist/GridMemoryLeakApp
```
```cmd
lite-server
```
4. Click `leak` button and open the memory profiler.
5. When the maximum screen lines limit is reached (50) the leak will be noticeable.

## Result  
Memory usage increases 

## Expected result  
Memory usage to remain unchanged 

## Code snippet

```ts
addNewTrap(trap: any) {
    if (this.memoryLeak)
      this.gridData.unshift(trap); // add items to the beginning of the array
    else
      this.gridData.push(trap); // add items to the end of the array
    while (this.gridData.length > this.maxScreenLines) {
      if (this.memoryLeak)
        this.gridData.pop(); // remove items from the end of the array
      else
        this.gridData.shift(); // remove items from the beginning of the array
    }
    // this.grid.markForCheck();
  }
```

## Attachments 
[GridMemoryLeak.zip](https://github.com/IgniteUI/igniteui-angular/files/4689588/GridMemoryLeak.zip)
![IEProblem1](https://user-images.githubusercontent.com/11193764/83038131-48a23900-a045-11ea-8a3b-963fb5442f88.JPG)
![memoryLeak](https://user-images.githubusercontent.com/11193764/83038147-4c35c000-a045-11ea-9175-b42a7bd13bad.gif)

**Comment by MayaKirova** [comment]
Using the three snapshot method via IE memory profiler no memory leaks were found.
There is no apparent memory usage increase when observing the non-garbage collected  objects and when comparing object between snapshots no ignite ui related elements seem to be left off. The count of igniteui objects also remain the same.

Snapshots:
![3snapshots](https://user-images.githubusercontent.com/10397980/85381878-15b96b00-b547-11ea-868b-557d871f883d.PNG)

Snapshot Comparison:
![Object_comparison_1vs2](https://user-images.githubusercontent.com/10397980/85382056-400b2880-b547-11ea-8dfe-a2fe4523b293.PNG)
![Object_comparison_2vs3](https://user-images.githubusercontent.com/10397980/85382078-44374600-b547-11ea-8993-110a241a6f73.PNG)

IgniteUI objects:

![snapshot1-igx-objects](https://user-images.githubusercontent.com/10397980/85382132-50230800-b547-11ea-8283-19d0d4633f82.PNG)
![snapshot3-igx-objects](https://user-images.githubusercontent.com/10397980/85382151-53b68f00-b547-11ea-85cb-00a61f8078d8.png)


While the IE’s process does take up more space as time passes the reason does not seem to be a memory leak on our side. Most probably this is a third party issue related to the way IE manages its own memory while the process constantly requires a high CPU usage (since the data is constantly changed over a small period of time).

As this is not something we can address in our product I’m closing this as a third party issue.
