### ISSUE TITLE
Ignite UI for Angular Licensing Clarification

### ISSUE THREAD

**Issue by Nick-Angel** [IgniteUI/igniteui-angular#7420]
## Question  
Hi all,

I'm a bit confused about the licensing of this library.
Both the README and the LICENSE file cite the Apache 2.0 license but later both say _This is a commercial product, requiring a valid paid-for license for commercial use. This product is free to use for non-commercial applications, like non-profits and educational usage._
This seems at odds with the Apache 2.0 license, unless the intent was to offer dual licensing.
I would like to better understand the conditions under which users or companies can use this library, specifically in commercial applications.
I have installed igniteui-angular through npm and there have been no trial watermarks. Can a commercial application use this library in the manner I just described, since such usage would be compliant with the Apache 2.0 license?

Thanks,
Nick Angelastro

 * igniteui-angular version: 9.0.15
 * browser: NA

**Comment by kdinev** [comment]
Hi @Nick-Angel,

The product has been on a dual-licensing model, since it was launched. The Apache 2.0 license is valid for non-commercial usage. For commercial usage, you need to obtain a paid-for commercial license for each developer that uses the product. For more information on pricing and how to obtain a commercial license, you can refer to the pricing section on the [Ignite UI for Angular product page](https://www.infragistics.com/products/ignite-ui-angular).
