### ISSUE TITLE
String column with non-defined value in the underlying data source shows "undefined" in edit mode

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#7441]
## Description  
When string column has non-defined value in the underlying data source and it enters edit mode the default value for its editor is" undefined".
 
## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/igx-grid-udefined-string-value?file=src%2Fapp%2Fgrid%2Fdata.ts) sample
2. Enter edit mode for "Name" column of the third row. 
3. Observe the editing provider`s default value

## Result  
The default value is "undefined".

## Expected result  
The default value should be empty.

## Attachments  
![Capture](https://user-images.githubusercontent.com/13034836/83277608-feeb5700-a1da-11ea-883f-5fca424d5007.PNG)

**Comment by damyanpetev** [comment]
Reproducible with just bits of the relative grid edit template bits:
```ts
public editValue = undefined;
```
```html
<igx-input-group>
    <input igxInput [value]="editValue" />
</igx-input-group>
```
Side-effect of setting the native input value to `undefined` which gets stringified. Keep in mind though, the reason for that is because `undefined` is **not valid** input value in general (same goes for `null` but the spec allows it for [legacy reasons](https://heycam.github.io/webidl/#LegacyNullToEmptyString)). That means that the same is reproducible with just the native input:
```html
<input [value]="editValue" />
```
This can be hit by users with custom edit templates just as well. I'm fairly certain we don't want to mess with the edit value to avoid modifying the underlying data source for no reason and normally, to leverage such data binding `ngModel` would be used (except in the grid where we avoid it for the extra dep it brings).

Either way, I'm quite alright with fixing this in the input directive, since we have control over the setter and I don't see a case where the invalid handling of `undefined` would be useful to keep.
