### ISSUE TITLE
igx-grid remote sorting and filtering not working with angular 9

### ISSUE THREAD

**Issue by MiguelPetrotec** [IgniteUI/igniteui-angular#7450]
[custom-grid.zip](https://github.com/IgniteUI/igniteui-angular/files/4710976/custom-grid.zip)

## Description  
When trying to apply remote sorting it only works for the first time on each column and the remote filtering and the advance filtering does not work.

 * igniteui-angular version:  v9.1.0-alpha.12 and worked on 9.0.0-beta3
 * browser: Chrome

## Result  
does not work correctly

## Expected result  
sort or filter

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
@MiguelPetrotec 
Unfortunately I was not able to create a runnable the sample from the code you have attached as it appears that some of its dependencies and data are missing.

I assume your sample is based on this one from our documentation as it uses a similar service for the excel style filtering:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html#unique-column-values-strategy

I have tested the sample we have for the excel filtering, as it appears to be using a similar service as the one in the code you have shared. 
The sample currently uses version 9.1.0, however I was not able to reproduce the behavior you have described in it.
I have also checked with our existing remote sorting and filtering sample at: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html#demo
And remote sorting and filtering work as expected in it.

Let me know if this issue still reproduces for you in the official release version (9.1.0). 
If so, please share a fully working sample with your exact scenario or modify one of the existing stackblitz samples so that it can more closely resemble your scenario:

Stackblitz sample for remote sorting & filtering: https://stackblitz.com/angular/mjpqdnkerdm
Stackblitz sample for excel style filtering with unique values strategy: https://stackblitz.com/angular/ymejgqqrepb

**Comment by kdinev** [comment]
@MayaKirova We had a meeting with Miguel and I committed that we will take the component and mock the state service. Could you try to recreate a mock data service with the provided component, because we saw at the meeting there was an issue and we couldn't isolate where it was coming from.

**Comment by MigDom** [comment]
@kdinev ir necessary any kind of help let me know, se can arrange a meeting and build the all example.

**Comment by MayaKirova** [comment]
@kdinev @MigDom 
I don’t think I can recreate the exact same scenario as it appears that most of the service communication and data handling is done outside of the actual component and is passed as an Input, hence most of the relevant code is omitted.

I’ve created a simplified version with one of our existing remote services, however I had no luck in reproducing any issues with sorting and filtering in it.
I’ve attached the sample for your reference here:
[remote-sample-custom-grid.zip](https://github.com/IgniteUI/igniteui-angular/files/4765504/remote-sample-custom-grid.zip)


Please test it and let me know if you find any of the before mentioned issues with it. If so please describe the exact steps needed to reproduce them.
Alternatively if the sample is not an accurate representation of what you are doing in your own application then please feel free to modify it so that it more closely resembles your scenario and send it back so that we may review it further.

**Comment by MiguelPetrotec** [comment]
Sorry for the delay I will start the checking today

**Comment by MiguelPetrotec** [comment]
[Ignite Angular 9.zip](https://github.com/IgniteUI/igniteui-angular/files/5156082/Ignite.Angular.9.zip)
@kdinev as requested by email here goes the zip with the example project

**Comment by MayaKirova** [comment]
@MiguelPetrotec 
Thank you for sharing a sample.
I’ve simplified it a bit so that the page with the grid opens on start with empty data and you can apply sorting: 
[simpler-sample.zip](https://github.com/IgniteUI/igniteui-angular/files/5157417/simpler-sample.zip)


Based on the email the steps to reproduce are:
1)	Open the sample
2)	Click on a column header twice to sort a column.

Result is:
Error is thrown on second click
Cannot assign to read only property 'fieldName' of object '[object Object]'

Expected result is:
No error is thrown.

**Comment by MayaKirova** [comment]
@MiguelPetrotec 

After looking into this it seems that everything passed to the RxJS Store  becomes Immutable (read-only).
And since the sorting and filtering expressions are stored there after the first operation (first click on header stores the sorting expression) the expression objects become read-only and cannot be modified.
One way to ensure the original objects are not affected by the RxJS store is to create copies of the objects before passing them to the store.

For example instead of passing the array of objects directly:


    let filteringExpr = this.grid.filteringExpressionsTree.filteringOperands;
    const sortingExpr = this.grid.sortingExpressions;
    this.store.dispatch(this.loadAction({
        itemCode: this.filterCode,
        options: {
          paging: {
            skip: 0,
            top: this.perPage
          },
          filteringArgs: filteringExpr,
          sortingArgs: sortingExpr
        }
    }));

You can create copies of the objects:


    let filteringExpr = this.grid.filteringExpressionsTree.filteringOperands;
    const sortingExpr = this.grid.sortingExpressions;
    this.store.dispatch(this.loadAction({
        itemCode: this.filterCode,
        options: {
          paging: {
            skip: 0,
            top: this.perPage
          },
          filteringArgs: filteringExpr.map(x => Object.assign({}, x)),
          sortingArgs: sortingExpr.map(x => Object.assign({}, x))
        }
      }));

This will ensure the original objects are not marked as read-only and can continue to be used inside the grid.
Let me know if this resolves your issue.

**Comment by MiguelPetrotec** [comment]
Problem detected and solved thank you @MayaKirova and @kdinev
