### ISSUE TITLE
igx-column editing by click

### ISSUE THREAD

**Issue by EvgeniyZhukovets** [IgniteUI/igniteui-angular#7503]
## Description  
When I open the page containing igx-grid and igx-column, I could open the input field for editing cells only with double click for the first time, then I could edit every column of this grid just with one click. Could you make editing all cells just with one click or how can I resolve it by myself?

 * igniteui-angular version:  9.0.1
 * browser: Google Chrome

## Steps to reproduce  

1. Create page with igx-grid
```
<igx-grid #grid1 [data]="..." [autoGenerate]="false" displayDensity="cosy" width="600px"
              height="600px" [paging]="true" [perPage]="10" [allowFiltering]="true" [filterMode]="'excelStyleFilter'">
      ...
      <igx-column-group>
        <ng-template igxHeader let-column>
          <h6 translate>...</h6>
        </ng-template>
        <igx-column field="..." [dataType]="'number'" [editable]="true" [filterable]="false" width="85px">
          <ng-template igxHeader let-column>
            <igx-icon [isActive]="false">access_time</igx-icon>
          </ng-template>
        </igx-column>
        <igx-column field="..." header="..." [dataType]="'number'" [editable]="true"
                    [sortable]="true" [filterable]="true"
                    width="85px">
          <ng-template igxHeader let-column>
            <igx-icon [isActive]="false">people_alt</igx-icon>
          </ng-template>
        </igx-column>
      </igx-column-group>
      ...
</igx-grid>
```
2. Try to edit one of the fields (input field opens only with a double click)
3. Try to edit again (every input field opens with one click)

## Result  
Every input field opens only with double click for the first time, then they open with one click.

## Expected result  
Every time I try to edit a cell, I could do it just by one click.

## Attachments  
First time I click on cell:
<img width="86" alt="image" src="https://user-images.githubusercontent.com/22504733/83972215-8e81bb80-a8e7-11ea-8887-b8a4428290fb.png">
Second time I click on cell:
<img width="91" alt="image" src="https://user-images.githubusercontent.com/22504733/83972237-a6f1d600-a8e7-11ea-991a-26e2b2ba44e9.png">
Then every time I click on any cell it edits with one click:
<img width="89" alt="image" src="https://user-images.githubusercontent.com/22504733/83972255-ba04a600-a8e7-11ea-9c03-ff7ab727f532.png">

**Comment by ddincheva** [comment]
Hello @EvgeniyZhukovets ,
The described behavior is by design. By default on single click only cell selection function is performed when cellSelection feature is enabled(which is the default grid state). But the IgxGrid exposes quite rich API so it is really easy to change the default behavior in a way that fulfill your use case. For the described scenario above you just need to subscribe to onCellClick event and to set the cell in edit mode. Please check this [sample](https://stackblitz.com/edit/angular-8crr4h) and let me know if this fulfill your use case or need some additional support.

**Comment by EvgeniyZhukovets** [comment]
Yes, it works! Thanks a lot!

**Comment by EvgeniyZhukovets** [comment]
Also question about cell editing by one click. Your solution works great if cell contains just text input, but if I use igx-radio-group and igx-radio inside, it doesn't edit by one click.
Code:
```
...
</igx-grid #grid (onCellClick)="cellClick($event)">
       ...
       <igx-column-group>
        <ng-template igxHeader let-column>
          <h6>...</h6>
        </ng-template>
        <igx-column field="channel" [dataType]="'string'" [editable]="true" [filterable]="false"
                    width="130px">
          <ng-template igxHeader let-column>
            <div class="inline-group required-header-group">
              <igx-icon>chat</igx-icon>
              <igx-icon>call</igx-icon>
              <igx-icon>videocam</igx-icon>
            </div>
          </ng-template>
          <ng-template igxCell igxCellEditor let-cell="cell">
            <igx-radio-group [(ngModel)]="cell.row.rowData.channel">
              <igx-radio value="chat"></igx-radio>
              <igx-radio value="audio"></igx-radio>
              <igx-radio value="video"></igx-radio>
            </igx-radio-group>
          </ng-template>
        </igx-column>
      </igx-column-group>
</igx-grid>
...
```
```
...
@ViewChild('grid')
  public grid: IgxGridComponent;

cellClick(args) {
    if (args.cell.editable && !this.grid.crudService.cell) {
      args.cell.setEditMode(true);
    }
  }
...
```
Layout:
<img width="62" alt="image" src="https://user-images.githubusercontent.com/22504733/84599321-df5e5a80-ae79-11ea-96b3-7ff0dc71c072.png">
First click on radio:
<img width="68" alt="image" src="https://user-images.githubusercontent.com/22504733/84599342-fac96580-ae79-11ea-9ddb-0e55dcc84389.png">
Second click on radio:
<img width="68" alt="image" src="https://user-images.githubusercontent.com/22504733/84599356-103e8f80-ae7a-11ea-9921-7cb33934ea50.png">

**Comment by ddincheva** [comment]
Hello @EvgeniyZhukovets ,
Can you please describe me in more details what are the specific steps in order to reproduce the problem that you face, because what can I see from the last code snippet that you provide .. you are using absolutely the same default and editing cell templates, so when you switch between edit mode and default mode there is no visual difference between the two states?!

**Comment by EvgeniyZhukovets** [comment]
Hello @ddincheva,
Nope. The problem is that I can not edit cells with radio group by one click. That is just for cells with radio group, every other cell edits by one click.

**Comment by ddincheva** [comment]
Hello @EvgeniyZhukovets ,
I am not absolutely sure that I am able to understand correctly the problem that you face. But I tried to investigate deeper the code snippet that you provide. What I can suggest based on it is:
 if you want to edit the cell value through the radio button you do not need to have defined a IgxCellEditor template, you can modify the value directly without the cell to enter edit mode. We provide nice api to easy achieve that. Also to update the value I suggest you to use either the grid.updateCell method or cell.update method. Please check this [sample](https://stackblitz.com/edit/angular-8crr4h-crhjbu) and if this not fulfill your use case, please describe me more in depth your problem is, so I can investigate it deeper.
