### ISSUE TITLE
FAB button extension

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#7542]
Due to the specification extension of the FAB button as a Material component, it is needed enhancement for the FAB button, so it allows adding icon+text, instead of just icon. The main differences compared to the Raised button (Icon+Text) are the increased padding and rounding. Furthermore, text style properties have to be set according to Material guidelines. After this enhancement, the button component is going to be fully aligned with the current Material guidelines.

Read more about this here:
https://material.io/components/buttons#hierarchy-and-placement
https://material.io/develop/android/components/floating-action-button/#extended-fabs

**Comment by StefanIvanov** [comment]
I would rather say that the main difference is not stylistically but rather in the behavior of the button to always float over a certain area with constraints that keep in on an absolute position of the device screen. Thus it comes with higher elevation and other statistical touches but the behavior is first and foremost. I agree that the proposed enhancement for the content of the button should be considered for the product.

**Comment by StefanIvanov** [comment]
ОК @radomirchev , we have spoken with @DaniMarinov about the specific needs of his team and we came to the conclusion that our current implementation for the FAB does not include the extended scenario currently described in the Material Guideline [here](https://material.io/components/buttons-floating-action-button#extended-fab) From my point of view there are two approaches to this:
1. Akin to Material to have an "extended" variant probably through a property
2. To make the FAB content area templatable and contain just an icon in its default template
IMO the scope is clear and we have sufficient clarity on the requirement in order to plan it for development.

**Comment by simeonoff** [comment]
This can be handled entirely via styling.
