### ISSUE TITLE
Column Hiding dropdown closes unintentional

### ISSUE THREAD

**Issue by AverageA** [IgniteUI/igniteui-angular#7569]
### Description  
Column Hiding dropdown closes when you hide a column and the horizontal scroll bar is at the right end of the grid. 

 * igniteui-angular version: 9.1.0
 * browser: Chrome

### Steps to reproduce  

1. Set the horizontal scroll bar on the right end of the grid.
2. Open the column hiding dropdown and hide any column.

### Result  
Column Hiding dropdown closes.

### Expected result  
Column Hiding dropdown stays open so the user can choose to hide any number of columns.

![columnhiding](https://user-images.githubusercontent.com/26189540/84404892-05ab9e00-abcd-11ea-94ce-705010327e09.gif)

**Comment by astaev** [comment]
@StefanIvanov @simeonoff 
Do you think that we can leave column hiding/pinning dropDowns opened during grid scrolling(like the advancedFiltering dialog)?
 And close them on outside and target click?

**Comment by StefanIvanov** [comment]
Upon user manually scrolling the grid the dropdown should be closed and what I see here is that because of the automatic scroll performed when a column is hidden in the described situation, we close the dropdown, when we actually shouldn't. Only when user manually interacts with the grid to scroll it the dropdowns should be implicitly closed.
