### ISSUE TITLE
IgxGrid does not apply header and cell style on IE11

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#7570]
## Description  
IgxGrid does not apply header and cell style on IE11. This is not seen in 9.0.17.

 * igniteui-angular version: 9.1.1
 * browser: IE11

## Steps to reproduce  
1. Run the attached sample
2. Observe the result

## Result  
Styles on header and cell are not applied.

## Expected result  
Styles on header and cell are applied.

## Attachments  
[igx-grid-ng9.zip](https://github.com/IgniteUI/igniteui-angular/files/4762020/igx-grid-ng9.zip)

Result on IE11:
![image](https://user-images.githubusercontent.com/14340675/84333495-e3188580-abca-11ea-9dbe-7aa9d320543b.png)

Result on Chrome:
![image](https://user-images.githubusercontent.com/14340675/84333564-12c78d80-abcb-11ea-9388-69fc85b90ec4.png)

**Comment by rkaraivanov** [comment]
@ymita 
With the 9.1 release you have to enable `$legacy-support` explicitly in order to support older browsers (IE 11 in this case).
This is documented both in the [changelog](https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#themes) and in the [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/component-themes.html#overview).

**Comment by ymita** [comment]
@rkaraivanov I confirmed it is working by adding the argument. Thank you!
