### ISSUE TITLE
Cannot add new transaction when open added row in edit mode and updo transactions

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#7579]
## Description  
Cannot add new transaction when open added row in edit mode and updo transactions

 * igniteui-angular version: 9.1
 * browser: n/a

## Steps to reproduce  
1. Open dev sample gridRowEdit
2. In the second grid click on Add Row button
3. Navigate to the added row and double click on a cell to enter row editing
4. Click button Undo
5. Try to add or delete a row

### Result  
It is not possible to add or delete row

### Expected result  
It should be possible to add and delete rows

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by 3phase** [comment]
@nrobakova  
The up-mentioned behavior is by design, ever since the developer is supposed to escape the editing mode prior undoing the transaction. In order to accomplish that, the custom, user-built `undo`-handler **is supposed to invoke endEdit**, when the grid can enter in edit mode. The snippet might look as follows:
 
```typescript 
public undo(grid: IgxGridComponent) {
  grid.endEdit(/* commit the edit transaction */ false);
}
``` 

Even though, it's not a bad idea to describe that in the docs. I'll keep you posted in a separate issue in our docs repo.
