### ISSUE TITLE
getNextCell and getPreviousCell don't return the expected next and previous cells when multi-row layout is used.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#7587]
## Description  
getNextCell and getPreviousCell don't return the expected next and previous cells when multi-row layout is used.

 * igniteui-angular version: 9.1.1
 * browser: Chrome, IE11, Firefox, Edge

## Steps to reproduce  

1. Run the attached reproducible sample 'my-app1' and open localhost:4200 in a browser.
2. Click the "Row 2, Col 3" cell.
3. Click the "Get the next and previous cells" button.
-> See the console log.

## Result  
Next Cell: rowIndex=2, visibleColumnIndex=1
Previous Cell: rowIndex=1, visibleColumnIndex=3

## Expected result  
Next Cell: rowIndex=2, visibleColumnIndex=3
Previous Cell: rowIndex=2, visibleColumnIndex=1

## Attachments  
[my-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/4777829/my-app1.zip)

**Comment by ddincheva** [comment]
Hello @norikois ,
I spend some time investigating in more details the sample that you have sent and noticed a few problems on application level. Firstly, the multi row layout is not set up absolutely correctly and this causes a few issues with the features that rely on visible column index property, this is described in [our official documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/multi_row_layout.html#multi-row-layout).
![image](https://user-images.githubusercontent.com/34240583/84890258-d8fef700-b0a2-11ea-9d01-6f6fcc72fd0f.png)

Second, when there is multi row layout enabled selection behaves a little bit differently
![image](https://user-images.githubusercontent.com/34240583/84890118-a48b3b00-b0a2-11ea-93de-c5500c77aa19.png)
 so in order to correctly determine next and previous cell strongly suggest you to use the activeNode. Please see the updated [sample](https://stackblitz.com/edit/angular-d4stj9) if this fulfill your use case and let me know if you need any additional help

**Comment by zdrawku** [comment]
@norikois, let us know if you have any other questions
