### ISSUE TITLE
Space button not working in igx-grid textbox without edit mode

### ISSUE THREAD

**Issue by SC003** [IgniteUI/igniteui-angular#7588]
## Description  
Describe the issue.
Space button not working in igx-grid textbox without entering in edit mode and it works when user double click or press enter button to enter in edit mode
 * igniteui-angular version: 9.1.0
 * browser: Google Chrome

## Steps to reproduce  

1. Create a sample grid with textbox
2. Execute program and try entering comments like "Remarks Remarks"
3. User will not be able to press space button
4. Once user double click on textbox and when textbox is in edit mode now user can press space button and remarks as required
5. Sample grid code attached

## Result  
Space button not working in igx-grid textbox without edit mode
![with space in edit mode](https://user-images.githubusercontent.com/66816383/84619692-73203d00-aef3-11ea-8812-cccd6cddf7fd.PNG)
![withoutspace](https://user-images.githubusercontent.com/66816383/84619695-74516a00-aef3-11ea-9e5c-3afb288cb209.PNG)

## Expected result  
Space button must be allowed in igx-grid textbox without entering in edit mode

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

![with space in edit mode](https://user-images.githubusercontent.com/66816383/84619707-7d423b80-aef3-11ea-9fc6-6e97cd78f19a.PNG)
![withoutspace](https://user-images.githubusercontent.com/66816383/84619712-80d5c280-aef3-11ea-9670-b16289931eaf.PNG)
[IGX-Grid Sample Code.txt](https://github.com/IgniteUI/igniteui-angular/files/4778101/IGX-Grid.Sample.Code.txt)

**Comment by ddincheva** [comment]
Hello @SC003,
Arrow keys, along with space key and the other keys that are described in [the our official documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/keyboard_navigation.html) have a default behavior in the grid. Space key is used for row selection for example. But if you need to change this behavior in order to fulfill your use case you just need to stop the keydown.space propagation and the space key will behave in default browser way or you can add any custom logic to it. The same applies and to the other key combination. Here is a small [example](https://stackblitz.com/edit/angular-nbocdo).. Please check it out and let me know if that fulfill your use case.

**Comment by SC003** [comment]
Dear @ddincheva 
Thanks for your reply.
I tried below stop propogation on (keydown) event and now it's working.

 <igx-column  field="Comments" header="Comments">
                <ng-template igxCell let-cell="cell">
                  <igx-input-group displayDensity="compact" **(keydown)="$event.stopPropagation()"** >
                    <input displayDensity="compact" [ngModelOptions]="{standalone: true}" igxInput [(ngModel)]="cell.rowData.Comments" type="text" autocomplete="off"
                            />
                  </igx-input-group>
                </ng-template>
              </igx-column>
