### ISSUE TITLE
Column cannot be dropped before the first column which width is smaller than 30 px

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#7653]
## Description  
Moving column cannot be dropped to the left side of the first column if the first column width is smaller than 30 px. In the attached sample, the width of first column is 24 px, which is the minimum column width for displayDensity.Compact.

 * igniteui-angular version: 9.1.3
 * browser: n/a

## Steps to reproduce  

1. Run the sample [igx-grid-col-move.zip](https://github.com/IgniteUI/igniteui-angular/files/4817315/igx-grid-col-move.zip)
2. Move 'Name' column to the left side of 'ID' column

## Result  
'Name' column cannot be dropped to the left side of 'ID' column.

## Expected result  
'Name' column can be dropped to the left side of 'ID' column.

## Attachments  
![igxGrid-column-moving](https://user-images.githubusercontent.com/14340675/85364881-19f18280-b55f-11ea-947b-879e41a80ca6.gif)

**Comment by MayaKirova** [comment]
@ymita This seems to be a documentation issue as the actual minimum display density sizes have been changed since version 8.0.2:
https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#802
Currently for DisplayDensity.compact min width is 56px.

Setting a smaller width than the minimum is not supported:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#known-limitations

**Comment by MayaKirova** [comment]
Separate documentation issue related to the wrong min-width values per display density is logged here: https://github.com/IgniteUI/igniteui-docfx/issues/2061

**Comment by ymita** [comment]
@MayaKirova Thank you for the information.
