### ISSUE TITLE
"PositionSettings" minSize property functionality

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#7674]
## Question  
Hey, i would like to specify a minimum-size for the igx-dialog, and found the minSize property in the PositionSettings Accessor. If i try to set this the dialog size does not change, please see attached stackblitz https://stackblitz.com/angular/mjjrrgmdpma

If this is not the correct way to use this property please let me know.

**Comment by zdrawku** [comment]
Hey @VirtualisProject, [minSize ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/positionsettings.html#minsize)property  is related only to the [elastic position strategy](https://www.infragistics.com/products/ignite-ui-angular/angular/components/overlay_position.html#elastic), its the size to which the element may shrink when shown.

The [dialog topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/dialog.html#position-and-animation-settings) provides detailed information on how to set a position strategy. Also, below you will find[ a sample](https://stackblitz.com/edit/dialog-with-elastic-strategy?file=src/app/dialog-sample-3/dialog-sample-3.component.ts) that I've created for you in order to demonstrate you how to configure it.
