### ISSUE TITLE
igxTreeGrid: Expansion indicator is not displayed if a row is expanded and the data is reloaded.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#7677]
## Description  
Describe the issue.

 * igniteui-angular version: 9.1.3
 * browser: Chrome

## Steps to reproduce  

1. Run the attached sample.
2. Click 'GetData' button.
3. Expand the first row.
4. Click 'GetData' button.

## Result  
The expansion indicator is not displayed for the first row.

## Expected result  
The expansion indicator is displayed for the first row.

## Attachments  
[igxTreeGrid.zip](https://github.com/IgniteUI/igniteui-angular/files/4829281/igxTreeGrid.zip)

**Comment by DiyanDimitrov** [comment]
@mkamiishi, When changing the data source, you should also clear the `expansionStates`. The load on demand feature relies on the `expansionStates` of the tree grid to know which rows were expanded. If a row has expanded state set to true and does not have children, we don't display the loading indicator.

The following code in the GetData method fixes the issue:

```ts
this.data = children;
this.treeGrid.expansionStates = new Map<any, boolean>();
this.treeGrid.isLoading = false;
```
We are not automatically resetting the `expansionStates` when changing the data since users that do not use load on demand, might want to preserve the expanded rows.
