### ISSUE TITLE
Do not close modal overlay on ESC key press

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#7697]
## Is your feature request related to a problem? Please describe.
There is no way to stop closing of `IgxDialog` on `ESC` key press. This is valid also for all components using `IgxOverlay` in modal mode.

## Describe the solution you'd like
Allow configuration of the overlay allowing to discard `ESC` key press. This could be added in `OverlaySettings`. We have now `closeOnOutsideClick` property. There should be and something like `closeOnEsc`.

**Comment by jackofdiamond5** [comment]
We've reopened this issue because we needed to define a way for the overlay to close on `Esc` keypress when it is not modal. Additionally, we had to discuss how we want to handle scenarios with stacked overlays. We came to an agreement that the stacked overlays should be closed from last to first. Also, it should not matter if the overlay is modal or not - if the settings have a `closeOnEsc` property set to `true`, it is considered a candidate for closing and will be closed when the key is pressed.
