### ISSUE TITLE
Wrong calculate width of igx-dialog

### ISSUE THREAD

**Issue by vazikh-yunusov** [IgniteUI/igniteui-angular#7727]
## Description  
Wrong calculates width of igx-dialog in another igx-dialog

 * igniteui-angular version: 9.1.4
 * browser: Google Chrome

## Steps to reproduce  

I have igx-dialog in another igx-dialog. When open inner dialog first time it looks fine. But when close it and open again it's width calculates wrong.
After first opening:
![image](https://user-images.githubusercontent.com/61229028/86238929-15ece280-bba7-11ea-9f38-50a89ef6b8a4.png)

After second opening:
![image](https://user-images.githubusercontent.com/61229028/86239729-89dbba80-bba8-11ea-9052-30c22dcfa42d.png)

After second opening inner dialog it's width calculates wrong 

## Expected result  
After second opening inner dialog it's width should calculates correct

**Comment by vazikh-yunusov** [comment]
When this bug will be fixed?

**Comment by zdrawku** [comment]
Hello @vazikh-yunusov, I am adding this issue to our sprint planning.

**Comment by simeonoff** [comment]
@vazikh-yunusov I tried reproducing the issue, however, nothing's breaking on my end. Could you provide a sample so that we can take a closer look at what's happening on your end?

I have prepared a [sample on CodeSandbox.](https://codesandbox.io/s/ecstatic-williams-brkn6?file=/src/app/dialog-sample-1/dialog-sample-1.component.html).
