### ISSUE TITLE
Allow tooltip positioning (ex. before, after, above, below) in relation to target element

### ISSUE THREAD

**Issue by DerekJDev** [IgniteUI/igniteui-angular#7775]
## Is your feature request related to a problem? Please describe.

I need to be able to position the tooltip in different areas around the target element besides below it, but with current documentation it doesn't look like there is a place to specify this setting.

## Describe the solution you'd like

Have an option to specify the position of the tooltip in relation to the target element, maybe add an attribute igxTooltipPosition="below | above | before | after"

## Describe alternatives you've considered

None other than a different UI framework.

**Comment by kdinev** [comment]
@DiyanDimitrov Does the tooltip currently utilize the same positioning strategy as the overlay?

**Comment by DiyanDimitrov** [comment]
@kdinev, yes, the tooltip positioning could be changed by modifying the [`overlaySettings`](https://www.infragistics.com/products/ignite-ui-angular/docs/10.0.5/typescript/classes/igxtooltiptargetdirective.html#overlaysettings).

**Comment by wnvko** [comment]
@DerekJDev 
[Here](https://stackblitz.com/edit/github-pdgjxe-rd432q?file=src%2Fapp%2Ftooltip-simple%2Ftooltip-simple.component.html) you can find a sample showing how you can use [OverlaySettings](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/overlaysettings.html) in order to position the tooltip.

***Note***: I know creating an overlay settings is not so straight forward task. This is why we are planning now to implement some factory methods that will create ready to use overlay settings. As soon as we implement these methods we will refer this issue too.

**Comment by wnvko** [comment]
@DerekJDev we have implemented the factory methods for creating an `OverlaySettings`. [Here](https://stackblitz.com/edit/github-pdgjxe-vjarxa?file=src%2Fapp%2Ftooltip-simple%2Ftooltip-simple.component.ts) you can find updated sample showing the tooltip by the help of the new factory methods.

**Comment by PlamenaMiteva** [comment]
@DerekJDev Ignite UI for Angular v10.2.0, which includes the new methods for creating `OverlaySettings`,  has been released. You can find more information and a demo about the new functionality [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/overlay_main.html#preset-overlay-settings).
