### ISSUE TITLE
Move PositionSettings to OverlaySettings

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#7807]
## Is your feature request related to a problem? Please describe.
Providing a simple change to `OverlaySettings` and merge the change to existing settings is really hard now. A flat structure will make this a lot simpler.

## Describe the solution you'd like
Has all the settings `IgxOverlayService` need in its `OverlaySettings`

**Comment by PlamenaMiteva** [comment]
Since the most common issue our clients face is changing the target of the Position settings, which then requires the strategy settings overriding we have moved the target property to overlay settings. This will now make it easier for the target to be changed without the need to alter/override the position settings every time.
