### ISSUE TITLE
Igniteui-angular depending on core-js-pure

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#7808]
## Description  
Angular 10 is complaining about igniteui-angular.js depending on core-js-pure when IgxGridModule is imported or IgxExcelExporterService is provided.
Please take a look at the attached screenshot.
Attached you will find a sample project replicating the described behavior as well.

I assume that the issue is related to the following [pull request](https://github.com/IgniteUI/igniteui-angular/pull/7792/files).

### Attachments: 
![core-js-pure](https://user-images.githubusercontent.com/44684385/87788593-4474e980-c846-11ea-9ca7-04e6fc1a132d.PNG)
[angular10.zip](https://github.com/IgniteUI/igniteui-angular/files/4937907/angular10.zip)

**Comment by damyanpetev** [comment]
The hammer warning is due to the import in main.ts - assuming that's setup provide by our `ng-add` schematic, otherwise it's just part of the project source. Funnily enough, we already moved it once specifically to `main.ts` for another issue, I guess we get to go back now. Per the old ways, to avoid this warning projects can just move the hammer script to `angular.json` for both `build` and `test`:
```json
  // ...
  "scripts": [
              "node_modules/hammerjs/hammer.min.js"
            ]
```
This is something we might address in the add schematic, but probably won't attempt to migrate.

The second and main issue is with a recent addition of `core-js-pure` as a dependency, which is apparently a CJS/AMD module and that can't be fixed without a new package.
@igdmdimitrov @rkaraivanov If I get it right, the package is in https://github.com/IgniteUI/igniteui-angular/pull/7792 for a single `setImmediate` method. Not sure how magical it is, but if the license is permissive can we consider integrating it in our code instead?

----
PS: I case you're wondering if the warning from the CLI has any basis in it - with 10.0.4:
```shell
chunk {main} main.js, main.js.map (main) 76.2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.35 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 8.77 MB [initial] [rendered]
```
with 10.0.3:
```shell
chunk {vendor} vendor.js, vendor.js.map (vendor) 8.05 MB [initial] [rendered]
```
Other chunks remain identical and of course there's no warning. So that one method does cost about ~0.7MB (yes, in debug, I know).
Moving the hammer script creates the scripts bundle:
```shell
chunk {scripts} scripts.js, scripts.js.map (scripts) 20.3 kB [entry] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.98 MB [initial] [rendered]
```
and the vendor drops by a little more than that, so the overhead (if any) is minimal on that one.
