### ISSUE TITLE
IgxGrid grouping remote operation

### ISSUE THREAD

**Issue by sddania** [IgniteUI/igniteui-angular#7863]
is it possible to add the remote operation "group by"?
Actually i can make from the remote server a facets for the specific grid column; is it possible to specify with a new grid's property the list of grouped value with the specific count, and when the user will expand the group an http request will fetch the data?

**Comment by ChronosSF** [comment]
Hey @sddania ,

So from what I understood you mostly need something like load on demand for group rows? Your grid shows only group rows, then when the end-user tries to expand one, your server gets parameters such as the column that is grouped and the value that the group represents and returns all rows for the group. Then the grid displays them. Is my assumption correct?

Generally speaking, there is no real remote groupby with igxGrid's grouping UI because what grouping does is just separate sorted data and insert non-data rows in the data view where the different values are. Sure, your sorting can be remote and we already show how this can be done in our [samples](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html#remote-sortingfiltering) but anything more would require your server to be strictly coupled with what the grid interprets as group rows, which doesn't make much sense.

If my earlier assumption is correct and you just need "load on demand", this also hits the same issue - the grid has to be able to come up with the UI showing all group rows as collapsed. It can either do it itself, by having all the sorted data (making load on demand pointless from that point on), or by receiving it from a server, but that would mean either the server sends the exact object signature of a group row, or there is some middleware that translates it. The latter could possibly work but it's not a good candidate for feature development as such servers are non-standard and everything falls down to very specific application scenarios.

My suggestion is to see if your scenario can be achieved with more common "load on demand"-enabled controls such as a [hierarchical grid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/load_on_demand.html) or a [tree grid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/load_on_demand.html).
