### ISSUE TITLE
ESF dialog is cut off by the grid in safari

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#7866]
## Description  
ESF dialog is cut off by the grid in safari

 * igniteui-angular version: **9.1.x, 10.0.x, 10.1.x**
 * browser: **Safari**

## Steps to reproduce  

1. Open dev demos Grid auto-size [sample](http://localhost:4200/gridAutoSize)
2. Open ESF

## Result  
The ESF dialog is cut off by the grid

## Expected result  
The ESF dialog should not be cut off

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[Screenshot](https://imgur.com/ZETF308)

**Comment by DiyanDimitrov** [comment]
@Lipata, this looks like an issue with the overlay. Could you please take a look at it?

**Comment by wnvko** [comment]
The grid has `overflow` set to `hidden` and the `position` of the overlay container is set to `fixed`. In Safari rendering such element leads to clipping the inner container. This is fixed in [Release 108](https://developer.apple.com/safari/technology-preview/release-notes/#r108), rendering section.
There is nothing we can do about it. As soon as this Safari release is published the issue should be fixed.
