### ISSUE TITLE
igxGrid navigateTo - scroll to last row 

### ISSUE THREAD

**Issue by Swiftpaws** [IgniteUI/igniteui-angular#7919]
## Question  
How to scroll to the last element with the navigateto method?
When debugging I can see that virtualization is working - elements in data 4k+ elements in _rowList 22.

But its not clear to me how I can programmatically scroll to the actual last possible element (not visible, actual last end of data)?

For example: Viewport is index 10 to 20 but I want to scroll to element 2000?

 * igniteui-angular version: 10.0.1
 * browser: latest chrome / edge

**Comment by ddincheva** [comment]
Hello @Swiftpaws , 
As you have noticed the rowList property consist only of the rows that are currently in the view, in order to be able to get all the records /including the records that are currently not visible/ the IgxGrid exposes the property dataView. Please check [this example](https://stackblitz.com/edit/angular-d4stj9-asr8jg) and see if this fulfill you use case.

**Comment by Swiftpaws** [comment]
Thanks for the answer! Yes this works for me.
