### ISSUE TITLE
Grid render infinite loop

### ISSUE THREAD

**Issue by Ferranteg-dev** [IgniteUI/igniteui-angular#8096]
## Description  
Hello,
i was making some performance check on my application and noticed that pages with grid are slower than pages without igxGrid, not much but still.
So i started checking some rendering loop etc. and noticed that the grid is constantly re-rendering.
I'll try to explain :
This code is the grid, i'm not really using the ng-template for the cell, i did it just to print logMe.
I've nested igx-column into a ng-container cause table headers are supposed to be multilingual, so columns array is just a key-value array 

```
{
key :string,
value:string
}

  public logMe(): void {
    console.log("Render");
  }

```

```
<igx-grid #myGridId="myGridId" [data]="tableData" [allowFiltering]="true"
          [displayDensity]="'cosy'" [filterMode]="'excelStyleFilter'" [cellSelection]="'none'" [rowSelection]="'single'"
          [hideRowSelectors]=true (onRowSelectionChange)="handleRowSelection($event)">
          <ng-container *ngFor="let column of columnNameMapping; trackBy: trackByColumns">
            <igx-column [field]="column.key" header="{{column.value | translate}}" [resizable]="true" [sortable]="true">
              <ng-template igxCell let-cell>
                {{cell}}
                {{logMe()}}
              </ng-template>
            </igx-column>
          </ng-container>
 </igx-grid>
```

 * igniteui-angular version:  10.1.1
 * browser: Chrome@latest

## Result  

i would expect that "Render" in console will happen just once for each column, maybe once for each row, but instead look at this screenshot

![image](https://user-images.githubusercontent.com/55274139/92391230-92a6ba80-f11c-11ea-83ed-23510b0ef95e.png)

and it goes up for the whole scrollbar length,
thousand of re-rendering

I suppose that thousand rendering is not what the grid is supposed to do

## Update
I've tried to switch all the height to px, instead of viewport or %, i gave the table a fixed heigth of 500px as test, but the rendering is still massive

**Comment by kdinev** [comment]
@gianmarcoFerranteProm The template with the function call you've defined is a cell template. Initial render would call this function once for each cell in the view, and then each time you run change detection on the page, the function will be called again for each cell going through change detection - when scrolling through the grid the cells are re-rendered.

If you're looking to provide a custom template for the column header and not the cells, then using the `igxHeader` template directive instead of the `igxCell`. https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#columns-configuration

**Comment by gianmarcoFerranteProm** [comment]
@kdinev  i understand that is a cell Template, and it may cause some extra rendering due to (cellNumber * row) that's why i've made another test into an empty component just to be sure that nothing is going with this process and i made it outside the cell render:

`<igx-grid #templateDashboardGrid id="templateDashboardGrid" [data]="tableData" [allowFiltering]="true"
          [displayDensity]="'cosy'" [filterMode]="'excelStyleFilter'" [cellSelection]="'none'" [rowSelection]="'single'"
          [hideRowSelectors]=true (onRowSelectionChange)="handleRowSelection($event)" [paging]="true" [perPage]="25">
          <ng-container *ngFor="let column of columnNameMapping; trackBy: trackByColumns">
            {{logMe()}}
            <igx-column [field]="column.key" header="{{column.value | translate}}" [resizable]="true" [sortable]="true">
            </igx-column>
          </ng-container>
 </igx-grid>` 

23k renders are a bit too much for an empty grid :)

![image](https://user-images.githubusercontent.com/55274139/92475180-42436180-f1dd-11ea-9b8a-c41b36e78cfb.png)

![image](https://user-images.githubusercontent.com/55274139/92475292-761e8700-f1dd-11ea-8985-1efcc12c729f.png)

**Comment by kdinev** [comment]
I don't think you need the `<ng-container>` in this example. Does the same thing happen if you apply the `*ngFor` directive directly on the `<igx-column>`?

**Comment by gianmarcoFerranteProm** [comment]
Same result i guess, cant bind the counter for the exact number without cell template but still:

```
  <igx-grid #draftTemplateGrid id="draftTemplateGrid" [data]="tableData" [allowFiltering]="true"
    [displayDensity]="'cosy'" [filterMode]="'excelStyleFilter'" [cellSelection]="'none'"
    [dropAreaTemplate]="layerDropArea" [rowSelection]="'single'" [hideRowSelectors]=true
    (onRowSelectionChange)="handleRowSelection($event)">
    <igx-column [field]="column.key" header="{{column.value | translate}}" [resizable]="true" [sortable]="true"
      [groupable]="true" *ngFor="let column of columnNameMapping; trackBy: trackByColumns">
    </igx-column>
  </igx-grid>
```
86310 Lines with 7x call each = 604.170 TrackBy call
![image](https://user-images.githubusercontent.com/55274139/92482193-a1a66f00-f1e7-11ea-9055-78c0e0acd387.png)
![image](https://user-images.githubusercontent.com/55274139/92482221-a9feaa00-f1e7-11ea-9a24-fd9d3fb613cf.png)

![image](https://user-images.githubusercontent.com/55274139/92482077-7facec80-f1e7-11ea-9327-2836e52bfc16.png)

**Comment by kdinev** [comment]
@gianmarcoFerranteProm Thanks a lot for the additional investigation. We definitely have to check what's going on!

@rkaraivanov @ChronosSF Guys, please take a look at this!

**Comment by gianmarcoFerranteProm** [comment]
Your are welcome, if you guys needs some more info just let me know!

**Comment by rkaraivanov** [comment]
@Ferranteg-dev 

The grid triggers its change detection cycle (which does not mean it always re-renders itself) based on the following:
1. An input property is changed
2. Resize/layout change of the grid container.
3. An event is fired inside the grid DOM tree.
4. Explicitly requesting the grid to trigger change detection.

Now back to your examples.

In the first one, as you've guessed, having a method call inside the template means that on each scroll in the grid, that method will be called because Angular has to know what to interpolate inside the template (same goes for getters, btw). If you want to reduce the number of calls,
transform that method to a pure pipe and leverage the memoization feature of the Angular pipes.

In your last two examples, your console calls are in the context of a ngFor loop which will always execute on each change detection.
Even more for the trackby function sample as trackby is just a performance mechanism to reduce the number of DOM mutations by Angular. And it is again, always called for each item in the collection for each detection cycle.
In the case of the grid however, the columns are just used as metadata objects for the rest of the grid DOM and are not fully fledged DOM elements.

The best way to tackle performance problems is to get a performance profile dump with a modern browser, and then focus on what takes the most CPU time/what causes the the most repaints in the browser. 
If you do have a serious performance degradation, feel free to provide such a profile and we'll be happy to help you resolve it.

**Comment by zdrawku** [comment]
Thank you Radoslav, @Ferranteg-dev closing this one for now, let us know if you want to add anything else
