### ISSUE TITLE
igx-combo initial validation issue

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#8098]
## Description  
When using a required igx-combo in a form, validation runs before the form is touched only for the combo. 

 * igniteui-angular version: 10.1.x
 * browser: N/A

## Steps to reproduce  

1. Add a required igx-combo in a form and bind it.
2. Add an igx-input-group to a form and bind it.
3. Observe the combo

## Result  
The combo is validated before the form is touched.

## Expected result  
The combo should not be validated.

**Comment by damyanpetev** [comment]
Okay, took me a minute to figure out how to repro - this only happens if the initial value for the model the combo is bound to is an empty array `[]`. My initial approach was setting `null` without thinking too much about it and it behaved as expected. See https://stackblitz.com/edit/github-xqtjmn (both combo's validate, only the second fails initially).

----

Details: As far as I see incoming model values go though a simple falsy check that sends the empty array though full selection logic, that shouldn't be used for this in any case at all because it ends up trying to write the new selection to the model - that's still empty array but different by reference, thus making the model dirty.
