### ISSUE TITLE
igCombo sample broken

### ISSUE THREAD

**Issue by ruslanss** [IgniteUI/igniteui-angular#81]
hi, igCombo sample appears to be broken: http://igniteui.github.io/igniteui-angular/samples/igCombo.html

I was looking for the answer whether ig-combo directive can be used with multi-select option?

**Comment by dkamburov** [comment]
We need to re-deploy  [ http://igniteui.github.io/igniteui-angular/](http://igniteui.github.io/igniteui-angular/), because of a missing reference for templating.

igCombo itself does not support initializing to multiple select, but it has an option for multiple selection you can review the combos from this [sample](http://www.igniteui.com/combo/selection-and-checkboxes)

**Comment by mpavlinov** [comment]
This should be resolved now by https://github.com/IgniteUI/igniteui-angular/commit/4441e3f69b4e7678f13ecb597fb03c676b823fcb
