### ISSUE TITLE
IgxGrid's reflow method does not refresh the grid.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#8124]
## Description  
IgxGrid's reflow method does not refresh the grid.

 * igniteui-angular version: 10.1.4
 * browser: Chrome

## Steps to reproduce  

1. Run and open the attached sample.
2. Click 'Clear "Row 0, Col 1" value in the bound data' button.

## Result  
The grid is not refreshed with the new value.

## Expected result  
The grid is refreshed with the new value.

## Attachments  
[cas33363-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/5205622/cas33363-app1.zip)

**Comment by zdrawku** [comment]
Hey @norikois, this is not a bug. As I see from the sample, if the relying data is changed at some point the grid wont know about this. This is because we strive to sustain a good performance and in order to do that we minimize unnecessary bindings and for example recalculation of the functions related with applied cell styles and etc.

A possible solution that you might consider is forcing the grid to reflect changes by executing **markForCheck** :

```ts
  buttonClick(){
    console.log("buttonClick");
    this.localData[0].Col1 = "";
    requestAnimationFrame(() => {
      this.grid1.markForCheck();
    })
  }
```
Although, even then, after marking the grid for check it will reflect any changes **on the next change detection cycle**.

**Comment by norikois** [comment]
Hi @zdrawku,
I got it! Thank you very much for the investigation.

**Comment by rkaraivanov** [comment]
@norikois
That would look something like:

```typescript
buttonClick() {
    console.log('button clicked');
    this.grid.updateRow({ ...this.localData[0], Col1: '' }, this.localData[0].ID);
    OR
    this.grid.updateCell('', this.localData[0].ID, 'Col1');
}
```

**Comment by norikois** [comment]
@rkaraivanov 
Understood. Thank you very much!
