### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError is thrown when IgxColumnHiding is used

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#8125]
## Description  
ExpressionChangedAfterItHasBeenCheckedError is thrown when IgxColumnHiding is used.

 * igniteui-angular version: 10.1.4
 * browser: n/a

## Steps to reproduce  

1. Run the attached sample
2. Observe the console

## Result  
ExpressionChangedAfterItHasBeenCheckedError is thrown.

## Expected result  
No error is thrown.

## Attachments  
[igx-grid-column-pinning-column-hiding.zip](https://github.com/IgniteUI/igniteui-angular/files/5206825/igx-grid-column-pinning-column-hiding.zip)

The same error is thrown at the StackBlitz sample https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-column-hiding-sample?file=src%2Fapp%2Fapp.module.ts

**Comment by ChronosSF** [comment]
This is the same as with the Pinning scenario in #8126 . Similarly you can just use the hiding UI from the toolbar and won't get the error. I'll look into how to avoid the error when using it standalone asap.

**Comment by MayaKirova** [comment]
This seems to be a general issue with the design since the columns collection always changes during initialization (as it is resolved from ContentChildren post-initialization). Angular does not like Input properties that change their value during initialization and would throw ExpressionChanged error for them, for example: https://stackblitz.com/edit/github-acxeqx1

As discussed with @ChronosSF we will change the Input to be the grid itself.
