### ISSUE TITLE
IgxGrid: Two headers and cells become active after columns are moved when templates are used for headers and cells.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#8127]
## Description  
IgxGrid: Two headers and cells become active after columns are moved when templates are used for headers and cells.

 * igniteui-angular version: 10.1.4, 9.1.15
 * browser: Chrome, IE11

## Steps to reproduce  

1. Run and open the attached sample.
2. Move the "name" column to the place between the "age" and "power" columns.
3. Move the "age" column to the place between the "name" and "power" columns.
4. Click the "name" header.
5. Click the "Robot-1" cell at the first row.

## Result  
At the step 4, both the "name" and "age" headers become active.
At the step 5, both the "Robot-1" cell and its right "age" cell become active.

## Expected result  
At the step 4, only the "name" header becomes active.
At the step 5, only the "Robot-1" cell becomes active.

## Attachments  
[cas33341-app4.zip](https://github.com/IgniteUI/igniteui-angular/files/5207081/cas33341-app4.zip)

**Comment by norikois** [comment]
Thank you for the cooperation!
Could you tell me whether this issue is also fixed for IE11?
The customer uses IE11 as well and wants to get fix for IE11 too.

**Comment by ViktorSlavov** [comment]
Hi @norikois ,
Thanks for the sample and the repro steps!
This is reproducible when any using any sort of template that affects a column / cell (e.g. `igxCell`, `igxHeader`, `igxFilterCellTemplate`, etc.).
This is **only** reproducible when the template is passed via `ng-container` w/ `*ngTemplateOutlet` (as is the case in the sample):
```html
<igx-grid>
    <igx-column
        ...
    >
        <ng-template igxCell let-value>
            <ng-container *ngTemplateOutlet="cellTemplate; context: { $implicit: value }">
            </ng-container>
        </ng-template>
    <igx-column>
</igx-grid>
...
<ng-template #cellTemplate let-value>
Templated {{ value }}
</ng-template>
```
If the template is **directly inserted** in the `igx-column` tag (w/o being passed via `ng-container` w/ `*ngTemplateOutlet`), the issue is not reproducible:

```html
<igx-grid>
    <igx-column
        ...
    >
        <ng-template igxCell let-value>
            Templated {{ value }}
        </ng-template>
    <igx-column>
</igx-grid>
```

If you could check with the client, if this approach would eliminate the issue on their end, that would be of great help.
This might still be a bug on our end, but it can also be related to Angular itself - context might be lost by passing several levels of templates.

**Comment by zdrawku** [comment]
Same as https://github.com/IgniteUI/igniteui-angular/issues/8129#issuecomment-707519242

Check out @rkaraivanov comment for more information:

>  ..the column object exposes setters for its templates, thus you can pass them outside of the declaration of the column tags and it works. In this instance I think the "bug" is just the weird way Angular resolves child queries (especially content based ones) and templates.
