### ISSUE TITLE
igxDatePicker: Input field is auto-focused on load (IE11)

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#8165]
## Description  
igxDatePicker's input field is automatically focused on load if mask property is set.
Once this happens, you cannot move the focus to another input if there are multiple instances on the page.

 * igniteui-angular version: 10.1.4,9.1.18
 * browser: IE11

## Steps to reproduce  
1. Run the sample with IE11.
2. Click inside the html input on the top.

## Result  
The second igxDatePicker is focused at step 1.
You are unable to focus the input at step 2.

## Expected result  
igxDatePicker should not be focused at step 1.
The clicked input should get focused at step 2.

## Attachments  
[datePicker.zip](https://github.com/IgniteUI/igniteui-angular/files/5237052/datePicker.zip)

**Comment by mkamiishi** [comment]
Reproducible with Angular9 too.

**Comment by jackofdiamond5** [comment]
Hi @mkamiishi, 

Originally the issue comes from IE because it fires an `input` event when the page loads. The interesting thing is that it does it only if there are some specific characters in the input - these include Japanese characters, characters such as `é`, `ñ`, etc. The workaround that we've come up with should prevent the problem described here from happening in the future. However, since the support for IE is slowly coming to an end, we are unlikely to see a fix for the original issue.
