### ISSUE TITLE
If igxMonthPicker is placed inside igxDropDown, the view gets duplicated when a year label is clicked.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#8180]
## Description  
If igxMonthPicker is placed inside igxDropDown, the view gets duplicated when a year label is clicked.
This happens only after the dropdown is re-opened.

 * igniteui-angular version: 9.1.11, 10.1.4
 * browser: Chrome

## Steps to reproduce  

1.Click the input twice to open and close the dropdown.
2.Click the input to reopen the dropdown.
3.Click the year label.

## Result  
Calendar view gets duplicated

## Expected result  
Calendar view should not get duplicated

## Attachments  
[igxMonthPicker10.zip](https://github.com/IgniteUI/igniteui-angular/files/5244642/igxMonthPicker10.zip)

**Comment by Aleksandyr** [comment]
@mkamiishi  I see what your point is and it turns out this is an [issue ](https://github.com/angular/angular/issues/26133) coming from angular.
The implementation behind the dropdown and the integration with the month picker does the same logic as it's described in the issue above.

There are several solutions to the scenario you would like to achieve.
1. The first one is to use directly the [overlay ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/overlay_main.html) and make your own 'toggle'.
2. That's the easier and faster way, you can directly use the [toggle](infragistics.com/products/ignite-ui-angular/angular/components/toggle.html).

We don't intend to do any workarounds here, because we have plenty of choices you can choose from in order to achieve the desired result.

Please let me know if everything is clear and if it's so let's close the issue.

**Comment by mkamiishi** [comment]
I went for igxDialog instead of igxDropDown.
Please close the issue if it's coming from Angular.
