### ISSUE TITLE
igx-grid - An error "Cannot convert undefined or null to object" occurs when autoGenerate = true, if the initial data is unset or empty array.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#832]
### Description  
igx-grid - An error "Cannot convert undefined or null to object" occurs when autoGenerate = true, if the initial data is unset or empty array.

### Steps to reproduce  

1. Use igniteui-angular@5.2.21.
2. Configure igx-grid as follows. 
```
<igx-grid [data]="" [autoGenerate]="true"></igx-grid>
```
Or like this.
```
<igx-grid [data]="[]" [autoGenerate]="true"></igx-grid>
```

### Result  
<img width="1531" alt="2018-03-26 8 20 17" src="https://user-images.githubusercontent.com/15909409/37881156-a80c6a0c-30ce-11e8-8fd0-32035c88eac8.png">

### Expected result  
The error should not occur. In other words, igx-grid with autoGenerate=true should accept empty data.

###  Current workaround
Put empty object in the array.
```
<igx-grid [data]="[{}]" [autoGenerate]="true"></igx-grid>
```

**Comment by zdrawku** [comment]
We are aware of this behavior and it is documented in the [official grid doc](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html).

If the data property is `undefined` or `empty string` this will result in an error when the grid tries to bind itself.

`Note: In the code below, you may wonder why are we setting the records property to an empty array before subscribing to the service. The Http request is asynchronous, and until it completes, the records property will be undefined which will result in an error when the grid tries to bind to it. You should either initialize it with a default value or use a BehaviorSubject.`

Also about the `autoGenerate` property, we are again mentioning that if there is no data, the grid will throw an error.

`Note: The grid autoGenerate property is best to be avoided when binding to remote data for now. It assumes that the data is available in order to inspect it and generate the appropriate columns. This is usually not the case until the remote service responds, and the grid will throw an error. Making autoGenerate available, when binding to remote service, is on our roadmap for future versions.`
