### ISSUE TITLE
Operations like paging, resize, pin or move does not exit edit mode and commit changes.

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#8329]
## Description  
operations like paging, resize, pin or move does not exit edit mode and commit changes.

 * igniteui-angular version: 10.2.0
 * browser: All

## Steps to reproduce  

1. Open any grid, tgrid or hgrid
2. Enter edit and perform any of the operations above

## Result  
Cell/row remains in edit and does not commit the new changes

## Expected result  
Regarding the [documentaiton ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell_editing.html#cell-editing) performing any of the operations above should close the editing and commit all new changes regardless of event cancelation.

**Comment by zdrawku** [comment]
Related to #8330

**Comment by hanastasov** [comment]
My observation over 10.2.x and master confirm the behaviors described in the [documentation ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell_editing.html#cell-editing) 

Paging, resize, pin or move **DO EXIT edit mode and commit** changes.
Sorting, filtering, searching and hiding **exit edit mode and DO NOT commit** changes operations;

**Comment by zdrawku** [comment]
@ddincheva, could you please let us know if we are missing something

**Comment by ddincheva** [comment]
In the issue description as an expected result is stated that paging, pin, or move should exit edit mode and commit changes event if cellEdit / rowEdit events are cancelled. During the quick test, I have made myself currently if you cancel the event and perform paging the grid layout is broken.

![editingEvents](https://user-images.githubusercontent.com/34240583/101137409-73ce9c00-3617-11eb-9207-965968aa2483.gif)
In this case, according to me is a better solution since the cellEdit event is cancelled to escape edit mode without committing the value, but this should be discussed deeply @zdrawku , @hanastasov.

**Comment by hanastasov** [comment]
[Here](https://infragisticsinc297.sharepoint.com/:x:/s/Phoenix/EdqQgxpvvzlKr745Bv3vYiUBNFcjhQXCCtr1Rrpp-sV6eg?e=BYlVlv) is a comparison table on Editing between our and competitor grids.

**Comment by zdrawku** [comment]
Related to https://github.com/IgniteUI/igniteui-angular/issues/8774
