### ISSUE TITLE
"Row added" snackbar hides too fast.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#8399]
## Description  
Currently the "Row Added" snackbar, that notifies when a row is added and allows scrolling to it via the "Show" button is configured to hide after 2000ms.
For some users that may be too soon as they may not be able to react in time to click the "Show" button and after the snackbar hides there's no way for them to find the added row.

Possible solutions are either to set a bigger default display time or expose the display time as an Input so that users can adjust it to their liking.

**Comment by MayaKirova** [comment]
@StefanIvanov what do you think? Should we set a bigger display time for the snackbar (if so what should it be) or should we perhaps allow the users to set it via an Input.

**Comment by StefanIvanov** [comment]
We should expose an input for the duration if we want to improve things because timeouts are always hard to get right especially when you are doing something generic that will fit a 1000 different scenarios and we will never get it right for everyone :) 2000ms is a good default but I agree it may not fit every use case out there.
