### ISSUE TITLE
DatePicker providing only two digits for the year input is parsed to 19_ _ instead of 20_ _

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#8475]
## Description  
A customer is using a DatePicker in dropdown mode with the default mask. When entering a shorter year such as 5/17/20 it first looks right, but instead of using the current year it uses the year 1920.
 * igniteui-angular version: 10.2.x, 9.1.x
 * browser: any

## Steps to reproduce  

1. Open the following sample: https://stackblitz.com/edit/github-datepikcer-two-digit-year
2. Enter the following value: 06/15/21
3. Click outside the datePicker

## Result  
The created date is 06/15/1921

## Expected result  
The created date should be 06/15/2021

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by damyanpetev** [comment]
Since the sample already specifies the format explicitly, if you actually use the two-digit format and (more importantly) mask the parsed values will actually be as expected:
```html
<igx-date-picker format="M/d/yy" mask="M/d/yy">
```
Here's the [updated sample](https://stackblitz.com/edit/github-datepikcer-two-digit-year-vpduz5?file=src%2Fapp%2Fscheduling%2Fdatepicker%2Fdatepicker-dropdown%2Fdatepicker-dropdown.component.html).

At the moment, the Date Picker will only prefix values with `20-` if the editing mask is the two-digit format and that's also static. Otherwise, the value as parsed is used to create a new date, which for `new Date(21, 05, 15)` will produce Jun 15 1921.

Note that this behavior will change once we go through a refactor of the Date Picker to use the new `igxDateTimeEditor` directive internally, which will handle two-digit values even in four digit format and will assume those are 2k years with threshold at 50 right now, though that's also a good feature request to make it controllable. 


PS: Funny thing is JS Date is a bit inconsistent as `new Date("Jun 15 21")` will actually result in 2021 as the year :D

**Comment by jackofdiamond5** [comment]
The issue will be resolved in https://github.com/IgniteUI/igniteui-angular/issues/6483
