### ISSUE TITLE
Treeview collapses on change event of any other element (input/select) on page.

### ISSUE THREAD

**Issue by frankdenouter** [IgniteUI/igniteui-angular#85]
Reproduce:
1) goto http://igniteui.github.io/igniteui-angular/samples/igTree.html
2) expand one or more nodes in the tree-view (e.g. Bikes)
3) on the right start typing in the textfield with 'Mountain Bikes'
4) the treeview collapses 

I would expect the treeview would keep its current collapse/expanded state.

**Comment by kdinev** [comment]
The expanded state of the igTree is not persisted when the view refreshes. The state is not controlled by the angular extension.

**Comment by frankdenouter** [comment]
It does not occur with an example with 'knockoutjs' binding : http://www.igniteui.com/tree/bind-tree-with-ko

In this case the treeview keeps its state.

**Comment by kdinev** [comment]
@frankdenouter That is correct. The case of the `igTreeGrid` is different though. The `igTreeGrid` keeps expanded state for it's records as part of the date source records, while the `igTree` doesn't do so. The `igTreeGrid` needs to do this in order to integrate the record expansion persistence with features like virtualization and paging. The `igTree` on the other hand is intended to be a navigation control and thus it does not have features like virtualization and paging built into it. Technically the `igTree` doesn't have an editing feature either, which is the functionality displayed in the sample.

I can give you a workaround though. If your data contains a flag for each record of whether it's expanded or collapsed, the `igTree` will take it into account when rendering the node.

http://igniteui.com/help/api/2016.1/ui.igtree#options:bindings.expandedKey

This is not exactly the same functionality the `igTreeGrid` has, but should be sufficient for the scenario you're trying to achieve.

**Comment by frankdenouter** [comment]
Thanks for your support @kdinev . The expandedKey did not fit our needs. I have removed the two-way-binding of the datasource in `$.ig.angular.igTree.bindEvents` and will manually trigger a datasource refresh.

**Comment by kdinev** [comment]
@frankdenouter Sorry to hear that my suggestion didn't help. When doing a manual refresh, you can still utilize API of the tree to update the UI for a particular node. 

http://igniteui.com/help/api/2016.1/ui.igtree#methods:applyChangesToNode

This method wouldn't re-render the whole node, so the expanded state will not be lost!

**Comment by frankdenouter** [comment]
@kdinev I tried the manual refresh with applyChangesToNode, but for some reason it does not trigger to update the text in the node, which I had set with the 'nodeContentTemplate'

**Comment by kdinev** [comment]
@frankdenouter What version of Ignite UI are you using? I remember we had an issue with that some time back, but it was fixed.

**Comment by frankdenouter** [comment]
@kdinev Just upgraded to 16.2.20162.1035
(I did not have the implementation on the 16.1 version, so I do not know if it worked back then)
I keep a reference of the node with the .nodeClick event (ui.node). Later I use this reference to set new data to the node:
`$('.selector').igTree('applyChangesToNode', $(referenceToNode), {  Id: 0, Name: 'Updated'  });`

**Comment by kdinev** [comment]
I see what the problem is. The reference is a node object of the form:

```
{
    path: path,
    element: element,
    data: data,
    bindings: bindings
}
```

Change your code to:

`$('.selector').igTree('applyChangesToNode', referenceToNode.element, { Id: 0, Name: 'Updated' });`
