### ISSUE TITLE
Grid Pinning doesn't work with pinning config

### ISSUE THREAD

**Issue by onlyexeption** [IgniteUI/igniteui-angular#8570]
## Description  
Columns don't get pinned where they are supposed when a pinning config is used

 * igniteui-angular version: 11
 * browser: n/a

## Steps to reproduce  

1. Open Grid Pinning Position demo - https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/vNext/angular-demos/grid/grid-sample-right-pinning

2. Pin several columns

## Result  
Columns don't get pinned where they are supposed to be and instead create empty space on the left.

## Expected result  
Should pin columns on the right

## Attachments  
![Capture](https://user-images.githubusercontent.com/19392175/98797985-0499c980-2416-11eb-8c9e-42eb6e283d0e.JPG)

**Comment by ddincheva** [comment]
This problem has been already addressed in issue #8569

**Comment by ChronosSF** [comment]
I don't think this is the same issue. With hgrid the flex order of the expander column was changed from unset to 2

With right side pinning, it seems the unpinned area gets order 3 so that it never gets to the left of the pinned area.

**Comment by ChronosSF** [comment]
@simeonoff , @desig9stein , you can get the branch "fix-pinning-order" based on master . In the Column Pinning dev sample I've added grids that show both issues. The first grid uses right pinning and has a pinned column that is made invisible because of the issue, as the pinned area is shown to the left and squished (with right pinning it should be to the right and the horizontal scrollbar is updated correctly to reflect that).

The second issue is visible in the second grid, which is hierarchical. The expander column of that grid has flex oder:2 which makes it display in the unpinned area, which is incorrect. In 10.2 it is displayed always first even before the drag/drop which is probably also incorrect. But it should be displayed *before* any data columns for sure. You can just make it consistent with what the design for ordering is as long as it is before all data columns.

Pasting a screenshot from 10.2 so you can see what the previous ordering was:
![Screenshot 2020-11-11 164419](https://user-images.githubusercontent.com/2188411/98825768-8cdf9500-243d-11eb-9aaf-a73d14823383.png)
