### ISSUE TITLE
Exit edit mode of cell with null value without changes would change the value to zero.

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#8696]
## Description  
If we start editing a cell with a null value and without any changes exit edit mode, the value would be changed to zero.

## Steps to reproduce  

1. Open the sample [here](https://stackblitz.com/edit/igx-grid-null-value-cell-editing?file=src/app/grid/grid-editing-sample/data.ts)
2. Start editing the first cell in the second column.
3. Exit edit mode without changing the value.

## Result  
The cell value would be zero.

## Expected result  
The cell value should remain null.

**Comment by i30044** [comment]
Hi,
Please provide a solution to this issue. Thanks in advance.

**Comment by ddincheva** [comment]
Hello @i30044 ,
The described behavior in this issue is by design. The empty value has been overridden when the column type is set to number and the default editing template has been used. If this is not the desired behavior you can easily change it by setting a custom editing template or you can use the `cellEdit` event and override newValue that has been set.
Please take a look at this [sample](https://stackblitz.com/edit/igx-grid-null-value-cell-editing-ur3emi?file=src/app/grid/grid-editing-sample/grid-editing-sample.component.ts) where you can see both of my suggestions implemented the first approach is used for the column `Reorder Level`, the second for the column `Units in Stock`. 
Please if you have any additional thoughts or questions just let us know.
