### ISSUE TITLE
Slider set as continuous does not show neither ticks nor bubbles of the value

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#8708]
## Description  
Setting continuous property to true does not show bubble or ticks. It is either documentation issue or a problem in the library.

## Steps to reproduce  

1. Open  https://stackblitz.com/edit/github-5unzke?file=src/app/slider-sample-1/slider-sample-1.component.html

## Result  
 Observe that the slider with continuous =  true does not show the value as bubble.

## Expected result  
A bubble should show when we mouseover the slider position

**Comment by ddincheva** [comment]
Hello @mddragnev , 
The described behavior in this issue is by design. You can check the slider [specification document](https://github.com/IgniteUI/igniteui-angular/wiki/Slider-Specification#general) and as far as I noticed this is also described as a note in the `Continuous Slider` section of the [slider topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider/slider#continuous-slider). Can you please point out where you find different information so we can update and unify it?

**Comment by mddragnev** [comment]
Hello @ddincheva,
In this case then the documentation in the angular library is incorrect. Please take a look here: https://github.com/IgniteUI/igniteui-angular/blob/7a4c652a99917a863b3575bbb1a42f13cbfb2393/projects/igniteui-angular/src/lib/slider/slider.component.ts#L405

**Comment by ddincheva** [comment]
@mddragnev ,
Thank you, we will address the issue in the API documentation 😊
