### ISSUE TITLE
Igx-Combo inside editable row doesn't detect elements removal

### ISSUE THREAD

**Issue by MiguelPetrotec** [IgniteUI/igniteui-angular#8710]
## Description  
Igx-Combo doesn't detect the removal of items from inside a igx-editable grid.

 * igniteui-angular version: "@infragistics/igniteui-angular": "^10.2.5",
 * browser: Chrome

## Steps to reproduce  

Open the cell for edition and remove some elements from inside the combo.
The grid does not detect the removal of items and when finishes it they appear again.

Watch the following video:

https://www.loom.com/share/18cc43431e594dcca47fff8f9edb3ebc

**Comment by damyanpetev** [comment]
This should be related to https://github.com/IgniteUI/igniteui-angular/issues/8343 (deep object merge messed up references and didn't allow removing items) and I'm fairly certain we looked at this scenario specifically so it should be fixed in https://github.com/IgniteUI/igniteui-angular/releases/tag/10.2.6

Can you check with that version (or newer) and post back if it resolves the issue?

**Comment by MiguelPetrotec** [comment]
After updating to version 10.2.6 it seems to be resolved the reported issue.

Many thanks
