### ISSUE TITLE
Grid context menu does not open on IOS devices

### ISSUE THREAD

**Issue by dobromirts** [IgniteUI/igniteui-angular#8723]
## Description  
Grid context menu does not open on IOS tablet and phone devices.
onContextMenu and onDoubleClick events are not triggered by holding tap or double tapping on any grid row and does not show the context menu. Running on a desktop PC or android device, it shows successfully with said events.

 * igniteui-angular version: 
 * browser: all

## Steps to reproduce  
Run https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection#grid-context-menu on a tablet device and try to show the context menu tapping on the demo.

## Expected result  
The context menu should work for IOS devices.

**Comment by Aleksandyr** [comment]
It seems that it is a third party [issue](https://bugs.webkit.org/show_bug.cgi?id=213953). The contextmenu evt is just not fired by safari under ios.

As for the double click in order to take advantage of that event, you have to integrate [hamerjs ](https://hammerjs.github.io/) and use [doubletap ](https://hammerjs.github.io/require-failure/) instead.
