### ISSUE TITLE
igx-grid column selection does not allow me to copy column values

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#8819]
## Description  
I have a grid with column selection and upon Ctrl+C on the selected column/s, I expect column values to be added to the clipboard.

 * igniteui-angular version: 11.0.11
 * browser: all

## Steps to reproduce  

1. Define a grid with `columnSelection`
2. Select a column
3. Ctrl+C

## Result  
Clipboard is empty.

## Expected result  
Clipboard should contain the column values.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by dobromirts** [comment]
@kdinev  If we have a selected column and a range of selected cells in the grid what should be the expected behavior? Prioritize the column copy or both selection should be added to the clipboard upon Ctrl+C?
![column-copy](https://user-images.githubusercontent.com/46093564/107958078-2de46b80-6faa-11eb-8731-c999a4c54c19.png)

**Comment by kdinev** [comment]
I would say both, but if there's an issue with the implementation, then I guess cells should be prioritized.
