### ISSUE TITLE
 ng add igniteui-angular fails

### ISSUE THREAD

**Issue by Lonli-Lokli** [IgniteUI/igniteui-angular#8822]
## Description  
Describe the issue.

ng add igniteui-angular   fails 
## Steps to reproduce  

1. Clone develop from https://gitlab.com/lonli.lokli/cv-app
2. run ng add igniteui-angular

## Result  
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
? Enable polyfills for IE, Edge and Safari? Yes
? Add CSS library to reset HTML element styles across browsers? Yes
    Including @types/hammerjs - Version: ^2.0.36
    Including hammerjs - Version: ^2.0.8
Could not find the project main file inside of the workspace config apps/cv/src

## Expected result  
Should work

**Comment by ViktorSlavov** [comment]
@Lonli-Lokli Thanks for bringing this to our attention!
The issue is caused by our schematics assuming that the test builder is the default one - karma. We're then looking to add the `hammerjs` module to the test config as well, so that test using our components don't fail. When using Karma, the path to the file is specified in the `angular.json`, under the target project, `architect.test.options.main`.
Since you're using `jest`, there is no such property (correct property in this case is `architect.test.options.setupFile`) and it comes as a bit of a surprise to our schematics 😄 .
We'll start looking into the possible "test" builders and work to cover more/most of them.
Additionally, we could just add a warning for test builders that are not covered (instead of erroring).

Lastly, to be able to correctly run `ng add igniteui-angular` w/o failing, you can manually add the following lines (`main` and `scripts`) to your `angular.json`, under `projects.cv.architest.test`:
```json
"builder": "@angular-builders/jest:run",
"options": {
  "configPath": "jest.config.js",
  "tsConfig": "tsconfig.spec.json",
  "setupFile": "apps/cv/src/test-setup.ts",
  _**"main": "apps/cv/src/test-setup.ts",
  "scripts": []**_
}
```
Note that the specified `setupFile` currently does not exist in your project source (not sure what your exact test setup is), so you should add that as well. After the package is successfully added, you can revert the manual changes.

**Comment by Lonli-Lokli** [comment]
@ViktorSlavov Thanks for clarification, I was able to run this command (it's actually ended with red color but I assume it's ok
_Packages installed successfully.
    
    Ignite UI for Angular Schematics installed
    - generate components using 'ng g @igniteui/angular-schematics:c'
    - to use as 'ng new' collection install globally 'npm i -g @igniteui/angular-schematics'
    Learn more: https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/cli-overview.html
    
**Cannot read property 'toString' of null**_

But there are no any references to 'igniteui-angular' in the package.json, so I am not able to import anything from there.

Does this guide miss some steps or this schematic fails before adding actual ignite-angular package?
https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/getting-started#installation
