### ISSUE TITLE
Detect RowSelectionChange fired in ts

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#8849]
I need to know in ts when I do a change. I know that exists  this event:

```
this.dataGrid.onRowSelectionChange.subscribe(selection => console.log(selection));
```

But if I do in ts:

`this.dataGrid.selectRows([1, 2, 3], true);`

The rows are selected but event doesn't emit. I've read that this event is only fired via user interaction in the grid, so, how I can detect the row selection chenge made in ts?

**Comment by zdrawku** [comment]
Yes, the event is not fired via API selected rows set. As you are performing the selection through your code, you can consider the selection change actions as `done` and proceed with your logic, meaning - using the API is considered as `final instance`, we do not perform additional validations or checks on that point, so you are free to proceed with your implementation logic.

For example, if you want to select rows with ID - 1,2 and 3 and on `rowSelectionChange` to get the selected rows and iterate through them in order to access a certain value - upon `selectRows(..)` action you can go ahead and directly call `getRowDataById()` in order to get the desired records. 

As a possible solution you can consider emitting the event by yourself upon selection through the API, you just need to pass the needed [IRowSelectionEvenArgs](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/irowselectioneventargs.html) - [StackBlitz example](https://stackblitz.com/edit/github-emit-selection-event?file=src/app/grid/grid-sample-selection/grid-selection.component.ts)

```ts
    public click() {
        this.grid1.selectRows([4, 5], true);

        let args: IRowSelectionEventArgs = {
                added: [],
                cancel: false,
                event: null,
                newSelection: [4, 5],
                oldSelection: this.grid1.selectedRows,
                removed: []
            };
            
        this.grid1.onRowSelectionChange.emit(args);
    }
```

**Comment by ssg127** [comment]
Thank you! Nice explanation.
