### ISSUE TITLE
Global filter and column filter at same time

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#8851]
I think it would be useful to be able to use the column filters in conjunction with a global filter. Currently they are not complementary.

You may want to filter by a column and then look at the filtered ones that have a text string in any column. Currently you cannot use both at the same time, for column filter the logic is `FilteringLogic.And` and for global filter is `FilteringLogic.Or`.

**Comment by DiyanDimitrov** [comment]
@ssg127 I would suggest you to use the [advanced filtering](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/advanced-filtering) instead of global filtering. Advanced filtering and column filtering are complementary. It is not necessary to use the advanced filtering UI if you don't need, you can just set the [`advancedFilteringExpressionsTree`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#advancedfilteringexpressionstree) property.

Let me know if this meets your requirements.

**Comment by ssg127** [comment]
@DiyanDimitrov I need the global filter because I want to always apply it to all columns and make it fast, without having to select options.

**Comment by DiyanDimitrov** [comment]
@ssg127 The `filterGlobal` method creates an expression tree with the same filtering condition for each column and sets it to the `filteringExpressionsTree` property.

What I am suggesting is instead of using the `filterGlobal` method, to create an expression tree with the same filtering condition for each column with code and set it to the `advancedFilteringExpressionsTree` property.

This way you could use the `filteringExpressionsTree` property for a column specific filtering conditions.

**Comment by ssg127** [comment]
@DiyanDimitrov could you provide me a basic example?

**Comment by onlyexeption** [comment]
@ssg127 I managed to create an example for you. You can check it out [here](https://stackblitz.com/edit/github-mn7nbp-zu74jc?file=src/app/grid/grid-advanced-filtering-sample/grid-advanced-filtering-sample.component.ts). If you have any questions, please let me know!

**Comment by ssg127** [comment]
@onlyexeption If i add a new row it will filter automatically? I will do this in onKeyPress emitter.

**Comment by onlyexeption** [comment]
@ssg127 Yes, it will. You need to use the grid's [**addRow** ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridbasedirective.html#addrow)method. I've updated the sample for you.

**Comment by ssg127** [comment]
Thank you! I will use this calling from an input.

**Comment by DiyanDimitrov** [comment]
@ssg127, Yes, subscribing to that event is ok. I apologize for the delayed response.
