### ISSUE TITLE
OnColumnMoving event should emit more relevant information

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#8852]
## Description  

 * browser: all

## Steps to reproduce  

1. Open column moving dev sample
2. Subscribe to the following events: onColumnMovingStart, onColumnMoving, and onColumnMovingEnd
2. Move a column of your choice by drag and drop
3. Observe the event arguments for each event that has been emitted

## Result  
What is the actual result after following the steps to reproduce?
OnColumnMoving event is emitted multiple times but its event arguments are the same and I can not understand from it where is the current column position/ target or to get any valuable information in order to decide whether I as a developer want to cancel the column moving or not.
As you may notice onColumnMovingEnd consists the drop target, but the event is not cancellable.

## Expected result  
What is the expected result after following the steps to reproduce?
I would like to be able to know the current target/position on the column that I am moving in order to be able to choose whether to cancel the column moving or not.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![movingEvents](https://user-images.githubusercontent.com/34240583/105970295-e006d280-6091-11eb-8eaf-439878ad14c6.gif)

**Comment by hanastasov** [comment]
Actually, the `onColumnMovingEnd` event is cancellable, so it seems we dont need to implement cancel opportunity for the `onColumnMoving` event too.

**Comment by viktorkombov** [comment]
The event arguments of the grid's columnMoving event still do not provide any information about the current position of the dragged column. However, since with the release of 12.1.0 of Ignite UI for Angular package the columnMovingEnd event is cancelable and returns the drop target. It could be used instead of columnMoving event, so probably at this point there is no need to modify its event args. @hanastasov do you think we can close the issue?
