### ISSUE TITLE
IsDevMode - check if `false` with production environment

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#8866]
Angular introduced a fix for [set ngDevMode to false when calling enableProdMode() ](https://github.com/angular/angular/commit/70b4816cd5fd51cfabd699c4c1cda51feaa1fa72). There was an issue that upon calling [isDevMode()](https://angular.io/api/core/isDevMode) from `ng build --prod` build was always returning `true` - [related PR from angular core repo](https://github.com/angular/angular/pull/40124).

As we are using `isDevMode` in our [Deprecation decorator](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/core/deprecateDecorators.ts), we need to check whether this issue is fixed with angular version `11.1.0` as the fix was introduced in `11.1.0-next.3`.

[Another related ref](https://stackoverflow.com/a/51093626/2940502) - We may consider using `environment.production` check instead of isDevMode() if it is more suitable option.

A related issue that needs to be investigated: Event that the old usage of `showToolbar` and `toolbarTitle` is no longer part of the angular dev demos, sometimes the warning is logged in the console. Steps to reproduce, open one of the following demos from our igniteui dev samples app - `grid-finjs.component`, `grid-toolbar.sample`, `grid-toolbar-custom.sample`

**Comment by ddincheva** [comment]
I perform some testing and built two projects with version 10.2.0 and 11.1.1 and I was not able to reproduce the problem. When the projects were built and served on prod  `ngDevMode()` returns `false` /the state is correct/ and no warning about deprecated properties or methods is logged into the console. 
We have some issues with the configurations in demos dev and in angular samples because I was not able to actually start them in prod using the described commands. So that is why in them we see the mentioned warnings.
Also inside our library, we do not have access to the environment variable. This is something that is set in the client application.

**Comment by zdrawku** [comment]
As Desislava mentioned, we didn't found any problems with the environment check. The only problems that were found are:
- There are no migrations for the deprecated methods -which is addressed [with this PR](https://github.com/IgniteUI/igniteui-angular/pull/9010)
- Some deprecated properties still show deprecation warning, and this is because the property still has a default value.
There is a workaround which we decided not to implement - to create getter/setter and hide the default value in a private property, example:

```ts
@DeprecateProperty('`columnPinningTitle` is deprecated')
@Input()
public get columnPinningTitle(): string {
    return this._columnPinningTitle;
}
public set columnPinningTitle(v: string) {
    this._columnPinningTitle = v;
}
/** @hidden @internal */
public get columnPinningTitleInternal(): string {
    return this._columnPinningTitle;
}
```
