### ISSUE TITLE
igx-combo no longer emitting Selection Change when selection is made the ngModel

### ISSUE THREAD

**Issue by jacevedo529** [IgniteUI/igniteui-angular#9133]
## Description  
Upgrade IgniteUI Angular from version 10.1.4 to 10.2.15 produces a breaking change that results in the SelectionChange event to no longer emit when the selected item is set through setting the ngModel. 

 * igniteui-angular version: My app uses Version 10.2.15. The provided sample uses Version 11.1.1
 * browser: Edge Chromium Version 89.0.774.45

## Steps to reproduce  
Navigate to this stackblitz sample:
https://stackblitz.com/edit/github-l4232e?file=src/app/combo-single-selection/combo-single-selection.component.ts

## Result  
SelectionChange doesn't trigger

## Expected result  
SelectionChange triggers as it use to with version 10.1.4

## Attachments  
Navigate to this stackblitz sample:
https://stackblitz.com/edit/github-l4232e?file=src/app/combo-single-selection/combo-single-selection.component.ts

**Comment by ViktorSlavov** [comment]
@jacevedo529 
This is by design. The change was introduced w/ the fix for https://github.com/IgniteUI/igniteui-angular/issues/8098 and, aside from fixing the issue, brings the combo inline with all of our other controls, none of which emit a "change" event triggered by the model. The initial implementation, where the combo emits for model change, was incorrect.
Since the data that is passed to the model is controlled by the developer, any validation on that can be done before passing it to the component.
