### ISSUE TITLE
Button group doesn't update selected button dynamically

### ISSUE THREAD

**Issue by VladB93** [IgniteUI/igniteui-angular#9141]
## Description  
Describe the issue.

 * igniteui-angular version: 11.1.1
 * browser: N/A

## Steps to reproduce  

Use the following demo:
https://stackblitz.com/edit/github-kc6bmu?file=src%2Fapp%2Fbutton-group-sample-2%2Fbutton-group-sample-2.component.html

On clicking the 'Switch' button the current selected button should change.

## Result  

The selection stays the same.

## Expected result  

The selection should be changed on new [selected] input.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by simeonoff** [comment]
@VladB93 we currently support changing the selected button dynamically by calling the `selectButton` method on the button group instance. It takes the index of the button you want to select.

[I've adapted your example](https://stackblitz.com/edit/github-kc6bmu-9b68ry?file=src/app/button-group-sample-2/button-group-sample-2.component.html) to show how this can be done.

We can definitely improve the API so that you don't have to call this method anymore, instead changing the `selected` property on the button will trigger an EventEmitter to inform the button group that a different button was selected, instead of the other way around (like it is now).
