### ISSUE TITLE
Themes: Use only palette colors in component themes

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#9177]
## Is your feature request related to a problem? Please describe.
Some components use custom colors instead of colors from the color palette, thus changing the palette using CSS variables will not update those colors.

## Describe the solution you'd like
Stick to using colors from the palette as much as possible when describing the colors in the component schema.

**Comment by desig9stein** [comment]
@simeonoff @StefanIvanov here is a list of components that require or don't some transparency.

**Components that require transparency**
- **Action Strip** - Transparency is required since the content behind the action buttons should be visible.
- **Flat button** - Transparency is required to achieve the background color on hover/focus.
We can have the button directive on all kinds of elements, even ones that do not have closing tags. Because of that, we can’t use :`:before` `::after` pseudo selectors. This also affects buttons with icons, we can’t have an icon button on an input of `type=”button”`.
- **Calendar** - warning and info colors in the bootstrap theme can be achieved only with some transparency on the color.
- **Carousel** - Navigation buttons in indigo themes need transparency so that the image behind them can be slightly visible.
- **Toast, Snackbar, tooltip** The background should be slightly transparent.

**Components that require solid colors**
- **Chip** - The background, while the chip is dragged, needs to be a solid color.
- **Button-group** - since borders overlap they should be a solid color.
- **Dock manager**  - The backgrounds need to be solid otherwise on drag the content behind will be visible.
- **Nav-drawer** - The background should be a solid color in the unpinned state otherwise the content behind will be visible. 
- **List** - Item background should be solid color because of the panning.
- **Switch** - The thumb background should be a solid color otherwise the track behind is visible.
- **Slider** - The floating label should have a solid background color so the content behind is not visible.
- **Banner** - Since it can be on top of other elements, like for example row adding in the grid, it needs to have a solid background color.
- **Grid** - All cells and rows backgrounds should have solid colors otherwise when we have pinned columns/rows we have a problem when we start to scroll the grid.
- **Summaries** - should have a solid background since that appears on top of the grid rows and columns.
- **Dropdown, Select, Combo, Splitter, Expansion Panel, Dialog, Badge** - They need to have solid background colors because we don't want the content behind them to be visible.

**Comment by kdinev** [comment]
@simeonoff @StefanIvanov Is there any leftover work on this item?

**Comment by simeonoff** [comment]
@kdinev I don't think so. I will close the issue now.
