### ISSUE TITLE
Unable to run igniteui-angular tests

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#9186]
## Description  
Unable to run igniteui-angular tests

 * igniteui-angular version: latest
 * browser: 

## Steps to reproduce  

1. Remove **node_modules** and **package-lock.json** 
2. Rebuild all dependencies
3. run **npm run test:lib**

The following error appears:
![image](https://user-images.githubusercontent.com/7037740/112138580-592a2e00-8bda-11eb-99dc-6943d6a7073c.png)

**Comment by rkaraivanov** [comment]
@Aleksandyr 
Do you have karma-coverage installed? Try running it after a clean `npm install`.
Alternatively, does `ng test igniteui-angular` fails too?

**Comment by Aleksandyr** [comment]
@rkaraivanov I have karma-coverage installed.
I have tried plenty of things and the actual command fails. Alternatively, the suggested **ng test igniteui-angular** works.

**Comment by rkaraivanov** [comment]
@Aleksandyr 
Seems there was a change of how coverage is handled in the karma configuration for Angular tests with v11.
See [this](https://github.com/karma-runner/karma-coverage/issues/426) for additional info.
The `ng test <library-name>` work as that runs it without coverage enabled.
Moreover since we don't use `npm run test:lib` in our CI because we combine the coverage from the different jasmine tag runs, we did not catch it.

As a fix, you can copy the configuration from any specific other karma configuration file and remove the specific jasmine-spec-tags section.

@nrobakova 
What are your thoughts on this issue? 
Should we even have this npm script command as it seems it is barely used at all and the coverage is currently generated though other means?

**Comment by nrobakova** [comment]
@Aleksandyr and @rkaraivanov,
We have a definition to run the tests without coverage:
test:lib:watch 
If you want I can create a similar to grid, hgrid, etc:
test:grid:watch 
test:hgrid:watch
test:others:watch
test:tgrid:watch

**Comment by Aleksandyr** [comment]
@rkaraivanov @nrobakova Sorry for rising that flag so high. I tought that it's the main command for the CI.
@nrobakova  There is no need of adding such commands, at least for me. We have enough.
But as a fix we should either remove the command or at least refer it to the main **karma.conf.js** file and add that karma-coverage plugin?

**Comment by radomirchev** [comment]
@Aleksandyr is the issue still reproducible?

**Comment by Aleksandyr** [comment]
No, it is not. I'm closing the issue.
