### ISSUE TITLE
Deleting a row from infinite scroll grid

### ISSUE THREAD

**Issue by vijrohit158** [IgniteUI/igniteui-angular#9192]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I try to delete any row from the infinite scroll grid, there is no example in Ignite's documentation to delete a row from the infinite scroll. Whenever I am trying to remove a row from the grid by this code **this.grid.deleteRowById(this.selectedUserRowData.id);**
It deletes the row intantly but after scroll down and up the row comes back in the grid

## Describe the solution you'd like
When I delete a row in an infinite scroll grid then that row should remove instantly without refreshing the grid and should not appear after scroll down or up, Can we have a smooth deletion of a row in infinite scroll grid or can you please provide an example if it's there already?

**Comment by 3phase** [comment]
@vijrohit158

The behavior you are describing in this issue appears correct to me. When you attempt to delete an item from a grid that operates with remote data, you'd rather need to handle the deletion in the remote service. 

The grid fetches new data each time you scroll. You might implement something like deleteRow by yourself, but if the data is not modified in your data source, the next time data is being fetched it would include that deleted row as well. That would lead to the obfuscation you are talking about.

In order to handle your delete functionality (as well as adding/editing), I'd suggest you to take a look at the [following topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/batch-editing). There, you'd see how to use the IgxTransactions in order to alter the grid data which seems to me as what you are looking for. Also, you might wish to check out our [blog post ](https://blog.angular.io/building-a-transaction-service-for-managing-large-scale-editing-experiences-ded666eafd5e)in the Angular blog for further clarifications and clarity. 

If you have other questions anyhow, I'm at your disposal.
