### ISSUE TITLE
Adding a dynamic row to infinite scroll grid

### ISSUE THREAD

**Issue by vijrohit158** [IgniteUI/igniteui-angular#9194]
## Is your feature request related to a problem? Please describe.
When I try to add a new row dynamically in the infinite scroll grid using **this.grid.addRow(record);** or **this.grid.data.unshift(record)** it adds the row but after scrolling down or up that row disappears.

## Describe the solution you'd like
Please provide a feature to add row dynamically in an infinite scroll grid or if you have then please provide the link.

## Additional context
Please provide an example of dynamically adding a row in an infinite scroll grid

**Comment by 3phase** [comment]
@vijrohit158 

The described behavior is expected. The infinite scroll grid sample uses remote data that ought to be handled by a remote service. That remote service is beyond the scope of this library and you should rather take care of it by yourself.

Be advised that the infinite scroll sample does not represent a feature of the igxGrid. It rather utilizes the grid and some features in a way to accomplish a well recognised and prominent design technique of a data container with remote data. 
All further customization and remote data operations though should be handled by yourself.

Because of the character of the problem, I won't be able to provide you with an example, since you need to take care of it in your data origin (i.e. your server).
