### ISSUE TITLE
Wrongly calculate the height of the grid body when the number of records is more than 10

### ISSUE THREAD

**Issue by HoangPhungBka** [IgniteUI/igniteui-angular#9200]
## Description  
Wrongly calculate the height of the grid body when the number of records is more than 10
I realized that this bug is because you set `protected _defaultTargetRecordNumber = 10;` on line 2831 in the file `grid-base.directive.ts`

 * igniteui-angular version: 11.1.3
 * browser: All

## Steps to reproduce  

1. Set grid height in html file in % or default to 100%.
    <igx-grid height="calc(100% - 100px)"></igx-grid>
2. Calling api returns the number of records is more than 10
```typescript
@ViewChild(IgxGridComponent, { static: true }) igxGridComponent!: IgxGridComponent;

public ngOnInit(): void {
    this.dataService.findMany({ page, perPage }).subscribe(response => {
        this.igxGridComponent.totalRecords = response.totalRecords;
        this.igxGridComponent.data = response.data;
    });
}
```
3. View results on UI

## Result  
![Screenshot from 2021-03-25 14-05-13](https://user-images.githubusercontent.com/14147408/112432242-2f583f00-8d73-11eb-93eb-edf6d591d3bd.png)

## Expected result  
The height of `.igx-grid__tbody-content` is full height of `.igx-grid__tbody`

**Comment by MayaKirova** [comment]
@HoangPhungBka 
As totalRecords is associated with paging I assume this is part of a remote paging implementation. 
I have tried reproducing your issue in an isolated stackblitz sample. You can refer to it here:
https://stackblitz.com/edit/github-1evqfd?file=src/app/grid/grid-remote-paging-defaultTemplate-sample/remote-paging-default-template.component.ts

In this sample the totalRecords count is 77 and each page has 20 record(perPage = 20).
The grid has height:100% and a container that has 800px height.

However I was not able to replicate your issue. The grid container seems to retain the correct size.

Could you let me know if I’m missing something from your scenario?
Or if you have a sample that reproduces the issue please share it so that we can investigate further.
