### ISSUE TITLE
Expand Row on hover during Drag and Drop.

### ISSUE THREAD

**Issue by Ashokkumar1995** [IgniteUI/igniteui-angular#9220]
## Is your feature request related to a problem? Please describe.
I need to expand the rows on hover during Drag and Drop, if the row is collapsed.

## Describe the solution you'd like
(onRowDragStart) and (onRowDragStop) is defined when the Drag and Drop is started and Stopped.
maybe i would suggest you to add a new Event onRowDragPaused by which i can check if the hover row is in Collapsed state and i can expand it pragramatically.

## Describe alternatives you've considered
i tried to do via dragMove in dragDirective, but i can't achieve it.

**Comment by Ashokkumar1995** [comment]
any update on this ?

**Comment by dafo** [comment]
@Ashokkumar1995 
Can you please check [this issue](https://github.com/IgniteUI/igniteui-angular/issues/8075) and specifically the [example ](https://codesandbox.io/s/heuristic-nightingale-kghks?file=/src/app/tree-grid-row-reorder/tree-grid-row-reorder.component.ts)@ViktorSlavov  provided there.
Check how he is obtaining the current position and use the same approach - only expand the hovered row if needed, instead of updating the drag ghost.

**Comment by Ashokkumar1995** [comment]
i tried to use this approach, but i cannot achieve what i want.

i used setTImeOut and it expands all the in between rows while dragging.

can you add a sample where i can only expand the hovered rows after 2secs.

Thanks,
Ashok

**Comment by dafo** [comment]
Closing this issue as such implementation will be covered in the row drag documentation. You can follow the progress on it in [this work item](https://github.com/IgniteUI/igniteui-docfx/issues/2788).
