### ISSUE TITLE
Using ng update to migrate breaking changes

### ISSUE THREAD

**Issue by TimFigs13** [IgniteUI/igniteui-angular#9230]
## Question  
Hello, I have followed along with your tutorials regarding angular schematics here: https://www.infragistics.com/community/blogs/b/engineering/posts/angular-schematics-for-libraries. At current I am trying to write a custom ng update schematic that will search *.html files and look for selectors within the file. The following code is what I have used to try and traverse a Tree and look within the html files. I believe the problem likes within the getDir() method that I have currently and what arguments to pass

```
export default function MigrationUpdate(options: any): Rule {
  return (host: Tree, _context: SchematicContext) => {
    
   const elements = document.querySelector("name_of_selector");

    //Traverse file system in angular application
    host.getDir(options).visit(filePath => {
      if (filePath.endsWith('.html') && elements) {
        /*Perform the necessary actions*/
      }
    });

    return host;
  };
}
```

 * igniteui-angular version: 
 * browser:

**Comment by jackofdiamond5** [comment]
Hi @TimFigs13, the `host.getDir` method accepts a string paramter which is the path of the `directory` to traverse. Instead of passing in `options`, you should pass in your `sourceRoot` directory. Which by default is the `/src` folder. You could find what is the `sourceRoot` directory of your project in the `angular.json` file. If you have multiple projects in your workspace, that you would like to apply the migration to, you will have to get all of the source roots and then pass them over to the visitor. Additionally, if you only want to apply the migration to components, you may want to change the first part of your check to something like this `filePath.endsWith('component.html')`.

On a side note, you can't use `document` here as it will be `undefined` and you will have to come up with a different way of locating your element(s). This may be somewhat tied to what you're trying to do with the migration and you may use `RegEx` or you could parse the file contents to `AST` and manipulate the nodes yourself (if you need to). The latter requires much more code to be written ([example](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/migrations/update-11_0_0/index.ts)) but could be the better option if you have a more complex scenario.

Hope this helps you!

**Comment by TimFigs13** [comment]
Thank you for you response, I was able to correctly traverse a file system within a project using the following: 
I can now get to work on the logic to filter out DOM nodes, by chance is there links somewhere providing documentation on AST and Typescript Compiler API?

```
export default function (options: any): Rule {
  return (host: Tree, context: SchematicContext) => {
    
    const workspace = getWorkspace(host);
    if(!options.project){
      options.project = Object.keys(workspace.projects)[0];
    }
    const project = workspace.projects[options.project];
    options.path = join(normalize(project.root), 'src');

    host.getDir(options.path).visit(file => {
      if (file.endsWith('component.html')) {
        context.logger.log('info','Searching HTML files'); 
      }
    });

    return host;
  };
}
```

**Comment by jackofdiamond5** [comment]
@TimFigs13, you could find the most comprehensive docs on `TypeScript`, at least the ones that I'm aware of, over here - [TS Wiki](https://github.com/microsoft/TypeScript/wiki). About `HTML` parsers, you could try with a separate package or you could use Angular's [HtmlParser](https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/compiler/src/compiler.ts#L74) class, though you may want to keep in mind that their compiler API is only public-ish. In the example that I gave you, in my previous reply, we're using Angular's `HtmlParser` ([parseFile](https://github.com/IgniteUI/igniteui-angular/blob/e2eafda976c55352cd0145ec721c9dc60173c8eb/projects/igniteui-angular/migrations/common/util.ts#L173)) to parse a template file so that we can later manipulate it, this could be a good starting point if that's the approach you'd like to go for.
