### ISSUE TITLE
Preventing the cell from going into edit mode still triggers row editing overlay.

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-angular#9279]
## Description  
Preventing the cell from going into edit mode still triggers row editing overlay.

 * igniteui-angular version: latest
 * browser: all

## Steps to reproduce  

1. Open [this sample](https://stackblitz.com/edit/github-d1cjye-3y9cjb?file=src/app/grid/grid-row-editing-sample/grid-row-editing-sample.component.ts)
2. Double click into a cell to enter in edit mode

## Result  
The entering state is prevented, however the row editing still continues

## Expected result  
Row editing should not trigger when the cell is stopped from entering into edit mode.

**Comment by Aleksandyr** [comment]
@rkaraivanov That is not a bug this is the expected behavior.
You can see from the [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing#event-arguments-and-sequence) that we first emit **rowEditEnter** which is again cancelable, and if it isn't canceled **rowEditEnter** is fired and then **cellEditEnter**. This was discussed with @damyanpetev during the CRUD refactoring.
