### ISSUE TITLE
Date and time picker component

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#9359]
## Is your feature request related to a problem? Please describe.
Right now only a date and time editor exists allowing me to edit the date and time portions of date but not to pick them through a UI.

## Describe the solution you'd like
A picker combining the date and time pickers in one UI allowing selection of the two portions.
e.g. 
![DateTimePicker](https://user-images.githubusercontent.com/1702064/115244127-4ef14600-a12c-11eb-97ae-7a52428b10c0.png)

**Comment by radomirchev** [comment]
@StefanIvanov if IgniteUI Date Picker & Time Picker components are used together and binded to the same data object, they act as a Date&Time picker component. Example:

![image](https://user-images.githubusercontent.com/52001020/117934085-f405d580-b30a-11eb-9fa2-64acad48034c.png)

It is intentional to give clients the option to use only Date or Time or Date&Time together. However it is a good point for creating a sample displaying the Date and Time Picker binded to the same data object. Here is link for the [Date & Time Picker Sample](https://github.com/IgniteUI/igniteui-angular-samples/issues/2660)

**Comment by DanielRose** [comment]
@radomirchev Unfortunately this doesn't work when using reactive forms, since the date picker will overwrite the time, and the time picker will overwrite the date. See #9515

**Comment by PlamenaMiteva** [comment]
We will make the following samples of the date and time picker working together:

- date and time picker using ngModel bound to one and the same date object in a template driven form
- date and time picker in a reactive form with a possible workaround that updates the value of the date picker on time picker value change and vice versa

**Comment by Lipata** [comment]
https://github.com/IgniteUI/igniteui-angular-samples/issues/2660
