### ISSUE TITLE
Do we have conditionally row styling in Tree grid?

### ISSUE THREAD

**Issue by vijrohit158** [IgniteUI/igniteui-angular#9370]
## Is your feature request related to a problem? Please describe.
I want to apply background color only to the topmost parent in the tree grid.

## Describe alternatives you've considered
This will be solved If we will have conditionally row styling then for which we don't have parents we will apply a class/style to that row.

<img width="332" alt="Capture" src="https://user-images.githubusercontent.com/81306261/115519465-db277880-a2a6-11eb-9439-ba0f97a24855.PNG">

**Comment by gedinakova** [comment]
Hello @vijrohit158,

The requirements you describe can be achieved with conditional cell styling and, more specifically, by using columns' `cellClasses` input. I created a [small sample application ](https://stackblitz.com/edit/github-g6jqfa?file=src/app/tree-grid-conditional-cell-style-sample/tree-grid-conditional-cell-style-sample.component.ts) demonstrating this approach.
First, a CSS class describing the desired styling should be defined, e.g.
``` css
  .topParent {
    background-color: aqua;
  }
```
Next, a callback function specifying when this class would be applied to grid cells needs to be declared. This callback function has the following signature:
``` typescript
(rowData: any, columnKey: string, cellValue: any, rowIndex: number) => boolean
```
So based on the specific requirement, one can use any parameter(s) in order to properly define the condition. For highlighting the top parent row, the callback function I used is as follows:
``` typescript
private parentCondition = (rowData: any, rowIndex: number): boolean => {
    return rowData.ParentID === -1;
  };
```
Then, the object literal that will be assigned to `cellClasses` input is created:
``` typescript
  public commonClasses = {
    topParent: this.parentCondition
  };
```
Finally, we loop through all columns and assign the object literal to the `cellClasses` input:
``` typescript
this.treeGrid.columns.forEach(col => {
      if (!col.cellClasses) {
        col.cellClasses = this.commonClasses;
      }
    });
```
More detailed information on conditional cell styling along with code snippets and demos is available in [TreeGrid's Conditional Cell Styling topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/conditional-cell-styling).

Please, let us know if you need further assistance.

**Comment by zdrawku** [comment]
@vijrohit158 we now have rowClasses and rowStyles that you can use in order to achieve yout requirements:

https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/conditional-cell-styling#using-rowclasses
