### ISSUE TITLE
[IgxSelect] Label and the value are overlap each other if a custom global theme is used.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#9455]
## Description  
[IgxSelect] Label and the value overlap each other if a custom global theme is used.

 * igniteui-angular version: 11.1.9

## Steps to reproduce  

1. npm install and npm start the attached reproducible sample.
2. Open the IgxSelect.
3. Click one of the items to select.

## Result  
The selected item and the label "Select..." overlaps each other.

## Expected result  
The label goes up and the label and the selected item don't overlap each other.

## Attachments  
[cas34529-app2.zip](https://github.com/IgniteUI/igniteui-angular/files/6390792/cas34529-app2.zip)
[cas34529-app1-movie1.zip](https://github.com/IgniteUI/igniteui-angular/files/6390556/cas34529-app1-movie1.zip)

## Answer
RE styles usage template: [app_styles_template.zip](https://github.com/IgniteUI/igniteui-angular/files/6608271/app_styles_template.zip)

**Comment by norikois** [comment]
I replaced the initially attached reproducible sample with cas34529-app2.zip, which looks more like what the customer provided to us. They would like to refer some variables in the global styles.scss in the app.component.scss. That's why they import the styles.scss in the app.component.scss. But with this, the label and the text of the selected item overlaps each other.

**Comment by IvayloG** [comment]
I have tested `cas34529-app2.zip` and it appears to me what's causing this is actually not using the theming correctly. I am attaching a sample `app_styles_template.zip` containing an alternative approach with the use of a separate variables.scss file.

Couple of points here:
1. For simplicity and in order to mitigate such issues, I suggest using a separate variables.scss file to contain the theme parameters, including the pallets, similarly to the samples from our theming sections like 
https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/data-entries/dropdown-styling?file=src%2F_variables.scss, under this topic section  
https://www.infragistics.com/products/ignite-ui-angular/angular/components/drop-down#using-css-variables

2. Including `igx-core` and `igx-typography` before `igx-theme` is essential. The igx-core mixin provides all base definitions needed for igx-theme to work.
Topic with more details here https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/sass/global-themes#igx-theme

In general, this is the basic template on how to add igx-core, igx-typography and igx-theme:
```
// IMPORTANT: Make sure you always include igx-core first!
@include igx-core();
// Add the typography styles before the main theme.
@include igx-typography();
// Pass the color palette we generated to the igx-theme mixin.
@include igx-theme($my-color-palette);
```

3. Apart from the above points & lastly, it seems likely that what is happening in the cas34529-app2.zip sample is, when refering @import '../styles.scss'; in app.component.scss, what happens is the @include igx-theme(...) is not executed in the right context. In general, when using @include igx-theme(...) it in an app.component.scss, it should be either 
```
//...use this for all normal browsers
 :host {
     @include igx-css-vars($my-color-palette);
 }

//...OR alternatively use this, if supporting IE11...
  :host  ::ng-deep {
    @include igx-theme($my-color-palette);
  }
```
