### ISSUE TITLE
Edit cell with datatype date allow select range

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#9584]
Currently, when editing a date cell, it allows you to select a day. It would be good to be able to select a range of days instead of just one day. Now to do that, I think thats it's possible using igxCellEditor but you need to rewrite some code and it would be more convenient if by default it allows to select one day or a range of days. 

I've used this [example](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing#angular-grid-cell-editing-and-edit-templates-example)

**Comment by ssg127** [comment]
@jackofdiamond5 In a cell showing a time range. For example, if I want to show the validity range of an offer and it is from 05/25/2021 - 05/29/2021. This is an example.

**Comment by kdinev** [comment]
@ssg127 Since we have to make an assumption on how the start and end dates are presented in the data record the row is bound to in order to provide sort of a `daterange` column type out of the box, the data would have to follow the assumed structure for the particular columns.

Currently, our `igx-date-range-picker` expects an object with `start` and `end` keys, and date objects as values for those keys. The column data in the data source would have to look like this:

```js
{ columnKey: { start: new Date(), end: new Date() } }
```

The default display cell of such data type would show like this:

 > startDateAccordingToPipeParams - endDateAccordingToPipeParams

Going into edit mode would initialize a date-range-picker.

However, what's not clear is how we should handle `sorting`, `filtering` and `grouping` with such type of column out of the box?
