### ISSUE TITLE
Deprecating Support for IE11 in `igniteui-angular` v13

### ISSUE THREAD

**Issue by loclv** [IgniteUI/igniteui-angular#9603]
## Is your feature request related to a problem? Please describe.

As you can see [angular-v12 release blog](https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49):

```text
Angular is an evergreen platform, meaning that it stays up-to-date with the evolving web ecosystem. Removing support for legacy browsers allows us to focus our efforts on providing modern solutions and better support to developers and users.

We are going to start including a new deprecation warning message in Angular v12 — and remove support for IE11 in Angular v13.
```

Deprecating support for IE11 can improve smaller bundle size.

## Describe the solution you'd like

Deprecating Support for IE11 in `igniteui-angular` v13.

Remove all IE11 supporting SCSS, JS...

## Additional context

Thank for supporting!

**Comment by kdinev** [comment]
@loclv We technically have no choice, but to also deprecate IE11 with 12.0.0, since the Angular framework has deprecated it. IE11 support code will stay until our v13.0.0 which will come out with Angular 13 and then IE11 support will be removed from our code also. 

As for smaller bundle sizes for styles for example, even now by default IE11 support is not turned on and styles are built without IE11 support. IE11 is supported by the theming engine only if you explicitly set `$legacy-support: true` 

https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/sass/configuration#legacy-support

This used to be true by default up until v9 or 10 of our framework but we changed it to default `false`. If you turn it on, you will see a dramatic increase of the theme size.

**Comment by loclv** [comment]
@kdinev Thank! I 'm warting for v13.
