### ISSUE TITLE
‘ResizeObserverEntry’ could not be found

### ISSUE THREAD

**Issue by MonikaKirkova** [IgniteUI/igniteui-angular#9612]
## Description  
In a project using igniteui-angular v12 in utils.d.ts file ‘ResizeObserverEntry’ could not be found

 * igniteui-angular version: 12.0.x

## Steps to reproduce  

1. Create new project with igniteui-angular v12
2. Open node_modules/igniteui-angular/lib/core/utils.d.ts

## Result  
‘ResizeObserverEntry’ is not imported

## Expected result  
‘ResizeObserverEntry’ should be imported

**Comment by damyanpetev** [comment]
@MonikaKirkova Would love a repro sample or at least the package.json/lock, because `ResizeObserverEntry` is defined in the DOM lib carried by TypeScript, thus it doesn't need to be imported at all. AFAIK Angular 12 uses just about the latest TypeScript version, which includes resize observer interfaces and it shouldn't cause such issue.

Further details:
Angular 12 updated dependencies to `"typescript": "~4.2.3"` which is also the version we use in the repo to build the lib and contains the Resize observer API since that's included from the 4.2.0 release - https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#lib-d-ts-updates. Also verified Angular CLI templates launched with this version and so did the `@angular/compiler-cli` (https://unpkg.com/browse/@angular/compiler-cli@12.0.0/package.json see peer deps)

**Comment by damyanpetev** [comment]
PS: Actually created a fresh 12 project and couldn't repro as expected, will need more info
[resize12.zip](https://github.com/IgniteUI/igniteui-angular/files/6571617/resize12.zip)

**Comment by MonikaKirkova** [comment]
By updating typescript to version “4.2.3” the issue is not reproduced.
