### ISSUE TITLE
Improve sorting experience for users

### ISSUE THREAD

**Issue by michalsgit** [IgniteUI/igniteui-angular#9674]
## Is your feature request related to a problem? Please describe.
Users can be frustrated to change sorting in grid when is allowed sorting by multiple columns. 
Let's suppose there is a grid with 3 columns: col1, col2,col3. It is sorted by col2(asc) and then by col3(asc).
User wants to sort it just by column col1
Right now user must find already sorted column and then click 5 times to achieve the expected sorting.

## Describe the solution you'd like
By clicking on sort icon, the current column should be sorted and other sorting criteria should be clear out.
Ctrl+click  should allow to add sorting of the current column in addition to existing sorted columns.

**Comment by sddania** [comment]
imho, should be implemented a sorting mode like the selection mode ('single', 'multiple')

**Comment by Eralmidia** [comment]
I agree with @sddania. The current way this works (allowing multi sorting) is definitely a feature worth having. Allowing ctrl + click most likely isn't clear for many users.

**Comment by Eralmidia** [comment]
@StefanIvanov Yes, that's a reasonable implementation. It is kinda like issue with the single select combo discussed at #9832, in that I feel this is sort of basic functionality with should have been simply a mode input (like for instance the changes you made to selection, in order to support single or multiple row/cell selection). But in our case, we already have a grid service as a layer on top of the igx grids to add additional functionality, so we can simply add the support into this service in order to achieve this.

**Comment by kdinev** [comment]
@StefanIvanov If we want to be consistent with the `igGrid` sorting behavior, then we should probably expose two modes. The jQuery grid does have `single` and `multi` modes, while the `igx-grid` has only multi by default. I think we should keep the default, in order to not make breaking changes, but to somehow enable a `single` behavior (not necessarily through a mode option). Ctrl+click is not a good option for us, as this would not work on mobile.

**Comment by sddania** [comment]
imho the sortingOptions input parameter is over-engineered. It makes sense that there might be other options to have to set for sorting, but now I can't think of anything.
Is better to expose directly a sortingMode enum in order to set it directly `sortingMode="single"` on the grid component.

**Comment by hanastasov** [comment]
Hi @michalsgit and @Eralmidia. This feature is one of the most wanted from our customers, and this is why we prioritize it now not for next, but for the sprint after the next one. Implementation will follow our [Sorting Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Sorting-Specification#options)  (see the Options section) and will also decouple grouping from sorting.
