### ISSUE TITLE
When switching tabs backwards, content of new tab gets created prior destroying the old one

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#9693]
## Description  
When the tabs are being switched either by changing the `selectedIndex` property of the component or manually, and when a smaller (previous) index is set, the new tab content get instantiated before the content of the current tab index get destroyed.

 * igniteui-angular version: 12.0.0
 * browser: Chrome/Brave 91.0.44, Firefox

## Steps to reproduce  

1. Open this [Stackblitz recreation of the issue](https://stackblitz.com/edit/tabs-issue-repro-attempt?file=src/app/tabs-sample-3/tabs-sample-3.component.ts) or follow steps 2-6;
2. Create a new tabs component. Disable the animation when tab switches and align tab items to center;
3. Create a new component to place inside an `<igx-tab-content>`. Do it in the following fashion:
`<igx-tab-content>   
  <sample-component></sample-component>
</igx-tab-content>`;
4. Create a variable to keep a track on the currently active tab. Change it in let's say `ngAfterViewInit` of the parent component by binding to the `selectedIndexChange` event of the tabs component;
5. Modify the tab contents by adding the structural directive `ngIf` to each of the sample-component instances. We want to do that because when the condition of the directive is not met, the component gets destroyed and we want to make sure that it is destroyed to observe the issue. Refer to that code:
`<sample-component *ngIf="currentIdx === 0"></sample-component>`;
6. Navigate the tabs starting from the last to the first;
7. Observe the console to see that the tabs are being created prior `onDestroy` of the previous tab was executed.

## Result  
New tab is being created prior destroying old one.

## Expected result  
Go through destroy hook before creating a new component

## Attachments  
Stackblitz sample: https://stackblitz.com/edit/tabs-issue-repro-attempt?file=src/app/tabs-sample-3/tabs-sample-3.component.ts

Image explanation:
![image](https://user-images.githubusercontent.com/8365193/121392117-bfac2600-c957-11eb-9d9c-f826367864c9.png)

**Comment by DiyanDimitrov** [comment]
@3phase
This is not an issue in the tabs component. The tabs component neither creates nor destroys the views. The behavior that you observe is standard for Angular since the `ngIf`s in the template are executed sequentially. You can see this behavior in this [sample](https://stackblitz.com/edit/tabs-issue-repro-attempt-f2adkr?file=src/app/tabs-sample-3/tabs-sample-3.component.html) which doesn't use tabs.

I was able to achieve the desired behavior of destroying the view before creating the new one using `ng-container` with `ngTemplateOutlet`. Here is the [sample](https://stackblitz.com/edit/tabs-issue-repro-attempt-tp8eeh?file=src/app/tabs-sample-3/tabs-sample-3.component.html)

**Comment by 3phase** [comment]
@DiyanDimitrov , thank you very much for the clarifications and for the time spent!
