### ISSUE TITLE
Swipe not working in time picker in touch devices

### ISSUE THREAD

**Issue by saj25** [IgniteUI/igniteui-angular#9717]
## Description  
When opening the time picker in mobile/ touch devices, unable to swipe through the hours and minutes list.

 * igniteui-angular version: all
 * browser: chrome, Firefox, safari iOS

## Steps to reproduce  

1. Open the time picker in any mobile device
2. Try to swipe through the time list

## Result  
Unable to swipe through the hours/minutes. Time can be changed by tapping on the top or bottom of the list.

## Expected result  
User should be able to swipe through the list in touch UI or some other option should be  given that is easy to understand (like up and down arrows on the top and bottom of the list on clicking which user can change the time).
Also the it would be nice if the input in the header is editable.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
Hi, @saj25, this is fixed and should be available next week in the patches for igniteui-angular. We have set threshold 10 for hammer.js config and it seems fine for both Android and iOS devices. However, because there isn't a scroll animation and inertia the experience seems that can be improved a lot. There is a separate issue for that: #6292.

**Comment by Lipata** [comment]
Hi, @saj25. You can use [12.1.3](https://github.com/IgniteUI/igniteui-angular/releases/tag/12.1.3) for igniteui-angular
