### ISSUE TITLE
Slider's lowerValue and upperValue don't work

### ISSUE THREAD

**Issue by VladB93** [IgniteUI/igniteui-angular#9728]
## Description  
We need this to be added in a 12.0 patch. 

 * igniteui-angular version: 12.0.0
 * browser: any

## Steps to reproduce  

Use this sample
https://stackblitz.com/edit/github-3shxbe-w2tswd?file=src%2Fapp%2Fslider-sample-1%2Fslider-sample-1.component.html

## Result  
The `upperValue` and `lowerValue` are set but they don't show as initial values for the slider.

## Expected result  

Setting `upperValue` and `lowerValue` should set the thumbs starting position.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by DaniMarinov** [comment]
@radomirchev @kdinev we will need this **only** for the slider with min and max value.

**Comment by VladB93** [comment]
We'll need this for the range slider. Min and max value and not connected to this issue.

**Comment by kdinev** [comment]
@DaniMarinov @VladB93 `upperValue` and `lowerValue` are not exposed as inputs, but are public properties and that's why they appear in the docs. I think it's OK if we just expose them as inputs.

**Comment by Aleksandyr** [comment]
@kdinev @VladB93 as far as I remember **lowerValue** and **upperValue** were meant to be only getters.
Don't know why they were exposed as setters, but the use case of those two props was when you are having labels that are not indicating numeric values and you don't know the **'index'** of the thumb position. 

IMO we should leave these two props only as getters, and leave the update of the thumbs only to the **value** property. Otherwise, everything is messing up, because we don't know which setter should take precedence. The **lowerValue | upperValue** or **value** prop.

**Comment by kdinev** [comment]
Since you can have two thumbs and correspondingly to values, we should have a setter for this. The precedence of these properties will be the order of setting them. How should we interact with an upper/lower value slider at the moment by spec? Should I bind to the getters to get the values and how do I set them?

**Comment by Aleksandyr** [comment]
@kdinev Basically the [value](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxslidercomponent.html#value) property does this.
You can either pass a number if the slider is not range and [lower|upper](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/irangeslidervalue.html) if the slider is range.

You can also take advantage of the two-way data bind which has been implemented in the component so it can handle both scenarios depending on the slider **type**.
