### ISSUE TITLE
How does collapsed input work on igx-splitter-pane?

### ISSUE THREAD

**Issue by amrit-moomie** [IgniteUI/igniteui-angular#9740]
## Question  
In my app, I want to have the ability to collapse and expand the splitter pane through the typescript code. 

Initially, I want to start with the collapsed = true state. With my Code example below, setting the[ [collapsed]="true"](https://stackblitz.com/edit/github-rhju94?file=src/app/splitter-nested-sample/splitter-nested-sample.component.html) does hide the content inside the pane, **but doesn't "collapse" the pane to completely close it.** 
![image](https://user-images.githubusercontent.com/6138925/122410317-cf2c0000-cf51-11eb-85f9-6045b06e6104.png)

**I can close the pane by clicking on the arrows.**
![image](https://user-images.githubusercontent.com/6138925/122410103-a3107f00-cf51-11eb-9271-37efa285ad5e.png)

[Stackblitz URL ](https://stackblitz.com/edit/github-rhju94?)

Also, check my code that in [ngAfterViewInit](https://stackblitz.com/edit/github-rhju94?file=src/app/splitter-nested-sample/splitter-nested-sample.component.ts), setting the collapsed property to true/ false on the element doesn't work

**Comment by kdinev** [comment]
@amrit-moomie Since you have splitter sizes of the different panels set at init time, together with a collapsed state, the splitter calculates its size based on the input and remains in a "collapsed" state, but with a size of 50%.

Use the `toggle()` method instead in this case to make the splitter collapsed: https://stackblitz.com/edit/github-rhju94-rytd7h?file=src/app/splitter-nested-sample/splitter-nested-sample.component.html

**Comment by amrit-moomie** [comment]
@kdinev  is there a way to avoid ExpressionChangedAfterItHasBeenCheckedError in your solution?

**Comment by kdinev** [comment]
@ChronosSF @MayaKirova Could you please comment on @amrit-moomie's question?

**Comment by MayaKirova** [comment]
@amrit-moomie  Since changes have occurred during the same detection cycle, you can force a new one after the toggle using the ChangeDetectorRef's detectChanges() method to prevent the error, for example:

`
  ngAfterViewInit(): void {
    this.collapseMeFirst.toggle();
    this.cdr.detectChanges();
  }
` 

Here's a stackblitz for your reference: https://stackblitz.com/edit/github-rhju94-syzxi9

**Comment by amrit-moomie** [comment]
@kdinev @MayaKirova Thanks

**Comment by kdinev** [comment]
@MayaKirova Can we keep this open as a feature request to allow setting panels as collapsed at init time?

**Comment by ChronosSF** [comment]
Changing this to a feature request.
