### ISSUE TITLE
Cell navigation with the arrow keys doesn't work on FF

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#9821]
## Description  
Noticed it for cell navigation but focus related operations might have other issues as well.

 * igniteui-angular version: n/a
 * browser: FF

## Steps to reproduce  

1. Open the attached sample on FF
2. Click a cell to focus it
3. Try to navigate with the arrows

## Result  
Nothing happens

## Expected result  
The active cell can be changed with the keyboard (like on Chrome)

## Attachments  
[srollable-igx-grids-one-page-du2qbq.zip](https://github.com/IgniteUI/igniteui-angular/files/6764417/srollable-igx-grids-one-page-du2qbq.zip)

**Comment by ddincheva** [comment]
Hello @ChronosSF ,
I tried to reproduce the issue that you described but without any success, as you can see in the gif below:

![NavigationFirefox](https://user-images.githubusercontent.com/34240583/128318397-5408dc20-4c38-4613-abdb-f90ad569b138.gif)

So can you please check and let me know if I am missing something or the issue is no longer reproducible

**Comment by ChronosSF** [comment]
I update the app with 12.1.1 and the issue still seems to reproduce using FF 91. I'll ask someone from my team to test it as well.

**Comment by ChronosSF** [comment]
looking into it with @dkamburov and @skrustev , it seems that it works only if you focus the cell you want to nav from with TAB first.

To reproduce make sure to only click with the mouse on a cell and try to use the arrow keys right afterwards.

**Comment by zdrawku** [comment]
@hanastasov I see that you moved this for the sprint, removing the postponed label

**Comment by katherinedragieva** [comment]
Currently I'm using igniteui-angular version: 12.0.0 and Firefox version 99.0 and everything seems to be working.

**Comment by ChronosSF** [comment]
Still reproduces with FF 99 and igniteui-angular 12.3.19 which is the latest patch. Check the previous comments - it seems the issue comes from the grid/cell not correctly receiving focus on a mouse click. You should only click on a cell with the mouse before trying to navigate to reproduce it.

Attaching sample using updated libs.
[srollable-igx-grids-one-page-du2qbq.zip](https://github.com/IgniteUI/igniteui-angular/files/8470372/srollable-igx-grids-one-page-du2qbq.zip)

**Comment by katherinedragieva** [comment]
After some investigation I found out that a [fix that was added in order to make the selection and dragging on Firefox work](https://github.com/IgniteUI/igniteui-angular/pull/9730), actually blocks KeyboardEvent, which leads to two bugs at time. Therefore, a solution needs to be provided to fix both.
