### ISSUE TITLE
Grouping hierarchy when toggling a group does mess up

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#9870]
## Description  
Grouping hierarchy when toggling a group is incorrect.

## Steps to reproduce  

1. Open this https://stackblitz.com/edit/github-wagbgu?file=src/app/grid/grid-groupby-sample/grid-groupby-sample.component.ts sample
2. Open DevTools console
3. Click the Test button and observe the console

In the console there are two arrays printed. The first one is before toggling a group, the second one is the same array after toggling a group
## Result  
You can observe that the first object consists of all group rows flattened which are in the view. After toggling a group, every root group row after the toggled group is replaced with the first child of that specific root. You can observe that from the second printed object in the console.

## Expected result  
The collection should stay the same.

## Note
This might be an issue caused by `getHierarchy` method in the operations.ts file
https://github.com/IgniteUI/igniteui-angular/blob/a3cddaf12026efff2e2eb52709275ceafb4f6c06/projects%2Figniteui-angular%2Fsrc%2Flib%2Fdata-operations%2Foperations.ts#L11

**Comment by MayaKirova** [comment]
@mddragnev @dkamburov This seems to always have worked like this. Reason is that row collection changes when grouping states change and some grouping rows will get cached, hence they will not be in the Dom but will still exist as row instances in the ViewChildren collection. We filter those out in the groupRows getter but when the collection changes the getter needs to be invoked again in order to get the new currently visible (non-cached) group row instances. I don't think this can be fixed on our side since ViewChildren will always return both the cached and visible groups and additional filtering needs to happen to return just the ones that are currently attached to the Dom.

**Comment by mddragnev** [comment]
> @mddragnev @dkamburov This seems to always have worked like this. Reason is that row collection changes when grouping states change and some grouping rows will get cached, hence they will not be in the Dom but will still exist as row instances in the ViewChildren collection. We filter those out in the groupRows getter but when the collection changes the getter needs to be invoked again in order to get the new currently visible (non-cached) group row instances. I don't think this can be fixed on our side since ViewChildren will always return both the cached and visible groups and additional filtering needs to happen to return just the ones that are currently attached to the Dom.

In this case if @dkamburov is cool, I suggest we close the issue.
