### ISSUE TITLE
IgxCombo: ability to filter multiple fields

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#9884]
## Is your feature request related to a problem? Please describe.
If you have a IgxCombo with a complex object you can only search one property.

see https://www.infragistics.com/products/ignite-ui-angular/angular/components/combo-templates#angular-combo-templates-example

In the example Combo the fields 'state' and 'region' are displayed but you can only search for 'state'.

## Describe the solution you'd like
How about adding a property `searchFields` where you can specify all fields to search like `['state', 'region']`.

## Describe alternatives you've considered
An alternatve solution would be to let the programmer customize the search with `[customFilter]="true"` and a `(filter)` event.

**Comment by Timmeeeey** [comment]
@Lipata Hi, is there any update on this?
I have another use case where I would need this functionality:
When I use remote binding and I remotely filter with multiple fields, not all results are displayed because on the client side filtering is done again and it is filtered only by the displaykey.

**Comment by Lipata** [comment]
Hi, @Timmeeeey. 

For me, it is always better to have a custom filter function. I can initiate an internal discussion, which will need to clarify that and after that, we will discuss when we can start working on that.

Regarding your last scenario - when you are having a remote filter, why do you need to have client one? Can you share an example in order to investigate further?
