### ISSUE TITLE
RowType

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#9922]
## Question  
I'm trying to move our application from igniteui 10 to 12, but I'm running into some issues. The upgrade guide states that there is a new RowType (also have to note that this is a really odd name, that make it sound like an enum), which should work as a replacement for the IgxRowComponent and its equivalent in the tree and hierarchical grids.

However, this does not seem to be the case, as there is a lot of things missing from this object. Please see the following errors I'm getting:

![image](https://user-images.githubusercontent.com/12936286/126966225-7c6a2b0b-aab3-4916-b353-a06076a30970.png)
The nativeElement is even listed in the docs for RowType, so I don't know why it's complaining about that one.
 
Also note that I'm doing this migration manually, because ng update @infragistics/igniteui doesnt work for me, going from v11 til 12. Not sure if any of there would have been auto-resolved?

 * igniteui-angular version: 12.0.9
 * browser: Chrome

**Comment by Lipata** [comment]
Hi, @Eralmidia.

I've created an Angular 11 project with our [CLI](https://github.com/IgniteUI/igniteui-cli/releases/tag/v7.1.0). In the new project I'm adding grid and when I type `ng update` then I see the following: 

![image](https://user-images.githubusercontent.com/2621802/127015425-1d0d8431-85a6-40f8-915c-73f5e2bdd249.png)

The name of the package is `@infragistics/igniteui-angular`, is that what you are using?

**Comment by Eralmidia** [comment]
Hi @Lipata 

Yes it is:
![image](https://user-images.githubusercontent.com/12936286/127033259-2128caac-d998-4fa7-b5fc-3b601113dc03.png)

**Comment by Eralmidia** [comment]
Taking a look at the interface, it does seem to lack a lot of things which is available from the IgxGirdRowComponent
![image](https://user-images.githubusercontent.com/12936286/127034031-c63642c3-5af7-4438-afb5-73efc02f17ae.png)

**Comment by Lipata** [comment]
@Eralmidia, you have written that you are using `@infragistics/igniteui` while it is `@infragistics/igniteui-angular`, I wanted to ensure that you are updating the correct package. Can you send the error that you are seeing, when you are running `ng update @infragistics/igniteui-angular`? The migrations are supposed to work and we want to fix them if there is a problem. Running the migrations of course doesn't ensure that everything will be migrated, because there is some logic that is not having migrations and we are describing such things in the our [Update Guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide).

Talking about the `RowType` problem, I think @zdrawku and @hanastasov can help you.

**Comment by Eralmidia** [comment]
@Lipata Yes it is indeed @infragistics/igniteui-angular no @infragistics/igniteui, so that should be correct.

The error I'm getting is:
![image](https://user-images.githubusercontent.com/12936286/127127271-fcdc206c-54b0-4f55-bc06-26d3a0cd08a1.png)


At firstr the error stated that it couldnt find the tsconfig, but our ts config is actually located inside the src folder, not the root. I created a new angular project and saw that the tsconfig is now in the root folder. Our application is quite old (in angular years), as we have been sticking to angular since it was in alpha or beta, so this might just be someting from the early days of angular. But I have now tried copying the tsconfig to the root folder of the application, which gives me the error in the screenshot.

This is the logfile
![image](https://user-images.githubusercontent.com/12936286/127127412-3e8fbc98-05ad-476a-8883-bb61edf0bdc0.png)


I do have my Angular version at 12.1.3, I'm guessing thats ok? The angular version has also been successfully updated with ng update.

As for the RowType, it would be nice to get some guidance there. Those errors are almost all of the errors I see after upgrading. The only other ones seems to be some issue with some typings:
![image](https://user-images.githubusercontent.com/12936286/127128319-16207d7a-e42c-4c78-b570-5d1c41e8516b.png)

**Comment by Eralmidia** [comment]
Come to think of it, I guess it might be the typings which is actually the error, and not the tsconfig, which is just I warning I guess?

**Comment by Eralmidia** [comment]
Oh, just saw you wrote about the pointer and gesture events in the chart forum 😉

**Comment by hanastasov** [comment]
Hi @Eralmidia, the `RowType` interface exposes just the public API of a row. Saying that, the `nativeElement` is not part of the public  API and is not exposed by the classes implementing `RowType`. I understand that customer's applciations may been in a state where replacement is impossible, so if you ever realy need to use the `nativeElement`, you can access it through the gridAPI ( I suggest this as a work-around, not as a good practice):

```typescript
const row = grid.getRowByIndex(0); // returns IgxGridRow, IgxTreeGridRow, IgxHierarchicalGridRow, implementing the RowType interface
const rowComp = grid.gridAPI.get_row_by_index(0);
```

The `RowType` is currently missing `cells`, but this will be changed with the upcoming 12.1. release. In 12.1, `IgxGridCellComponent` and others are hidden, and we expose the  `IgxGridCell`, exposing only the public API, described by the `CellType` interface . You will be able to access the row cells in this way:

```typescript
 const cells = row.cells; // returns IgxGridCell[]. IgxGridCell implements CellType interface
```

The update guide mentions these here https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide#igxgridcomponent-igxtreegridcomponent-igxhierarchicalgridcomponent.

**Comment by Eralmidia** [comment]
@hanastasov Thanks for the clarification about the cells being added. Viewing it in light of the virtualization that makes sense, and seems like a very good addition. 

But just to clarify, in light of what you wrote about IgxGridCell and CellType. Why does for instance getRowByKey not return an IgxGridRow object?
![image](https://user-images.githubusercontent.com/12936286/127143059-b17ad3ac-8f4c-4f8a-933f-3044f2e66570.png)

As for nativeElement I do agree, and there are just a couple of special cases we use it, so I'll change this to use the gridAPI, thank you.

And what about the other properties/methods we have used on the row component earlier, like focused, beginAddRow and crudService? In light of #9429 being marked as in development, I'm assuming that the undocumented beginAddRow is now hidden, and will be replaced by another method in 12.1? The crud service we seems to have used only to programatically set a row in edit mode
![image](https://user-images.githubusercontent.com/12936286/127143851-70dc504a-3491-4dfa-a3ea-113d54ed70fc.png)
Should I use the grid API for this, like with the nativeElement, or is there another preferred way to this?

**Comment by Eralmidia** [comment]
Oh, also, is the cells property added in the beta release yet?

**Comment by hanastasov** [comment]
- `[getRowByKey](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid/grid.component.ts#L1040)` also returns RowType, if this is screenshot from Visual Studio Code, I guess it may be a cached tooltip. Can you check that?

- `focused` was not public before, and is not exposed in the RowType interface too. If you have a reason for us to expose it, maybe this is somethinc to consider. `beginAddRowByIndex` will be entirely removed in future versions as you say.  And currently there are discussions what to be exposed as public api to replace `begginAddRowByIndex` and `row.addRow`. Most probably there will be method exposed by the grid, which will be responsible to trigger the UI on top of the grid.

-  The Crud service is also implemented as internal service, though it is public, it is not intended to be used by the developers. The alternative to enter a cell in edit mode is `cell.setEditMode(value)` until now, and `cell.editMode = true` from version 12.1.

- yes, the cells property is in the beta.

**Comment by Eralmidia** [comment]
@hanastasov Thank you, I think I have what I need to start solving the issues now. As for the focus, it seems it was used in a single place, and we can solve this in another way.

**Comment by damyanpetev** [comment]
@Eralmidia I initially thought the invalid path error is something to do with us passing windows-style paths, but digging in a bit it doesn't seem like it. The schematics virtual FS handles windows paths just fine, the only thing is that it normalizes everything against the virtual root (`/`) by basically prepending it. So if we end up with a path like say ` '..\\node_modules\\@types'`, it'll become something like `/../node_modules/..`
That'd make it both absolute (`/`) and at the same time one level up (`..`) which is considered invalid and thus the error :) 

My best guess is there's a `typeRoots` in your tsconfig that was pointing a level (or two) up since it was copied from a nested folder? If so, that'd no longer be valid in a root config. You can probably confirm if that's the case and if fixing the path resolved this. I suppose we can try to guard against such paths, but really don't think there are many cases to encounter them.

Anyway, for the original note about migrations not running in your project I've logged that separately (linked). Indeed old projects can be weird, but that doesn't mean you should be stuck doing manual migrations :) I'll assume there's still a root `angular.json` that'll have the tsconfig location at least for the build target and try to create some project structure tomorrow to test against.
